import test from 'node:test';
import assert from 'node:assert/strict';
import { once } from 'node:events';
import { randomUUID } from 'node:crypto';
import { applyAuditedAuthMutation, reconcileAuthAudit } from '../src/auth-audit-integrity.js';
import { AuthService, PostgresAuthStore } from '../src/auth.js';
import { StoreMesh } from '../src/domain.js';
import { PostgresRepository } from '../src/postgres-repository.js';
import { createServer } from '../src/server.js';
import { guardedHistoryCleanup } from '../support/postgres-cleanup.js';

const original=new Error('audit persistence failed');
test('failed audited auth mutation restores in-memory state without compensation',async()=>{for(const operation of['assignRole','revokeRole','assignBadge','assignPin']){let restored=false,compensated=false;await assert.rejects(()=>applyAuditedAuthMutation({apply:async()=>({operation}),record:()=>{throw original},writeAudit:async()=>{},restore:async()=>{restored=true},compensate:async()=>{compensated=true}}),error=>error===original);assert.equal(restored,true,operation);assert.equal(compensated,false,operation)}});

test('HTTP role, badge and PIN mutations restore prior auth state when audit recording fails',async()=>{const app=new StoreMesh(),auth=new AuthService({secret:'auth-audit-compensation-secret'}),adminId=randomUUID(),operatorId=randomUUID();auth.addUser({id:adminId,username:'admin-comp',password:'right',roles:['ADMIN']});auth.addUser({id:operatorId,username:'operator-comp',password:'right',roles:['VIEWER']});const server=createServer({app,auth});server.listen(0,'127.0.0.1');await once(server,'listening');try{const base=`http://127.0.0.1:${server.address().port}`,login=await fetch(base+'/api/auth/login',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({username:'admin-comp',password:'right'})}),token=(await login.json()).data.token,call=(path,method='POST',body)=>fetch(base+path,{method,headers:{authorization:`Bearer ${token}`,'content-type':'application/json','idempotency-key':randomUUID()},body:body===undefined?undefined:JSON.stringify(body)}),realRecord=app.record.bind(app),failType=type=>{app.record=(eventType,...args)=>{if(eventType===type)throw original;return realRecord(eventType,...args)}};failType('USER_ROLE_ASSIGNED');assert.equal((await call(`/api/users/${operatorId}/roles`,'POST',{roleCode:'RECEIVING_OPERATOR'})).status,500);assert.equal(auth.userById(operatorId).roles.includes('RECEIVING_OPERATOR'),false);failType('USER_ROLE_REVOKED');assert.equal((await call(`/api/users/${operatorId}/roles/VIEWER`,'DELETE')).status,500);assert.equal(auth.userById(operatorId).roles.includes('VIEWER'),true);const beforeBadge=auth.userById(operatorId).badgeCodeHash;failType('USER_BADGE_REGENERATED');assert.equal((await call(`/api/users/${operatorId}/badge`)).status,500);assert.equal(auth.userById(operatorId).badgeCodeHash,beforeBadge);const beforePin=auth.userById(operatorId).badgePinHash;failType('USER_BADGE_PIN_RESET');assert.equal((await call(`/api/users/${operatorId}/pin`)).status,500);assert.equal(auth.userById(operatorId).badgePinHash,beforePin)}finally{server.close();await once(server,'close')}});

test('reconciliation flags a manual mismatch but accepts a correctly audited role assignment',async()=>{const app=new StoreMesh(),auth=new AuthService({secret:'auth-audit-reconcile-secret'}),goodId=randomUUID(),badId=randomUUID();auth.addUser({id:goodId,username:'good',password:'right',roles:[]});auth.addUser({id:badId,username:'bad',password:'right',roles:['VIEWER']});await auth.assignRole(goodId,'RECEIVING_OPERATOR');app.record('USER_ROLE_ASSIGNED',goodId,{userId:goodId,roleCode:'RECEIVING_OPERATOR'});const report=reconcileAuthAudit({auth,app,logger:()=>{}});assert.equal(report.findings.some(x=>x.userId===goodId),false);assert.equal(report.findings.some(x=>x.code==='AUTH_ROLE_WITHOUT_AUDIT_GRANT'&&x.userId===badId&&x.roleCode==='VIEWER'),true)});

test('audited auth assignment reconciles after a real PostgreSQL reload',{skip:!process.env.DATABASE_URL},async()=>{const siteCode=`AUTH-AUDIT-${Date.now()}`,repo=new PostgresRepository({connectionString:process.env.DATABASE_URL,siteCode}),store=new PostgresAuthStore({pool:repo.pool,siteId:repo.siteId,siteCode}),auth=new AuthService({secret:'auth-audit-postgres-secret',site:siteCode,store}),userId=randomUUID();try{await auth.hydrate();auth.addUser({id:userId,username:'audited-user',password:'right',roles:[]});await auth.flush();const app=new StoreMesh({site:siteCode,seedDemoReferences:false});app.repository=repo;assert.equal(await auth.assignRole(userId,'RECEIVING_OPERATOR'),true);await auth.flush();app.record('USER_ROLE_ASSIGNED',userId,{userId,roleCode:'RECEIVING_OPERATOR'});app.persist();await app.flush();const restoredState=await repo.load(),restoredApp=new StoreMesh({site:siteCode,initialState:restoredState,seedDemoReferences:false}),restoredAuth=new AuthService({secret:'auth-audit-postgres-secret',site:siteCode,store});await restoredAuth.hydrate();const report=reconcileAuthAudit({auth:restoredAuth,app:restoredApp,logger:()=>{}});assert.equal(report.findings.some(x=>x.userId===userId),false)}finally{await guardedHistoryCleanup(repo.pool,repo.siteId);for(const table of['outbox_events','audit_events','idempotency_records','auth_sessions','user_roles','users','role_permissions','roles','site_state_versions'])await repo.pool.query(`DELETE FROM ${table} WHERE ${table==='role_permissions'?'role_id IN (SELECT id FROM roles WHERE site_id=$1)':'site_id=$1'}`,[repo.siteId]).catch(()=>{});await repo.pool.query('DELETE FROM sites WHERE id=$1',[repo.siteId]).catch(()=>{});await repo.close()}});
