import test from 'node:test';
import assert from 'node:assert/strict';
import { StoreMesh } from '../src/domain.js';
import { PostgresRepository } from '../src/postgres-repository.js';

let sequence=0;const key=label=>`${label}-${++sequence}`;
const activate=(app,scope,values)=>{const draft=app.createConfiguration({scope,values,userId:'author'},key('draft'));app.transitionConfiguration(draft.id,'APPROVE','reviewer',key('approve'));app.transitionConfiguration(draft.id,'ACTIVATE','reviewer',key('activate'));return draft};

test('every configuration scope rejects unknown fields and wrong types with field details',()=>{const cases={PACKAGING:['targetWeightKg','wrong'],PRINTING:['reprintThreshold','wrong'],CONSUMABLES:['gelPackCode',7],STATION_MACHINES:['FREEZE',7],RECEIVING:['weightVarianceLimit','wrong'],YIELD_THRESHOLDS:['minYieldPercent','wrong'],FRESH_EXPORT:['allowedNetWeightsKg','wrong'],SYSTEM_TIMEOUTS:['sessionIdleTimeoutMs','wrong']};for(const[scope,[field,wrongValue]]of Object.entries(cases)){assert.throws(()=>new StoreMesh().createConfiguration({scope,values:{unknownField:true},userId:'author'},key('unknown')),error=>error.code==='CONFIGURATION_SCHEMA_INVALID'&&error.details.field==='unknownField');assert.throws(()=>new StoreMesh().createConfiguration({scope,values:{[field]:wrongValue},userId:'author'},key('wrong')),error=>error.code==='CONFIGURATION_SCHEMA_INVALID'&&error.details.field===field)}});

test('configuration review snapshots proposed and current active values',()=>{const app=new StoreMesh(),active=activate(app,'PACKAGING',{targetWeightKg:1}),draft=app.createConfiguration({scope:'PACKAGING',values:{targetWeightKg:2},userId:'author'},key('next')),view=app.configurationVersionsView().find(x=>x.id===draft.id);assert.deepEqual(view.proposedValues,{targetWeightKg:2});assert.deepEqual(view.currentActiveValues,{targetWeightKg:1});assert.equal(view.currentActiveVersionId,active.id);assert.equal(view.currentActiveSequence,1)});

test('active SYSTEM_TIMEOUTS governs session expiry and device presence while constructor values remain fallback',()=>{let now=0;const fallback=new StoreMesh({clock:()=>new Date(now).toISOString(),idleSessionMs:2000,deviceOfflineAfterMs:3000}),session=fallback.openSession('operator','TEST-DEVICE');fallback.heartbeatDevice('TEST-DEVICE');now=1500;assert.equal(fallback.sweepIdleSessions(),0);assert.equal(fallback.devicesWithPresence().find(x=>x.code==='TEST-DEVICE').presence,'ONLINE');now=2500;assert.equal(fallback.sweepIdleSessions(),1);assert.equal(session.status,'SUSPENDED');assert.equal(fallback.devicesWithPresence().find(x=>x.code==='TEST-DEVICE').presence,'ONLINE');const configured=new StoreMesh({clock:()=>new Date(now).toISOString(),idleSessionMs:99999,deviceOfflineAfterMs:99999}),configuredSession=configured.openSession('operator','TEST-DEVICE');configured.heartbeatDevice('TEST-DEVICE');activate(configured,'SYSTEM_TIMEOUTS',{sessionIdleTimeoutMs:500,deviceOfflineAfterMs:600});now=3201;assert.equal(configured.sweepIdleSessions(),1);assert.equal(configuredSession.status,'SUSPENDED');assert.equal(configured.devicesWithPresence().find(x=>x.code==='TEST-DEVICE').presence,'OFFLINE')});

test('active SYSTEM_TIMEOUTS survives a real PostgreSQL reload', {skip:!process.env.DATABASE_URL},async()=>{const siteCode=`CONFIG-TIMEOUT-${Date.now()}`,repo=new PostgresRepository({connectionString:process.env.DATABASE_URL,siteCode});try{const app=new StoreMesh({site:siteCode,seedDemoReferences:false});app.repository=repo;activate(app,'SYSTEM_TIMEOUTS',{sessionIdleTimeoutMs:4321,deviceOfflineAfterMs:8765});await app.flush();const restoredState=await repo.load(),restored=new StoreMesh({site:siteCode,initialState:restoredState,seedDemoReferences:false,idleSessionMs:1,deviceOfflineAfterMs:1});assert.deepEqual(restored.systemTimeouts(),{sessionIdleTimeoutMs:4321,deviceOfflineAfterMs:8765})}finally{for(const table of['outbox_events','audit_events','idempotency_records','configuration_versions','site_state_versions'])await repo.pool.query(`DELETE FROM ${table} WHERE site_id=$1`,[repo.siteId]).catch(()=>{});await repo.pool.query('DELETE FROM sites WHERE id=$1',[repo.siteId]).catch(()=>{});await repo.close()}});
