import test from 'node:test';import assert from 'node:assert/strict';
import {StoreMesh} from '../src/domain.js';import {PostgresRepository} from '../src/postgres-repository.js';
import { guardedHistoryCleanup } from '../support/postgres-cleanup.js';

const openStockExceptions=(app,id)=>app.state.exceptions.filter(x=>x.entityId===id&&['CONSUMABLE_REORDER','CONSUMABLE_SHORTAGE'].includes(x.type)&&['OPEN','ASSIGNED'].includes(x.status));
test('consumable update validates and re-evaluates threshold crossings',()=>{const app=new StoreMesh(),item=app.createConsumable({code:'LIFE-A',name:'Old',unit:'EA',reorderThreshold:0},'create');app.receiveConsumable(item.id,{quantity:10,source:'supplier'},'receive');assert.equal(openStockExceptions(app,item.id).length,0);app.updateConsumable(item.id,{name:'New',unit:'BOX',reorderThreshold:5},'safe-update');assert.deepEqual({name:item.name,unit:item.unit,reorderThreshold:item.reorderThreshold},{name:'New',unit:'BOX',reorderThreshold:5});assert.equal(openStockExceptions(app,item.id).length,0);app.updateConsumable(item.id,{reorderThreshold:10},'cross-update');assert.equal(openStockExceptions(app,item.id).length,1);for(const [input,key] of[[{name:' '},'bad-name'],[{unit:''},'bad-unit'],[{reorderThreshold:-1},'bad-threshold']])assert.throws(()=>app.updateConsumable(item.id,input,key),e=>e.code==='CONSUMABLE_FIELDS_INVALID')});

test('deactivation protects open exceptions and inactive stock cannot be consumed',()=>{const app=new StoreMesh(),healthy=app.createConsumable({code:'HEALTHY',name:'Healthy',unit:'EA',reorderThreshold:0},'healthy');app.receiveConsumable(healthy.id,{quantity:2,source:'supplier'},'healthy-stock');assert.equal(app.deactivateConsumable(healthy.id,{},'deactivate').status,'INACTIVE');assert.throws(()=>app.consumeConsumableDirect('HEALTHY',1,'test',healthy.id),e=>e.code==='CONSUMABLE_NOT_CONFIGURED');const low=app.createConsumable({code:'LOW',name:'Low',unit:'EA',reorderThreshold:2},'low');assert.throws(()=>app.deactivateConsumable(low.id,{},'blocked'),e=>e.code==='CONSUMABLE_HAS_OPEN_EXCEPTION');const issue=openStockExceptions(app,low.id)[0];assert.equal(app.deactivateConsumable(low.id,{force:true},'forced').status,'INACTIVE');assert.equal(issue.status,'OPEN')});

test('activation re-evaluates low stock and can reopen reorder work',()=>{const app=new StoreMesh(),item=app.createConsumable({code:'REOPEN',name:'Reopen',unit:'EA',reorderThreshold:3},'create'),issue=openStockExceptions(app,item.id)[0];app.deactivateConsumable(item.id,{force:true},'deactivate');app.resolveException(issue.id,{decision:'RESOLVED',resolvedBy:'manager',resolutionNote:'temporarily accepted'},'resolve');assert.equal(openStockExceptions(app,item.id).length,0);app.activateConsumable(item.id,'activate');assert.equal(item.status,'ACTIVE');assert.equal(openStockExceptions(app,item.id).length,1)});

test('consumable lifecycle survives PostgreSQL reload',{skip:!process.env.DATABASE_URL},async()=>{const site=`CONSUMABLE-LIFE-${Date.now()}`,repository=new PostgresRepository({connectionString:process.env.DATABASE_URL,siteCode:site});try{let app=new StoreMesh({site,initialState:await repository.load()});app.repository=repository;const item=app.createConsumable({code:'PERSIST',name:'Original',unit:'EA',reorderThreshold:0},'create');app.receiveConsumable(item.id,{quantity:4,source:'supplier'},'receive');app.updateConsumable(item.id,{name:'Persisted',unit:'BOX',reorderThreshold:2},'update');app.deactivateConsumable(item.id,{},'deactivate');await app.flush();app=new StoreMesh({site,initialState:await repository.load()});const loaded=app.state.consumables.find(x=>x.id===item.id);assert.deepEqual({name:loaded.name,unit:loaded.unit,reorderThreshold:loaded.reorderThreshold,status:loaded.status},{name:'Persisted',unit:'BOX',reorderThreshold:2,status:'INACTIVE'})}finally{await guardedHistoryCleanup(repository.pool,repository.siteId);for(const table of['consumable_transactions','consumable_receipts'])await repository.pool.query(`DELETE FROM ${table} WHERE consumable_id IN (SELECT id FROM consumables WHERE site_id=$1)`,[repository.siteId]);for(const table of['outbox_events','audit_events','idempotency_records','operational_exceptions','consumables','devices','products','suppliers','grades','sizes','zones','package_types','site_state_versions'])await repository.pool.query(`DELETE FROM ${table} WHERE site_id=$1`,[repository.siteId]);await repository.pool.query('DELETE FROM sites WHERE id=$1',[repository.siteId]);await repository.close()}});
