import test from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {ConfiguredStoreMesh as StoreMesh} from '../test-support/configurations.js';
import {PostgresRepository} from '../src/postgres-repository.js';

const key=()=>randomUUID();
function readyUnit(app){const session=app.openSession('packer','PDA-PACK-01','PACKAGING','PACKAGING_OPERATOR'),container=app.createContainer({capacityKg:20},key()),batch=app.receive({sessionId:session.id,containerId:container.id,supplier:'S',product:'T',grade:'A',size:'L',weightKg:10},key());batch.status='DRIED';app.weighForPackaging({sessionId:session.id,batchId:batch.id,weightKg:10},key());const unit=app.createPackage({sessionId:session.id,type:'POUCH',level:'UNIT',items:[{batchId:batch.id,weightKg:1}],targetWeightKg:1,tolerancePercent:0},key());for(const action of['PACK','SEAL','PRINT','PRINT_SUCCESS','READY'])app.transitionPackage(unit.id,action,key());return{session,unit}}
function freshLot(app){const session=app.openSession('fresh','TEST-DEVICE','FRESH_EXPORT','FRESH_EXPORT_OPERATOR'),container=app.createContainer({capacityKg:20},key()),batch=app.receive({sessionId:session.id,containerId:container.id,supplier:'S',product:'T',grade:'A',size:'L',weightKg:10},key());Object.assign(batch,{status:'SORTED',destination:'FRESH_EXPORT',zone:'FRESH_EXPORT'});Object.assign(container,{zone:'FRESH_EXPORT',status:'SORTED'});return{session,lot:app.createFreshNetLot({sessionId:session.id,batchId:batch.id,containerId:container.id,unitWeightKg:1,count:5},key())}}

test('CARTON creation requires configured stock and consumes exactly one',()=>{const app=new StoreMesh(),{session,unit}=readyUnit(app),before=app.state.packages.length;assert.throws(()=>app.createPackage({sessionId:session.id,type:'CARTON',level:'CARTON'},key()),e=>e.code==='CONSUMABLE_NOT_CONFIGURED');assert.equal(app.state.packages.length,before);assert.equal(unit.parentPackageId,null);const cartonStock=app.createConsumable({code:'CARTON',name:'Carton',reorderThreshold:1},key());app.receiveConsumable(cartonStock.id,{quantity:2,source:'supplier'},key());app.createPackage({sessionId:session.id,type:'CARTON',level:'CARTON'},key());assert.equal(cartonStock.quantity,1);assert.equal(app.state.consumableTransactions.filter(x=>x.consumableId===cartonStock.id&&x.type==='CONSUMPTION').length,1)});

test('Fresh Shipping Box ignores spoofed client consumable codes',()=>{const app=new StoreMesh(),create=(code,quantity)=>{const item=app.createConsumable({code,name:code,reorderThreshold:0},key());app.receiveConsumable(item.id,{quantity,source:'supplier'},key());return item},eps=create('EPS_BOX',2),gel=create('GEL_PACK',4),other=create('UNRELATED',9),{session,lot}=freshLot(app);app.state.configurationVersions.push({id:key(),scope:'CONSUMABLES',status:'ACTIVE',values:{freshShippingBoxCode:'EPS_BOX',gelPackCode:'GEL_PACK'}});app.createShippingBox({sessionId:session.id,allocations:[{netLotId:lot.id,count:2}],gelPackCount:2,boxConsumableCode:'UNRELATED',gelPackConsumableCode:'UNRELATED'},key());assert.equal(eps.quantity,1);assert.equal(gel.quantity,2);assert.equal(other.quantity,9)});

test('every balance change evaluates and deduplicates reorder state',()=>{const app=new StoreMesh(),item=app.createConsumable({code:'TAPE',name:'Tape',reorderThreshold:5},key()),alerts=()=>app.state.exceptions.filter(x=>x.type==='CONSUMABLE_REORDER'&&x.entityId===item.id);assert.equal(alerts().length,1);app.receiveConsumable(item.id,{quantity:2,source:'supplier'},key());assert.equal(alerts().length,1);assert.equal(alerts()[0].status,'OPEN');app.receiveConsumable(item.id,{quantity:4,source:'supplier'},key());assert.equal(alerts().length,1);assert.equal(alerts()[0].status,'RESOLVED');assert.equal(alerts()[0].resolvedBy,'SYSTEM')});

test('replenishment resolution and shortage rollback survive PostgreSQL reload',{skip:!process.env.DATABASE_URL},async()=>{const site=`FR15-${Date.now()}`,repository=new PostgresRepository({connectionString:process.env.DATABASE_URL,siteCode:site});try{const app=new StoreMesh({site,initialState:await repository.load(),seedDemoReferences:true});app.repository=repository;const item=app.createConsumable({code:'CARTON',name:'Carton',reorderThreshold:2},key());app.receiveConsumable(item.id,{quantity:3,source:'supplier'},key());assert.equal(app.state.exceptions.find(x=>x.type==='CONSUMABLE_REORDER'&&x.entityId===item.id).status,'RESOLVED');const{session,unit}=readyUnit(app);app.consumeConsumableDirect('CARTON',3,'setup',unit.id);const before=app.state.packages.length;for(let attempt=0;attempt<2;attempt++)assert.throws(()=>app.createPackage({sessionId:session.id,type:'CARTON',level:'CARTON'},key()),e=>e.code==='CONSUMABLE_STOCK_INSUFFICIENT');await app.flush();const restored=await repository.load();assert.equal(restored.packages.length,before);assert.equal(restored.packages.find(x=>x.id===unit.id).parentPackageId,null);assert.equal(restored.exceptions.filter(x=>x.type==='CONSUMABLE_SHORTAGE'&&x.entityId===item.id).length,1);assert.equal(restored.exceptions.find(x=>x.type==='CONSUMABLE_REORDER'&&x.entityId===item.id).status,'RESOLVED')}finally{await repository.close()}});
