import test from 'node:test';
import assert from 'node:assert/strict';
import { ConfiguredStoreMesh as StoreMesh } from '../test-support/configurations.js';

const fixture=()=>{const app=new StoreMesh();app.state.consumables.push({id:crypto.randomUUID(),code:'CARTON',name:'Carton',unit:'EA',quantity:10,reorderThreshold:0,status:'ACTIVE',createdAt:new Date().toISOString()});const session=app.openSession('shipper','PDA-PACK-01','PACKAGING','PACKAGING_OPERATOR'),container=app.createContainer({capacityKg:20},'container'),batch=app.receive({sessionId:session.id,containerId:container.id,supplier:'S',product:'T',grade:'A',size:'L',weightKg:10},'receive');batch.status='DRIED';app.weighForPackaging({sessionId:session.id,batchId:batch.id,weightKg:10},'weigh');app.state.qualityChecks.push({id:crypto.randomUUID(),batchId:batch.id,result:'APPROVED',createdAt:new Date().toISOString()});const carton=n=>{const unit=app.createPackage({sessionId:session.id,type:'POUCH',level:'UNIT',items:[{batchId:batch.id,weightKg:1}],targetWeightKg:1,tolerancePercent:0},`unit-${n}`);for(const action of['PACK','SEAL','PRINT','PRINT_SUCCESS','READY'])app.transitionPackage(unit.id,action,`unit-${n}-${action}`);const c=app.createPackage({sessionId:session.id,type:'CARTON',level:'CARTON'},`carton-${n}`);app.transitionPackage(c.id,'PACK',`carton-${n}-pack`);app.scanPackageItem(c.id,{sessionId:session.id,unitPackageCode:unit.code},`carton-${n}-scan`);for(const action of['SEAL','PRINT','PRINT_SUCCESS','READY'])app.transitionPackage(c.id,action,`carton-${n}-${action}`);return c};return{app,session,carton}};

test('customer shipment enforces expected carton scans, vehicle and six-state lifecycle',()=>{const{app,session,carton}=fixture(),one=carton(1),two=carton(2),customer=app.createCustomer({code:'C-1',name:'Customer'},'customer'),order=app.createSalesOrder({customerId:customer.id,items:[{packageType:'CARTON',quantity:2}]},'order'),shipment=app.createShipment({salesOrderId:order.id,packageIds:[one.id,two.id]},'shipment');assert.equal(shipment.status,'DRAFT');assert.equal(app.state.tasks.filter(x=>x.entityId===one.id||x.entityId===two.id).length,2);app.updateShipment(shipment.id,'START_PICKING',{},'start');assert.throws(()=>app.updateShipment(shipment.id,'READY',{},'early'),e=>e.code==='SHIPMENT_SCAN_INCOMPLETE');app.scanShipmentCarton(shipment.id,{sessionId:session.id,cartonCode:one.code},'scan-1');assert.throws(()=>app.scanShipmentCarton(shipment.id,{sessionId:session.id,cartonCode:one.code},'duplicate'),e=>e.code==='SHIPMENT_CARTON_DUPLICATE');app.scanShipmentCarton(shipment.id,{sessionId:session.id,cartonCode:two.code},'scan-2');app.updateShipment(shipment.id,'READY',{},'ready');assert.throws(()=>app.updateShipment(shipment.id,'LOAD',{},'no-vehicle'),e=>e.code==='SHIPMENT_VEHICLE_REQUIRED');app.updateShipment(shipment.id,'LOAD',{vehicle:'TRUCK-42'},'load');app.updateShipment(shipment.id,'SHIP',{},'ship');assert.equal(order.status,'FULFILLED');assert.equal(one.status,'SHIPPED');assert.equal(app.updateShipment(shipment.id,'CLOSE',{},'close').status,'CLOSED')});

test('partial shipments remain partially fulfilled and cancellation releases cartons',()=>{const{app,session,carton}=fixture(),one=carton(1),two=carton(2),customer=app.createCustomer({code:'C-2',name:'Customer 2'},'customer'),order=app.createSalesOrder({customerId:customer.id,items:[{packageType:'CARTON',quantity:2}]},'order'),first=app.createShipment({salesOrderId:order.id,packageIds:[one.id]},'first');app.updateShipment(first.id,'START_PICKING',{},'start');app.scanShipmentCarton(first.id,{sessionId:session.id,cartonCode:one.code},'scan');app.updateShipment(first.id,'READY',{},'ready');app.updateShipment(first.id,'LOAD',{vehicle:'V1'},'load');app.updateShipment(first.id,'SHIP',{},'ship');assert.equal(order.status,'PARTIALLY_FULFILLED');const second=app.createShipment({salesOrderId:order.id,packageIds:[two.id]},'second');app.updateShipment(second.id,'CANCEL',{reason:'customer request'},'cancel');assert.equal(two.shipmentId,null);assert.equal(second.status,'CANCELLED')});
