import test from 'node:test'; import assert from 'node:assert/strict'; import { StoreMesh, DomainError } from '../src/domain.js';

const setup=()=>{const app=new StoreMesh();const session=app.openSession('operator-1');return{app,session};};
test('receiving creates batch, measurement, print job and audit event',()=>{const{app,session}=setup();const b=app.receive({sessionId:session.id,supplier:'S1',product:'Truffle',grade:'A',size:'Large',weightKg:10},'r1');assert.equal(b.weightKg,10);assert.equal(app.state.measurements.length,1);assert.equal(app.state.printJobs.length,1);assert.equal(app.state.outbox.at(-1).type,'BATCH_RECEIVED');});
test('duplicate request is idempotent',()=>{const{app,session}=setup();const input={sessionId:session.id,supplier:'S1',product:'Truffle',grade:'A',size:'L',weightKg:10};assert.equal(app.receive(input,'same').id,app.receive(input,'same').id);assert.equal(app.state.batches.length,1);});
test('movement preserves history',()=>{const{app,session}=setup();const b=app.receive({sessionId:session.id,supplier:'S1',product:'Truffle',grade:'A',size:'L',weightKg:10},'a');app.move(b.id,'COLD_ROOM',session.id,'b');assert.equal(app.batch(b.id).zone,'COLD_ROOM');assert.equal(app.state.movements[0].from,'RECEIVING');});
test('transform supports genealogy and prevents excess output',()=>{const{app,session}=setup();const b=app.receive({sessionId:session.id,supplier:'S1',product:'Truffle',grade:'A',size:'L',weightKg:10},'a');const c=app.transform({sessionId:session.id,parentIds:[b.id],process:'FREEZE_DRY',outputWeightKg:3},'b');assert.deepEqual(app.trace(c.id).ancestors.map(x=>x.id),[b.id]);assert.throws(()=>app.transform({sessionId:session.id,parentIds:[b.id],process:'DRY',outputWeightKg:11},'c'),DomainError);});
test('package cannot be assigned to two shipments',()=>{const{app,session}=setup();const b=app.receive({sessionId:session.id,supplier:'S1',product:'Truffle',grade:'A',size:'L',weightKg:10},'a');const p=app.createPackage({sessionId:session.id,type:'POUCH',items:[{batchId:b.id,weightKg:1}]},'p');app.createShipment({packageIds:[p.id],destinationSite:'DUBAI'},'s1');assert.throws(()=>app.createShipment({packageIds:[p.id],destinationSite:'ROME'},'s2'),DomainError);});
test('inventory cannot be consumed twice by processing',()=>{const{app,session}=setup();const b=app.receive({sessionId:session.id,supplier:'S',product:'Truffle',grade:'A',size:'L',weightKg:10},'r');app.transform({sessionId:session.id,inputs:[{batchId:b.id,consumeWeightKg:10}],process:'DRY',outputWeightKg:3},'t1');assert.equal(app.batch(b.id).status,'CONSUMED');assert.equal(app.batch(b.id).weightKg,0);assert.throws(()=>app.transform({sessionId:session.id,inputs:[{batchId:b.id,consumeWeightKg:1}],process:'DRY',outputWeightKg:1},'t2'),e=>e.code==='INSUFFICIENT_INVENTORY');});
test('packaging decrements stock and rejects overpacking',()=>{const{app,session}=setup();const b=app.receive({sessionId:session.id,supplier:'S',product:'Truffle',grade:'A',size:'L',weightKg:2},'r');app.createPackage({sessionId:session.id,type:'POUCH',items:[{batchId:b.id,weightKg:1.5}]},'p1');assert.equal(app.batch(b.id).weightKg,.5);assert.throws(()=>app.createPackage({sessionId:session.id,type:'POUCH',items:[{batchId:b.id,weightKg:1}]},'p2'),e=>e.code==='INSUFFICIENT_INVENTORY');});
