import test from 'node:test'; import assert from 'node:assert/strict'; import { StoreMesh, DomainError } from '../src/domain.js';

const setup=()=>{const app=new StoreMesh(),session=app.openSession('operator-1','TEST-DEVICE'),rawReceive=app.receive.bind(app),containers=new Map();app.receive=(input,key)=>{let container=containers.get(key);if(!container){container=app.createContainer({capacityKg:100},`container-${key}`);containers.set(key,container)}return rawReceive({...input,containerId:input.containerId??container.id},key)};return{app,session};};
test('receiving creates a measurement without reprinting a permanently-labelled basket',()=>{const{app,session}=setup();const b=app.receive({sessionId:session.id,supplier:'S1',product:'Truffle',grade:'A',size:'Large',weightKg:10},'r1');assert.equal(b.weightKg,10);assert.equal(app.state.measurements.length,1);assert.equal(app.state.printJobs.filter(x=>x.entityType==='BATCH'&&x.entityId===b.id).length,0);assert.equal(b.printRequired,false);assert.equal(app.state.outbox.at(-1).type,'BATCH_RECEIVED');});
test('duplicate request is idempotent',()=>{const{app,session}=setup();const input={sessionId:session.id,supplier:'S1',product:'Truffle',grade:'A',size:'L',weightKg:10};assert.equal(app.receive(input,'same').id,app.receive(input,'same').id);assert.equal(app.state.batches.length,1);});
test('same idempotency key with a different payload conflicts',()=>{const{app,session}=setup(),input={sessionId:session.id,supplier:'S1',product:'Truffle',grade:'A',size:'L',weightKg:10};app.receive(input,'same');assert.throws(()=>app.receive({...input,weightKg:11},'same'),e=>e.code==='IDEMPOTENCY_PAYLOAD_MISMATCH'&&e.status===409)});
test('movement preserves history',()=>{const{app,session}=setup();const b=app.receive({sessionId:session.id,supplier:'S1',product:'Truffle',grade:'A',size:'L',weightKg:10},'a');app.move(b.id,'COLD_ROOM',session.id,'b');assert.equal(app.batch(b.id).zone,'COLD_ROOM');assert.equal(app.state.movements[0].from,'RECEIVING');});
test('transform supports genealogy and prevents excess output',()=>{const{app,session}=setup();const b=app.receive({sessionId:session.id,supplier:'S1',product:'Truffle',grade:'A',size:'L',weightKg:10},'a');const c=app.transform({sessionId:session.id,parentIds:[b.id],process:'MERGE',outputWeightKg:3},'b');assert.deepEqual(app.trace(c.id).ancestors.map(x=>x.id),[b.id]);assert.throws(()=>app.transform({sessionId:session.id,parentIds:[b.id],process:'MERGE',outputWeightKg:11},'c'),DomainError);});
test('package cannot be assigned to two internal shipments',()=>{const{app,session}=setup();const b=app.receive({sessionId:session.id,supplier:'S1',product:'Truffle',grade:'A',size:'L',weightKg:10},'a');const p=app.createPackage({sessionId:session.id,type:'POUCH',items:[{batchId:b.id,weightKg:1}]},'p');for(const a of['PACK','SEAL','PRINT','PRINT_SUCCESS','READY'])app.transitionPackage(p.id,a,'p-'+a);app.createInternalShipment({packageIds:[p.id],destinationSite:'DUBAI'},'s1');assert.throws(()=>app.createInternalShipment({packageIds:[p.id],destinationSite:'ROME'},'s2'),DomainError);});
test('inventory cannot be consumed twice by processing',()=>{const{app,session}=setup();const b=app.receive({sessionId:session.id,supplier:'S',product:'Truffle',grade:'A',size:'L',weightKg:10},'r');app.transform({sessionId:session.id,inputs:[{batchId:b.id,consumeWeightKg:10}],process:'MERGE',outputWeightKg:3},'t1');assert.equal(app.batch(b.id).status,'CONSUMED');assert.equal(app.batch(b.id).weightKg,0);assert.throws(()=>app.transform({sessionId:session.id,inputs:[{batchId:b.id,consumeWeightKg:1}],process:'MERGE',outputWeightKg:1},'t2'),e=>e.code==='INSUFFICIENT_INVENTORY');});
test('packaging decrements stock and rejects overpacking',()=>{const{app,session}=setup();const b=app.receive({sessionId:session.id,supplier:'S',product:'Truffle',grade:'A',size:'L',weightKg:2},'r');app.createPackage({sessionId:session.id,type:'POUCH',items:[{batchId:b.id,weightKg:1.5}]},'p1');assert.equal(app.batch(b.id).weightKg,.5);assert.throws(()=>app.createPackage({sessionId:session.id,type:'POUCH',items:[{batchId:b.id,weightKg:1}]},'p2'),e=>e.code==='INSUFFICIENT_INVENTORY');});
