import test from 'node:test';
import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import { once } from 'node:events';
import { StoreMesh } from '../src/domain.js';
import { PostgresRepository } from '../src/postgres-repository.js';
import { AuthService } from '../src/auth.js';
import { createServer } from '../src/server.js';

const pgOnly={skip:!process.env.DATABASE_URL};let n=0;const key=label=>`${label}-${++n}`;

test('success failure and entity-less events persist truthful entity IDs',pgOnly,async()=>{const site=`EVENT-ENTITY-${Date.now()}`,repository=new PostgresRepository({connectionString:process.env.DATABASE_URL,siteCode:site});try{const app=new StoreMesh({site,initialState:await repository.load(),seedDemoReferences:true});app.repository=repository;const session=app.openSession('receiver','TEST-DEVICE'),delivery=app.startDelivery({supplierCode:'S',sessionId:session.id},key('delivery')),container=app.createContainer({capacityKg:10},key('container')),batch=app.receive({deliveryId:delivery.id,sessionId:session.id,containerId:container.id,supplier:'S',product:'T',grade:'A',size:'L',weightKg:3},key('receive'));app.completeDelivery(delivery.id,{sessionId:session.id},key('complete'));assert.throws(()=>app.adjustInventory({batchId:batch.id,deltaKg:0,reason:'invalid'},key('failed')),e=>e.code==='ADJUSTMENT_INVALID');app.run(key('entityless'),'ENTITYLESS_PROBE',()=>({ok:true}),{});await app.flush();const restored=await repository.load(),complete=restored.audit.find(x=>x.type==='DELIVERY_COMPLETED'),failed=restored.audit.find(x=>x.type==='INVENTORY_ADJUSTED'&&x.result==='FAILURE'),entityless=restored.audit.find(x=>x.type==='ENTITYLESS_PROBE');assert.equal(complete.entityId,delivery.id);assert.notEqual(complete.entityId,complete.id);assert.equal(failed.entityId,batch.id);assert.equal(entityless.entityId,null);assert.notEqual(entityless.entityId,entityless.id)}finally{await repository.close()}});

test('permission denial persists as a contextual security event and self logout remains available',pgOnly,async()=>{const site=`EVENT-DENIAL-${Date.now()}`,repository=new PostgresRepository({connectionString:process.env.DATABASE_URL,siteCode:site}),app=new StoreMesh({site,initialState:await repository.load(),seedDemoReferences:true});app.repository=repository;const auth=new AuthService({site,secret:'event-denial-secret'}),userId=randomUUID();auth.addUser({id:userId,username:'viewer',password:'right',roles:['VIEWER']});const server=createServer({app,auth,requireAuth:true});server.listen(0,'127.0.0.1');await once(server,'listening');try{const base=`http://127.0.0.1:${server.address().port}`,login=await fetch(`${base}/api/auth/login`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({username:'viewer',password:'right',deviceId:'WEB-CONSOLE-01'})}),token=(await login.json()).data.token,jti=JSON.parse(Buffer.from(token.split('.')[1],'base64url')).jti,headers={authorization:`Bearer ${token}`};assert.equal((await fetch(`${base}/api/audit`,{headers})).status,403);await app.flush();let restored=await repository.load(),denial=restored.audit.find(x=>x.type==='PERMISSION_DENIED');assert.ok(denial);assert.equal(denial.userId,userId);assert.equal(denial.result,'FAILURE');assert.deepEqual(denial.payload,{permission:'audit:read',path:'/api/audit',method:'GET'});assert.ok(!restored.audit.some(x=>x.type==='REQUEST_FAILED'&&x.payload?.path==='/api/audit'));assert.equal((await fetch(`${base}/api/auth/sessions/${jti}/revoke`,{method:'POST',headers})).status,200);await app.flush();restored=await repository.load();assert.ok(restored.audit.some(x=>x.type==='AUTH_SESSION_REVOKED'&&x.entityId===jti&&x.userId===userId))}finally{server.close();await once(server,'close');await repository.close()}});
