import test from'node:test';
import assert from'node:assert/strict';
import{randomUUID}from'node:crypto';
import{ConfiguredStoreMesh as StoreMesh}from'../test-support/configurations.js';
import{PostgresRepository}from'../src/postgres-repository.js';

const key=()=>randomUUID();
function baseFixture(site){const app=new StoreMesh({site}),session=app.openSession('shipper','TEST-DEVICE','PACKAGING','PACKAGING_OPERATOR'),cartonStock=app.createConsumable({code:'CARTON',name:'Carton',reorderThreshold:0},key()),container=app.createContainer({capacityKg:30},key()),batch=app.receive({sessionId:session.id,containerId:container.id,supplier:'S',product:'T',grade:'A',size:'L',weightKg:12},key());app.receiveConsumable(cartonStock.id,{quantity:3,source:'test'},key());batch.status='DRIED';app.weighForPackaging({sessionId:session.id,batchId:batch.id,weightKg:12},key());const checklist=app.createQcChecklist({code:`QC-${key()}`,product:batch.product,stage:'PACKAGING',name:'Shipment approval',items:[{code:'OK',prompt:'Approved'}]},key());app.qualityCheck({sessionId:session.id,batchId:batch.id,stage:'PACKAGING',checklistId:checklist.id,responses:[{itemCode:'OK',value:true}],result:'APPROVED',inspectorId:key(),actorRoles:['QUALITY_OPERATOR'],attestation:{confirmed:true,role:'QUALITY_OPERATOR'}},key());return{app,session,batch}}
function readyUnit(f){const unit=f.app.createPackage({sessionId:f.session.id,type:'POUCH',level:'UNIT',items:[{batchId:f.batch.id,weightKg:1}],targetWeightKg:1,tolerancePercent:0},key());for(const action of['PACK','SEAL','PRINT','PRINT_SUCCESS','READY'])f.app.transitionPackage(unit.id,action,key());return unit}
function readyCarton(f){const unit=readyUnit(f),carton=f.app.createPackage({sessionId:f.session.id,type:'CARTON',level:'CARTON'},key());f.app.transitionPackage(carton.id,'PACK',key());f.app.scanPackageItem(carton.id,{sessionId:f.session.id,unitPackageCode:unit.code},key());for(const action of['SEAL','PRINT','PRINT_SUCCESS','READY'])f.app.transitionPackage(carton.id,action,key());return carton}

test('cancelled customer shipment retains its original carton list after PostgreSQL reload',{skip:!process.env.DATABASE_URL},async()=>{const site=`FR82-CUSTOMER-${Date.now()}`,repository=new PostgresRepository({connectionString:process.env.DATABASE_URL,siteCode:site});try{const f=baseFixture(site);f.app.repository=repository;const cartons=[readyCarton(f),readyCarton(f)],customer=f.app.createCustomer({code:'FR82-C',name:'Snapshot customer'},key()),order=f.app.createSalesOrder({customerId:customer.id,items:[{packageType:'CARTON',quantity:2}]},key()),shipment=f.app.createShipment({salesOrderId:order.id,packageIds:cartons.map(x=>x.id)},key());f.app.updateShipment(shipment.id,'CANCEL',{reason:'customer cancellation'},key());await f.app.flush();const restored=await repository.load(),saved=restored.shipments.find(x=>x.id===shipment.id);assert.equal(saved.status,'CANCELLED');assert.deepEqual(new Set(saved.packageIds),new Set(cartons.map(x=>x.id)));assert.equal('expectedPackageIds'in saved,false);assert.ok(cartons.every(carton=>restored.packages.find(x=>x.id===carton.id).shipmentId===null))}finally{await repository.close()}});

test('cancelled internal shipment retains its original package list after PostgreSQL reload',{skip:!process.env.DATABASE_URL},async()=>{const site=`FR82-INTERNAL-${Date.now()}`,repository=new PostgresRepository({connectionString:process.env.DATABASE_URL,siteCode:site});try{const f=baseFixture(site);f.app.repository=repository;const packages=[readyUnit(f),readyUnit(f)],shipment=f.app.createInternalShipment({destinationSite:'DUBAI',packageIds:packages.map(x=>x.id)},key());f.app.updateInternalShipment(shipment.id,'CANCEL',{sessionId:f.session.id,reason:'route cancellation'},key());await f.app.flush();const restored=await repository.load(),saved=restored.shipments.find(x=>x.id===shipment.id);assert.equal(saved.status,'CANCELLED');assert.deepEqual(new Set(saved.packageIds),new Set(packages.map(x=>x.id)));assert.equal('expectedPackageIds'in saved,false);assert.ok(packages.every(pkg=>restored.packages.find(x=>x.id===pkg.id).shipmentId===null))}finally{await repository.close()}});
