import test from 'node:test';
import assert from 'node:assert/strict';
import { once } from 'node:events';
import { StoreMesh } from '../src/domain.js';
import { PostgresRepository } from '../src/postgres-repository.js';
import { AuthService } from '../src/auth.js';
import { createServer } from '../src/server.js';

const pgOnly={skip:!process.env.DATABASE_URL};
const key=()=>crypto.randomUUID();

function approve(app,batch){const stage=app.batchQcStage(batch)==='FRESH_EXPORT'?'PACKAGING':app.batchQcStage(batch),checklist=app.createQcChecklist({code:`FR55-${crypto.randomUUID()}`,product:batch.product,stage,name:'Shipping QC',items:[{code:'OK',prompt:'Approved'}]},key());app.qualityCheck({sessionId:app.state.sessions.find(x=>x.status==='ACTIVE')?.id,batchId:batch.id,stage,checklistId:checklist.id,responses:[{itemCode:'OK',value:true}],result:'APPROVED',notes:'Approved for shipping',inspectorId:crypto.randomUUID(),actorRoles:['QUALITY_OPERATOR'],attestation:{confirmed:true,role:'QUALITY_OPERATOR'}},key())}

test('FR55 full HTTP fresh-export chain survives real PostgreSQL reload',pgOnly,async()=>{
  const site=`FR55-${Date.now()}`,repo=new PostgresRepository({connectionString:process.env.DATABASE_URL,siteCode:site}),app=new StoreMesh({site,initialState:await repo.load(),seedDemoReferences:true});app.repository=repo;
  const seedSession=app.openSession(key(),'TEST-DEVICE','RECEIVING','RECEIVING_OPERATOR'),input=app.createContainer({capacityKg:30},key()),batch=app.receive({sessionId:seedSession.id,containerId:input.id,supplier:'S',product:'T',grade:'UNSORTED',size:'MIXED',weightKg:10},key());app.moveContainer(input.id,'COLD_ROOM_CLEAN',seedSession.id,key());
  const outputs=[app.createContainer({capacityKg:15},key()),app.createContainer({capacityKg:15},key())];for(const output of outputs)app.moveContainer(output.id,'SORTING',seedSession.id,key());for(const container of [input,...outputs])container.activeSessionId=null;
  const eps=app.createConsumable({code:'EPS_BOX',name:'EPS box',reorderThreshold:0},key());app.receiveConsumable(eps.id,{quantity:5,source:'test'},key());app.registerDevice({code:'FR55-SORT',type:'TERMINAL',assignedStation:'SORTING'},key());app.registerDevice({code:'FR55-FRESH',type:'TERMINAL',assignedStation:'FRESH_EXPORT'},key());const scale=app.registerDevice({code:'FR55-SCALE',type:'SCALE',assignedStation:'FRESH_EXPORT'},key());app.state.configurationVersions.push({id:key(),scope:'FRESH_EXPORT',sequence:1,status:'ACTIVE',values:{allowedNetWeightsKg:[1],requireBoxScaleEvidence:true,maxNetsPerBox:3,maxWeightKgPerBox:3},createdAt:new Date().toISOString()});
  const auth=new AuthService({secret:'fr55-http-secret',site});auth.addUser({id:key(),username:'admin-fr55',password:'right',roles:['ADMIN']});const server=createServer({app,auth});server.listen(0,'127.0.0.1');await once(server,'listening');
  const base=`http://127.0.0.1:${server.address().port}`,login=await fetch(base+'/api/auth/login',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({username:'admin-fr55',password:'right',deviceId:'FR55-HTTP'})}),token=(await login.json()).data.token,post=async(path,body={})=>{const response=await fetch(base+path,{method:'POST',headers:{authorization:`Bearer ${token}`,'content-type':'application/json','idempotency-key':key()},body:JSON.stringify(body)}),payload=await response.json();return{status:response.status,data:payload.data,errorCode:payload.errorCode,message:payload.message}};
  try{
    const sortingSession=(await post('/api/sessions',{deviceId:'FR55-SORT',station:'SORTING',selectedRole:'SORTING_OPERATOR'})).data,sorted=await post('/api/sorting',{sessionId:sortingSession.id,containerId:input.id,batchId:batch.id,outputs:[{grade:'A',size:'L',weightKg:5,containerId:outputs[0].id},{grade:'A',size:'L',weightKg:5,containerId:outputs[1].id}],lossReason:'MEASUREMENT_VARIANCE'});assert.equal(sorted.status,201,sorted.message);const children=sorted.data.children;
    for(const child of children){assert.equal((await post(`/api/batches/${child.id}/destination`,{destination:'FRESH_EXPORT'})).status,201);assert.equal((await post(`/api/containers/${child.containerId}/move`,{zone:'FRESH_EXPORT',sessionId:sortingSession.id,scannedContainerId:child.containerId})).status,201);app.state.containers.find(x=>x.id===child.containerId).activeSessionId=null}
    const freshSession=(await post('/api/sessions',{deviceId:'FR55-FRESH',station:'FRESH_EXPORT',selectedRole:'FRESH_EXPORT_OPERATOR'})).data,lot1=(await post('/api/fresh-net-lots',{sessionId:freshSession.id,containerId:children[0].containerId,unitWeightKg:1,sources:[{batchId:children[0].id,count:4}]})).data,lot2=(await post('/api/fresh-net-lots',{sessionId:freshSession.id,containerId:children[1].containerId,unitWeightKg:1,sources:[{batchId:children[0].id,count:1},{batchId:children[1].id,count:2}]})).data;
    let response=await post('/api/fresh-shipping-boxes/drafts',{sessionId:freshSession.id,allocations:[{netLotId:lot1.id,count:2},{netLotId:lot1.id,count:2}]});assert.equal(response.status,409);assert.equal(response.errorCode,'FRESH_SHIPPING_BOX_FULL');response=await post('/api/fresh-shipping-boxes/drafts',{sessionId:freshSession.id,allocations:[{netLotId:lot2.id,count:2},{netLotId:lot2.id,count:2}]});assert.equal(response.status,409);assert.equal(response.errorCode,'FRESH_NET_QUANTITY_INVALID');
    const draft=(await post('/api/fresh-shipping-boxes/drafts',{sessionId:freshSession.id,allocations:[{netLotId:lot1.id,count:1},{netLotId:lot1.id,count:1}]})).data;assert.equal(draft.status,'DRAFT');assert.equal(eps.quantity,5);assert.equal(app.state.printJobs.filter(x=>x.entityType==='FRESH_SHIPPING_BOX').length,0);response=await post(`/api/fresh-shipping-boxes/${draft.id}/draft`,{removeAllocations:[{netLotId:lot1.id,count:1}],addAllocations:[{netLotId:lot2.id,count:1}]});assert.equal(response.status,201);assert.deepEqual(new Set(response.data.items.map(x=>x.netLotId)),new Set([lot1.id,lot2.id]));
    const measurement=(await post('/api/measurements',{sessionId:freshSession.id,scaleId:scale.id,purpose:'FRESH_SHIPPING_BOX',rawReadingKg:2.25})).data,box=(await post(`/api/fresh-shipping-boxes/${draft.id}/confirm`,{sessionId:freshSession.id,measurementId:measurement.id,gelPackCount:0})).data,liveBox=app.state.shippingBoxes.find(x=>x.id===box.id);assert.equal(box.status,'LABEL_PENDING');assert.equal(eps.quantity,4);const label=app.state.labels.find(x=>x.entityId===box.id);assert.equal(label.payload.shipmentCode,undefined);const firstJob=app.state.printJobs.find(x=>x.entityId===box.id&&x.status==='PENDING');assert.equal((await post(`/api/print-jobs/${firstJob.id}/claim`,{sessionId:freshSession.id})).status,201);assert.equal((await post(`/api/print-jobs/${firstJob.id}/fail`,{sessionId:freshSession.id,reason:'paper jam'})).status,201);const retry=(await post(`/api/print-jobs/${firstJob.id}/retry`,{sessionId:freshSession.id,verifiedScan:box.code,reason:'paper replaced'})).data;assert.equal((await post(`/api/print-jobs/${retry.id}/complete`,{sessionId:freshSession.id})).status,201);assert.equal(liveBox.status,'LABEL_PRINTED');
    assert.equal((await post(`/api/fresh-shipping-boxes/${box.id}/cold-holding`,{sessionId:freshSession.id,location:'EXPORT-COLD-55'})).status,201);assert.equal(liveBox.status,'READY_TO_SHIP');response=await post(`/api/fresh-shipping-boxes/${box.id}/cold-holding`,{sessionId:freshSession.id,location:'EXPORT-COLD-55'});assert.equal(response.status,409);assert.equal(response.errorCode,'FRESH_SHIPPING_BOX_COLD_HOLDING_INVALID');for(const child of children)approve(app,app.batch(child.id));
    const customer=(await post('/api/customers',{code:'FR55-CUSTOMER',name:'Fresh destination'})).data,order=(await post('/api/sales-orders',{customerId:customer.id,items:[{packageType:'FRESH_SHIPPING_BOX',quantity:1}]})).data,shipment=(await post('/api/shipments',{salesOrderId:order.id,shippingBoxIds:[box.id]})).data;assert.equal(label.payload.shipmentCode,shipment.code);assert.equal(label.payload.customerCode,customer.code);assert.equal((await post(`/api/shipments/${shipment.id}/start_picking`)).status,201);assert.equal((await post(`/api/shipments/${shipment.id}/scans`,{sessionId:freshSession.id,itemCode:box.code})).status,201);assert.equal((await post(`/api/shipments/${shipment.id}/ready`)).status,201);assert.equal((await post(`/api/shipments/${shipment.id}/load`,{vehicle:'FR55-TRUCK'})).status,201);assert.equal((await post(`/api/shipments/${shipment.id}/ship`)).status,201);await app.flush();
    const restored=await repo.load(),savedBox=restored.shippingBoxes.find(x=>x.id===box.id),savedLot1=restored.freshNetLots.find(x=>x.id===lot1.id),savedLot2=restored.freshNetLots.find(x=>x.id===lot2.id),savedLabel=restored.labels.find(x=>x.id===label.id);assert.equal(savedBox.status,'SHIPPED');assert.equal(savedBox.measuredWeightKg,2.25);assert.equal(savedBox.weightMeasurementId,measurement.id);assert.equal(savedBox.warehouseLocation,'EXPORT-COLD-55');assert.equal(savedBox.warehouseHistory.length,1);assert.equal(savedLot1.remainingCount,3);assert.equal(savedLot2.remainingCount,2);assert.equal(savedLabel.payload.shipmentCode,shipment.code);assert.equal(restored.consumables.find(x=>x.id===eps.id).quantity,4)
  }finally{server.close();await once(server,'close');await app.flush().catch(()=>{});await repo.close()}
});
