import test from'node:test';
import assert from'node:assert/strict';
import{randomUUID}from'node:crypto';
import{once}from'node:events';
import{StoreMesh}from'../src/domain.js';
import{createServer}from'../src/server.js';
import{PostgresRepository}from'../src/postgres-repository.js';

const key=()=>randomUUID();
const fixture=(app=new StoreMesh())=>{const session=app.openSession('receiver','TEST-DEVICE','RECEIVING','RECEIVING_OPERATOR'),delivery=app.startDelivery({supplierCode:'S',sessionId:session.id},key()),container=app.createContainer({capacityKg:20},key()),batch=app.receive({deliveryId:delivery.id,sessionId:session.id,containerId:container.id,supplier:'S',product:'T',grade:'A',size:'L',weightKg:5},key());return{app,session,delivery,container,batch}};

test('fresh receiving batch cancellation records evidence, releases its container and unlinks delivery basket',()=>{const{app,session,delivery,container,batch}=fixture(),cancelled=app.cancelBatch(batch.id,{sessionId:session.id,reason:'duplicate weighing'},key());assert.deepEqual({status:cancelled.status,cancelledBy:cancelled.cancelledBy,cancelledSessionId:cancelled.cancelledSessionId,cancelledDeviceId:cancelled.cancelledDeviceId,cancellationReason:cancelled.cancellationReason},{status:'CANCELLED',cancelledBy:'receiver',cancelledSessionId:session.id,cancelledDeviceId:'TEST-DEVICE',cancellationReason:'duplicate weighing'});assert.ok(cancelled.cancelledAt);assert.equal(cancelled.containerId,null);assert.deepEqual(container.batchIds,[]);assert.equal(container.status,'AVAILABLE');assert.equal(app.state.deliveryBaskets.some(x=>x.deliveryId===delivery.id&&x.batchId===batch.id),false)});

test('receiving cancellation requires reason and rejects downstream or shared-container batches',()=>{const missing=fixture();assert.throws(()=>missing.app.cancelBatch(missing.batch.id,{sessionId:missing.session.id,reason:' '},key()),e=>e.code==='RECEIVING_CANCEL_REASON_REQUIRED');const moved=fixture();moved.app.state.movements.push({id:key(),batchId:moved.batch.id,containerId:moved.container.id});assert.throws(()=>moved.app.cancelBatch(moved.batch.id,{sessionId:moved.session.id,reason:'late'},key()),e=>e.code==='RECEIVING_CANCEL_NOT_ELIGIBLE');const shared=fixture();shared.container.batchIds.push(key());assert.throws(()=>shared.app.cancelBatch(shared.batch.id,{sessionId:shared.session.id,reason:'shared'},key()),e=>e.code==='RECEIVING_CANCEL_NOT_ELIGIBLE')});

test('POST cancel-receiving route exposes receiving cancellation',async()=>{const{app,session,container,batch}=fixture(),server=createServer({app,requireAuth:false});server.listen(0,'127.0.0.1');await once(server,'listening');try{const response=await fetch(`http://127.0.0.1:${server.address().port}/api/batches/${batch.id}/cancel-receiving`,{method:'POST',headers:{'content-type':'application/json','idempotency-key':key()},body:JSON.stringify({sessionId:session.id,reason:'operator correction'})}),payload=await response.json();assert.equal(response.status,201);assert.equal(payload.data.status,'CANCELLED');assert.equal(container.status,'AVAILABLE')}finally{server.close();await once(server,'close')}});

test('receiving cancellation evidence and released carrier survive PostgreSQL reload',{skip:!process.env.DATABASE_URL},async()=>{const site=`FR60-${Date.now()}`,repository=new PostgresRepository({connectionString:process.env.DATABASE_URL,siteCode:site});try{let app=new StoreMesh({site,initialState:await repository.load(),seedDemoReferences:true});app.repository=repository;const{session,delivery,container,batch}=fixture(app);app.cancelBatch(batch.id,{sessionId:session.id,reason:'persistent correction'},key());await app.flush();const restored=await repository.load(),stored=restored.batches.find(x=>x.id===batch.id),carrier=restored.containers.find(x=>x.id===container.id);assert.equal(stored.status,'CANCELLED');assert.equal(stored.cancelledBy,'receiver');assert.equal(stored.cancelledSessionId,session.id);assert.equal(stored.cancelledDeviceId,'TEST-DEVICE');assert.equal(stored.cancellationReason,'persistent correction');assert.ok(stored.cancelledAt);assert.equal(stored.containerId,null);assert.equal(carrier.status,'AVAILABLE');assert.deepEqual(carrier.batchIds,[]);assert.equal(restored.deliveryBaskets.some(x=>x.deliveryId===delivery.id&&x.batchId===batch.id),false)}finally{await repository.close()}});
