import test from'node:test';
import assert from'node:assert/strict';
import{randomUUID}from'node:crypto';
import{StoreMesh}from'../src/domain.js';
import{PostgresRepository}from'../src/postgres-repository.js';

const key=()=>randomUUID();
const setup=(ageDays=0,zone='COLD_ROOM_CLEAN')=>{let now=Date.parse('2026-08-30T12:00:00.000Z');const app=new StoreMesh({clock:()=>new Date(now).toISOString()});app.registerDevice({code:'DEVICE',type:'TERMINAL',assignedStation:'STORAGE'},key());const session=app.openSession('storage','DEVICE','STORAGE','STORAGE_OPERATOR'),batch={id:randomUUID(),code:'B-AGING',product:'T',grade:'A',size:'L',weightKg:10,zone,status:'RECEIVED',containerId:null,parentIds:[],createdAt:new Date(now-ageDays*86400000).toISOString()};app.state.batches.push(batch);return{app,batch,session,advance:days=>now+=days*86400000}};
const activate=(app,map)=>{const draft=app.createConfiguration({scope:'STORAGE',values:{agingWarningDaysByZone:map},userId:'author'},key());app.transitionConfiguration(draft.id,'APPROVE','reviewer',key());app.transitionConfiguration(draft.id,'ACTIVATE','reviewer',key())};

test('inventory exposes dwell age and raises one storage warning after the zone threshold',()=>{const{app,batch}=setup(6);activate(app,{COLD_ROOM_CLEAN:5});assert.equal(app.inventory().find(x=>x.id===batch.id).agingDays,6);assert.equal(app.inventory().find(x=>x.id===batch.id).agingWarning,true);assert.equal(app.state.exceptions.filter(x=>x.type==='STORAGE_AGING_WARNING'&&x.entityId===batch.id).length,1)});
test('within-tolerance inventory and zones without thresholds keep existing behavior',()=>{const within=setup(2);activate(within.app,{COLD_ROOM_CLEAN:5});assert.equal(within.app.inventory()[0].agingWarning,false);assert.equal(within.app.state.exceptions.length,0);const unconfigured=setup(20,'SORTING');activate(unconfigured.app,{COLD_ROOM_CLEAN:5});assert.equal(unconfigured.app.inventory()[0].agingWarning,false);assert.equal(unconfigured.app.state.exceptions.length,0)});
test('aging resets to current-zone dwell time after a move',()=>{const{app,batch,session,advance}=setup(10);app.move(batch.id,'SORTING',session.id,key());advance(2);assert.equal(app.inventory()[0].agingDays,2)});

test('aging warning promotes the existing operator task without creating duplicates',()=>{const{app,batch}=setup(8);activate(app,{COLD_ROOM_CLEAN:5});const workflow=app.autoTask(batch,'Move to sorting','SORTING','STORAGE_OPERATOR','BATCH_MOVED');const before=workflow.priority,first=app.inventory()[0],second=app.inventory()[0];assert.equal(first.agingTaskId,workflow.id);assert.equal(second.agingTaskId,workflow.id);assert.ok(workflow.priority>before);assert.equal(workflow.storageAgingWarning,true);assert.equal(app.state.tasks.length,1);assert.equal(app.state.exceptions.filter(x=>x.type==='STORAGE_AGING_WARNING'&&x.status==='OPEN').length,1);assert.equal(app.recommendedTask({roles:['STORAGE_OPERATOR'],skills:[]})?.id,workflow.id)});

test('aging warning creates one storage task and ranks older inventory first',()=>{const{app,batch}=setup(6);const older={...batch,id:randomUUID(),code:'B-OLDER',createdAt:new Date(Date.parse(batch.createdAt)-4*86400000).toISOString()};app.state.batches.push(older);activate(app,{COLD_ROOM_CLEAN:5});const items=app.inventory(),task=app.state.tasks.find(x=>x.storageAgingBatchId===batch.id),olderTask=app.state.tasks.find(x=>x.storageAgingBatchId===older.id);app.inventory();assert.equal(items.find(x=>x.id===batch.id).agingTaskId,task.id);assert.equal(task.requiredRole,'STORAGE_OPERATOR');assert.equal(task.storageAgingGenerated,true);assert.equal(app.state.tasks.filter(x=>x.storageAgingGenerated).length,2);assert.ok(olderTask.priority>task.priority);assert.equal(app.recommendedTask({roles:['STORAGE_OPERATOR'],skills:[]})?.id,olderTask.id)});

test('leaving the aging condition resolves the warning and removes its task priority effect',()=>{const{app,batch,session}=setup(8);activate(app,{COLD_ROOM_CLEAN:5});const workflow=app.autoTask(batch,'Review storage plan','COLD_ROOM_CLEAN','STORAGE_OPERATOR',null),original=workflow.priority;app.inventory();assert.ok(workflow.priority>original);app.move(batch.id,'SORTING',session.id,key());const item=app.inventory()[0],warning=app.state.exceptions.find(x=>x.type==='STORAGE_AGING_WARNING'&&x.entityId===batch.id);assert.equal(item.agingWarning,false);assert.equal(item.agingTaskId,null);assert.equal(warning.status,'RESOLVED');assert.equal(workflow.priority,original);assert.equal(workflow.storageAgingWarning,undefined)});

test('aging task priority and warning linkage survive a real PostgreSQL reload',{skip:!process.env.DATABASE_URL},async()=>{const site=`AGING-WORK-${Date.now()}`,repository=new PostgresRepository({connectionString:process.env.DATABASE_URL,siteCode:site});try{let now=Date.parse('2026-08-30T12:00:00.000Z'),app=new StoreMesh({site,clock:()=>new Date(now).toISOString()});app.repository=repository;const batch={id:randomUUID(),code:'B-AGING-PG',product:'T',grade:'A',size:'L',weightKg:10,zone:'COLD_ROOM_CLEAN',status:'RECEIVED',containerId:null,parentIds:[],createdAt:new Date(now-8*86400000).toISOString()};app.state.batches.push(batch);activate(app,{COLD_ROOM_CLEAN:5});const workflow=app.autoTask(batch,'Review storage plan','COLD_ROOM_CLEAN','STORAGE_OPERATOR',null),original=workflow.priority;app.inventory();await app.flush();const restoredState=await repository.load();app=new StoreMesh({site,clock:()=>new Date(now).toISOString(),initialState:restoredState});const restored=app.state.tasks.find(x=>x.id===workflow.id),item=app.inventory().find(x=>x.id===batch.id);assert.ok(restored.priority>original);assert.equal(restored.storageAgingBatchId,batch.id);assert.equal(restored.storageAgingWarning,true);assert.equal(item.agingTaskId,restored.id);assert.equal(app.state.tasks.filter(x=>x.storageAgingBatchId===batch.id).length,1)}finally{await repository.close()}});
