import test from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {StoreMesh} from '../src/domain.js';
import {PostgresRepository} from '../src/postgres-repository.js';

const key=()=>randomUUID(),now=()=>new Date().toISOString();
function base(app=new StoreMesh()){
  const session=app.openSession('trace','TEST-DEVICE'),container=app.createContainer({capacityKg:100},key()),root=app.receive({sessionId:session.id,containerId:container.id,supplier:'S',product:'T',grade:'A',size:'L',weightKg:20},key());
  return{app,session,root};
}
function customerPath(app,batch){const customer=app.createCustomer({code:'C-RECALL',name:'Recall Customer'},key()),order=app.createSalesOrder({customerId:customer.id,items:[{packageType:'CARTON',quantity:1}]},key()),unit={id:key(),code:'UNIT-TRACE',type:'POUCH',level:'UNIT',parentPackageId:null,status:'READY_TO_SHIP',shipmentId:null,items:[{batchId:batch.id,weightKg:1}],createdAt:now()},carton={id:key(),code:'CARTON-TRACE',type:'CARTON',level:'CARTON',parentPackageId:null,status:'SHIPPED',shipmentId:null,items:[],createdAt:now()};unit.parentPackageId=carton.id;app.state.packages.push(unit,carton);const shipment={id:key(),code:'S-TRACE',kind:'CUSTOMER',salesOrderId:order.id,customerId:customer.id,status:'SHIPPED',packageIds:[carton.id],shippingBoxIds:[],createdAt:now()};carton.shipmentId=shipment.id;app.state.shipments.push(shipment);return{customer,order,unit,carton,shipment}}

test('root follows split descendants to outer carton shipment and customer',()=>{const{app,root}=base(),left={...root,id:key(),code:'LEFT',parentIds:[root.id],grade:'A'},right={...root,id:key(),code:'RIGHT',parentIds:[root.id],grade:'B'};app.state.batches.push(left,right);const path=customerPath(app,left),result=app.traceForward(root.id);assert.deepEqual(new Set(result.descendantBatches.map(x=>x.id)),new Set([left.id,right.id]));assert.equal(result.packages[0].outerPackage.id,path.carton.id);assert.equal(result.packages[0].shipment.id,path.shipment.id);assert.equal(result.packages[0].customer.code,'C-RECALL')});

test('fresh lot contribution follows shipping box to customer',()=>{const{app,root}=base(),customer=app.createCustomer({code:'FRESH-C',name:'Fresh Customer'},key()),order=app.createSalesOrder({customerId:customer.id,items:[{packageType:'FRESH_SHIPPING_BOX',quantity:1}]},key()),lot={id:key(),code:'FN-X',batchId:root.id,sourceContributions:[{batchId:root.id,count:2,weightKg:2}],createdAt:now()},box={id:key(),code:'FB-X',type:'FRESH_SHIPPING_BOX',status:'SHIPPED',items:[{netLotId:lot.id,count:2}],shipmentId:null,createdAt:now()},shipment={id:key(),code:'S-FRESH',kind:'CUSTOMER',salesOrderId:order.id,customerId:customer.id,status:'SHIPPED',packageIds:[],shippingBoxIds:[box.id],createdAt:now()};box.shipmentId=shipment.id;app.state.freshNetLots.push(lot);app.state.shippingBoxes.push(box);app.state.shipments.push(shipment);const result=app.traceForward(root.id);assert.equal(result.freshLots[0].box.id,box.id);assert.equal(result.freshLots[0].shipment.id,shipment.id);assert.equal(result.freshLots[0].customer.name,'Fresh Customer')});

test('internal transfer is an explicit local trace boundary',()=>{const{app,root}=base(),unit={id:key(),code:'UNIT-IS',type:'POUCH',level:'UNIT',parentPackageId:null,status:'READY_TO_SHIP',shipmentId:null,items:[{batchId:root.id,weightKg:1}],createdAt:now()},shipment={id:key(),code:'IS-001',shipmentCode:'IS-001',kind:'INTERNAL_TRANSFER',destinationSite:'DUBAI',status:'DISPATCHED',packageIds:[unit.id],createdAt:now()};unit.shipmentId=shipment.id;app.state.packages.push(unit);app.state.shipments.push(shipment);const found=app.traceForward(root.id).packages[0].shipment;assert.equal(found.crossesTransferBoundary,true);assert.equal(found.destinationSite,'DUBAI');assert.equal(found.shipmentCode,'IS-001')});

test('unpackaged inventory returns empty downstream collections',()=>{const{app,root}=base(),result=app.traceForward(root.id);assert.deepEqual(result.packages,[]);assert.deepEqual(result.freshLots,[]);assert.deepEqual(result.integrityIssues,[])});

test('broken package hierarchy is reported without crashing',()=>{const{app,root}=base(),unit={id:key(),code:'BROKEN',type:'POUCH',level:'UNIT',parentPackageId:key(),status:'READY_TO_SHIP',items:[{batchId:root.id,weightKg:1}],createdAt:now()};app.state.packages.push(unit);const result=app.traceForward(root.id);assert.equal(result.packages[0].outerPackage.id,unit.id);assert.equal(result.integrityIssues[0].type,'PACKAGE_PARENT_MISSING')});

test('forward recall path survives PostgreSQL reload',{skip:!process.env.DATABASE_URL},async()=>{const repository=new PostgresRepository({connectionString:process.env.DATABASE_URL,siteCode:`FR29-${Date.now()}`});try{const app=new StoreMesh({site:repository.siteCode,initialState:await repository.load(),seedDemoReferences:true});app.repository=repository;const{root}=base(app),path=customerPath(app,root);app.persist();await app.flush();const restored=new StoreMesh({site:repository.siteCode,initialState:await repository.load()}),result=restored.traceForward(root.id);assert.equal(result.packages[0].outerPackage.id,path.carton.id);assert.equal(result.packages[0].shipment.id,path.shipment.id);assert.equal(result.packages[0].customer.code,path.customer.code)}finally{await repository.close()}});
