import test from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {StoreMesh} from '../src/domain.js';

const key=()=>randomUUID();
const activate=(app,values)=>{const draft=app.createConfiguration({scope:'PACKAGING',values,userId:'author'},key());app.transitionConfiguration(draft.id,'APPROVE','reviewer',key());app.transitionConfiguration(draft.id,'ACTIVATE','reviewer',key());return draft};
const fixture=()=>{const app=new StoreMesh(),session=app.openSession('packer','PDA-PACK-01','PACKAGING','PACKAGING_OPERATOR'),container=app.createContainer({capacityKg:20},key()),batch=app.receive({sessionId:session.id,containerId:container.id,supplier:'S',product:'T',grade:'A',size:'L',weightKg:10},key());batch.status='DRIED';app.weighForPackaging({sessionId:session.id,batchId:batch.id,weightKg:10},key());return{app,session,batch}};
const createUnit=(context,input={})=>context.app.createPackage({sessionId:context.session.id,type:'POUCH',level:'UNIT',items:[{batchId:context.batch.id,weightKg:1}],targetWeightKg:1,tolerancePercent:0,...input},key());

test('site-required scale evidence rejects an unmeasured UNIT and accepts a valid captured measurement',()=>{const context=fixture();activate(context.app,{targetWeightKg:1,weightTolerancePercent:0,requireScaleEvidence:true});assert.throws(()=>createUnit(context),error=>error.code==='PACKAGE_MEASUREMENT_REQUIRED'&&error.status===409);const scale=context.app.registerDevice({code:'PACK-SCALE',type:'SCALE',assignedStation:'PACKAGING'},key()),measurement=context.app.captureMeasurement({sessionId:context.session.id,scaleId:scale.id,batchId:context.batch.id,purpose:'PACKAGE_UNIT',rawReadingKg:1},key()),unit=createUnit(context,{measurementId:measurement.id});assert.equal(unit.measuredWeightKg,1);assert.equal(measurement.consumedBy,'PACKAGE_UNIT')});

test('optional scale evidence preserves legacy UNIT creation with false or no active configuration',()=>{assert.equal(createUnit(fixture()).level,'UNIT');const context=fixture();activate(context.app,{targetWeightKg:1,weightTolerancePercent:0,requireScaleEvidence:false});assert.equal(createUnit(context).level,'UNIT')});

test('PACKAGING configuration recognizes requireScaleEvidence only as a boolean',()=>{const app=new StoreMesh();assert.throws(()=>app.createConfiguration({scope:'PACKAGING',values:{requireScaleEvidence:'true'},userId:'author'},key()),error=>error.code==='CONFIGURATION_SCHEMA_INVALID');assert.equal(app.createConfiguration({scope:'PACKAGING',values:{requireScaleEvidence:true},userId:'author'},key()).values.requireScaleEvidence,true)});

const stockCartons=app=>{const item=app.createConsumable({code:'CARTON',name:'Carton',reorderThreshold:0},key());app.receiveConsumable(item.id,{quantity:10,source:'test'},key())};
const readyUnit=(context,product='T',grade='A')=>{const container=context.app.createContainer({capacityKg:20},key()),batch=context.app.receive({sessionId:context.session.id,containerId:container.id,supplier:'S',product,grade,size:'L',weightKg:5},key());batch.status='DRIED';context.app.weighForPackaging({sessionId:context.session.id,batchId:batch.id,weightKg:5},key());const unit=context.app.createPackage({sessionId:context.session.id,type:'POUCH',level:'UNIT',items:[{batchId:batch.id,weightKg:1}],targetWeightKg:1,tolerancePercent:0},key());for(const action of['PACK','SEAL','PRINT','PRINT_SUCCESS','READY'])context.app.transitionPackage(unit.id,action,key());return unit};

test('carton content is built only by physical UNIT scans',()=>{const context=fixture();stockCartons(context.app);const unit=readyUnit(context),carton=context.app.createPackage({sessionId:context.session.id,type:'CARTON',level:'CARTON'},key());assert.deepEqual(carton.childPackageIds,[]);assert.throws(()=>context.app.createPackage({sessionId:context.session.id,type:'CARTON',level:'CARTON',childPackageIds:[unit.id]},key()),error=>error.code==='CARTON_PREALLOCATION_FORBIDDEN');assert.throws(()=>context.app.transitionPackage(carton.id,'SEAL',key()),error=>error.code==='CARTON_ITEM_SCAN_REQUIRED');const scan=context.app.scanPackageItem(carton.id,{sessionId:context.session.id,unitPackageCode:unit.code},key());assert.equal(scan.unitPackageId,unit.id);assert.deepEqual(carton.childPackageIds,[unit.id]);assert.equal(unit.parentPackageId,carton.id);context.app.transitionPackage(carton.id,'PACK',key());assert.equal(context.app.transitionPackage(carton.id,'SEAL',key()).status,'READY_FOR_LABEL')});

test('scan-first carton enforces mixed-content policy incrementally',()=>{const context=fixture();stockCartons(context.app);activate(context.app,{targetWeightKg:1,weightTolerancePercent:0,allowMixedProducts:false,allowMixedGrades:false});const one=readyUnit(context,'T'),two=readyUnit(context,'Truffle'),carton=context.app.createPackage({sessionId:context.session.id,type:'CARTON',level:'CARTON'},key());context.app.scanPackageItem(carton.id,{sessionId:context.session.id,unitPackageCode:one.code},key());assert.throws(()=>context.app.scanPackageItem(carton.id,{sessionId:context.session.id,unitPackageCode:two.code},key()),error=>error.code==='CARTON_MIXED_CONTENT_FORBIDDEN');assert.deepEqual(carton.childPackageIds,[one.id]);assert.equal(two.parentPackageId,null)});
