import test from 'node:test';
import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import { StoreMesh } from '../src/domain.js';
import { PostgresRepository } from '../src/postgres-repository.js';

const key=()=>randomUUID();
const fixture=()=>{const app=new StoreMesh(),session=app.openSession('washer','TEST-DEVICE','WASHING','WASHING_OPERATOR'),container=app.createContainer({capacityKg:20},key()),batch=app.receive({sessionId:session.id,containerId:container.id,supplier:'S',product:'T',grade:'A',size:'L',weightKg:10},key());Object.assign(batch,{status:'SORTED',zone:'WASHING'});Object.assign(container,{zone:'WASHING',status:'READY_FOR_WASHING'});return{app,session,container,batch}};
const checklist=app=>app.createQcChecklist({code:`SORT-${key()}`,product:'T',stage:'SORTING',name:'Sorting release',items:[{code:'OK',prompt:'Sorting output accepted'}]},key());
const inspect=(app,batch,list,result)=>app.qualityCheck({batchId:batch.id,stage:'SORTING',checklistId:list.id,responses:[{itemCode:'OK',value:result==='APPROVED'}],result,inspectorId:key(),actorRoles:['QUALITY_OPERATOR'],attestation:{confirmed:true,role:'QUALITY_OPERATOR'}},key());
const wash=({app,session,container,batch})=>app.transform({sessionId:session.id,containerId:container.id,inputs:[{batchId:batch.id}],process:'WASH'},key());

test('an active Sorting checklist gates Washing until a matching approval exists',()=>{const context=fixture(),list=checklist(context.app);assert.throws(()=>wash(context),error=>error.code==='BATCH_QC_APPROVAL_REQUIRED'&&error.status===409);inspect(context.app,context.batch,list,'APPROVED');assert.equal(wash(context),context.batch)});

test('a rejected Sorting result remains blocked',()=>{const context=fixture(),list=checklist(context.app);inspect(context.app,context.batch,list,'REJECTED');assert.throws(()=>wash(context),error=>error.code==='BATCH_QC_REJECTED')});

test('products without an active Sorting checklist retain the existing workflow',()=>{const context=fixture();assert.equal(wash(context),context.batch)});

test('open high and critical batch concerns block operations until resolved while advisory concerns do not',()=>{for(const severity of['HIGH','CRITICAL']){const context=fixture(),raised=context.app.raiseException({type:'QUALITY_CONCERN',entityType:'BATCH',entityId:context.batch.id,severity,note:'Unexpected discoloration'},key());assert.throws(()=>wash(context),error=>error.code==='BATCH_EXCEPTION_OPEN'&&error.details.exceptionId===raised.id&&error.details.exceptionType==='QUALITY_CONCERN');context.app.resolveException(raised.id,{decision:'RESOLVED',resolvedBy:'manager',resolutionNote:'Inspected and cleared'},key());assert.equal(wash(context),context.batch)}for(const severity of['WARNING','INFO']){const context=fixture();context.app.raiseException({type:'QUALITY_CONCERN',entityType:'BATCH',entityId:context.batch.id,severity,note:'Observe'},key());assert.equal(wash(context),context.batch)}});

test('operator concern note and rework lineage survive a real PostgreSQL reload',{skip:!process.env.DATABASE_URL},async()=>{const repository=new PostgresRepository({connectionString:process.env.DATABASE_URL,siteCode:`FR27B-${Date.now()}`});try{const context=fixture();context.app.repository=repository;context.app.site=repository.siteCode;const raised=context.app.raiseException({type:'QUALITY_CONCERN',entityType:'BATCH',entityId:context.batch.id,severity:'HIGH',note:'  Surface damage near stem  '},key()),list=checklist(context.app),rejected=inspect(context.app,context.batch,list,'REJECTED'),reinspection=inspect(context.app,context.batch,list,'APPROVED');await context.app.flush();const restored=await repository.load(),stored=restored.exceptions.find(x=>x.id===raised.id),storedReinspection=restored.qualityChecks.find(x=>x.id===reinspection.id);assert.equal(stored.note,'Surface damage near stem');assert.equal(stored.status,'OPEN');assert.equal(storedReinspection.previousCorrectiveTaskId,rejected.correctiveTaskId);assert.equal(restored.tasks.find(x=>x.id===rejected.correctiveTaskId).requiredRole,'QUALITY_OPERATOR')}finally{await repository.close()}});

test('corrective work defaults to Quality and reinspection links to the still-open task',()=>{const context=fixture(),list=checklist(context.app),rejected=inspect(context.app,context.batch,list,'REJECTED'),task=context.app.state.tasks.find(x=>x.id===rejected.correctiveTaskId);assert.equal(task.requiredRole,'QUALITY_OPERATOR');const reinspection=inspect(context.app,context.batch,list,'APPROVED');assert.equal(reinspection.previousCorrectiveTaskId,task.id)});

test('an explicit rework role overrides the Quality default',()=>{const context=fixture(),list=checklist(context.app),rejected=context.app.qualityCheck({batchId:context.batch.id,stage:'SORTING',checklistId:list.id,responses:[{itemCode:'OK',value:false}],result:'REJECTED',reworkRole:'WASHING_OPERATOR',inspectorId:key(),actorRoles:['QUALITY_OPERATOR'],attestation:{confirmed:true,role:'QUALITY_OPERATOR'}},key());assert.equal(context.app.state.tasks.find(x=>x.id===rejected.correctiveTaskId).requiredRole,'WASHING_OPERATOR')});
