import test from'node:test';import assert from'node:assert/strict';import{randomUUID}from'node:crypto';import{StoreMesh}from'../src/domain.js';import{PostgresRepository}from'../src/postgres-repository.js';
const key=()=>randomUUID();
const receive=(app,session,supplier,weight=5)=>{const container=app.createContainer({capacityKg:20},key());return app.receive({sessionId:session.id,containerId:container.id,supplier,product:'T',grade:'A',size:'L',weightKg:weight},key())};
const merge=(app,session,parents)=>{const container=app.createContainer({capacityKg:20,zone:'SORTING',designatedZones:['SORTING']},key()),child=app.transform({sessionId:session.id,process:'MERGE',containerId:container.id,inputs:parents.map(batch=>({batchId:batch.id,consumeWeightKg:2})),outputWeightKg:parents.length*2,grade:'A',size:'L'},key());return child};

test('mixed-supplier merge snapshots every supplier contribution while keeping scalar identity honest',()=>{const app=new StoreMesh(),session=app.openSession('sorter','TEST-DEVICE'),a=receive(app,session,'S'),b=receive(app,session,'S1'),child=merge(app,session,[a,b]);assert.equal(child.supplier,null);assert.equal(child.supplierId,null);assert.deepEqual(new Set(child.suppliers),new Set(['S','S1']));assert.equal(child.supplierIds.length,2);assert.deepEqual(Object.fromEntries(child.supplierContributions.map(x=>[x.supplier,x.contributedWeightKg])),{S:2,S1:2})});

test('same-supplier merge retains scalar identity and deduplicates its contribution',()=>{const app=new StoreMesh(),session=app.openSession('sorter','TEST-DEVICE'),a=receive(app,session,'S'),b=receive(app,session,'S'),child=merge(app,session,[a,b]);assert.equal(child.supplier,'S');assert.equal(child.supplierId,a.supplierId);assert.deepEqual(child.suppliers,['S']);assert.deepEqual(child.supplierIds,[a.supplierId]);assert.deepEqual(child.supplierContributions,[{supplierId:a.supplierId,supplier:'S',contributedWeightKg:4}])});

test('multi-parent MERGE requires and audits a valid physical output container',()=>{const app=new StoreMesh(),session=app.openSession('sorter','TEST-DEVICE'),a=receive(app,session,'S'),b=receive(app,session,'S1'),input={sessionId:session.id,process:'MERGE',inputs:[{batchId:a.id,consumeWeightKg:2},{batchId:b.id,consumeWeightKg:2}],outputWeightKg:4};assert.throws(()=>app.transform(input,key()),error=>error.code==='MERGE_PHYSICAL_CONFIRMATION_REQUIRED');const container=app.createContainer({capacityKg:20,zone:'SORTING',designatedZones:['SORTING']},key()),child=app.transform({...input,containerId:container.id},key()),event=app.state.audit.findLast(x=>x.type==='BATCH_TRANSFORMED');assert.equal(child.containerId,container.id);assert.equal(event.afterState.containerId,container.id)});

test('supplier snapshots survive a real PostgreSQL reload',{skip:!process.env.DATABASE_URL},async()=>{const site=`FR76-A-${Date.now()}`,repository=new PostgresRepository({connectionString:process.env.DATABASE_URL,siteCode:site});try{const app=new StoreMesh({site,initialState:await repository.load()});app.repository=repository;const session=app.openSession('sorter','TEST-DEVICE'),child=merge(app,session,[receive(app,session,'S'),receive(app,session,'S1')]);await app.flush();const loaded=(await repository.load()).batches.find(x=>x.id===child.id);assert.deepEqual(new Set(loaded.suppliers),new Set(['S','S1']));assert.equal(loaded.supplierContributions.length,2);assert.equal(loaded.supplier,null)}finally{await repository.close()}});
