import test from'node:test';
import assert from'node:assert/strict';
import{randomUUID}from'node:crypto';
import{StoreMesh}from'../src/domain.js';
import{PostgresRepository}from'../src/postgres-repository.js';

const key=()=>randomUUID(),activate=(app,required)=>{const draft=app.createConfiguration({scope:'WAREHOUSE_MOVEMENT',values:{requireDestinationScan:required},userId:'author'},key());app.transitionConfiguration(draft.id,'APPROVE','reviewer',key());app.transitionConfiguration(draft.id,'ACTIVATE','reviewer',key())},fixture=(app=new StoreMesh())=>{const session=app.openSession('storage','TEST-DEVICE','STORAGE','STORAGE_OPERATOR'),container=app.createContainer({capacityKg:20},key());return{app,session,container}};

test('public container movement rejects a missing or mismatched physical container scan',()=>{const{app,session,container}=fixture();assert.throws(()=>app.moveContainer(container.id,'SORTING',session.id,key(),null,{}),e=>e.code==='CONTAINER_SCAN_REQUIRED');assert.throws(()=>app.moveContainer(container.id,'SORTING',session.id,key(),null,{scannedContainerId:key()}),e=>e.code==='CONTAINER_SCAN_MISMATCH')});
test('destination scan is required and must match only when configured',()=>{const required=fixture();activate(required.app,true);assert.throws(()=>required.app.moveContainer(required.container.id,'SORTING',required.session.id,key(),null,{scannedContainerId:required.container.id}),e=>e.code==='MOVEMENT_DESTINATION_SCAN_REQUIRED');assert.throws(()=>required.app.moveContainer(required.container.id,'SORTING',required.session.id,key(),null,{scannedContainerId:required.container.id,destinationZoneCode:'WASHING'}),e=>e.code==='MOVEMENT_DESTINATION_SCAN_REQUIRED');assert.equal(required.app.moveContainer(required.container.id,'SORTING',required.session.id,key(),null,{scannedContainerId:required.container.id,destinationZoneCode:'SORTING'}).to,'SORTING');const optional=fixture();assert.equal(optional.app.moveContainer(optional.container.id,'SORTING',optional.session.id,key(),null,{scannedContainerId:optional.container.id}).to,'SORTING')});
test('scan configuration and movement survive real PostgreSQL reload',{skip:!process.env.DATABASE_URL},async()=>{const site=`FR61-${Date.now()}`,repository=new PostgresRepository({connectionString:process.env.DATABASE_URL,siteCode:site});try{let app=new StoreMesh({site,initialState:await repository.load(),seedDemoReferences:true});app.repository=repository;const{session,container}=fixture(app);activate(app,true);app.moveContainer(container.id,'SORTING',session.id,key(),null,{scannedContainerId:container.id,destinationZoneCode:'SORTING'});await app.flush();const restored=await repository.load();assert.equal(restored.configurationVersions.find(x=>x.scope==='WAREHOUSE_MOVEMENT'&&x.status==='ACTIVE').values.requireDestinationScan,true);assert.equal(restored.containers.find(x=>x.id===container.id).zone,'SORTING');assert.ok(restored.movements.some(x=>x.containerId===container.id&&x.to==='SORTING'))}finally{await repository.close()}});
