import test from 'node:test';
import assert from 'node:assert/strict';
import {StoreMesh} from '../src/domain.js';
import {PostgresRepository} from '../src/postgres-repository.js';

const key=()=>crypto.randomUUID();
const fixture=(app=new StoreMesh())=>{const session=app.openSession('fresh','TEST-DEVICE','FRESH_EXPORT','FRESH_EXPORT_OPERATOR'),container=app.createContainer({capacityKg:30},key()),batch=app.receive({sessionId:session.id,containerId:container.id,supplier:'S',product:'T',grade:'A',size:'L',weightKg:20},key());Object.assign(batch,{status:'SORTED',destination:'FRESH_EXPORT',zone:'FRESH_EXPORT'});Object.assign(container,{zone:'FRESH_EXPORT',status:'SORTED',activeSessionId:null});return{app,session,container,batch}};
const activate=(app,scope,values)=>{const draft=app.createConfiguration({scope,values,userId:'author'},key());app.transitionConfiguration(draft.id,'APPROVE','reviewer',key());app.transitionConfiguration(draft.id,'ACTIVATE','reviewer',key());return draft};
const stockShippingBoxes=app=>{const item=app.createConsumable({code:'EPS_BOX',name:'EPS box',reorderThreshold:0},key());app.receiveConsumable(item.id,{quantity:10,source:'test'},key())};

test('active Fresh Export configuration rejects defaults and ignores client-expanded weights',()=>{const{app,session,container,batch}=fixture();activate(app,'FRESH_EXPORT',{allowedNetWeightsKg:[.5,1,2]});const input={sessionId:session.id,batchId:batch.id,containerId:container.id,count:1};assert.throws(()=>app.createFreshNetLot({...input,unitWeightKg:5,allowedWeightsKg:[5]},key()),e=>e.code==='FRESH_NET_CONFIGURATION_INVALID');const lot=app.createFreshNetLot({...input,unitWeightKg:2,allowedWeightsKg:[5]},key());assert.equal(lot.unitWeightKg,2)});
test('client allowed weights remain the compatibility behavior without active Fresh Export configuration',()=>{const{app,session,container,batch}=fixture(),lot=app.createFreshNetLot({sessionId:session.id,batchId:batch.id,containerId:container.id,unitWeightKg:2,count:1,allowedWeightsKg:[2]},key());assert.equal(lot.unitWeightKg,2)});
test('shipping-box label includes total net count and total weight',()=>{const{app,session,container,batch}=fixture();stockShippingBoxes(app);const lot=app.createFreshNetLot({sessionId:session.id,batchId:batch.id,containerId:container.id,unitWeightKg:.5,count:6},key()),box=app.createShippingBox({sessionId:session.id,allocations:[{netLotId:lot.id,count:4}]},key()),label=app.state.labels.find(x=>x.entityType==='FRESH_SHIPPING_BOX'&&x.entityId===box.id);assert.equal(label.payload.totalNetCount,4);assert.equal(label.payload.totalWeightKg,2)});
test('shipping-box label totals survive PostgreSQL reload',{skip:!process.env.DATABASE_URL},async()=>{const site=`FR23-${Date.now()}`,repository=new PostgresRepository({connectionString:process.env.DATABASE_URL,siteCode:site});try{const app=new StoreMesh({site,initialState:await repository.load(),seedDemoReferences:true});app.repository=repository;const{session,container,batch}=fixture(app);stockShippingBoxes(app);const lot=app.createFreshNetLot({sessionId:session.id,batchId:batch.id,containerId:container.id,unitWeightKg:1,count:5},key()),box=app.createShippingBox({sessionId:session.id,allocations:[{netLotId:lot.id,count:3}]},key());await app.flush();const restored=await repository.load(),label=restored.labels.find(x=>x.entityType==='FRESH_SHIPPING_BOX'&&x.entityId===box.id);assert.equal(label.payload.totalNetCount,3);assert.equal(label.payload.totalWeightKg,3)}finally{await repository.close()}});
