import test from'node:test';
import assert from'node:assert/strict';
import{StoreMesh}from'../src/domain.js';

const key=()=>crypto.randomUUID();
function fixture(){const app=new StoreMesh({site:'IRAN'}),session=app.openSession('loader','TEST-DEVICE','SHIPPING','SHIPPING_OPERATOR'),container=app.createContainer({capacityKg:20},key()),batch=app.receive({sessionId:session.id,containerId:container.id,supplier:'S',product:'T',grade:'A',size:'L',weightKg:8},key()),pkg=app.createPackage({sessionId:session.id,type:'POUCH',items:[{batchId:batch.id,weightKg:2}]},key());for(const action of['PACK','SEAL','PRINT','PRINT_SUCCESS','READY'])app.transitionPackage(pkg.id,action,key());const stage=app.batchQcStage(batch),checklist=app.createQcChecklist({code:`QC-${key()}`,product:batch.product,stage,name:'Transfer QC',items:[{code:'OK',prompt:'Approved'}]},key()),record=result=>app.qualityCheck({sessionId:app.state.sessions.find(x=>x.status==='ACTIVE')?.id,batchId:batch.id,stage,checklistId:checklist.id,responses:[{itemCode:'OK',value:result==='APPROVED'}],result,notes:result,inspectorId:key(),actorRoles:['QUALITY_OPERATOR'],attestation:{confirmed:true,role:'QUALITY_OPERATOR'}},key());record('APPROVED');return{app,session,batch,pkg,record}}

test('internal LOAD requires session and vehicle and revalidates every reserved package',()=>{let x=fixture(),shipment=x.app.createInternalShipment({destinationSite:'DUBAI',packageIds:[x.pkg.id]},key());assert.throws(()=>x.app.updateInternalShipment(shipment.id,'LOAD',{vehicle:'TRUCK'},key()),e=>e.code==='SESSION_NOT_FOUND');assert.throws(()=>x.app.updateInternalShipment(shipment.id,'LOAD',{sessionId:x.session.id},key()),e=>e.code==='SHIPMENT_VEHICLE_REQUIRED');x.app.state.packages.find(p=>p.id===x.pkg.id).status='DAMAGED';assert.throws(()=>x.app.updateInternalShipment(shipment.id,'LOAD',{sessionId:x.session.id,vehicle:'TRUCK'},key()),e=>e.code==='PACKAGE_NOT_READY_TO_SHIP');x=fixture();shipment=x.app.createInternalShipment({destinationSite:'DUBAI',packageIds:[x.pkg.id]},key());x.record('REJECTED');assert.throws(()=>x.app.updateInternalShipment(shipment.id,'LOAD',{sessionId:x.session.id,vehicle:'TRUCK'},key()),e=>e.code==='BATCH_QC_REJECTED')});

test('internal DISPATCH revalidates eligibility in addition to physical package scans',()=>{const x=fixture(),shipment=x.app.createInternalShipment({destinationSite:'DUBAI',packageIds:[x.pkg.id]},key());x.app.updateInternalShipment(shipment.id,'LOAD',{sessionId:x.session.id,vehicle:'TRUCK-2'},key());assert.equal(shipment.loadedBy,'loader');assert.equal(shipment.loadedDeviceId,'TEST-DEVICE');assert.throws(()=>x.app.updateInternalShipment(shipment.id,'DISPATCH',{sessionId:x.session.id,scannedPackageCodes:[]},key()),e=>e.code==='TRANSFER_PHYSICAL_SCAN_REQUIRED');x.pkg.locked=true;assert.throws(()=>x.app.updateInternalShipment(shipment.id,'DISPATCH',{sessionId:x.session.id,scannedPackageCodes:[x.pkg.code]},key()),e=>e.code==='SHIPMENT_ITEM_LOCKED');x.pkg.locked=false;x.app.updateInternalShipment(shipment.id,'DISPATCH',{sessionId:x.session.id,scannedPackageCodes:[x.pkg.code]},key());assert.equal(shipment.status,'DISPATCHED')});
