import test from'node:test';
import assert from'node:assert/strict';
import{StoreMesh}from'../src/domain.js';

const key=()=>crypto.randomUUID();
function approve(app,batch){const stage=app.batchQcStage(batch),checklist=app.createQcChecklist({code:`QC-${key()}`,product:batch.product,stage,name:'Transfer QC',items:[{code:'OK',prompt:'Approved'}]},key());app.qualityCheck({batchId:batch.id,stage,checklistId:checklist.id,responses:[{itemCode:'OK',value:true}],result:'APPROVED',notes:'approved',inspectorId:key(),actorRoles:['QUALITY_OPERATOR'],attestation:{confirmed:true,role:'QUALITY_OPERATOR'}},key())}
function sourceFixture(){const source=new StoreMesh({site:'IRAN'}),session=source.openSession('source-operator','TEST-DEVICE','SHIPPING','SHIPPING_OPERATOR'),container=source.createContainer({capacityKg:10},key()),batch=source.receive({sessionId:session.id,containerId:container.id,supplier:'S',product:'Truffle',grade:'A',size:'L',weightKg:4},key()),pkg=source.createPackage({sessionId:session.id,type:'POUCH',items:[{batchId:batch.id,weightKg:2}]},key());for(const action of['PACK','SEAL','PRINT','PRINT_SUCCESS','READY'])source.transitionPackage(pkg.id,action,key());approve(source,batch);return{source,session,batch,pkg}}
function dispatchedManifest(){const x=sourceFixture(),shipment=x.source.createInternalShipment({packageIds:[x.pkg.id],destinationSite:'DUBAI'},key());x.source.updateInternalShipment(shipment.id,'LOAD',{sessionId:x.session.id,vehicle:'TRUCK-1'},key());assert.throws(()=>x.source.updateInternalShipment(shipment.id,'DISPATCH',{sessionId:x.session.id,scannedPackageCodes:[]},key()),e=>e.code==='TRANSFER_PHYSICAL_SCAN_REQUIRED');x.source.updateInternalShipment(shipment.id,'DISPATCH',{sessionId:x.session.id,scannedPackageCodes:[x.pkg.code]},key());return{...x,shipment,manifest:x.source.shipmentManifest(shipment.id)}}
function destination(){const app=new StoreMesh({site:'DUBAI'}),session=app.openSession('actual-receiver','TEST-DEVICE','RECEIVING','RECEIVING_OPERATOR'),container=app.createContainer({capacityKg:20},key());return{app,session,container}}

test('destination receipt requires a physical container and derives receiver from its session',()=>{const{manifest,pkg}=dispatchedManifest(),target=destination(),body={sessionId:target.session.id,manifest,receivedBy:'forged',scannedPackageCodes:[pkg.code]};assert.throws(()=>target.app.receiveInternalTransfer(body,key()),e=>e.code==='CONTAINER_SCAN_REQUIRED');const result=target.app.receiveInternalTransfer({...body,containerId:target.container.id},key());assert.equal(result.transfer.receivedBy,'actual-receiver');assert.equal(result.transfer.receiptScan.containerId,target.container.id);assert.ok(result.batches.every(batch=>batch.containerId===target.container.id));assert.deepEqual(target.container.batchIds,result.batches.map(x=>x.id));assert.equal(target.container.status,'IN_USE')});

test('tampered manifest fields still fail signature verification',()=>{const{manifest,pkg}=dispatchedManifest();for(const changed of[{...manifest,destinationSite:'ROME'},{...manifest,status:'READY'},{...manifest,packages:[{...manifest.packages[0],items:[{...manifest.packages[0].items[0],weightKg:200}]}]}]){const target=destination();assert.throws(()=>target.app.receiveInternalTransfer({sessionId:target.session.id,containerId:target.container.id,manifest:changed,scannedPackageCodes:[pkg.code]},key()),e=>e.code==='TRANSFER_SIGNATURE_INVALID')}});

test('signed manifests with duplicate package or batch identities are rejected',()=>{const{source,manifest,pkg}=dispatchedManifest(),sign=unsigned=>({...unsigned,signature:source.signTransferManifest(unsigned)}),{signature:_signature,...unsigned}=manifest;for(const packages of[[unsigned.packages[0],structuredClone(unsigned.packages[0])],[{...unsigned.packages[0],items:[unsigned.packages[0].items[0],structuredClone(unsigned.packages[0].items[0])]}]]){const target=destination(),duplicate=sign({...unsigned,shipmentCode:key(),packages});assert.throws(()=>target.app.receiveInternalTransfer({sessionId:target.session.id,containerId:target.container.id,manifest:duplicate,scannedPackageCodes:[pkg.code]},key()),e=>e.code==='TRANSFER_MANIFEST_DUPLICATE')}});
