import test from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {StoreMesh} from '../src/domain.js';
import {PostgresRepository} from '../src/postgres-repository.js';

const key=()=>randomUUID();
function fixture(app=new StoreMesh()){const session=app.openSession('storage-user','TEST-DEVICE','STORAGE','STORAGE_OPERATOR'),container=app.createContainer({capacityKg:20},key()),batch=app.receive({sessionId:session.id,containerId:container.id,supplier:'S',product:'T',grade:'A',size:'L',weightKg:7},key());return{app,session,container,batch}}

test('contained Batch cannot move independently but free-standing Batch can',()=>{const{app,session,container,batch}=fixture();assert.throws(()=>app.move(batch.id,'COLD_ROOM_CLEAN',session.id,key()),e=>e.code==='BATCH_MOVE_REQUIRES_CONTAINER_MOVE');assert.equal(batch.zone,'RECEIVING');assert.equal(container.zone,'RECEIVING');container.batchIds=[];batch.containerId=null;const movement=app.move(batch.id,'COLD_ROOM_CLEAN',session.id,key(),null,'manual relocation');assert.equal(batch.zone,'COLD_ROOM_CLEAN');assert.deepEqual({quantityKg:movement.quantityKg,unit:movement.unit,userId:movement.userId,objectType:movement.objectType,movementType:movement.movementType,reason:movement.reason},{quantityKg:7,unit:'KG',userId:'storage-user',objectType:'BATCH',movementType:'ZONE_CHANGE',reason:'manual relocation'})});

test('Container movement records its own row and one contextual cascade row per Batch',()=>{const{app,session,container,batch}=fixture(),second=app.receive({sessionId:session.id,containerId:app.createContainer({capacityKg:10},key()).id,supplier:'S',product:'T',grade:'A',size:'L',weightKg:3},key());app.assignBatchToContainer(container.id,second.id,session.id,key());const movement=app.moveContainer(container.id,'COLD_ROOM_DIRTY',session.id,key(),'scheduled storage'),rows=app.state.movements.filter(x=>x.containerId===container.id);assert.equal(movement.objectType,'CONTAINER');assert.equal(movement.quantityKg,10);assert.equal(rows.length,3);assert.deepEqual(new Set(rows.map(x=>x.objectType)),new Set(['CONTAINER','BATCH']));assert.ok(rows.every(x=>x.unit==='KG'&&x.userId==='storage-user'&&x.movementType==='ZONE_CHANGE'&&x.reason==='scheduled storage'));assert.equal(batch.zone,'COLD_ROOM_DIRTY');assert.equal(second.zone,'COLD_ROOM_DIRTY')});

test('Batch and Container movement context survives PostgreSQL reload',{skip:!process.env.DATABASE_URL},async()=>{const site=`FR16-${Date.now()}`,repository=new PostgresRepository({connectionString:process.env.DATABASE_URL,siteCode:site});try{const app=new StoreMesh({site,initialState:await repository.load(),seedDemoReferences:true});app.repository=repository;const{session,container,batch}=fixture(app);app.moveContainer(container.id,'COLD_ROOM_DIRTY',session.id,key(),'cold storage');const free=app.createContainer({capacityKg:10},key()),loose=app.receive({sessionId:session.id,containerId:free.id,supplier:'S',product:'T',grade:'A',size:'L',weightKg:2},key());free.batchIds=[];loose.containerId=null;app.move(loose.id,'SORTING',session.id,key(),null,'manual sort');await app.flush();const restored=await repository.load(),containerRow=restored.movements.find(x=>x.containerId===container.id&&x.objectType==='CONTAINER'),cascade=restored.movements.find(x=>x.batchId===batch.id&&x.objectType==='BATCH'),batchRow=restored.movements.find(x=>x.batchId===loose.id);assert.deepEqual([containerRow.quantityKg,containerRow.unit,containerRow.userId,containerRow.movementType,containerRow.reason],[7,'KG','storage-user','ZONE_CHANGE','cold storage']);assert.deepEqual([cascade.quantityKg,cascade.unit,cascade.userId,cascade.containerId],[7,'KG','storage-user',container.id]);assert.deepEqual([batchRow.quantityKg,batchRow.unit,batchRow.userId,batchRow.objectType,batchRow.reason],[2,'KG','storage-user','BATCH','manual sort'])}finally{await repository.close()}});
