import test from'node:test';
import assert from'node:assert/strict';
import{randomUUID}from'node:crypto';
import{once}from'node:events';
import{StoreMesh}from'../src/domain.js';
import{PostgresRepository}from'../src/postgres-repository.js';
import{AuthService}from'../src/auth.js';
import{createServer}from'../src/server.js';

const key=()=>randomUUID();
function fixture(app=new StoreMesh()){const operator=app.openSession('operator','TEST-DEVICE','STORAGE','STORAGE_OPERATOR'),manager=app.openSession('manager','TEST-TERMINAL-02','STORAGE','MANAGER'),now=new Date().toISOString(),other={id:key(),operatorId:'other',deviceId:'OTHER',station:'STORAGE',selectedRole:'STORAGE_OPERATOR',status:'ACTIVE',draft:{},startedAt:now,updatedAt:now,lastActivityAt:now};app.state.sessions.push(other);const pkg={id:key(),code:'PK-LOC',type:'CARTON',level:'CARTON',status:'READY_TO_SHIP',warehouseLocation:null,warehouseHistory:[],createdAt:now},box={id:key(),code:'FB-LOC',type:'FRESH_SHIPPING_BOX',status:'READY_TO_SHIP',warehouseLocation:null,warehouseHistory:[],sessionId:operator.id,deviceId:operator.deviceId,items:[],createdAt:now};app.state.packages.push(pkg);app.state.shippingBoxes.push(box);return{app,operator,other,manager,pkg,box}}

test('routine package and fresh-box moves retain attributable warehouse history',()=>{const f=fixture(),moved=f.app.moveInventoryItem('PACKAGE',f.pkg.id,{sessionId:f.operator.id,warehouseLocation:'FG-A-01'},key());assert.equal(moved.item.warehouseLocation,'FG-A-01');assert.equal(moved.move.operatorId,'operator');assert.equal(moved.move.deviceId,'TEST-DEVICE');f.app.moveInventoryItem('FRESH_SHIPPING_BOX',f.box.id,{sessionId:f.operator.id,warehouseLocation:'COLD-02'},key());assert.equal(f.box.warehouseLocation,'COLD-02');assert.equal(f.box.warehouseHistory.length,1);assert.ok(f.app.state.audit.some(x=>x.type==='WAREHOUSE_LOCATION_CHANGED'&&x.entityId===f.box.id))});

test('UNIT CARTON EPS and PALLET package levels each carry an independent location',()=>{const f=fixture();for(const level of['UNIT','CARTON','EPS','PALLET']){const pkg={...f.pkg,id:key(),code:`PK-${level}`,type:'CARTON',level,warehouseLocation:null,warehouseHistory:[]};f.app.state.packages.push(pkg);const result=f.app.moveInventoryItem('PACKAGE',pkg.id,{sessionId:f.operator.id,location:`ZONE-${level}`},key());assert.equal(result.item.warehouseLocation,`ZONE-${level}`);assert.equal(result.item.warehouseHistory[0].operatorId,'operator');assert.ok(result.item.warehouseMovedAt)}});

test('routine move rejects terminal, locked, and another active-session inventory',()=>{const f=fixture();f.pkg.status='DAMAGED';assert.throws(()=>f.app.moveInventoryItem('PACKAGE',f.pkg.id,{sessionId:f.operator.id,location:'X'},key()),e=>e.code==='INVENTORY_ITEM_INACTIVE');f.pkg.status='READY_TO_SHIP';f.pkg.locked=true;assert.throws(()=>f.app.moveInventoryItem('PACKAGE',f.pkg.id,{sessionId:f.operator.id,location:'X'},key()),e=>e.code==='INVENTORY_ITEM_LOCKED');f.pkg.locked=false;f.pkg.activeSessionId=f.other.id;assert.throws(()=>f.app.moveInventoryItem('PACKAGE',f.pkg.id,{sessionId:f.operator.id,location:'X'},key()),e=>e.code==='INVENTORY_ITEM_ASSIGNED_TO_ACTIVE_SESSION')});

test('location correction is a draft requiring a distinct approver',()=>{const f=fixture();f.app.moveInventoryItem('PACKAGE',f.pkg.id,{sessionId:f.operator.id,location:'FG-A'},key());const draft=f.app.requestInventoryAdjustment({adjustmentType:'LOCATION_CORRECTION',itemType:'PACKAGE',itemId:f.pkg.id,location:'FG-B',reason:'scanner location was wrong',requestedBy:'manager'},key());assert.equal(draft.status,'DRAFT');assert.equal(f.pkg.warehouseLocation,'FG-A');assert.throws(()=>f.app.approveInventoryAdjustment(draft.id,'manager',key()),e=>e.code==='SELF_APPROVAL_FORBIDDEN');f.app.approveInventoryAdjustment(draft.id,'second-manager',key());assert.equal(f.pkg.warehouseLocation,'FG-B');assert.equal(draft.approvedBy,'second-manager')});

test('manager emergency relocation requires a reason and bypasses lock and ownership',()=>{const f=fixture();f.pkg.locked=true;f.pkg.activeSessionId=f.other.id;assert.throws(()=>f.app.emergencyRelocate('PACKAGE',f.pkg.id,{sessionId:f.manager.id,location:'SAFE'},key()),e=>e.code==='EMERGENCY_RELOCATION_REASON_REQUIRED');const result=f.app.emergencyRelocate('PACKAGE',f.pkg.id,{sessionId:f.manager.id,location:'SAFE',reason:'fire suppression alarm'},key());assert.equal(result.item.warehouseLocation,'SAFE');assert.equal(result.move.reason,'fire suppression alarm');assert.ok(f.app.state.audit.some(x=>x.type==='EMERGENCY_RELOCATION'&&x.entityId===f.pkg.id))});

test('emergency relocation uniformly bypasses locks for containers packages and shipping boxes',()=>{const f=fixture(),container=f.app.createContainer({capacityKg:10},key());for(const[type,item]of[['CONTAINER',container],['PACKAGE',f.pkg],['FRESH_SHIPPING_BOX',f.box]]){item.locked=true;item.activeSessionId=f.other.id;const result=f.app.emergencyRelocate(type,item.id,{sessionId:f.manager.id,location:`SAFE-${type}`,reason:'verified emergency'},key());assert.equal(result.move.emergency,true);assert.equal(item.warehouseLocation??item.zone,`SAFE-${type}`)}});

test('HTTP manager-gates emergency relocation',async()=>{const f=fixture(),auth=new AuthService({secret:'fr50-secret'});auth.addUser({id:'operator',username:'operator',password:'right',roles:['STORAGE_OPERATOR']});auth.addUser({id:'manager',username:'manager',password:'right',roles:['MANAGER']});f.pkg.locked=true;const server=createServer({app:f.app,auth});server.listen(0,'127.0.0.1');await once(server,'listening');try{const base=`http://127.0.0.1:${server.address().port}`,login=async username=>(await(await fetch(base+'/api/auth/login',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({username,password:'right'})})).json()).data.token,operator=await login('operator'),manager=await login('manager'),post=token=>fetch(`${base}/api/inventory-items/PACKAGE/${f.pkg.id}/emergency-relocate`,{method:'POST',headers:{authorization:`Bearer ${token}`,'content-type':'application/json','idempotency-key':key()},body:JSON.stringify({sessionId:f.manager.id,location:'SAFE',reason:'verified emergency'})});assert.equal((await post(operator)).status,403);assert.equal((await post(manager)).status,201)}finally{server.close();await once(server,'close')}});

test('all package levels fresh-box location and correction survive PostgreSQL reload',{skip:!process.env.DATABASE_URL},async()=>{const repository=new PostgresRepository({connectionString:process.env.DATABASE_URL,siteCode:`FR50-${Date.now()}`});try{const f=fixture(new StoreMesh());f.app.repository=repository;const packageIds=[];for(const level of['UNIT','CARTON','EPS','PALLET']){const pkg={...f.pkg,id:key(),code:`DB-${level}-${key().slice(0,6)}`,type:'CARTON',level,warehouseLocation:null,warehouseHistory:[]};f.app.state.packages.push(pkg);packageIds.push(pkg.id);f.app.moveInventoryItem('PACKAGE',pkg.id,{sessionId:f.operator.id,location:`DB-${level}`},key())}f.app.moveInventoryItem('FRESH_SHIPPING_BOX',f.box.id,{sessionId:f.operator.id,location:'COLD-A'},key());const draft=f.app.requestInventoryAdjustment({adjustmentType:'LOCATION_CORRECTION',itemType:'FRESH_SHIPPING_BOX',itemId:f.box.id,location:'COLD-B',reason:'verified bay correction',requestedBy:'manager'},key());f.app.approveInventoryAdjustment(draft.id,'second-manager',key());await f.app.flush();const state=await repository.load(),box=state.shippingBoxes.find(x=>x.id===f.box.id),adjustment=state.inventoryAdjustments.find(x=>x.id===draft.id);assert.deepEqual(packageIds.map(id=>state.packages.find(x=>x.id===id).warehouseLocation),['DB-UNIT','DB-CARTON','DB-EPS','DB-PALLET']);assert.equal(box.warehouseLocation,'COLD-B');assert.equal(box.warehouseHistory.length,2);assert.equal(adjustment.adjustmentType,'LOCATION_CORRECTION');assert.equal(adjustment.itemId,f.box.id);assert.equal(adjustment.status,'APPROVED');assert.equal(adjustment.approvedBy,'second-manager');assert.ok(state.audit.some(x=>x.type==='WAREHOUSE_LOCATION_CHANGED'))}finally{await repository.close()}});
