import test from 'node:test';
import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import { StoreMesh } from '../src/domain.js';
import { PostgresRepository } from '../src/postgres-repository.js';

const key=()=>randomUUID();
const template={id:'TPL-RECEIVING-100X50',name:'QR ظرف یک‌بارمصرف',objectType:'BASKET',printPoint:'RECEIVING_SINGLE_USE',widthMm:100,heightMm:50,dpi:203,orientation:'LANDSCAPE',active:true,elements:[{id:'qr',type:'QR',field:'QR_TRACEABILITY',xMm:3,yMm:3,widthMm:30,heightMm:30},{id:'code',type:'TEXT',field:'BARCODE',xMm:36,yMm:5,widthMm:58,heightMm:8,fontSize:12}]};
function activate(app,printer){const values={fieldsByType:{BASKET:['BARCODE','QR_TRACEABILITY','CONTAINER_TYPE']},templates:[template],assignments:[{id:'ASN-RECEIVING-01',deviceCode:'TEST-DEVICE',objectType:'BASKET',printPoint:'RECEIVING_SINGLE_USE',templateId:template.id,printerCode:printer.code}],strictRouting:true,allowedReprintReasons:['OTHER'],reprintApprovalByType:{BASKET:false},reprintThreshold:3},version=app.createConfiguration({scope:'LABEL',values,userId:'author'},key());app.transitionConfiguration(version.id,'APPROVE','reviewer',key());app.transitionConfiguration(version.id,'ACTIVATE','reviewer',key());return version}

test('device-specific route resolves printer and immutable label dimensions',()=>{const app=new StoreMesh(),printer=app.registerDevice({code:'PRINTER-RECEIVING-01',type:'PRINTER',assignedStation:'RECEIVING'},key()),session=app.openSession('operator','TEST-DEVICE','RECEIVING','RECEIVING_OPERATOR');activate(app,printer);const container=app.createContainer({capacityKg:20,type:'SINGLE_USE',singleUse:true},key()),result=app.requestContainerLabel(container.id,key(),{sessionId:session.id}),job=result.printJob,attempt=app.state.printAttempts.find(x=>x.id===job.id),label=app.state.labels.find(x=>x.id===job.labelId);assert.equal(job.selectedPrinterId,printer.id);assert.equal(job.labelTemplateId,template.id);assert.equal(job.printPoint,'RECEIVING_SINGLE_USE');assert.equal(job.workstationDeviceId,'TEST-DEVICE');assert.equal(job.labelTemplateSnapshot.widthMm,100);assert.equal(attempt.labelAssignmentId,'ASN-RECEIVING-01');assert.equal(label.payload.template.widthMm,100);assert.equal(label.payload.qrTraceabilityCode,container.code)});

test('strict routing rejects an unassigned terminal and invalid configuration references',()=>{const app=new StoreMesh(),printer=app.registerDevice({code:'PRINTER-RECEIVING-02',type:'PRINTER',assignedStation:'RECEIVING'},key()),other=app.registerDevice({code:'OTHER-TERMINAL',type:'TERMINAL',assignedStation:'RECEIVING'},key());activate(app,printer);const session=app.openSession('operator',other.code,'RECEIVING','RECEIVING_OPERATOR'),container=app.createContainer({capacityKg:20,type:'SINGLE_USE',singleUse:true},key());assert.throws(()=>app.requestContainerLabel(container.id,key(),{sessionId:session.id}),error=>error.code==='LABEL_ROUTE_NOT_CONFIGURED');assert.throws(()=>app.createConfiguration({scope:'LABEL',values:{fieldsByType:{BASKET:['BARCODE']},templates:[template],assignments:[{id:'bad',siteDefault:true,objectType:'BASKET',printPoint:'RECEIVING_SINGLE_USE',templateId:template.id,printerCode:'MISSING'}],allowedReprintReasons:['OTHER'],reprintApprovalByType:{BASKET:false},reprintThreshold:3},userId:'author'},key()),error=>error.code==='LABEL_ASSIGNMENT_PRINTER_INVALID')});

test('template route metadata survives PostgreSQL reload',{skip:!process.env.DATABASE_URL},async()=>{const repository=new PostgresRepository({connectionString:process.env.DATABASE_URL,siteCode:`LABEL-ROUTE-${Date.now()}`});try{const app=new StoreMesh({site:repository.siteCode,initialState:await repository.load(),seedDemoReferences:true});app.repository=repository;const printer=app.registerDevice({code:'PRINTER-PG-01',type:'PRINTER',assignedStation:'RECEIVING'},key()),session=app.openSession('operator','TEST-DEVICE','RECEIVING','RECEIVING_OPERATOR');activate(app,printer);const container=app.createContainer({capacityKg:20,type:'SINGLE_USE',singleUse:true},key()),job=app.requestContainerLabel(container.id,key(),{sessionId:session.id}).printJob;await app.flush();const restored=await repository.load(),attempt=restored.printAttempts.find(x=>x.id===job.id);assert.equal(attempt.labelTemplateId,template.id);assert.equal(attempt.printPoint,'RECEIVING_SINGLE_USE');assert.equal(attempt.labelTemplateSnapshot.heightMm,50);assert.equal(attempt.workstationDeviceId,'TEST-DEVICE')}finally{await repository.close()}});
