import test from 'node:test';
import assert from 'node:assert/strict';
import { StoreMesh } from '../src/domain.js';

let sequence=0;const key=label=>`${label}-${++sequence}`;
const setup=()=>{const app=new StoreMesh({clock:()=> '2026-08-24T09:00:00.000Z'}),session=app.openSession('operator','TEST-DEVICE','RECEIVING','STORAGE_OPERATOR');return{app,session}};

test('fresh sites seed only the split cold-room zones',()=>{const app=new StoreMesh();const zones=app.state.masterData.zones;assert.equal(zones.some(x=>x.code==='COLD_ROOM'),false);assert.equal(zones.find(x=>x.code==='COLD_ROOM_CLEAN')?.status,'ACTIVE');assert.equal(zones.find(x=>x.code==='COLD_ROOM_DIRTY')?.status,'ACTIVE')});

test('container label is optional and requested only by an explicit action',()=>{const{app}=setup(),container=app.createContainer({capacityKg:20},key('container'));assert.equal(app.state.printJobs.some(x=>x.entityId===container.id),false);const requested=app.requestContainerLabel(container.id,key('label'));assert.equal(requested.printJob.entityId,container.id);assert.equal(requested.container.labelRequested,true)});

test('reusable tare derives net while single-use records gross directly',()=>{const{app,session}=setup(),basket=app.createContainer({capacityKg:20,tareWeightKg:2},key('basket')),net=app.receive({sessionId:session.id,containerId:basket.id,supplier:'S',product:'T',grade:'A',size:'L',grossWeightKg:12},key('net'));assert.equal(net.weightKg,10);assert.equal(net.tareWeightKg,2);const single=app.createContainer({type:'SINGLE_USE',singleUse:true,capacityKg:20,tareWeightKg:9},key('single')),gross=app.receive({sessionId:session.id,containerId:single.id,supplier:'S',product:'T',grade:'A',size:'L',grossWeightKg:12},key('gross'));assert.equal(gross.weightKg,12);assert.equal(single.tareWeightKg,null)});

test('grade and size product scopes are enforced in receiving',()=>{const{app,session}=setup(),fruit=app.createReference('products',{code:'FRUIT_X',name:'Fruit X'},key('product')),grade=app.createReference('grades',{code:'FRUIT_GRADE',name:'Fruit grade',productCodes:[fruit.code]},key('grade')),size=app.createReference('sizes',{code:'FRUIT_SIZE',name:'Fruit size',productCodes:[fruit.code]},key('size')),container=app.createContainer({capacityKg:20},key('container'));assert.throws(()=>app.receive({sessionId:session.id,containerId:container.id,supplier:'S',product:'T',grade:grade.code,size:size.code,weightKg:5},key('invalid')),e=>e.code==='PRODUCT_DIMENSION_INVALID')});

test('washed-container cold-room reversal warns, moves, and raises a durable exception',()=>{const{app,session}=setup(),container=app.createContainer({capacityKg:20,designatedZones:['WASHING','SORTING']},key('container'));app.moveContainer(container.id,'WASHING',session.id,key('wash'));const movement=app.moveContainer(container.id,'COLD_ROOM_CLEAN',session.id,key('reverse'));assert.equal(movement.hygieneWarning,true);assert.equal(container.zone,'COLD_ROOM_CLEAN');assert.ok(app.state.exceptions.some(x=>x.type==='WASHED_CONTAINER_COLD_ROOM_DEVIATION'&&x.entityId===container.id));assert.ok(app.state.audit.some(x=>x.type==='WASHED_CONTAINER_COLD_ROOM_DEVIATION'&&x.result==='WARNING'))});

test('partial consumption leaves source usable and preserves genealogy',()=>{const{app,session}=setup(),container=app.createContainer({capacityKg:20},key('container')),batch=app.receive({sessionId:session.id,containerId:container.id,supplier:'S',product:'T',grade:'A',size:'L',weightKg:10},key('receive')),child=app.transform({sessionId:session.id,process:'MERGE',inputs:[{batchId:batch.id,consumeWeightKg:4}],outputWeightKg:3.5},key('partial'));assert.equal(batch.weightKg,6);assert.notEqual(batch.status,'CONSUMED');assert.equal(batch.containerId,container.id);assert.deepEqual(child.parentIds,[batch.id])});

test('fresh nets aggregate counts, preserve remainder, and consume shipping supplies',()=>{const{app}=setup(),session=app.openSession('fresh','TEST-DEVICE','FRESH_EXPORT','FRESH_EXPORT_OPERATOR'),boxSupply=app.createConsumable({code:'EPS_BOX',name:'EPS box',reorderThreshold:1},key('eps')),gel=app.createConsumable({code:'GEL_PACK',name:'Gel pack',reorderThreshold:2},key('gel'));app.receiveConsumable(boxSupply.id,{quantity:2,source:'purchase'},key('eps-in'));app.receiveConsumable(gel.id,{quantity:4,source:'purchase'},key('gel-in'));const container=app.createContainer({capacityKg:20},key('container')),batch=app.receive({sessionId:session.id,containerId:container.id,supplier:'S',product:'T',grade:'A',size:'L',weightKg:10},key('receive'));batch.status='SORTED';batch.destination='FRESH_EXPORT';batch.zone='FRESH_EXPORT';container.zone='FRESH_EXPORT';container.status='SORTED';const lot=app.createFreshNetLot({sessionId:session.id,batchId:batch.id,containerId:container.id,unitWeightKg:1,count:7},key('nets'));assert.equal(batch.weightKg,3);assert.equal(lot.count,7);const box=app.createShippingBox({sessionId:session.id,allocations:[{netLotId:lot.id,count:5}],gelPackCount:2},key('box'));assert.equal(box.items[0].batchId,batch.id);assert.equal(lot.remainingCount,2);assert.equal(boxSupply.quantity,1);assert.equal(gel.quantity,2);assert.ok(app.state.exceptions.some(x=>x.type==='CONSUMABLE_REORDER'))});
