import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {StoreMesh} from '../src/domain.js';

const setup=(role=null)=>{const app=new StoreMesh(),session=app.openSession('operator','TEST-DEVICE','station',role),container=app.createContainer({capacityKg:100},'container'),batch=app.receive({sessionId:session.id,containerId:container.id,supplier:'S',product:'T',grade:'UNSORTED',size:'MIXED',weightKg:10},'receive');return{app,session,container,batch}};
const errorCode=code=>error=>error.code===code;

test('quarantined inventory is rejected by every production, packaging, and shipment gate',()=>{
  const{app,session,container,batch}=setup('PACKAGING_OPERATOR');
  app.state.qcChecklists.push({id:'qc',product:'T',stage:'RECEIVING',active:true,items:[{code:'safe',required:true}]});
  app.qualityCheck({batchId:batch.id,result:'QUARANTINED',stage:'RECEIVING',checklistId:'qc',responses:[{itemCode:'safe',value:false}],inspectorId:'manager',attestation:{confirmed:true,role:'MANAGER'}},'quarantine');
  assert.equal(batch.status,'QUARANTINED');
  Object.assign(container,{zone:'COLD_ROOM_CLEAN',status:'IN_USE'});assert.throws(()=>app.sortBatch({sessionId:session.id,containerId:container.id,batchId:batch.id,outputs:[{grade:'A',size:'L',weightKg:9}]},'sort-q'),errorCode('BATCH_QUARANTINED'));
  Object.assign(container,{zone:'WASHING',status:'READY_FOR_WASHING'});assert.throws(()=>app.transform({sessionId:session.id,containerId:container.id,inputs:[{batchId:batch.id,consumeWeightKg:10}],process:'WASH',outputWeightKg:10},'wash-q'),errorCode('BATCH_QUARANTINED'));
  Object.assign(container,{zone:'DRYING',status:'READY_FOR_DRYING'});assert.throws(()=>app.createCycle({sessionId:session.id,type:'DRY',machineId:'dryer',containerIds:[container.id]},'cycle-q'),errorCode('BATCH_QUARANTINED'));
  assert.throws(()=>app.weighForPackaging({sessionId:session.id,batchId:batch.id,weightKg:10},'weigh-q'),errorCode('BATCH_QUARANTINED'));
  assert.throws(()=>app.createPackage({sessionId:session.id,type:'POUCH',level:'UNIT',items:[{batchId:batch.id,weightKg:1}],targetWeightKg:1},'package-q'),errorCode('BATCH_QUARANTINED'));
  const customer=app.createCustomer({code:'C',name:'Customer'},'customer'),order=app.createSalesOrder({customerId:customer.id,items:[{packageType:'CARTON',quantity:1}]},'order'),carton={id:crypto.randomUUID(),code:'P-Q',type:'CARTON',level:'CARTON',status:'READY_TO_SHIP',items:[{batchId:batch.id,weightKg:1}],childPackageIds:[],createdAt:new Date().toISOString()};app.state.packages.push(carton);
  assert.throws(()=>app.createShipment({salesOrderId:order.id,packageIds:[carton.id]},'shipment-q'),errorCode('BATCH_QUARANTINED'));
});

test('failed sorting rolls back every mutation while retaining the failure audit',()=>{const{app,session,container,batch}=setup();app.moveContainer(container.id,'COLD_ROOM_CLEAN',session.id,'cold');const before={batches:app.state.batches.length,tasks:app.state.tasks.length,prints:app.state.printJobs.length,weight:batch.weightKg};assert.throws(()=>app.sortBatch({sessionId:session.id,containerId:container.id,batchId:batch.id,outputs:[{grade:'A',size:'L',weightKg:4},{grade:'BOGUS',size:'L',weightKg:3}]},'bad-sort'),errorCode('MASTER_DATA_REFERENCE_INVALID'));assert.deepEqual({batches:app.state.batches.length,tasks:app.state.tasks.length,prints:app.state.printJobs.length,weight:batch.weightKg},before);assert.equal(app.state.audit.at(-1).result,'FAILURE')});

test('all seven formerly blind idempotent operations hash their real request payload',async()=>{const source=await readFile(new URL('../src/domain.js',import.meta.url),'utf8');for(const name of['releaseQuarantine','adjustInventory','createConfiguration','transitionConfiguration','requestOverride','resolveOverride','updateInternalShipment']){const start=source.indexOf(`${name}(`),end=source.indexOf('\n',start);assert.match(source.slice(start,end),/},(?:input|\{[^}]+\})\)/,`${name} must pass its request to run()`)}const{app,batch}=setup();const first=app.adjustInventory({batchId:batch.id,deltaKg:-1,reason:'count'},'same-adjustment-key');assert.equal(first.deltaKg,-1);assert.throws(()=>app.adjustInventory({batchId:batch.id,deltaKg:5,reason:'different'},'same-adjustment-key'),errorCode('IDEMPOTENCY_PAYLOAD_MISMATCH'));assert.equal(batch.weightKg,9)});

test('quarantine release restores the exact prior status and validates destination zone',()=>{const{app,batch}=setup();batch.status='SORTED';batch.zone='SORTING';app.state.qcChecklists.push({id:'qc',product:'T',stage:'SORTING',active:true,items:[]});app.qualityCheck({batchId:batch.id,result:'QUARANTINED',stage:'SORTING',checklistId:'qc',responses:[],inspectorId:'manager',attestation:{confirmed:true,role:'MANAGER'}},'q');assert.throws(()=>app.releaseQuarantine({batchId:batch.id,reason:'clear',destinationZone:'NOT_REAL'},'bad-release'),errorCode('MASTER_DATA_REFERENCE_INVALID'));app.releaseQuarantine({batchId:batch.id,reason:'clear',destinationZone:'WASHING'},'release');assert.equal(batch.status,'SORTED');assert.equal(batch.zone,'WASHING')});

test('sorting records and consumes process loss instead of leaving saleable remainder',()=>{const{app,session,container,batch}=setup();app.moveContainer(container.id,'COLD_ROOM_CLEAN',session.id,'cold');const result=app.sortBatch({sessionId:session.id,containerId:container.id,batchId:batch.id,outputs:[{grade:'A',size:'L',weightKg:7}],lossKg:3},'sort-loss');assert.equal(result.lossKg,3);assert.equal(batch.sortingLossKg,3);assert.equal(batch.weightKg,0);assert.equal(batch.status,'CONSUMED');assert.equal(batch.containerId,null)});

test('washing permits measured gain, records it, and raises a warning exception',()=>{const{app,session,container,batch}=setup();batch.status='SORTED';Object.assign(container,{zone:'WASHING',status:'READY_FOR_WASHING'});batch.zone='WASHING';const output=app.transform({sessionId:session.id,containerId:container.id,inputs:[{batchId:batch.id,consumeWeightKg:10}],process:'WASH',outputWeightKg:10.3},'wash-gain');assert.equal(output.weightGainKg,.3);assert.equal(output.processLossKg,0);assert.equal(app.state.exceptions.at(-1).type,'WASH_WEIGHT_GAIN')});

test('packaging checkpoint blocks accidental inventory inflation and stores configured tolerance',()=>{const{app,session,batch}=setup('PACKAGING_OPERATOR');batch.status='DRIED';batch.zone='PACKAGING';assert.throws(()=>app.weighForPackaging({sessionId:session.id,batchId:batch.id,weightKg:100},'typo'),errorCode('PACKAGING_WEIGHT_ADJUSTMENT_REQUIRED'));assert.equal(batch.weightKg,10);app.state.configurationVersions.push({id:crypto.randomUUID(),scope:'PACKAGING',status:'ACTIVE',values:{weightTolerancePercent:5,checkpointVariancePercent:5}});app.weighForPackaging({sessionId:session.id,batchId:batch.id,weightKg:10},'checkpoint');const unit=app.createPackage({sessionId:session.id,type:'POUCH',level:'UNIT',items:[{batchId:batch.id,weightKg:1.04}],targetWeightKg:1},'unit');assert.equal(unit.tolerancePercent,5)});

test('same-container assignment is capacity-neutral and consumed batches release their container',()=>{const{app,session,container,batch}=setup();container.capacityKg=10;assert.doesNotThrow(()=>app.assignBatchToContainer(container.id,batch.id,session.id,'same-container'));batch.status='SORTED';Object.assign(container,{zone:'WASHING',status:'READY_FOR_WASHING'});app.transform({sessionId:session.id,containerId:container.id,inputs:[{batchId:batch.id,consumeWeightKg:10}],process:'WASH',outputWeightKg:9},'consume');assert.equal(batch.containerId,null);assert.ok(!container.batchIds.includes(batch.id))});

test('MERGE produces a usable sorted batch rather than a dead-end status',()=>{const{app,session,batch}=setup();batch.status='SORTED';const merged=app.transform({sessionId:session.id,inputs:[{batchId:batch.id,consumeWeightKg:5}],process:'MERGE',outputWeightKg:5},'merge');assert.equal(merged.status,'SORTED');assert.equal(merged.zone,'SORTING')});

test('nested carton manifests recurse to UNIT allocations and empty transfers are rejected',()=>{const{app,session,batch}=setup('PACKAGING_OPERATOR');batch.status='DRIED';app.weighForPackaging({sessionId:session.id,batchId:batch.id,weightKg:10},'weigh');const unit=app.createPackage({sessionId:session.id,type:'POUCH',level:'UNIT',items:[{batchId:batch.id,weightKg:2}],targetWeightKg:2,tolerancePercent:0},'unit');for(const action of['PACK','SEAL','PRINT','PRINT_SUCCESS','READY'])app.transitionPackage(unit.id,action,`unit-${action}`);const carton=app.createPackage({sessionId:session.id,type:'CARTON',level:'CARTON',childPackageIds:[unit.id]},'carton');app.transitionPackage(carton.id,'PACK','carton-pack');app.scanPackageItem(carton.id,{sessionId:session.id,unitPackageCode:unit.code},'scan');for(const action of['SEAL','PRINT','PRINT_SUCCESS','READY'])app.transitionPackage(carton.id,action,`carton-${action}`);const shipment=app.createInternalShipment({packageIds:[carton.id],destinationSite:'DUBAI'},'shipment');app.updateInternalShipment(shipment.id,'LOAD','load');app.updateInternalShipment(shipment.id,'DISPATCH','dispatch');const manifest=app.shipmentManifest(shipment.id);assert.equal(manifest.packages[0].items.length,1);assert.equal(manifest.packages[0].items[0].weightKg,2);const destination=new StoreMesh({site:'DUBAI'}),targetSession=destination.openSession('receiver','TEST-DEVICE');const received=destination.receiveInternalTransfer({sessionId:targetSession.id,receivedBy:'receiver',manifest},'receive-transfer');assert.equal(received.batches.length,1);assert.throws(()=>destination.receiveInternalTransfer({sessionId:targetSession.id,receivedBy:'receiver',manifest:{...manifest,shipmentCode:'EMPTY',packages:[{packageCode:'P',type:'CARTON',items:[]}]}},'empty-transfer'),errorCode('TRANSFER_CONTENT_EMPTY'))});

test('nested packages cannot be cancelled and customer shipment transitions reject internal transfers',()=>{const{app,session,batch}=setup('PACKAGING_OPERATOR');batch.status='DRIED';app.weighForPackaging({sessionId:session.id,batchId:batch.id,weightKg:10},'weigh');const unit=app.createPackage({sessionId:session.id,type:'POUCH',level:'UNIT',items:[{batchId:batch.id,weightKg:1}],targetWeightKg:1,tolerancePercent:0},'unit');for(const action of['PACK','SEAL','PRINT','PRINT_SUCCESS','READY'])app.transitionPackage(unit.id,action,`unit-${action}`);const carton=app.createPackage({sessionId:session.id,type:'CARTON',level:'CARTON',childPackageIds:[unit.id]},'carton');assert.throws(()=>app.transitionPackage(unit.id,'CANCEL','nested-cancel',{reason:'wrong'}),errorCode('PACKAGE_NESTED_TERMINATION_FORBIDDEN'));assert.equal(batch.weightKg,9);assert.equal(carton.childPackageIds[0],unit.id);carton.status='READY_TO_SHIP';const shipment=app.createInternalShipment({packageIds:[carton.id],destinationSite:'DUBAI'},'internal');assert.throws(()=>app.updateShipment(shipment.id,'LOAD',{vehicle:'V'},'wrong-machine'),errorCode('CUSTOMER_SHIPMENT_NOT_FOUND'));assert.equal(shipment.status,'READY')});
