import test from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {StoreMesh} from '../src/domain.js';
import {PostgresRepository} from '../src/postgres-repository.js';

const key=()=>randomUUID();
const stockCartons=app=>{const item=app.createConsumable({code:'CARTON',name:'Carton',reorderThreshold:0},key());app.receiveConsumable(item.id,{quantity:20,source:'test'},key())};
const activate=(app,values)=>{const draft=app.createConfiguration({scope:'PACKAGING',values,userId:'author'},key());app.transitionConfiguration(draft.id,'APPROVE','reviewer',key());app.transitionConfiguration(draft.id,'ACTIVATE','reviewer',key());return draft};
const setup=(app=new StoreMesh())=>{stockCartons(app);const session=app.openSession('packer','PDA-PACK-01','PACKAGING','PACKAGING_OPERATOR');return{app,session}};
const makeBatch=(app,session,product='T',grade='A',weightKg=10)=>{const container=app.createContainer({capacityKg:20},key()),batch=app.receive({sessionId:session.id,containerId:container.id,supplier:'S',product,grade,size:'L',weightKg},key());batch.status='DRIED';app.weighForPackaging({sessionId:session.id,batchId:batch.id,weightKg},key());return batch};
const makeUnit=(app,session,batch,weightKg=1,input={})=>app.createPackage({sessionId:session.id,type:'POUCH',level:'UNIT',items:[{batchId:batch.id,weightKg}],targetWeightKg:weightKg,tolerancePercent:0,...input},key());
const readyUnit=(app,unit)=>{for(const action of['PACK','SEAL','PRINT','PRINT_SUCCESS','READY'])app.transitionPackage(unit.id,action,key());return unit};
const carton=(app,session)=>app.createPackage({sessionId:session.id,type:'CARTON',level:'CARTON'},key());

test('UNIT and nested package labels contain truthful product and aggregate content',()=>{const{app,session}=setup(),batch=makeBatch(app,session),one=makeUnit(app,session,batch,1),unitLabel=app.state.labels.find(x=>x.entityType==='PACKAGE'&&x.entityId===one.id);assert.deepEqual({product:unitLabel.payload.product,grade:unitLabel.payload.grade,size:unitLabel.payload.size,weightKg:unitLabel.payload.weightKg,sourceBatchCode:unitLabel.payload.sourceBatchCode},{product:'T',grade:'A',size:'L',weightKg:1,sourceBatchCode:batch.code});readyUnit(app,one);const two=readyUnit(app,makeUnit(app,session,batch,1.5)),box=carton(app,session,[one,two]);app.transitionPackage(box.id,'PACK',key());app.scanPackageItem(box.id,{sessionId:session.id,unitPackageCode:one.code},key());app.scanPackageItem(box.id,{sessionId:session.id,unitPackageCode:two.code},key());app.transitionPackage(box.id,'SEAL',key());const label=app.state.labels.find(x=>x.entityType==='PACKAGE'&&x.entityId===box.id);assert.equal(label.payload.childCount,2);assert.equal(label.payload.totalWeightKg,2.5);assert.deepEqual(label.payload.sourceBatchCodes,[batch.code])});

test('package label payloads survive PostgreSQL reload',{skip:!process.env.DATABASE_URL},async()=>{const site=`FR24-LABEL-${Date.now()}`,repository=new PostgresRepository({connectionString:process.env.DATABASE_URL,siteCode:site});try{const app=new StoreMesh({site,initialState:await repository.load(),seedDemoReferences:true});app.repository=repository;const{session}=setup(app),batch=makeBatch(app,session),unit=readyUnit(app,makeUnit(app,session,batch,2)),box=carton(app,session,[unit]);app.transitionPackage(box.id,'PACK',key());app.scanPackageItem(box.id,{sessionId:session.id,unitPackageCode:unit.code},key());app.transitionPackage(box.id,'SEAL',key());await app.flush();const restored=await repository.load(),unitLabel=restored.labels.find(x=>x.entityId===unit.id),boxLabel=restored.labels.find(x=>x.entityId===box.id);assert.equal(unitLabel.payload.product,batch.product);assert.equal(unitLabel.payload.weightKg,2);assert.equal(boxLabel.payload.childCount,1);assert.equal(boxLabel.payload.totalWeightKg,2)}finally{await repository.close()}});

test('active packaging configuration governs mixed cartons and persists the enforced target',()=>{const{app,session}=setup(),oneBatch=makeBatch(app,session,'T'),twoBatch=makeBatch(app,session,'Truffle');activate(app,{targetWeightKg:1,weightTolerancePercent:0,allowMixedProducts:false,allowMixedGrades:false});const one=readyUnit(app,makeUnit(app,session,oneBatch,1,{targetWeightKg:99})),two=readyUnit(app,makeUnit(app,session,twoBatch,1,{targetWeightKg:99}));assert.equal(one.targetWeightKg,1);const blocked=carton(app,session);app.scanPackageItem(blocked.id,{sessionId:session.id,unitPackageCode:one.code},key());assert.throws(()=>app.scanPackageItem(blocked.id,{sessionId:session.id,unitPackageCode:two.code},key()),error=>error.code==='CARTON_MIXED_CONTENT_FORBIDDEN');activate(app,{targetWeightKg:1,weightTolerancePercent:0,allowMixedProducts:true,allowMixedGrades:true});const allowed=carton(app,session);app.scanPackageItem(allowed.id,{sessionId:session.id,unitPackageCode:two.code},key());assert.equal(allowed.childPackageIds.length,1)});

test('mixed cartons retain compatibility behavior without active packaging configuration',()=>{const{app,session}=setup(),one=readyUnit(app,makeUnit(app,session,makeBatch(app,session,'T'))),two=readyUnit(app,makeUnit(app,session,makeBatch(app,session,'Truffle'))),mixed=carton(app,session);app.scanPackageItem(mixed.id,{sessionId:session.id,unitPackageCode:one.code},key());app.scanPackageItem(mixed.id,{sessionId:session.id,unitPackageCode:two.code},key());assert.equal(mixed.childPackageIds.length,2)});

test('cancelled carton scan evidence survives reload and its UNIT can be scanned again',{skip:!process.env.DATABASE_URL},async()=>{const site=`FR24-SCAN-${Date.now()}`,repository=new PostgresRepository({connectionString:process.env.DATABASE_URL,siteCode:site});try{const app=new StoreMesh({site,initialState:await repository.load(),seedDemoReferences:true});app.repository=repository;const{session}=setup(app),batch=makeBatch(app,session),unit=readyUnit(app,makeUnit(app,session,batch)),first=carton(app,session,[unit]);app.transitionPackage(first.id,'PACK',key());const original=app.scanPackageItem(first.id,{sessionId:session.id,unitPackageCode:unit.code},key());assert.throws(()=>app.scanPackageItem(first.id,{sessionId:session.id,unitPackageCode:unit.code},key()),error=>error.code==='CARTON_DUPLICATE_SCAN');app.transitionPackage(first.id,'CANCEL',key(),{reason:'incorrect carton'});const second=carton(app,session,[unit]);app.transitionPackage(second.id,'PACK',key());const replacement=app.scanPackageItem(second.id,{sessionId:session.id,unitPackageCode:unit.code},key());await app.flush();const restored=await repository.load();assert.ok(restored.cartonScanEvents.some(x=>x.id===original.id&&x.packageId===first.id));assert.ok(restored.cartonScanEvents.some(x=>x.id===replacement.id&&x.packageId===second.id));assert.equal(restored.cartonScanEvents.filter(x=>x.itemIdentity===unit.code).length,2)}finally{await repository.close()}});
