import test from 'node:test';
import assert from 'node:assert/strict';
import { StoreMesh } from '../src/domain.js';

let sequence=0;const key=prefix=>`${prefix}-${++sequence}`;
function fixture({type='BASKET',zone='RECEIVING',status='AVAILABLE',batchStatus='RECEIVED'}={}){const app=new StoreMesh(),session=app.openSession('operator','TEST-TERMINAL-01'),receiving=app.createContainer({type:'BASKET',capacityKg:100},key('receiving')),batch=app.receive({sessionId:session.id,containerId:receiving.id,supplier:'S',product:'T',grade:'A',size:'L',weightKg:10},key('receive')),container=type==='BASKET'?receiving:app.createContainer({type,capacityKg:100},key('container'));if(container!==receiving){app.assignBatchToContainer(container.id,batch.id,session.id,key('assign'))}container.zone=zone;container.status=status;container.activeSessionId=null;batch.zone=zone;batch.status=batchStatus;return{app,session,container,batch}}
const cases=[
 {name:'sorting',setup:{zone:'COLD_ROOM_CLEAN',status:'IN_USE'},call:({app,session,batch},id)=>{const outputs=[{grade:'A',size:'L',weightKg:5}];if(id.containerId){const target=app.createContainer({capacityKg:10},key('sort-output'));app.moveContainer(target.id,'SORTING',session.id,key('stage-output'));outputs[0].containerId=target.id}return app.sortBatch({sessionId:session.id,batchId:batch.id,...id,outputs,lossReason:'MEASUREMENT_VARIANCE'},key('sort'))},id:c=>({containerId:c.id})},
 {name:'washing',setup:{zone:'WASHING',status:'READY_FOR_WASHING',batchStatus:'SORTED'},call:({app,session,batch},id)=>app.transform({sessionId:session.id,inputs:[{batchId:batch.id,consumeWeightKg:10}],process:'WASH',outputWeightKg:9,...id},key('wash')),id:c=>({containerId:c.id})},
 {name:'slicing',setup:{zone:'SLICING',status:'WASHED',batchStatus:'WASHED'},call:({app,session,batch},id)=>app.transform({sessionId:session.id,inputs:[{batchId:batch.id,consumeWeightKg:10}],process:'SLICE',outputWeightKg:9,...id},key('slice')),id:c=>({containerId:c.id})},
 {name:'freezing',setup:{type:'TRAY',zone:'FREEZING',status:'SLICED',batchStatus:'SLICED'},call:({app,session},id)=>app.createCycle({sessionId:session.id,type:'FREEZE',machineId:'FREEZER-01',...(id.trayId?{trayIds:[id.trayId]}:{})},key('freeze')),id:c=>({trayId:c.id})},
 {name:'freeze drying',setup:{type:'TRAY',zone:'FREEZE_DRYING',status:'FROZEN',batchStatus:'FROZEN'},call:({app,session},id)=>app.createCycle({sessionId:session.id,type:'FREEZE_DRY',machineId:'FD-01',...(id.trayId?{trayIds:[id.trayId]}:{})},key('freeze-dry')),id:c=>({trayId:c.id})},
 {name:'drying',setup:{zone:'DRYING',status:'READY_FOR_DRYING',batchStatus:'SORTED'},call:({app,session},id)=>app.createCycle({sessionId:session.id,type:'DRY',machineId:'DRYER-01',...(id.containerId?{containerIds:[id.containerId]}:{})},key('dry')),id:c=>({containerId:c.id})}
];
test('receiving requires an empty available scanned basket and claims it atomically',()=>{const app=new StoreMesh(),session=app.openSession('receiver','TEST-TERMINAL-01'),input={sessionId:session.id,supplier:'S',product:'T',grade:'A',size:'L',weightKg:5};assert.throws(()=>app.receive(input,key('missing')),e=>e.code==='CONTAINER_SCAN_REQUIRED');const basket=app.createContainer({type:'BASKET',capacityKg:10},key('basket')),batch=app.receive({...input,containerId:basket.id},key('valid'));assert.equal(batch.containerId,basket.id);assert.equal(basket.status,'IN_USE');assert.equal(basket.activeSessionId,session.id);assert.throws(()=>app.receive({...input,containerId:basket.id},key('reuse')),e=>['CONTAINER_STATUS_INVALID','CONTAINER_NOT_AVAILABLE'].includes(e.code))});
for(const scenario of cases)test(`${scenario.name} requires a correctly staged physical scan`,()=>{const missing=fixture(scenario.setup);assert.throws(()=>scenario.call(missing,{}),e=>['CONTAINER_SCAN_REQUIRED','TRAY_SCAN_REQUIRED'].includes(e.code));const wrong=fixture(scenario.setup);wrong.container.locked=true;assert.throws(()=>scenario.call(wrong,scenario.id(wrong.container)),e=>e.code==='CONTAINER_LOCKED');const occupied=fixture(scenario.setup),other=occupied.app.openSession('other','TEST-TERMINAL-02');occupied.container.activeSessionId=other.id;assert.throws(()=>scenario.call(occupied,scenario.id(occupied.container)),e=>e.code==='CONTAINER_ASSIGNED_TO_ACTIVE_SESSION');const valid=fixture(scenario.setup);assert.doesNotThrow(()=>scenario.call(valid,scenario.id(valid.container)))});
