import test from'node:test';import assert from'node:assert/strict';import{StoreMesh}from'../src/domain.js';import{PostgresRepository}from'../src/postgres-repository.js';

const fixture=()=>{const app=new StoreMesh(),one=app.openSession('printer-one','TEST-DEVICE'),two=app.openSession('printer-two','TEST-TERMINAL-02'),container=app.createContainer({capacityKg:10},'container'),batch=app.receive({sessionId:one.id,containerId:container.id,supplier:'S',product:'T',grade:'A',size:'L',weightKg:5},'receive'),pkg=app.createPackage({sessionId:one.id,type:'POUCH',items:[{batchId:batch.id,weightKg:1}]},'package');app.transitionPackage(pkg.id,'PACK','pack');app.transitionPackage(pkg.id,'SEAL','seal');app.transitionPackage(pkg.id,'PRINT','print');return{app,one,two,batch,pkg,job:app.state.printJobs.find(x=>x.entityId===pkg.id)}};

test('print completion requires an owned lease and atomically cascades to label and package',()=>{const{app,one,two,pkg,job}=fixture(),label=app.state.labels.find(x=>x.id===job.labelId);assert.throws(()=>app.completePrint(job.id,one.id),e=>e.code==='PRINT_JOB_LEASE_REQUIRED');app.claimPrint(job.id,one.id);assert.throws(()=>app.claimPrint(job.id,two.id),e=>e.code==='PRINT_JOB_ALREADY_LEASED');app.completePrint(job.id,one.id);assert.equal(job.status,'PRINTED');assert.equal(label.status,'PRINTED');assert.equal(pkg.status,'LABEL_PRINTED')});

test('failed attempts cannot be completed and verified retry creates the only new printable attempt',()=>{const{app,one,job}=fixture();app.claimPrint(job.id,one.id);app.failPrint(job.id,'paper jam',one.id);assert.throws(()=>app.completePrint(job.id,one.id),e=>e.code==='FAILED_PRINT_REQUIRES_RETRY');const retry=app.retryPrint(job.id,job.label,one.id,'paper replaced');app.claimPrint(retry.id,one.id);assert.equal(app.completePrint(retry.id,one.id).status,'PRINTED')});

test('a successful represented operation auto-completes only its matching entity task in the same run',()=>{const app=new StoreMesh(),session=app.openSession('storage','TEST-DEVICE'),container=app.createContainer({capacityKg:10},'container'),batch=app.receive({sessionId:session.id,containerId:container.id,supplier:'S',product:'T',grade:'A',size:'L',weightKg:5},'receive'),task=app.createTask({title:'Move inventory',zone:'COLD_ROOM_DIRTY',entityId:container.id,requiredRole:'STORAGE_OPERATOR',operationType:'CONTAINER_MOVED'},'task'),other=app.createTask({title:'Inspect later',zone:'QC',entityId:batch.id},'other');app.moveContainer(container.id,'COLD_ROOM_DIRTY',session.id,'move');assert.equal(task.status,'COMPLETED');assert.equal(task.stateHistory.at(-1).action,'AUTO_CONTAINER_MOVED');assert.equal(other.status,'OPEN')});

test('real PostgreSQL preserves an active print lease across service restart',{skip:!process.env.DATABASE_URL},async()=>{const site=`FR8D-${Date.now()}`,repository=new PostgresRepository({connectionString:process.env.DATABASE_URL,siteCode:site});try{const app=new StoreMesh({site,initialState:await repository.load(),seedDemoReferences:true});app.repository=repository;const one=app.openSession('printer-one','TEST-DEVICE'),two=app.openSession('printer-two','TEST-TERMINAL-02'),container=app.createContainer({capacityKg:10},'container'),batch=app.receive({sessionId:one.id,containerId:container.id,supplier:'S',product:'T',grade:'A',size:'L',weightKg:5},'receive'),pkg=app.createPackage({sessionId:one.id,type:'POUCH',items:[{batchId:batch.id,weightKg:1}]},'package');app.transitionPackage(pkg.id,'PACK','pack');app.transitionPackage(pkg.id,'SEAL','seal');app.transitionPackage(pkg.id,'PRINT','print');const job=app.state.printJobs.find(x=>x.entityId===pkg.id);app.claimPrint(job.id,one.id);await app.flush();const restarted=new StoreMesh({site,initialState:await repository.load(),seedDemoReferences:false});restarted.repository=repository;assert.throws(()=>restarted.claimPrint(job.id,two.id),error=>error.code==='PRINT_JOB_ALREADY_LEASED');restarted.completePrint(job.id,one.id);await restarted.flush();const restored=await repository.load();assert.equal(restored.printAttempts.find(x=>x.id===job.id).status,'PRINTED');assert.equal(restored.labels.find(x=>x.id===job.labelId).status,'PRINTED');assert.equal(restored.packages.find(x=>x.id===pkg.id).status,'LABEL_PRINTED')}finally{await repository.close()}});
