import test from 'node:test';
import assert from 'node:assert/strict';
import {once} from 'node:events';
import {AuthService} from '../src/auth.js';
import {StoreMesh} from '../src/domain.js';
import {createServer} from '../src/server.js';

test('custom roles reject wildcard and unknown permissions',async()=>{const auth=new AuthService({secret:'test-secret'});await assert.rejects(()=>auth.createRole({code:'ROOT_ROLE',name:'Root',permissions:['*']}),e=>e.code==='ROLE_PERMISSION_INVALID');await assert.rejects(()=>auth.createRole({code:'UNKNOWN_ROLE',name:'Unknown',permissions:['made-up:permission']}),e=>e.code==='ROLE_PERMISSION_INVALID')});

test('manager cannot create roles, self-assign, or mint administrator credentials',async()=>{const app=new StoreMesh(),auth=new AuthService({secret:'test-secret'});auth.addUser({id:'manager-id',username:'manager',password:'right',roles:['MANAGER']});auth.addUser({id:'admin-id',username:'admin',password:'right',roles:['ADMIN']});const server=createServer({app,auth});server.listen(0);await once(server,'listening');try{const base=`http://127.0.0.1:${server.address().port}`,login=await fetch(`${base}/api/auth/login`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({username:'manager',password:'right',deviceId:'WEB-01'})}),token=(await login.json()).data.token,headers={authorization:`Bearer ${token}`,'content-type':'application/json','idempotency-key':'security-test'},request=(path,body)=>fetch(base+path,{method:'POST',headers,body:JSON.stringify(body??{})});assert.equal((await request('/api/roles',{code:'CUSTOM',name:'Custom',permissions:['inventory:read']})).status,403);assert.equal((await request('/api/users/manager-id/roles',{roleCode:'VIEWER'})).status,403);assert.equal((await request('/api/users/admin-id/badge')).status,403);assert.equal((await request('/api/users/admin-id/pin')).status,403)}finally{server.close();await once(server,'close')}});

test('manager can onboard station operators and issue their badge and PIN but still cannot create roles',async()=>{const app=new StoreMesh(),auth=new AuthService({secret:'manager-onboarding-secret'});auth.addUser({id:'manager-onboarding',username:'manager-onboarding',password:'right',roles:['MANAGER']});auth.addUser({id:'operator-onboarding',username:'operator-onboarding',password:'right',roles:[]});const server=createServer({app,auth});server.listen(0);await once(server,'listening');try{const base=`http://127.0.0.1:${server.address().port}`,login=await fetch(base+'/api/auth/login',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({username:'manager-onboarding',password:'right',deviceId:'WEB-CONSOLE-01'})}),token=(await login.json()).data.token,request=(path,body={})=>fetch(base+path,{method:'POST',headers:{authorization:`Bearer ${token}`,'content-type':'application/json','idempotency-key':crypto.randomUUID()},body:JSON.stringify(body)});for(const roleCode of['RECEIVING_OPERATOR','SORTING_OPERATOR','WASHING_OPERATOR','SLICING_OPERATOR','FREEZING_OPERATOR','DRYING_OPERATOR','PACKAGING_OPERATOR','SHIPPING_OPERATOR','QUALITY_OPERATOR','STORAGE_OPERATOR'])assert.equal((await request('/api/users/operator-onboarding/roles',{roleCode})).status,201,roleCode);assert.equal((await request('/api/users/operator-onboarding/badge')).status,201);assert.equal((await request('/api/users/operator-onboarding/pin')).status,201);assert.equal((await request('/api/roles',{code:'MANAGER_CREATED',name:'Forbidden',permissions:['inventory:read']})).status,403)}finally{server.close();await once(server,'close')}});

test('authenticated identity overrides spoofed requester and approver fields',async()=>{const app=new StoreMesh(),auth=new AuthService({secret:'test-secret'});auth.addUser({id:'manager-id',username:'manager',password:'right',roles:['MANAGER']});const server=createServer({app,auth});server.listen(0);await once(server,'listening');try{const base=`http://127.0.0.1:${server.address().port}`,login=await fetch(`${base}/api/auth/login`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({username:'manager',password:'right',deviceId:'WEB-01'})}),token=(await login.json()).data.token,post=async(path,body,key)=>{const r=await fetch(base+path,{method:'POST',headers:{authorization:`Bearer ${token}`,'content-type':'application/json','idempotency-key':key},body:JSON.stringify(body)});return{status:r.status,json:await r.json()}};const created=await post('/api/configurations',{scope:'STATION_MACHINES',values:{FREEZE:'M-1'},userId:'spoofed-user'},'config-create');assert.equal(created.status,201);assert.equal(created.json.data.createdBy,'manager-id');const approved=await post(`/api/configurations/${created.json.data.id}/approve`,{userId:'spoofed-approver'},'config-approve');assert.equal(approved.status,403);assert.equal(approved.json.errorCode,'SELF_APPROVAL_FORBIDDEN');const override=await post('/api/overrides',{type:'QUALITY',entityId:crypto.randomUUID(),reason:'test',requestedBy:'spoofed-requester'},'override-create');assert.equal(override.status,201);assert.equal(override.json.data.requestedBy,'manager-id')}finally{server.close();await once(server,'close')}});
