import { activateTestStationMachines, createTestCycle } from '../test-support/station-machines.js';
import test from 'node:test';
import assert from 'node:assert/strict';
import {once} from 'node:events';
import {StoreMesh} from '../src/domain.js';
import {AuthService} from '../src/auth.js';
import {createServer} from '../src/server.js';

const key=()=>crypto.randomUUID();
const stageCycle=(app,session,type)=>{const receiving=app.createContainer({capacityKg:20},key()),batch=app.receive({sessionId:session.id,containerId:receiving.id,supplier:'S',product:'T',grade:'A',size:'L',weightKg:10},key());if(type==='FREEZE_DRY'){const tray=app.createContainer({type:'TRAY',capacityKg:20},key());app.assignBatchToContainer(tray.id,batch.id,session.id,key());Object.assign(batch,{status:'FROZEN',zone:'FREEZE_DRYING'});Object.assign(tray,{status:'FROZEN',zone:'FREEZE_DRYING',activeSessionId:null});return{carrier:tray,batch}}Object.assign(batch,{status:'SORTED',zone:'DRYING'});Object.assign(receiving,{status:'READY_FOR_DRYING',zone:'DRYING',activeSessionId:null});return{carrier:receiving,batch}};

test('HTTP separates conventional drying and freeze-drying permissions for create and transition',async()=>{const app=new StoreMesh(),dryId=key(),freezeDryId=key(),drySession=app.openSession(dryId,'TEST-DEVICE','DRYING','DRYING_OPERATOR'),freezeDrySession=app.openSession(freezeDryId,'RT-01','FREEZE_DRYING','FREEZE_DRY_OPERATOR'),dry=stageCycle(app,drySession,'DRY'),freezeDry=stageCycle(app,freezeDrySession,'FREEZE_DRY'),auth=new AuthService({secret:'production-role-secret'});activateTestStationMachines(app);auth.addUser({id:dryId,username:'dryer',password:'right',roles:['DRYING_OPERATOR']});auth.addUser({id:freezeDryId,username:'freeze-dryer',password:'right',roles:['FREEZE_DRY_OPERATOR']});const server=createServer({app,auth});server.listen(0,'127.0.0.1');await once(server,'listening');try{const base=`http://127.0.0.1:${server.address().port}`,login=async username=>(await(await fetch(base+'/api/auth/login',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({username,password:'right'})})).json()).data.token,post=(path,token,body)=>fetch(base+path,{method:'POST',headers:{authorization:`Bearer ${token}`,'content-type':'application/json','idempotency-key':key()},body:JSON.stringify(body)}),dryToken=await login('dryer'),freezeDryToken=await login('freeze-dryer');assert.equal((await post('/api/cycles',dryToken,{type:'FREEZE_DRY',machineId:'FD-1',sessionId:freezeDrySession.id,trayIds:[freezeDry.carrier.id]})).status,403);assert.equal((await post('/api/cycles',freezeDryToken,{type:'DRY',machineId:'D-1',sessionId:drySession.id,containerIds:[dry.carrier.id]})).status,403);const dryCreated=await post('/api/cycles',dryToken,{type:'DRY',machineId:'D-1',sessionId:drySession.id,containerIds:[dry.carrier.id]});assert.equal(dryCreated.status,201);const dryCycle=(await dryCreated.json()).data;assert.equal((await post(`/api/cycles/${dryCycle.id}/start`,freezeDryToken,{sessionId:drySession.id})).status,403);assert.equal((await post(`/api/cycles/${dryCycle.id}/start`,dryToken,{sessionId:drySession.id})).status,201);const fdCreated=await post('/api/cycles',freezeDryToken,{type:'FREEZE_DRY',machineId:'FD-1',sessionId:freezeDrySession.id,trayIds:[freezeDry.carrier.id]});assert.equal(fdCreated.status,201);const fdCycle=(await fdCreated.json()).data;assert.equal((await post(`/api/cycles/${fdCycle.id}/start`,dryToken,{sessionId:freezeDrySession.id})).status,403);assert.equal((await post(`/api/cycles/${fdCycle.id}/start`,freezeDryToken,{sessionId:freezeDrySession.id})).status,201)}finally{server.close();await once(server,'close')}});

test('completed freezing creates work specifically for a freeze-drying operator',()=>{const app=new StoreMesh(),session=app.openSession('freezer','TEST-DEVICE','FREEZING','FREEZING_OPERATOR'),receiving=app.createContainer({capacityKg:20},key()),batch=app.receive({sessionId:session.id,containerId:receiving.id,supplier:'S',product:'T',grade:'A',size:'L',weightKg:10},key()),tray=app.createContainer({type:'TRAY',capacityKg:20},key());app.assignBatchToContainer(tray.id,batch.id,session.id,key());Object.assign(batch,{status:'SLICED',zone:'FREEZING'});Object.assign(tray,{status:'SLICED',zone:'FREEZING',activeSessionId:null});const cycle=createTestCycle(app,{type:'FREEZE',machineId:'F-1',sessionId:session.id,trayIds:[tray.id]},key());app.transitionCycle(cycle.id,'START',{sessionId:session.id},key());app.transitionCycle(cycle.id,'COMPLETE',{sessionId:session.id},key());app.transitionCycle(cycle.id,'FINISH',{sessionId:session.id},key());assert.equal(app.state.tasks.findLast(x=>x.title.startsWith('Freeze dry:')).requiredRole,'FREEZE_DRY_OPERATOR')});

test('HTTP MERGE is forbidden to general operators and remains available to sorting and manager roles',async()=>{const app=new StoreMesh(),washingId=key(),sortingId=key(),managerId=key(),washingSession=app.openSession(washingId,'TEST-DEVICE','WASHING','WASHING_OPERATOR'),sortingSession=app.openSession(sortingId,'RT-01','SORTING','SORTING_OPERATOR'),managerSession=app.openSession(managerId,'DEVICE-01','SORTING','MANAGER'),receive=(session,label)=>{const container=app.createContainer({capacityKg:10},key());return app.receive({sessionId:session.id,containerId:container.id,supplier:'S',product:'T',grade:'A',size:'L',weightKg:5},key())},a=receive(sortingSession,'a'),b=receive(sortingSession,'b'),c=receive(managerSession,'c'),d=receive(managerSession,'d'),auth=new AuthService({secret:'merge-role-secret'});auth.addUser({id:washingId,username:'washer',password:'right',roles:['WASHING_OPERATOR']});auth.addUser({id:sortingId,username:'sorter',password:'right',roles:['SORTING_OPERATOR']});auth.addUser({id:managerId,username:'manager',password:'right',roles:['MANAGER']});const server=createServer({app,auth});server.listen(0,'127.0.0.1');await once(server,'listening');try{const base=`http://127.0.0.1:${server.address().port}`,login=async username=>(await(await fetch(base+'/api/auth/login',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({username,password:'right'})})).json()).data.token,post=(token,body)=>fetch(base+'/api/transforms',{method:'POST',headers:{authorization:`Bearer ${token}`,'content-type':'application/json','idempotency-key':key()},body:JSON.stringify(body)}),washer=await login('washer'),sorter=await login('sorter'),manager=await login('manager'),merge=(session,x,y)=>{const container=app.createContainer({type:'BASKET',capacityKg:20,zone:'SORTING',designatedZones:['SORTING']},key());return{process:'MERGE',sessionId:session.id,containerId:container.id,inputs:[{batchId:x.id,consumeWeightKg:5},{batchId:y.id,consumeWeightKg:5}],outputWeightKg:9,grade:'A',size:'L'}};assert.equal((await post(washer,merge(washingSession,a,b))).status,403);assert.equal((await post(sorter,merge(sortingSession,a,b))).status,201);assert.equal((await post(manager,merge(managerSession,c,d))).status,201)}finally{server.close();await once(server,'close')}});

const finishDryCycle=(app,{finalWeight=5.5,configured=true,min=70,max=90}={})=>{const session=app.openSession(key(),'TEST-DEVICE','DRYING','DRYING_OPERATOR');if(configured){const draft=app.createConfiguration({scope:'YIELD_THRESHOLDS',values:{...(min===undefined?{}:{minYieldPercent:min}),...(max===undefined?{}:{maxYieldPercent:max})},userId:'author'},key());app.transitionConfiguration(draft.id,'APPROVE','reviewer',key());app.transitionConfiguration(draft.id,'ACTIVATE','reviewer',key())}const{carrier,batch}=stageCycle(app,session,'DRY'),cycle=createTestCycle(app,{type:'DRY',machineId:'D-1',sessionId:session.id,containerIds:[carrier.id]},key());app.transitionCycle(cycle.id,'START',{sessionId:session.id},key());app.transitionCycle(cycle.id,'COMPLETE',{sessionId:session.id},key());app.transitionCycle(cycle.id,'FINISH',{sessionId:session.id,finalWeights:{[batch.id]:finalWeight}},key());return{batch,cycle}};
test('configured low yield raises an advisory exception without blocking cycle finish',()=>{const app=new StoreMesh(),{batch,cycle}=finishDryCycle(app);assert.equal(cycle.status,'COMPLETED');assert.equal(batch.status,'DRIED');assert.equal(batch.yieldPercent,55);assert.ok(app.state.exceptions.some(x=>x.type==='YIELD_OUT_OF_RANGE'&&x.entityId===batch.id&&x.severity==='WARNING'))});
test('yield inside the configured range raises no warning',()=>{const app=new StoreMesh(),{batch}=finishDryCycle(app,{finalWeight:8});assert.equal(batch.yieldPercent,80);assert.equal(app.state.exceptions.some(x=>x.type==='YIELD_OUT_OF_RANGE'),false)});
test('low yield remains unchanged and unwarned when no threshold configuration is active',()=>{const app=new StoreMesh(),{batch,cycle}=finishDryCycle(app,{configured:false});assert.equal(cycle.status,'COMPLETED');assert.equal(batch.status,'DRIED');assert.equal(batch.yieldPercent,55);assert.equal(app.state.exceptions.some(x=>x.type==='YIELD_OUT_OF_RANGE'),false)});
