import test from 'node:test';
import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import { StoreMesh } from '../src/domain.js';
import { PostgresRepository } from '../src/postgres-repository.js';

const key=()=>randomUUID();
function received(app,session,period,weightKg=10){const container=app.createContainer({capacityKg:50},key()),batch=app.receive({sessionId:session.id,containerId:container.id,supplier:'S',product:'T',grade:'A',size:'L',weightKg},key());batch.harvestPeriod=period;batch.harvestPeriods=[period];return batch}
function cycleBatch(app,session,type,weightKg=10){const batch=received(app,session,'2026-W30',weightKg);batch.status=type==='FREEZE_DRY'?'FROZEN':type==='DRY'?'SORTED':'SLICED';batch.zone=type==='FREEZE_DRY'?'FREEZE_DRYING':type==='DRY'?'DRYING':'FREEZING';return batch}

test('MERGE preserves every distinct contributing harvest period without duplicates',()=>{const app=new StoreMesh(),session=app.openSession('operator','TEST-DEVICE'),mergeContainer=()=>app.createContainer({type:'BASKET',capacityKg:20,zone:'SORTING',designatedZones:['SORTING']},key()),a=received(app,session,'2026-W30'),b=received(app,session,'2026-W31'),merged=app.transform({sessionId:session.id,process:'MERGE',containerId:mergeContainer().id,inputs:[{batchId:a.id,consumeWeightKg:2},{batchId:b.id,consumeWeightKg:3}],outputWeightKg:5},key());assert.deepEqual(merged.harvestPeriods,['2026-W30','2026-W31']);assert.equal(merged.harvestPeriod,'2026-W31');const same=app.transform({sessionId:session.id,process:'MERGE',containerId:mergeContainer().id,inputs:[{batchId:a.id,consumeWeightKg:2},{batchId:received(app,session,'2026-W30').id,consumeWeightKg:2}],outputWeightKg:4},key());assert.deepEqual(same.harvestPeriods,['2026-W30']);assert.equal(same.harvestPeriod,'2026-W30')});

test('FREEZE_DRY and DRY accept batch identity plus total input weight without carrier scans',()=>{for(const type of ['FREEZE_DRY','DRY']){const app=new StoreMesh(),session=app.openSession('operator','TEST-DEVICE'),a=cycleBatch(app,session,type,6),b=cycleBatch(app,session,type,4),cycle=app.createCycle({type,machineId:`M-${type}`,sessionId:session.id,batchIds:[a.id,b.id],inputWeightKg:9},key());assert.deepEqual(cycle.containerIds,[]);assert.deepEqual(cycle.batchIds,[a.id,b.id]);assert.equal(cycle.inputWeightKg,9)}});

test('legacy scanned carrier flow remains supported while FREEZE still requires a tray scan',()=>{for(const type of ['FREEZE_DRY','DRY']){const app=new StoreMesh(),session=app.openSession('operator','TEST-DEVICE'),batch=cycleBatch(app,session,type),zone=batch.zone,carrier=app.createContainer({type:type==='DRY'?'BASKET':'TRAY',stage:'POST_SORT',capacityKg:50},key());app.assignBatchToContainer(carrier.id,batch.id,session.id,key());batch.zone=zone;carrier.zone=zone;carrier.status=type==='DRY'?'READY_FOR_DRYING':'FROZEN';carrier.activeSessionId=null;const cycle=app.createCycle({type,machineId:`M-${type}`,sessionId:session.id,...(type==='DRY'?{containerIds:[carrier.id]}:{trayIds:[carrier.id]})},key());assert.deepEqual(cycle.containerIds,[carrier.id]);assert.deepEqual(cycle.batchIds,[batch.id])}const app=new StoreMesh(),session=app.openSession('operator','TEST-DEVICE'),batch=cycleBatch(app,session,'FREEZE');assert.throws(()=>app.createCycle({type:'FREEZE',machineId:'M-FREEZE',sessionId:session.id,batchIds:[batch.id],inputWeightKg:batch.weightKg},key()),error=>error.code==='TRAY_SCAN_REQUIRED')});

test('harvest-period arrays and scan-optional cycle input survive PostgreSQL reload',{skip:!process.env.DATABASE_URL},async()=>{const site=`FR41-${Date.now()}`,repository=new PostgresRepository({connectionString:process.env.DATABASE_URL,siteCode:site});try{const app=new StoreMesh({site,seedDemoReferences:true});app.repository=repository;const session=app.openSession('operator','TEST-DEVICE'),a=received(app,session,'2026-W30'),b=received(app,session,'2026-W31'),mergeContainer=app.createContainer({type:'BASKET',capacityKg:20,zone:'SORTING',designatedZones:['SORTING']},key()),merged=app.transform({sessionId:session.id,process:'MERGE',containerId:mergeContainer.id,inputs:[{batchId:a.id,consumeWeightKg:2},{batchId:b.id,consumeWeightKg:3}],outputWeightKg:5},key());merged.status='FROZEN';merged.zone='FREEZE_DRYING';const cycle=app.createCycle({type:'FREEZE_DRY',machineId:'FD-1',sessionId:session.id,batchIds:[merged.id],inputWeightKg:4.5},key());await app.flush();const restored=await repository.load(),storedBatch=restored.batches.find(x=>x.id===merged.id),storedCycle=restored.cycles.find(x=>x.id===cycle.id);assert.deepEqual(storedBatch.harvestPeriods,['2026-W30','2026-W31']);assert.equal(storedBatch.harvestPeriod,'2026-W31');assert.deepEqual(storedCycle.batchIds,[merged.id]);assert.deepEqual(storedCycle.containerIds,[]);assert.equal(storedCycle.inputWeightKg,4.5)}finally{await repository.close()}});
