import test from'node:test';import assert from'node:assert/strict';import{randomUUID}from'node:crypto';import{StoreMesh}from'../src/domain.js';import{PostgresRepository}from'../src/postgres-repository.js';
const key=()=>randomUUID();
function washed(app=new StoreMesh()){const session=app.openSession('operator','TEST-DEVICE','WASHING','WASHING_OPERATOR'),container=app.createContainer({capacityKg:20},key()),batch=app.receive({sessionId:session.id,containerId:container.id,supplier:'S',product:'T',grade:'A',size:'L',weightKg:5},key());Object.assign(batch,{status:'WASHED',zone:'SLICING'});Object.assign(container,{zone:'SLICING',status:'WASHED'});return{app,session,container,batch}}
function checklist(app){return app.createQcChecklist({code:`WASH-${key()}`,product:'T',stage:'WASHING',name:'Washing release',items:[{code:'OK',prompt:'Washing accepted'}]},key())}
function approve(app,batch,list){return app.qualityCheck({batchId:batch.id,stage:'WASHING',checklistId:list.id,responses:[{itemCode:'OK',value:true}],result:'APPROVED',inspectorId:key(),actorRoles:['QUALITY_OPERATOR'],attestation:{confirmed:true,role:'QUALITY_OPERATOR'}},key())}
function slice({app,session,container,batch}){return app.transform({sessionId:session.id,containerId:container.id,inputs:[{batchId:batch.id}],process:'SLICE'},key())}
test('an active Washing checklist blocks Slicing until approved',()=>{const context=washed(),list=checklist(context.app);assert.throws(()=>slice(context),e=>e.code==='BATCH_QC_APPROVAL_REQUIRED');approve(context.app,context.batch,list);assert.equal(slice(context),context.batch)});
test('a stage without an active checklist remains ungated',()=>{const context=washed();assert.equal(slice(context),context.batch)});
test('non-Sorting QC gate survives PostgreSQL reload',{skip:!process.env.DATABASE_URL},async()=>{const repository=new PostgresRepository({connectionString:process.env.DATABASE_URL,siteCode:`FR35-${Date.now()}`});try{const context=washed(new StoreMesh({site:repository.siteCode,initialState:await repository.load(),seedDemoReferences:true}));context.app.repository=repository;const list=checklist(context.app);context.app.persist();await context.app.flush();const restored=new StoreMesh({site:repository.siteCode,initialState:await repository.load()});assert.throws(()=>restored.assertBatchUsable(restored.batch(context.batch.id)),e=>e.code==='BATCH_QC_APPROVAL_REQUIRED');approve(restored,restored.batch(context.batch.id),restored.state.qcChecklists.find(x=>x.id===list.id));assert.equal(restored.assertBatchUsable(restored.batch(context.batch.id)).id,context.batch.id)}finally{await repository.close()}});
