import test from 'node:test';
import assert from 'node:assert/strict';
import {once} from 'node:events';
import {randomUUID} from 'node:crypto';
import {StoreMesh} from '../src/domain.js';
import {PostgresRepository} from '../src/postgres-repository.js';
import {AuthService} from '../src/auth.js';
import {createServer} from '../src/server.js';

test('real PostgreSQL HTTP QC rejection and attested JWT role survive reload and block operations',{skip:!process.env.DATABASE_URL},async()=>{const site=`FR8B-${Date.now()}`,repository=new PostgresRepository({connectionString:process.env.DATABASE_URL,siteCode:site}),initialState=await repository.load(),app=new StoreMesh({site,initialState,seedDemoReferences:true});app.repository=repository;const seedSession=app.openSession('seed','TEST-DEVICE'),container=app.createContainer({capacityKg:20},'container'),batch=app.receive({sessionId:seedSession.id,containerId:container.id,supplier:'S',product:'T',grade:'A',size:'L',weightKg:7},'receive'),checklist=app.createQcChecklist({code:'QC-PG',product:'T',stage:'RECEIVING',name:'Receiving QC',items:[{code:'SAFE',prompt:'Safe'}]},'checklist');await app.flush();const auth=new AuthService({site,secret:'qc-postgres-http-secret'}),qualityUserId=randomUUID();auth.addUser({id:qualityUserId,username:'quality',password:'right',roles:['QUALITY_OPERATOR']});const server=createServer({app,auth});server.listen(0,'127.0.0.1');await once(server,'listening');try{const base=`http://127.0.0.1:${server.address().port}`,login=await fetch(`${base}/api/auth/login`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({username:'quality',password:'right'})}),token=(await login.json()).data.token,post=body=>fetch(`${base}/api/quality-checks`,{method:'POST',headers:{authorization:`Bearer ${token}`,'content-type':'application/json','idempotency-key':randomUUID()},body:JSON.stringify(body)}),request={sessionId:seedSession.id,batchId:batch.id,stage:'RECEIVING',checklistId:checklist.id,responses:[{itemCode:'SAFE',value:false}],result:'REJECTED',attestation:{confirmed:true,role:'MANAGER'}};assert.equal((await post({...request,actorRoles:['MANAGER']})).status,403);request.attestation.role='QUALITY_OPERATOR';assert.equal((await post(request)).status,201);await app.flush();const restored=await repository.load(),restoredApp=new StoreMesh({site,initialState:restored,seedDemoReferences:false}),storedCheck=restored.qualityChecks.find(x=>x.batchId===batch.id);assert.equal(storedCheck.result,'REJECTED');assert.equal(storedCheck.inspectorId,qualityUserId);assert.equal(storedCheck.attestation.role,'QUALITY_OPERATOR');assert.throws(()=>restoredApp.assertBatchUsable(restoredApp.batch(batch.id)),error=>error.code==='BATCH_QC_REJECTED')}finally{server.close();await once(server,'close');await repository.close()}});
