import test from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {once} from 'node:events';
import {StoreMesh} from '../src/domain.js';
import {AuthService} from '../src/auth.js';
import {createServer} from '../src/server.js';

const rejected=()=>{const app=new StoreMesh(),session=app.openSession('quality-user','TEST-DEVICE','QC','QUALITY_OPERATOR'),container=app.createContainer({capacityKg:20},'container'),batch=app.receive({sessionId:session.id,containerId:container.id,supplier:'S',product:'T',grade:'A',size:'L',weightKg:10},'receive'),checklist=app.createQcChecklist({code:'QC-RECEIVE',product:'T',stage:'RECEIVING',name:'Receiving QC',items:[{code:'SAFE',prompt:'Safe product'}]},'checklist');app.qualityCheck({batchId:batch.id,stage:'RECEIVING',checklistId:checklist.id,responses:[{itemCode:'SAFE',value:false}],result:'REJECTED',inspectorId:randomUUID(),actorRoles:['QUALITY_OPERATOR'],attestation:{confirmed:true,role:'QUALITY_OPERATOR'}},'reject');return{app,session,container,batch}};
const rejectedCode=fn=>assert.throws(fn,error=>error.code==='BATCH_QC_REJECTED'&&error.status===409);

test('latest REJECTED QC blocks sorting, transforms, cycles, weighing, packaging, and shipping',()=>{
  for(const operation of['sort','transform','cycle','weigh','package','shipment']){
    const{app,session,container,batch}=rejected();
    if(operation==='sort'){Object.assign(container,{zone:'COLD_ROOM_CLEAN',status:'IN_USE',activeSessionId:null});rejectedCode(()=>app.sortBatch({sessionId:session.id,containerId:container.id,batchId:batch.id,outputs:[{grade:'A',size:'L',weightKg:9}]},'sort'))}
    if(operation==='transform')rejectedCode(()=>app.transform({sessionId:session.id,process:'MERGE',inputs:[{batchId:batch.id,consumeWeightKg:1}],outputWeightKg:1},'transform'));
    if(operation==='cycle'){Object.assign(batch,{status:'SORTED',zone:'DRYING'});Object.assign(container,{zone:'DRYING',status:'READY_FOR_DRYING',activeSessionId:null});rejectedCode(()=>app.createCycle({sessionId:session.id,type:'DRY',machineId:'DRYER-1',containerIds:[container.id]},'cycle'))}
    if(operation==='weigh'){session.selectedRole='PACKAGING_OPERATOR';batch.status='DRIED';rejectedCode(()=>app.weighForPackaging({sessionId:session.id,batchId:batch.id,weightKg:10},'weigh'))}
    if(operation==='package'){session.selectedRole='PACKAGING_OPERATOR';batch.status='READY_FOR_PACKAGING';rejectedCode(()=>app.createPackage({sessionId:session.id,type:'POUCH',level:'UNIT',items:[{batchId:batch.id,weightKg:1}],targetWeightKg:1},'package'))}
    if(operation==='shipment'){const pkg={id:randomUUID(),code:'P-REJECTED',type:'CARTON',level:'CARTON',status:'READY_TO_SHIP',items:[{batchId:batch.id,weightKg:1}],childPackageIds:[],createdAt:new Date().toISOString()},customer=app.createCustomer({code:'QC-C',name:'QC Customer'},'customer'),order=app.createSalesOrder({customerId:customer.id,items:[{packageType:'CARTON',quantity:1}]},'order');app.state.packages.push(pkg);rejectedCode(()=>app.createShipment({salesOrderId:order.id,packageIds:[pkg.id]},'shipment'))}
  }
});

test('QC checklist stage and signing role come from actual server state and authenticated roles',()=>{const app=new StoreMesh(),session=app.openSession('quality-user','TEST-DEVICE'),container=app.createContainer({capacityKg:20},'container'),batch=app.receive({sessionId:session.id,containerId:container.id,supplier:'S',product:'T',grade:'A',size:'L',weightKg:5},'receive'),wrong=app.createQcChecklist({code:'QC-SORT',product:'T',stage:'SORTING',name:'Sorting QC',items:[{code:'SAFE',prompt:'Safe'}]},'wrong'),right=app.createQcChecklist({code:'QC-RECV',product:'T',stage:'RECEIVING',name:'Receiving QC',items:[{code:'SAFE',prompt:'Safe'}]},'right'),base={batchId:batch.id,responses:[{itemCode:'SAFE',value:true}],result:'APPROVED',inspectorId:randomUUID(),actorRoles:['QUALITY_OPERATOR']};assert.throws(()=>app.qualityCheck({...base,stage:'SORTING',checklistId:wrong.id,attestation:{confirmed:true,role:'QUALITY_OPERATOR'}},'wrong-stage'),e=>e.code==='QC_CHECKLIST_STAGE_MISMATCH');assert.throws(()=>app.qualityCheck({...base,stage:'RECEIVING',checklistId:right.id,attestation:{confirmed:true,role:'MANAGER'}},'forged-role'),e=>e.code==='QC_ATTESTATION_ROLE_MISMATCH');assert.equal(app.qualityCheck({...base,stage:'RECEIVING',checklistId:right.id,attestation:{confirmed:true,role:'QUALITY_OPERATOR'}},'valid').result,'APPROVED')});

test('quarantine and release keep the physical container aligned with its batch',()=>{const app=new StoreMesh(),session=app.openSession('quality-user','TEST-DEVICE'),container=app.createContainer({capacityKg:20},'container'),batch=app.receive({sessionId:session.id,containerId:container.id,supplier:'S',product:'T',grade:'A',size:'L',weightKg:5},'receive'),checklist=app.createQcChecklist({code:'QC-Q',product:'T',stage:'RECEIVING',name:'Receiving QC',items:[{code:'SAFE',prompt:'Safe'}]},'checklist');app.qualityCheck({batchId:batch.id,stage:'RECEIVING',checklistId:checklist.id,responses:[{itemCode:'SAFE',value:false}],result:'QUARANTINED',inspectorId:randomUUID(),actorRoles:['QUALITY_OPERATOR'],attestation:{confirmed:true,role:'QUALITY_OPERATOR'}},'quarantine');assert.deepEqual([batch.zone,container.zone,container.status],['QUARANTINE','QUARANTINE','QUARANTINED']);app.releaseQuarantine({batchId:batch.id,destinationZone:'COLD_ROOM_CLEAN',reason:'Retest passed',inspectorId:randomUUID()},'release');assert.deepEqual([batch.zone,container.zone,container.status],['COLD_ROOM_CLEAN','COLD_ROOM_CLEAN','IN_USE']);assert.equal(app.assertBatchUsable(batch),batch)});

test('HTTP QC attestation cannot forge a role outside the verified JWT',async()=>{const app=new StoreMesh(),session=app.openSession('seed','TEST-DEVICE'),container=app.createContainer({capacityKg:20},'container'),batch=app.receive({sessionId:session.id,containerId:container.id,supplier:'S',product:'T',grade:'A',size:'L',weightKg:5},'receive'),checklist=app.createQcChecklist({code:'QC-HTTP',product:'T',stage:'RECEIVING',name:'Receiving QC',items:[{code:'SAFE',prompt:'Safe'}]},'checklist'),auth=new AuthService({secret:'qc-http-secret'}),userId=randomUUID();auth.addUser({id:userId,username:'quality',password:'right',roles:['QUALITY_OPERATOR']});const server=createServer({app,auth});server.listen(0,'127.0.0.1');await once(server,'listening');try{const base=`http://127.0.0.1:${server.address().port}`,login=await fetch(`${base}/api/auth/login`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({username:'quality',password:'right'})}),token=(await login.json()).data.token,submit=role=>fetch(`${base}/api/quality-checks`,{method:'POST',headers:{authorization:`Bearer ${token}`,'content-type':'application/json','idempotency-key':randomUUID()},body:JSON.stringify({batchId:batch.id,stage:'RECEIVING',checklistId:checklist.id,responses:[{itemCode:'SAFE',value:true}],result:'APPROVED',actorRoles:['MANAGER'],attestation:{confirmed:true,role}})});const forged=await submit('MANAGER');assert.equal(forged.status,403);assert.equal((await forged.json()).errorCode,'QC_ATTESTATION_ROLE_MISMATCH');assert.equal((await submit('QUALITY_OPERATOR')).status,201)}finally{server.close();await once(server,'close')}});
