import test from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {once} from 'node:events';
import {StoreMesh} from '../src/domain.js';
import {PostgresRepository} from '../src/postgres-repository.js';
import {AuthService} from '../src/auth.js';
import {createServer} from '../src/server.js';

const key=()=>randomUUID();
const fixture=(app=new StoreMesh())=>{const session=app.openSession('quality-user','TEST-DEVICE','QC','QUALITY_OPERATOR'),container=app.createContainer({capacityKg:20},key()),batch=app.receive({sessionId:session.id,containerId:container.id,supplier:'S',product:'T',grade:'A',size:'L',weightKg:5},key()),checklist=app.createQcChecklist({code:`QC-${key()}`,product:'T',stage:'RECEIVING',name:'Receiving QC',items:[{code:'VISUAL',prompt:'Visual pass'},{code:'TEMP',prompt:'Temperature pass'}]},key());return{app,session,container,batch,checklist}};
const attested=(inspectorId=randomUUID(),role='QUALITY_OPERATOR')=>({inspectorId,actorRoles:['QUALITY_OPERATOR'],attestation:{confirmed:true,role}});
const quarantine=({app,batch,checklist},inspectorId=randomUUID())=>app.qualityCheck({sessionId:app.state.sessions.find(x=>x.status==='ACTIVE')?.id,batchId:batch.id,stage:'RECEIVING',checklistId:checklist.id,responses:[{itemCode:'VISUAL',value:false},{itemCode:'TEMP',value:true}],result:'QUARANTINED',...attested(inspectorId)},key());

test('quarantine release requires explicit attestation and an authenticated signing role',()=>{const context=fixture(),{app,batch}=context;quarantine(context);const base={sessionId:context.session.id,batchId:batch.id,reason:'Retest passed',destinationZone:'COLD_ROOM_CLEAN',inspectorId:randomUUID(),actorRoles:['QUALITY_OPERATOR']};assert.throws(()=>app.releaseQuarantine(base,key()),error=>error.code==='QC_ATTESTATION_REQUIRED');assert.throws(()=>app.releaseQuarantine({sessionId:app.state.sessions.find(x=>x.status==='ACTIVE')?.id,...base,attestation:{confirmed:true,role:'MANAGER'}},key()),error=>error.code==='QC_ATTESTATION_ROLE_MISMATCH');assert.equal(batch.status,'QUARANTINED')});

test('HTTP quarantine release derives signing-role eligibility from the JWT',async()=>{const context=fixture(),{app,batch,session}=context;quarantine(context);const userId=randomUUID(),auth=new AuthService({secret:'qc-release-secret'});auth.addUser({id:userId,username:'quality-release',password:'right',roles:['QUALITY_OPERATOR']});const server=createServer({app,auth});server.listen(0,'127.0.0.1');await once(server,'listening');try{const base=`http://127.0.0.1:${server.address().port}`,login=await fetch(`${base}/api/auth/login`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({username:'quality-release',password:'right'})}),token=(await login.json()).data.token,release=role=>fetch(`${base}/api/quality-checks/release`,{method:'POST',headers:{authorization:`Bearer ${token}`,'content-type':'application/json','idempotency-key':key()},body:JSON.stringify({batchId:batch.id,reason:'Retest passed',destinationZone:'COLD_ROOM_CLEAN',sessionId:session.id,actorRoles:['MANAGER'],attestation:{confirmed:true,role}})});const forged=await release('MANAGER');assert.equal(forged.status,403);assert.equal((await forged.json()).errorCode,'QC_ATTESTATION_ROLE_MISMATCH');assert.equal((await release('QUALITY_OPERATOR')).status,201)}finally{server.close();await once(server,'close')}});

test('release attestation and linked exception resolution survive PostgreSQL reload',{skip:!process.env.DATABASE_URL},async()=>{const site=`FR25-${Date.now()}`,repository=new PostgresRepository({connectionString:process.env.DATABASE_URL,siteCode:site});try{const app=new StoreMesh({site,initialState:await repository.load(),seedDemoReferences:true});app.repository=repository;const context=fixture(app),inspectorId=randomUUID(),quarantineCheck=quarantine(context,inspectorId),raised=app.state.exceptions.find(x=>x.id===quarantineCheck.exceptionId);assert.equal(raised.status,'OPEN');const release=app.releaseQuarantine({sessionId:app.state.sessions.find(x=>x.status==='ACTIVE')?.id,batchId:context.batch.id,reason:'Laboratory retest passed',destinationZone:'COLD_ROOM_CLEAN',...attested(inspectorId)},key());assert.equal(raised.status,'RESOLVED');assert.equal(release.exceptionId,raised.id);await app.flush();const restored=await repository.load(),storedRelease=restored.qualityChecks.find(x=>x.id===release.id),storedQuarantine=restored.qualityChecks.find(x=>x.id===quarantineCheck.id),storedException=restored.exceptions.find(x=>x.id===raised.id);assert.deepEqual(storedRelease.attestation,{confirmed:true,role:'QUALITY_OPERATOR',signedAt:release.attestation.signedAt,userId:inspectorId});assert.equal(storedQuarantine.exceptionId,raised.id);assert.equal(storedRelease.exceptionId,raised.id);assert.equal(storedException.status,'RESOLVED');assert.equal(storedException.resolvedBy,inspectorId)}finally{await repository.close()}});

test('QC responses reject unknown duplicate missing and contradictory values while normal approval succeeds',()=>{const{app,batch,checklist}=fixture(),base={batchId:batch.id,stage:'RECEIVING',checklistId:checklist.id,result:'APPROVED',...attested()};assert.throws(()=>app.qualityCheck({sessionId:app.state.sessions.find(x=>x.status==='ACTIVE')?.id,...base,responses:[{itemCode:'VISUAL',value:true},{itemCode:'TEMP',value:true},{itemCode:'OTHER',value:true}]},key()),error=>error.code==='QC_RESPONSE_UNKNOWN_ITEM');assert.throws(()=>app.qualityCheck({sessionId:app.state.sessions.find(x=>x.status==='ACTIVE')?.id,...base,responses:[{itemCode:'VISUAL',value:true},{itemCode:'VISUAL',value:true},{itemCode:'TEMP',value:true}]},key()),error=>error.code==='QC_RESPONSE_DUPLICATE_ITEM');assert.throws(()=>app.qualityCheck({sessionId:app.state.sessions.find(x=>x.status==='ACTIVE')?.id,...base,responses:[{itemCode:'VISUAL',value:null},{itemCode:'TEMP',value:true}]},key()),error=>error.code==='QC_RESPONSE_VALUE_REQUIRED');for(const value of[false,'fail','REJECTED'])assert.throws(()=>app.qualityCheck({sessionId:app.state.sessions.find(x=>x.status==='ACTIVE')?.id,...base,responses:[{itemCode:'VISUAL',value},{itemCode:'TEMP',value:true}]},key()),error=>error.code==='QC_RESULT_RESPONSE_MISMATCH');const approved=app.qualityCheck({sessionId:app.state.sessions.find(x=>x.status==='ACTIVE')?.id,...base,responses:[{itemCode:'VISUAL',value:true},{itemCode:'TEMP',value:'PASS'}]},key());assert.equal(approved.result,'APPROVED')});
