import test from 'node:test';
import assert from 'node:assert/strict';
import {StoreMesh} from '../src/domain.js';
import {PostgresRepository} from '../src/postgres-repository.js';

const key=()=>crypto.randomUUID();
const fixture=()=>{const app=new StoreMesh(),session=app.openSession('receiver','TEST-DEVICE','RECEIVING','RECEIVING_OPERATOR');return{app,session}};

test('an empty open delivery can be cancelled with reason and immediately replaced',()=>{const{app,session}=fixture(),delivery=app.startDelivery({supplierCode:'S',sessionId:session.id},key()),cancelled=app.cancelDelivery(delivery.id,{sessionId:session.id,reason:' Wrong supplier selected '},key());assert.equal(cancelled.status,'CANCELLED');assert.equal(cancelled.cancelledReason,'Wrong supplier selected');assert.ok(cancelled.cancelledAt);assert.equal(app.startDelivery({supplierCode:'S1',sessionId:session.id},key()).status,'OPEN')});
test('delivery cancellation requires a non-empty reason',()=>{const{app,session}=fixture(),delivery=app.startDelivery({supplierCode:'S',sessionId:session.id},key());for(const reason of[undefined,'','   '])assert.throws(()=>app.cancelDelivery(delivery.id,{sessionId:session.id,reason},key()),e=>e.code==='DELIVERY_CANCEL_REASON_REQUIRED')});
test('a delivery with a weighed basket cannot be cancelled',()=>{const{app,session}=fixture(),delivery=app.startDelivery({supplierCode:'S',sessionId:session.id},key()),container=app.createContainer({capacityKg:20},key());app.receive({deliveryId:delivery.id,sessionId:session.id,containerId:container.id,supplier:'S',product:'T',grade:'A',size:'L',weightKg:5},key());assert.throws(()=>app.cancelDelivery(delivery.id,{sessionId:session.id,reason:'abandon'},key()),e=>e.code==='DELIVERY_HAS_BASKETS')});
test('completed and already cancelled deliveries cannot be cancelled',()=>{const{app,session}=fixture(),completed=app.startDelivery({supplierCode:'S',sessionId:session.id},key()),container=app.createContainer({capacityKg:20},key());app.receive({deliveryId:completed.id,sessionId:session.id,containerId:container.id,supplier:'S',product:'T',grade:'A',size:'L',weightKg:5},key());app.completeDelivery(completed.id,{sessionId:session.id},key());assert.throws(()=>app.cancelDelivery(completed.id,{sessionId:session.id,reason:'late'},key()),e=>e.code==='DELIVERY_NOT_OPEN');const cancelled=app.startDelivery({supplierCode:'S1',sessionId:session.id},key());app.cancelDelivery(cancelled.id,{sessionId:session.id,reason:'mistake'},key());assert.throws(()=>app.cancelDelivery(cancelled.id,{sessionId:session.id,reason:'again'},key()),e=>e.code==='DELIVERY_NOT_OPEN')});
test('active RECEIVING configuration overrides a client attempt to widen weight tolerance',()=>{const{app,session}=fixture(),draft=app.createConfiguration({scope:'RECEIVING',values:{weightVarianceLimit:.1},userId:'author'},key());app.transitionConfiguration(draft.id,'APPROVE','reviewer',key());app.transitionConfiguration(draft.id,'ACTIVATE','reviewer',key());const container=app.createContainer({capacityKg:100},key()),batch=app.receive({sessionId:session.id,containerId:container.id,supplier:'S',product:'T',grade:'A',size:'L',weightKg:80,expectedWeightKg:100,weightVarianceLimit:.9},key());assert.equal(batch.configVersionId,draft.id);assert.ok(app.state.exceptions.some(x=>x.type==='WEIGHT_ANOMALY'&&x.entityId===batch.id))});
test('client weight tolerance cannot replace the receiving default without an active configuration',()=>{const{app,session}=fixture(),container=app.createContainer({capacityKg:100},key()),batch=app.receive({sessionId:session.id,containerId:container.id,supplier:'S',product:'T',grade:'A',size:'L',weightKg:80,expectedWeightKg:100,weightVarianceLimit:.9},key());assert.equal(batch.configVersionId,null);assert.ok(app.state.exceptions.some(x=>x.type==='WEIGHT_ANOMALY'&&x.entityId===batch.id))});
test('a recent same-supplier open or completed delivery raises an advisory warning without blocking',()=>{for(const priorStatus of['OPEN','COMPLETED']){let now='2026-08-27T08:00:00.000Z';const app=new StoreMesh({clock:()=>now}),firstSession=app.openSession('one','TEST-DEVICE','RECEIVING','RECEIVING_OPERATOR'),first=app.startDelivery({supplierCode:'S',sessionId:firstSession.id},key());if(priorStatus==='COMPLETED'){const container=app.createContainer({capacityKg:20},key());app.receive({deliveryId:first.id,sessionId:firstSession.id,containerId:container.id,supplier:'S',product:'T',grade:'A',size:'L',weightKg:5},key());app.completeDelivery(first.id,{sessionId:firstSession.id},key())}now='2026-08-27T10:00:00.000Z';const secondSession=app.openSession('two','RT-01','RECEIVING','RECEIVING_OPERATOR'),second=app.startDelivery({supplierCode:'S',sessionId:secondSession.id},key()),warning=app.state.exceptions.find(x=>x.type==='DUPLICATE_DELIVERY_SUSPECTED'&&x.entityId===second.id);assert.equal(second.status,'OPEN');assert.equal(warning?.severity,'WARNING')}});
test('different suppliers and same suppliers more than four hours later do not raise duplicate warnings',()=>{let now='2026-08-27T08:00:00.000Z';const app=new StoreMesh({clock:()=>now}),one=app.openSession('one','TEST-DEVICE','RECEIVING','RECEIVING_OPERATOR');app.startDelivery({supplierCode:'S',sessionId:one.id},key());const two=app.openSession('two','RT-01','RECEIVING','RECEIVING_OPERATOR');app.startDelivery({supplierCode:'S1',sessionId:two.id},key());now='2026-08-27T12:00:01.000Z';const three=app.openSession('three','DEVICE-01','RECEIVING','RECEIVING_OPERATOR'),later=app.startDelivery({supplierCode:'S',sessionId:three.id},key());assert.equal(app.state.exceptions.some(x=>x.type==='DUPLICATE_DELIVERY_SUSPECTED'&&x.entityId===later.id),false);assert.equal(app.state.exceptions.length,0)});
test('delivery cancellation and duplicate warning survive PostgreSQL reload',{skip:!process.env.DATABASE_URL},async()=>{const site=`FR21-${Date.now()}`,repository=new PostgresRepository({connectionString:process.env.DATABASE_URL,siteCode:site});try{const app=new StoreMesh({site,initialState:await repository.load(),seedDemoReferences:true});app.repository=repository;const first=app.openSession('one','TEST-DEVICE','RECEIVING','RECEIVING_OPERATOR'),cancelled=app.startDelivery({supplierCode:'S',sessionId:first.id},key());app.cancelDelivery(cancelled.id,{sessionId:first.id,reason:'duplicate paperwork'},key());const second=app.openSession('two','RT-01','RECEIVING','RECEIVING_OPERATOR'),prior=app.startDelivery({supplierCode:'S1',sessionId:second.id},key()),third=app.openSession('three','DEVICE-01','RECEIVING','RECEIVING_OPERATOR'),duplicate=app.startDelivery({supplierCode:'S1',sessionId:third.id},key());await app.flush();const restored=await repository.load(),stored=restored.deliveries.find(x=>x.id===cancelled.id);assert.equal(stored.status,'CANCELLED');assert.equal(stored.cancelledReason,'duplicate paperwork');assert.ok(stored.cancelledAt);assert.ok(restored.deliveries.some(x=>x.id===prior.id));assert.ok(restored.exceptions.some(x=>x.type==='DUPLICATE_DELIVERY_SUSPECTED'&&x.entityId===duplicate.id))}finally{await repository.close()}});
