import test from 'node:test';
import assert from 'node:assert/strict';
import { once } from 'node:events';
import { randomUUID } from 'node:crypto';
import { StoreMesh } from '../src/domain.js';
import { AuthService } from '../src/auth.js';
import { createServer } from '../src/server.js';

test('custom role created and assigned through HTTP gates real endpoints',async()=>{
  const app=new StoreMesh(),auth=new AuthService({secret:'round12-secret',site:'IRAN'}),adminId=randomUUID(),userId=randomUUID();
  auth.addUser({id:adminId,username:'admin-r12',password:'secret',roles:['ADMIN']});auth.addUser({id:userId,username:'auditor-r12',password:'secret',roles:[]});
  const server=createServer({app,auth,requireAuth:true});server.listen(0);await once(server,'listening');const base=`http://127.0.0.1:${server.address().port}`;
  const login=async username=>(await (await fetch(base+'/api/auth/login',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({username,password:'secret',deviceId:'WEB-R12'})})).json()).data.token;
  try{const admin=await login('admin-r12'),headers={authorization:`Bearer ${admin}`,'content-type':'application/json'};let response=await fetch(base+'/api/roles',{method:'POST',headers,body:JSON.stringify({code:'CUSTOM_AUDITOR',name:'Custom auditor',permissions:['inventory:read']})});assert.equal(response.status,201);response=await fetch(`${base}/api/users/${userId}/roles`,{method:'POST',headers,body:JSON.stringify({roleCode:'CUSTOM_AUDITOR'})});assert.equal(response.status,201);const token=await login('auditor-r12');assert.equal((await fetch(base+'/api/inventory',{headers:{authorization:`Bearer ${token}`}})).status,200);assert.equal((await fetch(base+'/api/sessions',{method:'POST',headers:{authorization:`Bearer ${token}`,'content-type':'application/json'},body:'{}'})).status,403)}finally{server.close();await once(server,'close')}
});

test('admin user listing exposes assignments but never credential material',async()=>{
  const auth=new AuthService({secret:'users-list-secret',site:'IRAN'}),app=new StoreMesh({site:'IRAN'}),adminId=randomUUID(),userId=randomUUID();
  auth.addUser({id:adminId,username:'admin-users',password:'right',roles:['ADMIN']});auth.addUser({id:userId,username:'operator-users',password:'secret-value',roles:['RECEIVING_OPERATOR']});auth.assignBadge(userId);
  const server=createServer({app,auth});server.listen(0,'127.0.0.1');await once(server,'listening');const base=`http://127.0.0.1:${server.address().port}`;
  try{const login=await fetch(base+'/api/auth/login',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({username:'admin-users',password:'right'})}),token=(await login.json()).data.token,response=await fetch(base+'/api/users',{headers:{authorization:`Bearer ${token}`}}),payload=await response.json();assert.equal(response.status,200);const listed=payload.items.find(x=>x.id===userId);assert.deepEqual(listed.roles,['RECEIVING_OPERATOR']);assert.equal(listed.badgeAssigned,true);assert.equal('passwordHash'in listed,false);assert.equal('salt'in listed,false);assert.equal('badgeCodeHash'in listed,false)}finally{server.close();await once(server,'close')}
});
test('the final active administrator role cannot be revoked',async()=>{const auth=new AuthService({secret:'last-admin',site:'IRAN'}),id=randomUUID();auth.addUser({id,username:'only-admin',password:'right',roles:['ADMIN']});await assert.rejects(()=>auth.revokeRole(id,'ADMIN'),e=>e.code==='LAST_ADMIN_ROLE_REQUIRED'&&e.status===409);assert.deepEqual(auth.userById(id).roles,['ADMIN'])});

test('QC checklist requires explicit attestation and spawns corrective work',()=>{const app=new StoreMesh(),session=app.openSession('op','TEST-DEVICE'),container=app.createContainer({capacityKg:20},'container'),batch=app.receive({sessionId:session.id,containerId:container.id,supplier:'S',product:'T',grade:'A',size:'L',weightKg:8},'receive'),checklist=app.createQcChecklist({code:'QC-RECEIVE',product:'T',stage:'RECEIVING',name:'Receiving QC',items:[{code:'VISUAL',prompt:'Visual condition'}]},'checklist');assert.throws(()=>app.qualityCheck({batchId:batch.id,stage:'RECEIVING',checklistId:checklist.id,responses:[],result:'REJECTED'},'bad'),e=>e.code==='QC_CHECKLIST_INCOMPLETE');const result=app.qualityCheck({batchId:batch.id,stage:'RECEIVING',checklistId:checklist.id,responses:[{itemCode:'VISUAL',value:false}],attestation:{confirmed:true,role:'QUALITY_OPERATOR'},inspectorId:randomUUID(),result:'REJECTED'},'qc');assert.ok(result.attestation.signedAt);assert.equal(app.task(result.correctiveTaskId).status,'OPEN')});

test('cancelled and damaged packages release allocated inventory exactly once',()=>{const app=new StoreMesh(),session=app.openSession('op','TEST-DEVICE','PACKAGING','PACKAGING_OPERATOR'),container=app.createContainer({capacityKg:20},'container'),batch=app.receive({sessionId:session.id,containerId:container.id,supplier:'S',product:'T',grade:'A',size:'L',weightKg:10},'receive');batch.status='DRIED';app.weighForPackaging({sessionId:session.id,batchId:batch.id,weightKg:10},'weigh');const pkg=app.createPackage({type:'POUCH',level:'UNIT',sessionId:session.id,items:[{batchId:batch.id,weightKg:4}],targetWeightKg:4,tolerancePercent:0},'package');assert.equal(batch.weightKg,6);app.transitionPackage(pkg.id,'CANCEL','cancel',{reason:'packing error'});assert.equal(batch.weightKg,10);assert.equal(pkg.status,'CANCELLED');assert.throws(()=>app.transitionPackage(pkg.id,'CANCEL','again',{reason:'again'}),e=>e.code==='PACKAGE_TERMINATION_INVALID')});

test('carton assembly accepts distinct incremental physical UNIT scan events',()=>{const app=new StoreMesh(),session=app.openSession('op','PDA-PACK-01','PACKAGING','PACKAGING_OPERATOR'),container=app.createContainer({capacityKg:20},'container'),batch=app.receive({sessionId:session.id,containerId:container.id,supplier:'S',product:'T',grade:'A',size:'L',weightKg:10},'receive');batch.status='DRIED';app.weighForPackaging({sessionId:session.id,batchId:batch.id,weightKg:10},'weigh');const makeUnit=(weight,key)=>{const unit=app.createPackage({type:'POUCH',level:'UNIT',sessionId:session.id,items:[{batchId:batch.id,weightKg:weight}],targetWeightKg:weight,tolerancePercent:0},key);for(const action of['PACK','SEAL','PRINT','PRINT_SUCCESS','READY'])app.transitionPackage(unit.id,action,`${key}-${action}`);return unit},unitOne=makeUnit(1,'unit1'),unitTwo=makeUnit(2,'unit2'),pkg=app.createPackage({type:'CARTON',level:'CARTON',sessionId:session.id,childPackageIds:[unitOne.id,unitTwo.id]},'package');app.transitionPackage(pkg.id,'PACK','pack');const one=app.scanPackageItem(pkg.id,{unitPackageCode:unitOne.code,sessionId:session.id},'scan1'),two=app.scanPackageItem(pkg.id,{unitPackageCode:unitTwo.code,sessionId:session.id},'scan2');assert.deepEqual([one.sequenceNo,two.sequenceNo],[1,2]);assert.notEqual(one.scannedAt,undefined);assert.equal(one.deviceId,'PDA-PACK-01');assert.equal(app.transitionPackage(pkg.id,'SEAL','seal').status,'READY_FOR_LABEL')});

test('audit snapshots actor role and immutable before and after state',()=>{const app=new StoreMesh();app.withAuditContext({userId:'actor',roles:['MANAGER'],station:'QC-01',requestId:'request-r12',ipAddress:'127.0.0.1'},()=>{const task=app.createTask({title:'Inspect',zone:'QC'},'task');app.claimTask(task.id,'operator','claim')});const event=app.state.audit.find(x=>x.type==='TASK_CLAIMED');assert.deepEqual(event.actorRoles,['MANAGER']);assert.equal(event.actorStation,'QC-01');assert.equal(event.beforeState.status,'OPEN');assert.equal(event.afterState.status,'IN_PROGRESS')});

test('device presence and aggregation reports are computed server-side',()=>{let now=0;const app=new StoreMesh({clock:()=>new Date(now).toISOString()}),device=app.registerDevice({code:'PDA-R12',type:'PDA'},'device');app.heartbeatDevice(device.code);assert.equal(app.devicesWithPresence(1000).find(x=>x.id===device.id).presence,'ONLINE');now=2000;assert.equal(app.devicesWithPresence(1000).find(x=>x.id===device.id).presence,'OFFLINE');const report=app.reports();assert.ok(report.yield);assert.ok(report.equipmentUtilization);assert.ok(report.exceptions);assert.ok(report.tasks)});
