import test from'node:test';
import assert from'node:assert/strict';
import{once}from'node:events';
import{StoreMesh}from'../src/domain.js';
import{PostgresRepository}from'../src/postgres-repository.js';
import{AuthService}from'../src/auth.js';
import{createServer}from'../src/server.js';

const key=()=>crypto.randomUUID();
const fixture=async repository=>{const site=repository?.siteCode??'IRAN',app=new StoreMesh({site,initialState:repository?await repository.load():undefined,seedDemoReferences:true});if(repository)app.repository=repository;const session=app.openSession('sorter','TEST-DEVICE'),input=app.createContainer({capacityKg:30},key()),batch=app.receive({sessionId:session.id,containerId:input.id,supplier:'S',product:'T',grade:'UNSORTED',size:'MIXED',weightKg:10},key());app.moveContainer(input.id,'COLD_ROOM_CLEAN',session.id,key());const output=()=>{const c=app.createContainer({capacityKg:15},key());app.moveContainer(c.id,'SORTING',session.id,key());return c};return{app,session,input,batch,output}};

test('sorting rejects every missing duplicate occupied or unstaged output container before mutation',async()=>{const{app,session,input,batch,output}=await fixture(),before=app.state.batches.length,first=output();assert.throws(()=>app.sortBatch({sessionId:session.id,containerId:input.id,batchId:batch.id,outputs:[{grade:'A',size:'L',weightKg:4,containerId:first.id},{grade:'B',size:'S',weightKg:5}]},key()),error=>error.code==='SORT_OUTPUT_CONTAINER_SCAN_REQUIRED');assert.equal(app.state.batches.length,before);assert.equal(batch.weightKg,10);assert.throws(()=>app.sortBatch({sessionId:session.id,containerId:input.id,batchId:batch.id,outputs:[{grade:'A',size:'L',weightKg:4,containerId:first.id},{grade:'B',size:'S',weightKg:5,containerId:first.id}]},key()),error=>error.code==='SORT_OUTPUT_CONTAINER_DUPLICATE');const unstaged=app.createContainer({capacityKg:15},key());assert.throws(()=>app.sortBatch({sessionId:session.id,containerId:input.id,batchId:batch.id,outputs:[{grade:'A',size:'L',weightKg:9,containerId:unstaged.id}]},key()),error=>error.code==='SORT_OUTPUT_CONTAINER_NOT_AVAILABLE')});

test('HTTP sorting cannot complete until every output references a distinct staged container',async()=>{const{app,session,input,batch,output}=await fixture(),auth=new AuthService({secret:'fr10b-http-secret'});auth.addUser({id:session.operatorId,username:'sorter',password:'right',roles:['SORTING_OPERATOR']});const server=createServer({app,auth});server.listen(0,'127.0.0.1');await once(server,'listening');try{const base=`http://127.0.0.1:${server.address().port}`,login=await fetch(`${base}/api/auth/login`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({username:'sorter',password:'right'})}),token=(await login.json()).data.token,post=outputs=>fetch(`${base}/api/sorting`,{method:'POST',headers:{authorization:`Bearer ${token}`,'content-type':'application/json','idempotency-key':key()},body:JSON.stringify({sessionId:session.id,containerId:input.id,batchId:batch.id,outputs})}),first=output(),second=output();let response=await post([{grade:'A',size:'L',weightKg:4,containerId:first.id},{grade:'B',size:'S',weightKg:5}]),payload=await response.json();assert.equal(response.status,400);assert.equal(payload.errorCode,'SORT_OUTPUT_CONTAINER_SCAN_REQUIRED');response=await post([{grade:'A',size:'L',weightKg:4,containerId:first.id},{grade:'B',size:'S',weightKg:5,containerId:second.id}]);payload=await response.json();assert.equal(response.status,201);assert.deepEqual(payload.data.children.map(x=>x.containerId),[first.id,second.id])}finally{server.close();await once(server,'close')}});

test('real PostgreSQL reload keeps each sorted output in its distinct scanned container',{skip:!process.env.DATABASE_URL},async()=>{const site=`FR10B-${Date.now()}`,repository=new PostgresRepository({connectionString:process.env.DATABASE_URL,siteCode:site});try{const{app,session,input,batch,output}=await fixture(repository),first=output(),second=output(),result=app.sortBatch({sessionId:session.id,containerId:input.id,batchId:batch.id,outputs:[{grade:'A',size:'L',weightKg:4,containerId:first.id},{grade:'B',size:'S',weightKg:5,containerId:second.id}]},key());await app.flush();const restored=await repository.load(),children=result.children.map(child=>restored.batches.find(x=>x.id===child.id)),containers=[first,second].map(target=>restored.containers.find(x=>x.id===target.id)),storedInput=restored.containers.find(x=>x.id===input.id);assert.deepEqual(children.map(x=>x.containerId),[first.id,second.id]);assert.deepEqual(containers.map(x=>x.batchIds),children.map(x=>[x.id]));assert.ok(containers.every(x=>x.status==='SORTED'&&x.zone==='SORTING'));assert.equal(storedInput.status,'AVAILABLE');assert.deepEqual(storedInput.batchIds,[])}finally{await repository.close()}});
