import test from 'node:test';
import assert from 'node:assert/strict';
import { StoreMesh } from '../src/domain.js';
import { configureUnitPackaging } from '../test-support/configurations.js';

const scenario=(number,title,run)=>test(`SC-${String(number).padStart(3,'0')} ${title}`,run);
const receiveFixture=(suffix='x',weightKg=10)=>{const app=new StoreMesh(),session=app.openSession(`operator-${suffix}`,'TEST-DEVICE'),container=app.createContainer({capacityKg:weightKg},`container-${suffix}`),batch=app.receive({sessionId:session.id,containerId:container.id,supplier:'S',product:'T',grade:'A',size:'L',weightKg},`receive-${suffix}`);return{app,session,container,batch}};
const packagingFixture=(suffix='x',weightKg=10)=>{const app=new StoreMesh();configureUnitPackaging(app,{weightTolerancePercent:2});const session=app.openSession(`packer-${suffix}`,'PDA-PACK-01','PACKAGING','PACKAGING_OPERATOR'),container=app.createContainer({capacityKg:weightKg},`container-${suffix}`),batch=app.receive({sessionId:session.id,containerId:container.id,supplier:'S',product:'T',grade:'A',size:'L',weightKg},`receive-${suffix}`);batch.status='DRIED';app.weighForPackaging({sessionId:session.id,batchId:batch.id,weightKg},`weigh-${suffix}`);app.state.qualityChecks.push({id:crypto.randomUUID(),batchId:batch.id,result:'APPROVED',createdAt:new Date().toISOString()});return{app,session,batch}};
const readyCarton=(app,session,batch,suffix,weight=1)=>{if(!app.state.consumables.some(x=>x.code==='CARTON'))app.state.consumables.push({id:crypto.randomUUID(),code:'CARTON',name:'Carton',unit:'EA',quantity:100,reorderThreshold:0,status:'ACTIVE',createdAt:new Date().toISOString()});const unit=app.createPackage({sessionId:session.id,type:'POUCH',level:'UNIT',items:[{batchId:batch.id,weightKg:weight}],targetWeightKg:weight,tolerancePercent:0},`unit-${suffix}`);for(const action of['PACK','SEAL','PRINT','PRINT_SUCCESS','READY'])app.transitionPackage(unit.id,action,`unit-${suffix}-${action}`);const carton=app.createPackage({sessionId:session.id,type:'CARTON',level:'CARTON'},`carton-${suffix}`);app.transitionPackage(carton.id,'PACK',`carton-${suffix}-pack`);app.scanPackageItem(carton.id,{sessionId:session.id,unitPackageCode:unit.code},`carton-${suffix}-scan`);for(const action of['SEAL','PRINT','PRINT_SUCCESS','READY'])app.transitionPackage(carton.id,action,`carton-${suffix}-${action}`);return carton};

for(let i=1;i<=10;i++)scenario(i,`device ${i} registers, heartbeats, and becomes online`,()=>{const app=new StoreMesh(),device=app.registerDevice({code:`PDA-SC-${i}`,type:'PDA',assignedStation:`ST-${i}`},`device-${i}`);assert.equal(device.status,'ACTIVE');app.heartbeatDevice(device.code);const current=app.devicesWithPresence().find(x=>x.id===device.id);assert.equal(current.presence,'ONLINE');assert.ok(current.lastSeenAt)});

const roles=['RECEIVING_OPERATOR','SORTING_OPERATOR','WASHING_OPERATOR','SLICING_OPERATOR','FREEZING_OPERATOR','DRYING_OPERATOR','PACKAGING_OPERATOR','SHIPPING_OPERATOR','QUALITY_OPERATOR','STORAGE_OPERATOR'];
roles.forEach((role,index)=>scenario(11+index,`${role} opens an attributable active session`,()=>{const app=new StoreMesh(),session=app.openSession(`operator-${index}`,'TEST-DEVICE',`STATION-${index}`,role);assert.equal(session.selectedRole,role);assert.equal(session.deviceId,'TEST-DEVICE');assert.equal(session.status,'ACTIVE');assert.ok(app.state.audit.some(x=>x.type==='SESSION_OPENED'&&x.sessionId===session.id))}));

for(let i=1;i<=10;i++)scenario(20+i,`receiving weight ${i} creates batch, measurement, and basket assignment`,()=>{const{app,session,container,batch}=receiveFixture(`r${i}`,i);assert.equal(batch.weightKg,i);assert.equal(batch.containerId,container.id);assert.deepEqual(container.batchIds,[batch.id]);const measurement=app.state.measurements.find(x=>x.batchId===batch.id);assert.equal(measurement.weightKg,i);assert.equal(measurement.reason,'RECEIVING');assert.equal(measurement.deviceId,session.deviceId)});

for(let i=1;i<=10;i++)scenario(30+i,`container capacity rejects overflow variant ${i} without corrupting inventory`,()=>{const{app,session,container,batch}=receiveFixture(`c${i}`,5);const other=app.createContainer({capacityKg:i},`other-${i}`),second=app.receive({sessionId:session.id,containerId:other.id,supplier:'S',product:'T',grade:'A',size:'L',weightKg:i},`second-${i}`);assert.throws(()=>app.assignBatchToContainer(container.id,second.id,session.id,`overflow-${i}`),e=>e.code==='CONTAINER_CAPACITY_EXCEEDED');assert.equal(batch.containerId,container.id);assert.equal(second.containerId,other.id);assert.equal(container.batchIds.length,1)});

for(let i=1;i<=10;i++)scenario(40+i,`merge variant ${i} preserves genealogy and never creates weight`,()=>{const{app,session,batch}=receiveFixture(`m${i}`,10+i),consume=1+i/10,output=consume-.1,child=app.transform({sessionId:session.id,process:'MERGE',inputs:[{batchId:batch.id,consumeWeightKg:consume}],outputWeightKg:output,grade:'A',size:'L'},`merge-${i}`);assert.deepEqual(child.parentIds,[batch.id]);assert.equal(child.weightKg,output);assert.ok(batch.weightKg>=0);assert.ok(child.weightKg<=consume);assert.ok(app.state.audit.some(x=>x.type==='BATCH_TRANSFORMED'&&x.entityId===child.id))});

for(let i=1;i<=10;i++)scenario(50+i,`UNIT weight inside tolerance variant ${i} is accepted`,()=>{const{app,session,batch}=packagingFixture(`pa${i}`),target=1,actual=Number((1+(i-5)*.002).toFixed(3)),unit=app.createPackage({sessionId:session.id,type:'POUCH',level:'UNIT',items:[{batchId:batch.id,weightKg:actual}],targetWeightKg:target,tolerancePercent:2},`package-${i}`);assert.equal(unit.level,'UNIT');assert.equal(unit.measuredWeightKg,actual);assert.equal(unit.targetWeightKg,target);assert.equal(unit.deviceId,session.deviceId)});

for(let i=1;i<=10;i++)scenario(60+i,`UNIT weight outside tolerance variant ${i} is rejected atomically`,()=>{const{app,session,batch}=packagingFixture(`pr${i}`),before=batch.weightKg,actual=Number((1.02+i/100).toFixed(3));assert.throws(()=>app.createPackage({sessionId:session.id,type:'POUCH',level:'UNIT',items:[{batchId:batch.id,weightKg:actual}],targetWeightKg:1,tolerancePercent:2},`reject-${i}`),e=>e.code==='PACKAGE_WEIGHT_OUT_OF_TOLERANCE');assert.equal(batch.weightKg,before);assert.equal(app.state.packages.length,0)});

roles.forEach((role,index)=>scenario(71+index,`${role} can claim its matching eligible task`,()=>{const app=new StoreMesh(),task=app.createTask({title:`Role work ${index}`,zone:'PROCESSING',requiredRole:role,priority:50+index},`task-${index}`);assert.throws(()=>app.claimTask(task.id,{operatorId:'wrong',roles:[],skills:[]},`wrong-${index}`),e=>e.code==='TASK_NOT_ELIGIBLE');const claimed=app.claimTask(task.id,{operatorId:`operator-${index}`,roles:[role],skills:[]},`claim-${index}`);assert.equal(claimed.status,'IN_PROGRESS');assert.equal(claimed.assignedTo,`operator-${index}`)}));

const severities=['INFO','WARNING','HIGH','CRITICAL'];
for(let i=1;i<=10;i++)scenario(80+i,`durable exception variant ${i} assigns and resolves with history`,()=>{const app=new StoreMesh(),item=app.raiseException({type:`SCENARIO_${i}`,entityType:'SYSTEM',severity:severities[(i-1)%4]},`exception-${i}`);assert.equal(item.status,'OPEN');app.assignException(item.id,{assignedTo:`manager-${i}`},`assign-${i}`);const resolved=app.resolveException(item.id,{decision:'RESOLVED',resolvedBy:`manager-${i}`,resolutionNote:`verified ${i}`},`resolve-${i}`);assert.equal(resolved.status,'RESOLVED');assert.ok(resolved.resolvedAt);assert.ok(app.state.audit.some(x=>x.type==='EXCEPTION_RESOLVED'&&x.entityId===item.id))});

for(let i=1;i<=10;i++)scenario(90+i,`customer shipment variant ${i} verifies cartons and completes six states`,()=>{const{app,session,batch}=packagingFixture(`s${i}`,5),carton=readyCarton(app,session,batch,`s${i}`),customer=app.createCustomer({code:`CUS-${i}`,name:`Customer ${i}`},`customer-${i}`),order=app.createSalesOrder({customerId:customer.id,items:[{packageType:'CARTON',quantity:1}]},`order-${i}`),shipment=app.createShipment({salesOrderId:order.id,packageIds:[carton.id]},`shipment-${i}`);assert.equal(shipment.status,'DRAFT');app.updateShipment(shipment.id,'START_PICKING',{},`start-${i}`);assert.throws(()=>app.updateShipment(shipment.id,'READY',{},`premature-${i}`),e=>e.code==='SHIPMENT_SCAN_INCOMPLETE');const scan=app.scanShipmentCarton(shipment.id,{sessionId:session.id,cartonCode:carton.code},`scan-${i}`);assert.equal(scan.deviceId,session.deviceId);app.updateShipment(shipment.id,'READY',{},`ready-${i}`);app.updateShipment(shipment.id,'LOAD',{vehicle:`TRUCK-${i}`},`load-${i}`);app.updateShipment(shipment.id,'SHIP',{},`ship-${i}`);assert.equal(app.updateShipment(shipment.id,'CLOSE',{},`close-${i}`).status,'CLOSED');assert.equal(order.status,'FULFILLED');assert.equal(carton.status,'SHIPPED')});
