import test from'node:test';
import assert from'node:assert/strict';
import{StoreMesh}from'../src/domain.js';
import{PostgresRepository}from'../src/postgres-repository.js';

const pgOnly={skip:!process.env.DATABASE_URL};

test('operation-backed task rejects manual completion and closes only after real work',()=>{const app=new StoreMesh(),session=app.openSession('storage','TEST-DEVICE','STORAGE','STORAGE_OPERATOR'),container=app.createContainer({capacityKg:10},'container'),batch=app.receive({sessionId:session.id,containerId:container.id,supplier:'S',product:'T',grade:'A',size:'L',weightKg:5},'receive'),task=app.task(batch.coldStorageTaskId),actor={operatorId:'storage',roles:['STORAGE_OPERATOR'],skills:[]};assert.equal(task.operationType,'BATCH_MOVED');app.claimTask(task.id,actor,'claim');assert.throws(()=>app.transitionTask(task.id,'COMPLETE',{actor},'fake-complete'),e=>e.code==='TASK_MANUAL_COMPLETION_FORBIDDEN');assert.equal(task.status,'IN_PROGRESS');app.move(batch.id,'COLD_ROOM_DIRTY',session.id,'move');assert.equal(task.status,'COMPLETED');assert.equal(task.stateHistory.at(-1).action,'AUTO_BATCH_MOVED')});

test('ad-hoc task without operation type remains manually completable',()=>{const app=new StoreMesh(),task=app.createTask({title:'Count spare labels',zone:'QC'},'task');app.claimTask(task.id,'operator','claim');assert.equal(app.transitionTask(task.id,'COMPLETE',{},'complete').status,'COMPLETED')});

test('operation type and real-operation completion survive PostgreSQL reload',pgOnly,async()=>{const site=`TASK-OP-${Date.now()}`,repository=new PostgresRepository({connectionString:process.env.DATABASE_URL,siteCode:site});try{let app=new StoreMesh({site,initialState:await repository.load(),seedDemoReferences:true});app.repository=repository;const session=app.openSession('storage','TEST-DEVICE','STORAGE','STORAGE_OPERATOR'),container=app.createContainer({capacityKg:10},'container'),batch=app.receive({sessionId:session.id,containerId:container.id,supplier:'S',product:'T',grade:'A',size:'L',weightKg:5},'receive'),taskId=batch.coldStorageTaskId;await app.flush();app=new StoreMesh({site,initialState:await repository.load(),seedDemoReferences:true});app.repository=repository;const task=app.task(taskId);assert.equal(task.operationType,'BATCH_MOVED');app.claimTask(task.id,{operatorId:'storage',roles:['STORAGE_OPERATOR'],skills:[]},'claim');assert.throws(()=>app.transitionTask(task.id,'COMPLETE',{},'fake'),e=>e.code==='TASK_MANUAL_COMPLETION_FORBIDDEN');app.move(batch.id,'COLD_ROOM_DIRTY',session.id,'move');await app.flush();assert.equal((await repository.load()).tasks.find(x=>x.id===task.id).status,'COMPLETED')}finally{await repository.close()}});
