import test from 'node:test';import assert from 'node:assert/strict';import {randomUUID} from 'node:crypto';
import {StoreMesh} from '../src/domain.js';import {PostgresRepository} from '../src/postgres-repository.js';

const actor={operatorId:'operator-a',roles:[],skills:[]};
test('HIGH exceptions block OPEN and IN_PROGRESS tasks and resolution restores each prior state',()=>{const app=new StoreMesh(),entityId=randomUUID(),open=app.createTask({title:'Open',zone:'QC',entityId},'open'),active=app.createTask({title:'Active',zone:'QC',entityId},'active');app.claimTask(active.id,actor,'claim');const issue=app.raiseException({type:'QUALITY_HOLD',entityType:'BATCH',entityId,severity:'HIGH'},'raise');for(const task of[open,active]){assert.equal(task.status,'BLOCKED');assert.equal(task.blockedByExceptionId,issue.id);assert.equal(app.taskView(task).overdue,false)}assert.equal(open.unblockedStatus,'OPEN');assert.equal(active.unblockedStatus,'IN_PROGRESS');app.resolveException(issue.id,{decision:'RESOLVED',resolvedBy:'manager',resolutionNote:'cleared'},'resolve');assert.equal(open.status,'OPEN');assert.equal(active.status,'IN_PROGRESS');assert.equal(open.blockedByExceptionId,null);assert.equal(active.blockedByExceptionId,null)});

test('LOW and WARNING exceptions do not block and terminal or paused tasks stay unchanged',()=>{const app=new StoreMesh(),entityId=randomUUID(),tasks=['PAUSED','COMPLETED','FAILED'].map((status,index)=>{const task=app.createTask({title:String(index),zone:'QC',entityId},`task-${index}`);task.status=status;return task});const open=app.createTask({title:'open',zone:'QC',entityId},'open');app.raiseException({type:'LOW_NOTE',entityType:'BATCH',entityId,severity:'INFO'},'low');app.raiseException({type:'WARNING_NOTE',entityType:'BATCH',entityId,severity:'WARNING'},'warning');assert.equal(open.status,'OPEN');const high=app.raiseException({type:'HIGH_NOTE',entityType:'BATCH',entityId,severity:'CRITICAL'},'high');assert.deepEqual(tasks.map(x=>x.status),['PAUSED','COMPLETED','FAILED']);assert.equal(open.blockedByExceptionId,high.id)});

test('claim and every transition action reject blocked tasks while unrelated resolution does nothing',()=>{const app=new StoreMesh(),entityId=randomUUID(),task=app.createTask({title:'Blocked',zone:'QC',entityId},'task'),issue=app.raiseException({type:'HOLD',entityType:'BATCH',entityId,severity:'HIGH'},'issue'),other=app.raiseException({type:'OTHER',entityType:'BATCH',entityId:randomUUID(),severity:'HIGH'},'other');assert.throws(()=>app.claimTask(task.id,actor,'claim'),e=>e.code==='TASK_BLOCKED');for(const action of['COMPLETE','PAUSE','FAIL','RESUME','REOPEN'])assert.throws(()=>app.transitionTask(task.id,action,{reason:'test'},`transition-${action}`),e=>e.code==='TASK_BLOCKED');app.resolveException(other.id,{decision:'RESOLVED',resolvedBy:'manager',resolutionNote:'other fixed'},'resolve-other');assert.equal(task.status,'BLOCKED');assert.equal(task.blockedByExceptionId,issue.id)});

test('blocked state and prior status survive PostgreSQL reload',{skip:!process.env.DATABASE_URL},async()=>{const site=`TASK-BLOCK-${Date.now()}`,repository=new PostgresRepository({connectionString:process.env.DATABASE_URL,siteCode:site});try{let app=new StoreMesh({site,initialState:await repository.load()});app.repository=repository;const entityId=randomUUID(),task=app.createTask({title:'Persist blocked',zone:'QC',entityId},'task'),issue=app.raiseException({type:'DATABASE_HOLD',entityType:'BATCH',entityId,severity:'HIGH'},'issue');await app.flush();app=new StoreMesh({site,initialState:await repository.load()});const loaded=app.state.tasks.find(x=>x.id===task.id);assert.equal(loaded.status,'BLOCKED');assert.equal(loaded.blockedByExceptionId,issue.id);assert.equal(loaded.unblockedStatus,'OPEN');app.repository=repository;app.resolveException(issue.id,{decision:'RESOLVED',resolvedBy:'manager',resolutionNote:'fixed'},'resolve');await app.flush();assert.equal((await repository.load()).tasks.find(x=>x.id===task.id).status,'OPEN')}finally{for(const table of['outbox_events','audit_events','idempotency_records','tasks','operational_exceptions','devices','products','suppliers','grades','sizes','zones','package_types','site_state_versions'])await repository.pool.query(`DELETE FROM ${table} WHERE site_id=$1`,[repository.siteId]);await repository.pool.query('DELETE FROM sites WHERE id=$1',[repository.siteId]);await repository.close()}});
