import test from'node:test';
import assert from'node:assert/strict';
import{once}from'node:events';
import{randomUUID}from'node:crypto';
import{StoreMesh}from'../src/domain.js';
import{AuthService}from'../src/auth.js';
import{createServer}from'../src/server.js';

test('HTTP task eligibility uses selected session role and keeps other operators work out of My Tasks',async()=>{const app=new StoreMesh(),auth=new AuthService({secret:'task-session-role-secret'}),operatorA=randomUUID(),operatorB=randomUUID();auth.addUser({id:operatorA,username:'multi-role',password:'right',roles:['RECEIVING_OPERATOR','PACKAGING_OPERATOR']});auth.addUser({id:operatorB,username:'other-receiver',password:'right',roles:['RECEIVING_OPERATOR']});const packaging=app.createTask({title:'Pack',zone:'PACKAGING',requiredRole:'PACKAGING_OPERATOR'},'packaging'),available=app.createTask({title:'Receive',zone:'RECEIVING',requiredRole:'RECEIVING_OPERATOR'},'available'),other=app.createTask({title:'Other work',zone:'RECEIVING',requiredRole:'RECEIVING_OPERATOR'},'other');app.claimTask(other.id,{operatorId:operatorB,roles:['RECEIVING_OPERATOR'],skills:[]},'other-claim');const server=createServer({app,auth});server.listen(0,'127.0.0.1');await once(server,'listening');const base=`http://127.0.0.1:${server.address().port}`,login=async username=>(await(await fetch(`${base}/api/auth/login`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({username,password:'right'})})).json()).data.token,call=(path,token,{method='GET',body}={})=>fetch(base+path,{method,headers:{authorization:`Bearer ${token}`,'content-type':'application/json','idempotency-key':randomUUID()},...(body?{body:JSON.stringify(body)}:{})});try{const token=await login('multi-role'),session=(await(await call('/api/sessions',token,{method:'POST',body:{deviceId:'TEST-DEVICE',station:'RECEIVING',selectedRole:'RECEIVING_OPERATOR'}})).json()).data;assert.equal((await call(`/api/tasks/${packaging.id}/claim`,token,{method:'POST',body:{sessionId:session.id}})).status,403);assert.equal((await call(`/api/tasks/${available.id}/claim`,token,{method:'POST',body:{sessionId:session.id}})).status,201);const scoped=await(await call(`/api/tasks?eligible=me&sessionId=${session.id}`,token)).json();assert.deepEqual(scoped.available,[]);assert.deepEqual(scoped.mine.map(x=>x.id),[available.id]);assert.ok(!scoped.mine.some(x=>x.id===other.id));assert.equal((await call(`/api/tasks/recommended?sessionId=${session.id}`,token)).status,200);const foreign=app.openSession(operatorB,'TEST-DEVICE','RECEIVING','RECEIVING_OPERATOR');assert.equal((await call(`/api/tasks?eligible=me&sessionId=${foreign.id}`,token)).status,403)}finally{server.close();await once(server,'close')}});
