import test from 'node:test';
import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import { once } from 'node:events';
import { StoreMesh } from '../src/domain.js';
import { PostgresRepository } from '../src/postgres-repository.js';
import { AuthService } from '../src/auth.js';
import { createServer } from '../src/server.js';

const pgOnly={skip:!process.env.DATABASE_URL};let n=0;const key=label=>`${label}-${++n}`;
const batch=(id,parents=[])=>({id,code:`B-${id.slice(0,8)}`,site:'IRAN',product:'T',grade:'A',size:'L',supplier:'S',weightKg:1,zone:'RECEIVING',status:'RECEIVED',parentIds:parents,createdAt:new Date().toISOString()});

test('trace reports missing parents while retaining every resolvable ancestor',()=>{const rootId=randomUUID(),goodId=randomUUID(),missingId=randomUUID(),app=new StoreMesh();app.state.batches.push(batch(goodId),batch(rootId,[goodId,missingId]));const result=app.trace(rootId);assert.deepEqual(result.ancestors.map(x=>x.id),[goodId]);assert.equal(result.integrityIssues[0].type,'GENEALOGY_PARENT_MISSING');assert.equal(result.integrityIssues[0].entityId,rootId);assert.equal(result.integrityIssues[0].missingParentId,missingId)});
test('trace detects a cyclic genealogy without unbounded recursion',()=>{const a=randomUUID(),b=randomUUID(),app=new StoreMesh();app.state.batches.push(batch(a,[b]),batch(b,[a]));const result=app.trace(a);assert.deepEqual(result.ancestors.map(x=>x.id),[b]);assert.equal(result.integrityIssues[0].type,'GENEALOGY_CYCLE_DETECTED');assert.equal(result.integrityIssues[0].entityId,b)});

test('MERGE persists per-parent quantities and genealogy edges remain append-only',pgOnly,async()=>{const site=`TRACE-EDGE-${Date.now()}`,repository=new PostgresRepository({connectionString:process.env.DATABASE_URL,siteCode:site});try{const app=new StoreMesh({site,initialState:await repository.load(),seedDemoReferences:true});app.repository=repository;const session=app.openSession('operator','TEST-DEVICE'),receive=(weight,label)=>{const container=app.createContainer({capacityKg:10},key(`container-${label}`));return app.receive({sessionId:session.id,containerId:container.id,supplier:'S',product:'T',grade:'A',size:'L',weightKg:weight},key(`receive-${label}`))},a=receive(3,'a'),b=receive(2,'b'),mergeContainer=app.createContainer({type:'BASKET',capacityKg:10,zone:'SORTING',designatedZones:['SORTING']},key('merge-container')),child=app.transform({sessionId:session.id,process:'MERGE',containerId:mergeContainer.id,inputs:[{batchId:a.id,consumeWeightKg:3},{batchId:b.id,consumeWeightKg:2}],outputWeightKg:4.5},key('merge'));await app.flush();let rows=(await repository.pool.query('SELECT parent_batch_id,input_weight_kg FROM batch_genealogy WHERE child_batch_id=$1 ORDER BY parent_batch_id',[child.id])).rows;assert.deepEqual(Object.fromEntries(rows.map(x=>[x.parent_batch_id,Number(x.input_weight_kg)])),{[a.id]:3,[b.id]:2});child.parentContributions=[{batchId:a.id,inputWeightKg:99},{batchId:b.id,inputWeightKg:98}];app.persist();await app.flush();rows=(await repository.pool.query('SELECT parent_batch_id,input_weight_kg FROM batch_genealogy WHERE child_batch_id=$1 ORDER BY parent_batch_id',[child.id])).rows;assert.deepEqual(Object.fromEntries(rows.map(x=>[x.parent_batch_id,Number(x.input_weight_kg)])),{[a.id]:3,[b.id]:2});const restored=(await repository.load()).batches.find(x=>x.id===child.id);assert.deepEqual(Object.fromEntries(restored.parentContributions.map(x=>[x.batchId,x.inputWeightKg])),{[a.id]:3,[b.id]:2})}finally{await repository.close()}});

test('HTTP trace requires inventory read and persists an attributable search audit',pgOnly,async()=>{const site=`TRACE-AUDIT-${Date.now()}`,repository=new PostgresRepository({connectionString:process.env.DATABASE_URL,siteCode:site}),app=new StoreMesh({site,initialState:await repository.load(),seedDemoReferences:true});app.repository=repository;const session=app.openSession('seed','TEST-DEVICE'),container=app.createContainer({capacityKg:10},key('container')),target=app.receive({sessionId:session.id,containerId:container.id,supplier:'S',product:'T',grade:'A',size:'L',weightKg:2},key('receive'));await app.flush();const auth=new AuthService({site,secret:'trace-audit-secret'}),viewerId=randomUUID(),blockedId=randomUUID();auth.addUser({id:viewerId,username:'viewer',password:'right',roles:['VIEWER']});auth.addUser({id:blockedId,username:'blocked',password:'right',roles:[]});const server=createServer({app,auth,requireAuth:true});server.listen(0,'127.0.0.1');await once(server,'listening');try{const base=`http://127.0.0.1:${server.address().port}`,login=async username=>(await(await fetch(`${base}/api/auth/login`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({username,password:'right',deviceId:'WEB-CONSOLE-01'})})).json()).data.token,blocked=await login('blocked'),viewer=await login('viewer');assert.equal((await fetch(`${base}/api/trace/${target.id}`,{headers:{authorization:`Bearer ${blocked}`}})).status,403);assert.equal((await fetch(`${base}/api/trace/${target.id}`,{headers:{authorization:`Bearer ${viewer}`,'x-request-id':'trace-request-1'}})).status,200);const restored=await repository.load(),event=restored.audit.find(x=>x.type==='TRACE_SEARCHED'&&x.entityId===target.id);assert.equal(event.userId,viewerId);assert.equal(event.payload.searchedBatchId,target.id);assert.equal(event.payload.searchType,'BATCH');assert.equal(event.requestId,'trace-request-1')}finally{server.close();await once(server,'close');await repository.close()}});
