import test from 'node:test';
import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import { once } from 'node:events';
import { StoreMesh } from '../src/domain.js';
import { AuthService } from '../src/auth.js';
import { createServer } from '../src/server.js';
import { PostgresRepository } from '../src/postgres-repository.js';

const id=()=>randomUUID(),now=()=>new Date().toISOString();
function fixture(app=new StoreMesh()){
  const supplier={id:id(),code:'SUP-TRACE',name:'Trace Farms',status:'ACTIVE'};app.state.masterData.suppliers.push(supplier);
  const customer={id:id(),code:'CUS-TRACE',name:'Trace Buyer',status:'ACTIVE',createdAt:now()};app.state.customers.push(customer);
  const order1={id:id(),code:'SO-T1',customerId:customer.id,status:'CONFIRMED',items:[],createdAt:now()},order2={id:id(),code:'SO-T2',customerId:customer.id,status:'CONFIRMED',items:[],createdAt:now()};app.state.salesOrders.push(order1,order2);
  const receiving1={id:id(),code:'B-RECV-1',site:app.site,supplier:supplier.code,product:'T',grade:'UNSORTED',size:'MIXED',weightKg:10,zone:'RECEIVING',status:'CONSUMED',isAggregate:true,parentIds:[],createdAt:now()},receiving2={...structuredClone(receiving1),id:id(),code:'B-RECV-2'},production1={...structuredClone(receiving1),id:id(),code:'B-PROD-1',supplier:null,status:'DRIED',weightKg:5,isAggregate:false,parentIds:[receiving1.id],parentContributions:[{batchId:receiving1.id,inputWeightKg:5}]},production2={...structuredClone(receiving1),id:id(),code:'B-PROD-2',supplier:null,status:'DRIED',weightKg:4,isAggregate:false,parentIds:[receiving2.id],parentContributions:[{batchId:receiving2.id,inputWeightKg:4}]};app.state.batches.push(receiving1,receiving2,production1,production2);
  const shipment1={id:id(),code:'SH-TRACE-1',kind:'CUSTOMER',salesOrderId:order1.id,customerId:customer.id,status:'SHIPPED',packageIds:[],shippingBoxIds:[],createdAt:now()},shipment2={...structuredClone(shipment1),id:id(),code:'SH-TRACE-2',salesOrderId:order2.id};app.state.shipments.push(shipment1,shipment2);
  const packagePair=(code,batch,shipment)=>{const carton={id:id(),code:`CT-${code}`,type:'CARTON',level:'CARTON',status:'SHIPPED',shipmentId:shipment?.id??null,items:[],childPackageIds:[],createdAt:now()},unit={id:id(),code:`PK-${code}`,type:'POUCH',level:'UNIT',status:'SHIPPED',shipmentId:null,parentPackageId:carton.id,items:[{batchId:batch.id,weightKg:2}],childPackageIds:[],createdAt:now()};carton.childPackageIds=[unit.id];app.state.packages.push(carton,unit);if(shipment)shipment.packageIds.push(carton.id);return{carton,unit}};
  const shipped1=packagePair('ONE',production1,shipment1),shipped2=packagePair('TWO',production2,shipment2),warehouse=packagePair('WAREHOUSE',production1,null);
  return{app,supplier,customer,receiving1,receiving2,production1,production2,shipment1,shipment2,shipped1,shipped2,warehouse};
}

test('object lookup resolves carton shipment and supplier name to genuine batches',()=>{const f=fixture();assert.deepEqual(f.app.resolveTraceEntryPoint(f.shipped1.carton.code).batchIds,[f.production1.id]);assert.deepEqual(f.app.resolveTraceEntryPoint(f.shipment2.code).batchIds,[f.production2.id]);assert.deepEqual(new Set(f.app.resolveTraceEntryPoint(f.supplier.name).batchIds),new Set([f.receiving1.id,f.receiving2.id]));assert.throws(()=>f.app.resolveTraceEntryPoint('NO-SUCH-OBJECT'),e=>e.code==='TRACE_OBJECT_NOT_FOUND'&&e.status===404)});

test('supplier aggregation spans receiving roots descendants packages shipments and customer',()=>{const f=fixture(),result=f.app.supplierTrace(f.supplier.code);assert.deepEqual(new Set(result.receivingBatches.map(x=>x.id)),new Set([f.receiving1.id,f.receiving2.id]));assert.deepEqual(new Set(result.productionBatches.map(x=>x.id)),new Set([f.production1.id,f.production2.id]));assert.equal(result.shipments.length,2);assert.deepEqual(result.customers.map(x=>x.id),[f.customer.id]);assert.ok(result.packages.some(x=>x.id===f.shipped1.carton.id))});

test('customer aggregation walks two shipments backward to weighted supplier contributions',()=>{const f=fixture(),result=f.app.customerTrace(f.customer.id);assert.equal(result.shipments.length,2);assert.deepEqual(new Set(result.productionBatches.map(x=>x.id)),new Set([f.production1.id,f.production2.id]));assert.deepEqual(result.supplierContributions.map(x=>({supplierCode:x.supplierCode,weightKg:x.weightKg})),[{supplierCode:f.supplier.code,weightKg:4}])});

test('recall separates shipped customer exposure from warehouse inventory and is read-only',()=>{const f=fixture(),before=JSON.stringify({batches:f.app.state.batches,packages:f.app.state.packages,shipments:f.app.state.shipments}),result=f.app.recallAnalysis(f.receiving1.id);assert.ok(result.stillInWarehouse.some(x=>x.item.id===f.warehouse.carton.id));assert.ok(result.shippedToCustomers.some(x=>x.item.id===f.shipped1.carton.id&&x.customer.id===f.customer.id));assert.ok(result.stillInWarehouse.every(x=>x.customer===undefined));assert.equal(JSON.stringify({batches:f.app.state.batches,packages:f.app.state.packages,shipments:f.app.state.shipments}),before)});

async function httpFixture(app){const auth=new AuthService({secret:'fr53'});auth.addUser({id:'admin',username:'admin',password:'right',roles:['ADMIN']});const server=createServer({app,auth});server.listen(0,'127.0.0.1');await once(server,'listening');const base=`http://127.0.0.1:${server.address().port}`,login=await fetch(`${base}/api/auth/login`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({username:'admin',password:'right',deviceId:'TEST-DEVICE'})}),token=(await login.json()).data.token,get=path=>fetch(base+path,{headers:{authorization:`Bearer ${token}`}});return{server,get,close:async()=>{server.close();await once(server,'close')}}}

test('HTTP search supplier customer and recall routes record distinct successful searches',async()=>{const f=fixture(),http=await httpFixture(f.app);try{for(const[path,type]of[[`/api/trace/search?code=${f.shipped1.carton.code}`,'CODE_LOOKUP'],[`/api/trace/supplier/${f.supplier.code}`,'SUPPLIER'],[`/api/trace/customer/${f.customer.id}`,'CUSTOMER'],[`/api/trace/${f.receiving1.id}/recall`,'RECALL']]){const response=await http.get(path);assert.equal(response.status,200,path);assert.equal(f.app.state.audit.at(-1).payload.searchType,type)}assert.equal((await http.get('/api/trace/search?code=NOPE')).status,404)}finally{await http.close()}});

test('trace search and aggregation data survive real PostgreSQL reload',{skip:!process.env.DATABASE_URL},async()=>{const site=`FR53-${Date.now()}`,repository=new PostgresRepository({connectionString:process.env.DATABASE_URL,siteCode:site});try{const app=new StoreMesh({site,initialState:await repository.load(),seedDemoReferences:true});app.repository=repository;const f=fixture(app);app.persist();await app.flush();const restored=new StoreMesh({site,initialState:await repository.load(),seedDemoReferences:false});assert.deepEqual(restored.resolveTraceEntryPoint(f.shipped1.carton.code).batchIds,[f.production1.id]);assert.equal(restored.supplierTrace(f.supplier.code).shipments.length,2);assert.equal(restored.customerTrace(f.customer.id).supplierContributions[0].weightKg,4)}finally{await repository.close()}});
