import test from'node:test';
import assert from'node:assert/strict';
import{once}from'node:events';
import{StoreMesh}from'../src/domain.js';
import{PostgresRepository}from'../src/postgres-repository.js';
import{AuthService}from'../src/auth.js';
import{createServer}from'../src/server.js';

const key=()=>crypto.randomUUID();
const fixture=async repository=>{const site=repository?.siteCode??'IRAN',app=new StoreMesh({site,initialState:repository?await repository.load():undefined,seedDemoReferences:true});if(repository)app.repository=repository;const session=app.openSession('operator','TEST-DEVICE'),scale=app.registerDevice({code:`SCALE-${site}`,type:'SCALE'},key()),container=app.createContainer({capacityKg:20},key()),batch=app.receive({sessionId:session.id,containerId:container.id,supplier:'S',product:'T',grade:'A',size:'L',weightKg:10},key());batch.status='SORTED';app.moveContainer(container.id,'WASHING',session.id,key());return{app,session,scale,container,batch}};

test('wash and slice preserve one batch identity genealogy label and official weight',async()=>{const{app,session,scale,container,batch}=await fixture(),identity={id:batch.id,code:batch.code,weightKg:batch.weightKg,batches:app.state.batches.length,labels:app.state.labels.length,parents:[...batch.parentIds]},washReading=app.captureMeasurement({sessionId:session.id,scaleId:scale.id,batchId:batch.id,purpose:'WASH_OBSERVATION',rawReadingKg:10.4},key()),washed=app.transform({sessionId:session.id,containerId:container.id,inputs:[{batchId:batch.id}],process:'WASH',measurementId:washReading.id},key());assert.equal(washed,batch);assert.deepEqual({id:batch.id,code:batch.code,weightKg:batch.weightKg,batches:app.state.batches.length,labels:app.state.labels.length,parents:batch.parentIds},identity);assert.equal(app.state.tasks.find(x=>x.entityId===batch.id&&x.requiredRole==='SORTING_OPERATOR').status,'OPEN');app.moveContainer(container.id,'SLICING',session.id,key());const sliceReading=app.captureMeasurement({sessionId:session.id,scaleId:scale.id,batchId:batch.id,purpose:'SLICE_OBSERVATION',rawReadingKg:9.6},key()),sliced=app.transform({sessionId:session.id,containerId:container.id,inputs:[{batchId:batch.id}],process:'SLICE',measurementId:sliceReading.id},key());assert.equal(sliced,batch);assert.equal(batch.id,identity.id);assert.equal(batch.code,identity.code);assert.equal(batch.weightKg,identity.weightKg);assert.equal(app.state.batches.length,identity.batches);assert.equal(app.state.labels.length,identity.labels);assert.deepEqual(batch.parentIds,identity.parents);assert.equal(sliceReading.consumedBy,`SLICE:${batch.id}`);assert.equal(container.batchIds[0],batch.id)});

test('HTTP cannot turn wash or slice client weights into inventory or new batch identities',async()=>{const{app,session,container,batch}=await fixture(),auth=new AuthService({secret:'fr10-http-secret'});auth.addUser({id:session.operatorId,username:'processor',password:'right',roles:['WASHING_OPERATOR','SLICING_OPERATOR']});const server=createServer({app,auth});server.listen(0,'127.0.0.1');await once(server,'listening');try{const base=`http://127.0.0.1:${server.address().port}`,login=await fetch(`${base}/api/auth/login`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({username:'processor',password:'right'})}),token=(await login.json()).data.token,post=body=>fetch(`${base}/api/transforms`,{method:'POST',headers:{authorization:`Bearer ${token}`,'content-type':'application/json','idempotency-key':key()},body:JSON.stringify(body)});let response=await post({sessionId:session.id,containerId:container.id,process:'WASH',inputs:[{batchId:batch.id,consumeWeightKg:1}],outputWeightKg:999});assert.equal(response.status,201);let result=(await response.json()).data;assert.equal(result.id,batch.id);assert.equal(result.code,batch.code);assert.equal(result.weightKg,10);app.moveContainer(container.id,'SLICING',session.id,key());response=await post({sessionId:session.id,containerId:container.id,process:'SLICE',inputs:[{batchId:batch.id,consumeWeightKg:2}],outputWeightKg:.1});assert.equal(response.status,201);result=(await response.json()).data;assert.equal(result.id,batch.id);assert.equal(result.weightKg,10);assert.equal(app.state.batches.length,1)}finally{server.close();await once(server,'close')}});

test('real PostgreSQL reload preserves wash and slice identity and informational observations',{skip:!process.env.DATABASE_URL},async()=>{const site=`FR10A-${Date.now()}`,repository=new PostgresRepository({connectionString:process.env.DATABASE_URL,siteCode:site});try{const{app,session,scale,container,batch}=await fixture(repository),id=batch.id,code=batch.code,wash=app.captureMeasurement({sessionId:session.id,scaleId:scale.id,batchId:id,purpose:'WASH_OBSERVATION',rawReadingKg:10.5},key());app.transform({sessionId:session.id,containerId:container.id,inputs:[{batchId:id}],process:'WASH',measurementId:wash.id},key());app.moveContainer(container.id,'SLICING',session.id,key());const slice=app.captureMeasurement({sessionId:session.id,scaleId:scale.id,batchId:id,purpose:'SLICE_OBSERVATION',rawReadingKg:9.5},key());app.transform({sessionId:session.id,containerId:container.id,inputs:[{batchId:id}],process:'SLICE',measurementId:slice.id},key());await app.flush();const restored=await repository.load(),stored=restored.batches.filter(x=>x.code===code),observations=restored.measurements.filter(x=>[wash.id,slice.id].includes(x.id));assert.equal(stored.length,1);assert.equal(stored[0].id,id);assert.equal(stored[0].weightKg,10);assert.equal(stored[0].status,'SLICED');assert.equal(stored[0].containerId,container.id);assert.equal(observations.length,2);assert.deepEqual(new Set(observations.map(x=>x.purpose)),new Set(['WASH_OBSERVATION','SLICE_OBSERVATION']));assert.ok(observations.every(x=>x.consumedAt&&x.consumedBy))}finally{await repository.close()}});
