import { randomUUID, createHash } from 'node:crypto';
import { AsyncLocalStorage } from 'node:async_hooks';
const PROCESS_RULES={SORT:{status:'SORTED',zone:'SORTING'},WASH:{status:'WASHED',zone:'WASHING'},SLICE:{status:'SLICED',zone:'SLICING'},FREEZE:{status:'FROZEN',zone:'FREEZING'},FREEZE_DRY:{status:'FREEZE_DRIED',zone:'FREEZE_DRYING'},DRY:{status:'DRIED',zone:'DRYING'},MERGE:{status:'SORTED',zone:'SORTING'}};
const CONTAINER_GATES={
  RECEIVE:{field:'containerId',types:['BASKET','CRATE'],zone:'RECEIVING',statuses:['AVAILABLE'],empty:true},
  SORT:{field:'containerId',types:['BASKET','CRATE'],zone:'COLD_ROOM',statuses:['IN_USE'],batchStatuses:['RECEIVED']},
  WASH:{field:'containerId',types:['BASKET','CRATE'],zone:'WASHING',statuses:['READY_FOR_WASHING'],batchStatuses:['SORTED']},
  SLICE:{field:'containerId',types:['BASKET','CRATE'],zone:'SLICING',statuses:['WASHED'],batchStatuses:['WASHED']},
  FREEZE:{field:'trayId',types:['TRAY'],zone:'FREEZING',statuses:['SLICED'],batchStatuses:['SLICED']},
  FREEZE_DRY:{field:'trayId',types:['TRAY'],zone:'FREEZE_DRYING',statuses:['FROZEN'],batchStatuses:['FROZEN']},
  DRY:{field:'containerId',types:['BASKET','CRATE','TRAY'],zone:'DRYING',statuses:['READY_FOR_DRYING'],batchStatuses:['SORTED']}
};
const CYCLE_TYPES=new Set(['FREEZE','FREEZE_DRY','DRY']);
const ACTIVE_CYCLE_STATUSES=new Set(['READY','LOADING','RUNNING','IN_PROGRESS','PAUSED','COMPLETING']);
const UUID_PATTERN=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const REFERENCE_TYPES=new Set(['products','suppliers','grades','sizes','zones','packageTypes']);
export const DEMO_REFERENCES={products:['T','Truffle','Fruit'],suppliers:['S','S1'],grades:['A','B','UNSORTED'],sizes:['L','Large','MIXED','S','M'],zones:['RECEIVING','COLD_ROOM','SORTING','WASHING','SLICING','FREEZING','FREEZE_DRYING','DRYING','PROCESSING','PACKAGING','SHIPPING','QC','QUARANTINE','WASTE'],packageTypes:['POUCH','CARTON','EPS','PALLET']};
const DEMO_DEVICES=['TEST-DEVICE','TEST-TERMINAL-01','TEST-TERMINAL-02','RT-01','DEVICE-01','DEVICE-CYCLE-01','PDA-PACK-01','WEB-CONSOLE-01','device-1'];

export class DomainError extends Error {
  constructor(code, message, status = 422) { super(message); this.code = code; this.status = status; }
}

export class StoreMesh {
  constructor({ site = 'IRAN', clock = () => new Date().toISOString(), repository = null, initialState = null, seedDemoReferences = process.env.NODE_ENV!=='production',idleSessionMs=Number(process.env.SESSION_IDLE_TIMEOUT_MS||1800000), persistenceErrorLogger = error => console.error(JSON.stringify({level:'error',component:'persistence',errorCode:error.code??'PERSISTENCE_FAILED',message:error.message,at:new Date().toISOString()})) } = {}) {
    this.site = site; this.clock = clock;
    this.repository = repository;this.idleSessionMs=idleSessionMs;
    this.auditContext = new AsyncLocalStorage();
    this.pendingPersistence = Promise.resolve();
    this.lastPersistenceError = null;this.persistenceErrorLogger=persistenceErrorLogger;
    this.state = initialState || repository?.load() || { sessions: [], batches: [], measurements: [], movements: [], inventoryAdjustments: [], containers: [], cycles: [], packages: [], shipments: [], internalTransfers: [], labels: [], printAttempts: [], printJobs: [], audit: [], outbox: [], tasks: [], qualityChecks: [], exceptions: [], configurationVersions: [], overrides: [], idempotency: new Map(), idempotencyMeta: new Map() };
    if (this.state instanceof Promise) throw new Error('Async repositories must be loaded before constructing StoreMesh');
    this.state.tasks ??= []; this.state.qualityChecks ??= [];this.state.qcChecklists??=[];this.state.exceptions??=[];this.state.cartonScanEvents??=[];this.state.devices??=[];this.state.deliveries??=[];this.state.deliveryBaskets??=[];this.state.harvestPeriods??=[];this.state.customers??=[];this.state.salesOrders??=[];this.state.shipmentCartonScans??=[];
    this.state.configurationVersions ??= []; this.state.overrides ??= []; this.state.containers ??= []; this.state.cycles ??= []; this.state.internalTransfers ??= []; this.state.inventoryAdjustments ??= [];this.state.labels??=[];this.state.printAttempts??=[];this.state.idempotencyMeta=this.state.idempotencyMeta instanceof Map?this.state.idempotencyMeta:new Map(this.state.idempotencyMeta??[]);
    this.state.masterData??=Object.fromEntries([...REFERENCE_TYPES].map(type=>[type,seedDemoReferences?(DEMO_REFERENCES[type]??[]).map(code=>({id:randomUUID(),code,name:code,status:'ACTIVE'})):[]]));
    if(seedDemoReferences)for(const type of REFERENCE_TYPES)if(!this.state.masterData[type]?.length)this.state.masterData[type]=(DEMO_REFERENCES[type]??[]).map(code=>({id:randomUUID(),code,name:code,status:'ACTIVE'}));
    if(seedDemoReferences&&!this.state.devices.length)this.state.devices=DEMO_DEVICES.map(code=>({id:randomUUID(),code,type:code.includes('PDA')?'PDA':'TERMINAL',status:'ACTIVE',assignedStation:null,lastSeenAt:null,createdAt:this.clock()}));
    this.lastDurableState=structuredClone(this.state);
  }
  persist() {
    if (!this.repository) return;
    if (this.repository.isAsync) {
      const snapshot = structuredClone({ ...this.state, idempotency: [...this.state.idempotency.entries()], idempotencyMeta:[...this.state.idempotencyMeta.entries()] });
      snapshot.idempotency = new Map(snapshot.idempotency);
      snapshot.idempotencyMeta = new Map(snapshot.idempotencyMeta);
      const write=this.pendingPersistence.then(async()=>{await this.repository.save(snapshot);this.lastDurableState=structuredClone(snapshot)});
      this.pendingPersistence=write.catch(error=>{this.state=structuredClone(this.lastDurableState);this.lastPersistenceError??=error;this.persistenceErrorLogger(error)});
    } else {const snapshot=structuredClone(this.state);try{this.repository.save(this.state);this.lastDurableState=snapshot}catch(error){this.state=structuredClone(this.lastDurableState);throw error}}
  }
  async flush() { await this.pendingPersistence;if(this.lastPersistenceError){const error=this.lastPersistenceError;this.lastPersistenceError=null;throw error} }
  withAuditContext(context,fn){return this.auditContext.run(context,fn)}
  requireUuid(value,field,{optional=false}={}){if((value===null||value===undefined||value==='')&&optional)return null;if(typeof value!=='string'||!UUID_PATTERN.test(value))throw new DomainError('UUID_INVALID',`${field} must be a valid UUID`,400);return value}
  reference(type,code){if(!REFERENCE_TYPES.has(type))throw new DomainError('MASTER_DATA_TYPE_INVALID','Unknown master-data type',400);const item=this.state.masterData[type].find(x=>x.code===code&&x.status==='ACTIVE');if(!item)throw new DomainError('MASTER_DATA_REFERENCE_INVALID',`${type} code ${code} is not active`,400);return item}
  createReference(type,input,key){return this.run(key,'MASTER_DATA_CREATED',()=>{if(!REFERENCE_TYPES.has(type))throw new DomainError('MASTER_DATA_TYPE_INVALID','Unknown master-data type',400);const code=String(input.code??'').trim();if(!code||!input.name?.trim())throw new DomainError('MASTER_DATA_FIELDS_REQUIRED','Code and name are required',400);if(this.state.masterData[type].some(x=>x.code===code))throw new DomainError('MASTER_DATA_CODE_DUPLICATE','Code already exists',409);const item={id:randomUUID(),code,name:input.name.trim(),status:'ACTIVE',createdAt:this.clock()};this.state.masterData[type].push(item);return item},input)}
  updateReference(type,id,input,key){return this.run(key,'MASTER_DATA_UPDATED',()=>{if(!REFERENCE_TYPES.has(type))throw new DomainError('MASTER_DATA_TYPE_INVALID','Unknown master-data type',400);const item=this.state.masterData[type].find(x=>x.id===id);if(!item)throw new DomainError('MASTER_DATA_NOT_FOUND','Reference item not found',404);if(input.name!==undefined)item.name=String(input.name).trim();if(input.status!==undefined){if(!['ACTIVE','INACTIVE'].includes(input.status))throw new DomainError('MASTER_DATA_STATUS_INVALID','Status must be ACTIVE or INACTIVE',400);item.status=input.status}item.updatedAt=this.clock();return item},{type,id,input})}
  createHarvestPeriod(input,key){return this.run(key,'HARVEST_PERIOD_CREATED',()=>{const code=String(input.code??'').trim(),label=String(input.label??'').trim(),startDate=String(input.startDate??''),endDate=String(input.endDate??'');if(!code||!label||!/^\d{4}-\d{2}-\d{2}$/.test(startDate)||!/^\d{4}-\d{2}-\d{2}$/.test(endDate)||startDate>endDate)throw new DomainError('HARVEST_PERIOD_INVALID','Code, label and a valid date range are required',400);if(this.state.harvestPeriods.some(x=>x.code===code))throw new DomainError('HARVEST_PERIOD_DUPLICATE','Harvest period code already exists',409);if(this.state.harvestPeriods.some(x=>x.status==='ACTIVE'&&startDate<=x.endDate&&endDate>=x.startDate))throw new DomainError('HARVEST_PERIOD_OVERLAP','Active harvest periods cannot overlap',409);const period={id:randomUUID(),code,label,startDate,endDate,status:'ACTIVE',createdAt:this.clock()};this.state.harvestPeriods.push(period);return period},input)}
  updateHarvestPeriod(id,input,key){return this.run(key,'HARVEST_PERIOD_UPDATED',()=>{const period=this.state.harvestPeriods.find(x=>x.id===id);if(!period)throw new DomainError('HARVEST_PERIOD_NOT_FOUND','Harvest period not found',404);const label=input.label===undefined?period.label:String(input.label).trim(),startDate=input.startDate??period.startDate,endDate=input.endDate??period.endDate,status=input.status??period.status;if(!label||!/^[0-9]{4}-[0-9]{2}-[0-9]{2}$/.test(startDate)||!/^[0-9]{4}-[0-9]{2}-[0-9]{2}$/.test(endDate)||startDate>endDate)throw new DomainError('HARVEST_PERIOD_INVALID','Label and a valid date range are required',400);if(!['ACTIVE','INACTIVE'].includes(status))throw new DomainError('HARVEST_PERIOD_STATUS_INVALID','Status must be ACTIVE or INACTIVE',400);if(status==='ACTIVE'&&this.state.harvestPeriods.some(x=>x.id!==id&&x.status==='ACTIVE'&&startDate<=x.endDate&&endDate>=x.startDate))throw new DomainError('HARVEST_PERIOD_OVERLAP','Active harvest periods cannot overlap',409);Object.assign(period,{label,startDate,endDate,status,updatedAt:this.clock()});return period},{id,...input})}
  harvestPeriodFor(instant){const day=String(instant??this.clock()).slice(0,10);return this.state.harvestPeriods.find(x=>x.status==='ACTIVE'&&x.startDate<=day&&x.endDate>=day)??null}
  raiseExceptionRecord(input){this.requireUuid(input.entityId,'entityId',{optional:true});const item={id:randomUUID(),type:input.type,entityType:input.entityType,entityId:input.entityId??null,severity:input.severity??'WARNING',status:'OPEN',assignedTo:null,raisedAt:this.clock()};if(!item.type||!item.entityType||!['INFO','WARNING','HIGH','CRITICAL'].includes(item.severity))throw new DomainError('EXCEPTION_FIELDS_INVALID','Exception type, entity type and valid severity are required',400);this.state.exceptions.push(item);return item}
  raiseException(input,key){return this.run(key,'EXCEPTION_RAISED',()=>this.raiseExceptionRecord(input),input)}
  assignException(id,input,key){return this.run(key,'EXCEPTION_ASSIGNED',()=>{const item=this.state.exceptions.find(x=>x.id===id);if(!item)throw new DomainError('EXCEPTION_NOT_FOUND','Exception not found',404);if(!['OPEN','ASSIGNED'].includes(item.status)||!input.assignedTo)throw new DomainError('EXCEPTION_ASSIGNMENT_INVALID','Only open exceptions may be assigned',409);item.status='ASSIGNED';item.assignedTo=input.assignedTo;return item},{id,...input})}
  resolveException(id,input,key){return this.run(key,'EXCEPTION_RESOLVED',()=>{const item=this.state.exceptions.find(x=>x.id===id);if(!item)throw new DomainError('EXCEPTION_NOT_FOUND','Exception not found',404);if(!['OPEN','ASSIGNED'].includes(item.status)||!['RESOLVED','DISMISSED'].includes(input.decision)||!input.resolutionNote?.trim())throw new DomainError('EXCEPTION_RESOLUTION_INVALID','Resolution requires a decision and note',409);item.status=input.decision;item.resolvedBy=input.resolvedBy;item.resolutionNote=input.resolutionNote.trim();item.resolvedAt=this.clock();return item},{id,...input})}
  restoreSnapshot(snapshot) {
    for (const key of Object.keys(this.state)) if (!(key in snapshot)) delete this.state[key];
    for (const [key, saved] of Object.entries(snapshot)) {
      const current=this.state[key];
      if(Array.isArray(saved)&&Array.isArray(current)){
        const existingById=new Map(current.filter(x=>x&&typeof x==='object'&&x.id).map(x=>[x.id,x]));
        const restored=saved.map(item=>{
          if(!item||typeof item!=='object'||!item.id)return structuredClone(item);
          const existing=existingById.get(item.id);
          if(!existing)return structuredClone(item);
          for(const field of Object.keys(existing))if(!(field in item))delete existing[field];
          Object.assign(existing,structuredClone(item));
          return existing;
        });
        current.splice(0,current.length,...restored);
      }else if(saved instanceof Map)this.state[key]=new Map(structuredClone([...saved.entries()]));
      else this.state[key]=structuredClone(saved);
    }
  }
  run(key, action, fn, request = {}) {
    const now=Date.parse(this.clock());for(const[k,meta]of this.state.idempotencyMeta)if(Date.parse(meta.expiresAt)<=now){this.state.idempotencyMeta.delete(k);this.state.idempotency.delete(k)}
    if (!key) throw new DomainError('IDEMPOTENCY_KEY_REQUIRED', 'Idempotency-Key is required', 400);
    const requestHash=createHash('sha256').update(JSON.stringify(request)).digest('hex'),existing=this.state.idempotencyMeta.get(key);
    if(existing&&existing.requestHash!==requestHash)throw new DomainError('IDEMPOTENCY_PAYLOAD_MISMATCH','Idempotency key was already used with a different payload',409);
    if (this.state.idempotency.has(key)) return this.state.idempotency.get(key);
    const before=structuredClone(this.findEntity(request.id??request.batchId??request.entityId)),snapshot=structuredClone(this.state);
    try{const result = fn(); this.state.idempotency.set(key, result);this.state.idempotencyMeta.set(key,{requestHash,createdAt:this.clock(),expiresAt:new Date(Date.parse(this.clock())+7*86400000).toISOString()}); this.record(action, result.id,{beforeState:before,afterState:structuredClone(this.findEntity(result.id)??result)},request.sessionId,null,'SUCCESS'); this.persist(); return result;}catch(error){const snapshotExceptionIds=new Set(snapshot.exceptions.map(x=>x.id)),raised=this.state.exceptions.filter(x=>!snapshotExceptionIds.has(x.id)).map(x=>structuredClone(x));this.restoreSnapshot(snapshot);this.state.exceptions.push(...raised);this.record(action,null,{errorCode:error.code??'SYSTEM',beforeState:before,afterState:null},request.sessionId,null,'FAILURE');this.persist();throw error}
  }
  findEntity(id){if(!id)return null;for(const value of Object.values(this.state))if(Array.isArray(value)){const found=value.find(x=>x?.id===id);if(found)return found}return null}
  record(type, entityId, payload = {}, sessionId = null, explicitDeviceId = null, result='SUCCESS') {
    const context=this.auditContext.getStore()??{},session=sessionId?this.state.sessions.find(x=>x.id===sessionId):null,deviceId=explicitDeviceId??session?.deviceId??context.deviceId??'SYSTEM';
    const beforeState=payload.beforeState??null,afterState=payload.afterState??null,eventPayload={...payload};delete eventPayload.beforeState;delete eventPayload.afterState;
    const requestId=context.requestId??randomUUID(),id=randomUUID();
    const event = { id, site: this.site, type, entityId:entityId??id, sessionId:session?.id??sessionId, deviceId, userId:context.userId??session?.operatorId??null,requestId,ipAddress:context.ipAddress??null,result,payload:eventPayload,beforeState,afterState,actorRoles:[...(context.roles??[])],actorStation:context.station??session?.station??null,occurredAt: this.clock(), schemaVersion:2 };
    this.state.audit.push(event); this.state.outbox.push({ ...event, status: 'PENDING' }); return event;
  }
  openSession(operatorId, deviceId, station = 'terminal-01',selectedRole=null) {
    if(!deviceId?.trim())throw new DomainError('DEVICE_ID_REQUIRED','A registered originating device ID is required',400);
    const device=this.state.devices.find(x=>x.code===deviceId.trim());if(!device||device.status!=='ACTIVE')throw new DomainError('DEVICE_NOT_ACTIVE','Device is not registered and active for this site',403);if(device.assignedStation&&device.assignedStation!==station)throw new DomainError('DEVICE_STATION_MISMATCH','Device is assigned to a different station',403);device.lastSeenAt=this.clock();
    const session = { id: randomUUID(), site: this.site, operatorId, deviceId:deviceId.trim(), station,selectedRole,status: 'ACTIVE', startedAt: this.clock(), updatedAt: this.clock(),lastActivityAt:this.clock() };
    this.state.sessions.push(session); this.record('SESSION_OPENED', session.id,{},session.id,session.deviceId); this.persist(); return session;
  }
  registerDevice(input,key){return this.run(key,'DEVICE_REGISTERED',()=>{const code=String(input.code??'').trim();if(!code||!['TERMINAL','PDA','SCALE','PRINTER'].includes(input.type))throw new DomainError('DEVICE_FIELDS_INVALID','Device code and supported type are required',400);if(this.state.devices.some(x=>x.code===code))throw new DomainError('DEVICE_CODE_DUPLICATE','Device code already exists',409);const device={id:randomUUID(),code,type:input.type,status:'ACTIVE',assignedStation:input.assignedStation??null,lastSeenAt:null,createdAt:this.clock()};this.state.devices.push(device);return device},input)}
  heartbeatDevice(code){const device=this.state.devices.find(x=>x.code===code);if(!device)throw new DomainError('DEVICE_NOT_FOUND','Device not found',404);if(device.status!=='ACTIVE')throw new DomainError('DEVICE_RETIRED','Retired device cannot send heartbeat',409);device.lastSeenAt=this.clock();this.record('DEVICE_HEARTBEAT',device.id);this.persist();return device}
  devicesWithPresence(offlineAfterMs=Number(process.env.DEVICE_OFFLINE_AFTER_MS||120000)){const now=Date.parse(this.clock());return this.state.devices.map(x=>({...x,online:x.status==='ACTIVE'&&x.lastSeenAt!=null&&now-Date.parse(x.lastSeenAt)<=offlineAfterMs,presence:x.status!=='ACTIVE'?'RETIRED':x.lastSeenAt!=null&&now-Date.parse(x.lastSeenAt)<=offlineAfterMs?'ONLINE':'OFFLINE'}))}
  retireDevice(id,key){return this.run(key,'DEVICE_RETIRED',()=>{const device=this.state.devices.find(x=>x.id===id);if(!device)throw new DomainError('DEVICE_NOT_FOUND','Device not found',404);if(this.state.sessions.some(x=>x.deviceId===device.code&&x.status==='ACTIVE'))throw new DomainError('DEVICE_HAS_ACTIVE_SESSION','Close active device sessions before retirement',409);device.status='RETIRED';return device},{id})}
  requireSession(id) {
    const s = this.state.sessions.find(x => x.id === id);
    if (!s) throw new DomainError('SESSION_NOT_FOUND', 'Session not found', 404);
    if(s.status==='ACTIVE'&&Date.parse(this.clock())-Date.parse(s.lastActivityAt??s.updatedAt??s.startedAt)>this.idleSessionMs){s.status='SUSPENDED';s.updatedAt=this.clock();this.record('SESSION_TIMED_OUT',s.id,{idleSessionMs:this.idleSessionMs},s.id,s.deviceId);this.persist()}
    if (s.status !== 'ACTIVE') throw new DomainError('SESSION_NOT_ACTIVE', 'Session is not active', 409);s.lastActivityAt=this.clock();s.updatedAt=s.lastActivityAt; return s;
  }
  sweepIdleSessions(){let count=0;for(const s of this.state.sessions.filter(x=>x.status==='ACTIVE'))if(Date.parse(this.clock())-Date.parse(s.lastActivityAt??s.updatedAt??s.startedAt)>this.idleSessionMs){s.status='SUSPENDED';s.updatedAt=this.clock();this.record('SESSION_TIMED_OUT',s.id,{idleSessionMs:this.idleSessionMs},s.id,s.deviceId);count++}if(count)this.persist();return count}
  updateSession(id, action) {
    const s=this.state.sessions.find(x=>x.id===id);if(!s)throw new DomainError('SESSION_NOT_FOUND','Session not found',404);
    const allowed={ACTIVE:{SUSPEND:'SUSPENDED',COMPLETE:'COMPLETED',CANCEL:'CANCELLED'},SUSPENDED:{RESUME:'ACTIVE',CANCEL:'CANCELLED'}};
    const next=allowed[s.status]?.[action];if(!next)throw new DomainError('SESSION_TRANSITION_INVALID',`Cannot ${action} a ${s.status} session`,409);
    s.status=next;s.updatedAt=this.clock();if(next!=='ACTIVE')for(const c of this.state.containers)if(c.activeSessionId===s.id)c.activeSessionId=null;if(['COMPLETED','CANCELLED'].includes(next))s.closedAt=this.clock();this.record(`SESSION_${next}`,s.id,{},s.id);this.persist();return s;
  }
  forceCloseSession(id,actorId){const s=this.state.sessions.find(x=>x.id===id);if(!s)throw new DomainError('SESSION_NOT_FOUND','Session not found',404);if(!['ACTIVE','SUSPENDED'].includes(s.status))throw new DomainError('SESSION_TRANSITION_INVALID','Session is already closed',409);s.status='CANCELLED';s.terminatedBy=actorId;s.closedAt=this.clock();s.updatedAt=this.clock();this.record('SESSION_FORCE_CLOSED',s.id,{terminatedBy:actorId},s.id,s.deviceId);this.persist();return s}
  handoverSession(id,fromOperatorId,toOperatorId){const s=this.requireSession(id);if(s.operatorId!==fromOperatorId||!toOperatorId?.trim())throw new DomainError('SESSION_HANDOVER_INVALID','Active owner and target operator are required',403);const previous=s.operatorId;s.operatorId=toOperatorId.trim();s.handedOverFrom=previous;s.updatedAt=this.clock();s.lastActivityAt=s.updatedAt;this.record('SESSION_HANDED_OVER',s.id,{fromOperatorId:previous,toOperatorId:s.operatorId},s.id,s.deviceId);this.persist();return s}
  saveSessionDraft(id,draft){const s=this.requireSession(id);s.draft=structuredClone(draft??{});s.updatedAt=this.clock();this.record('SESSION_DRAFT_SAVED',s.id,{draft:s.draft},s.id);this.persist();return s}
  containerForOperation(operation,input,batchIds=[]){
    const gate=CONTAINER_GATES[operation],requiredZone=this.reference('zones',gate.zone),id=input[gate.field];
    if(!id)throw new DomainError(gate.field==='trayId'?'TRAY_SCAN_REQUIRED':'CONTAINER_SCAN_REQUIRED',`${gate.field} must come from a physical QR scan`,400);
    const c=this.state.containers.find(x=>x.id===id);if(!c)throw new DomainError(gate.field==='trayId'?'TRAY_NOT_FOUND':'CONTAINER_NOT_FOUND',`${gate.field==='trayId'?'Tray':'Container'} not found`,404);
    const session=this.requireSession(input.sessionId),owner=this.state.sessions.find(x=>x.id===c.activeSessionId&&x.status==='ACTIVE');
    if(c.locked)throw new DomainError('CONTAINER_LOCKED','Scanned container is locked',409);
    if(owner&&owner.id!==session.id)throw new DomainError('CONTAINER_ASSIGNED_TO_ACTIVE_SESSION',`Container is assigned to active session ${owner.id}`,409);
    if(!gate.types.includes(c.type))throw new DomainError('CONTAINER_TYPE_INVALID',`${operation} requires ${gate.types.join(' or ')}`,409);
    if(c.zoneId!==requiredZone.id&&c.zone!==requiredZone.code)throw new DomainError('CONTAINER_STAGE_INVALID',`${operation} requires container zone ${requiredZone.code}`,409);
    if(c.designatedZone&&c.designatedZone!==requiredZone.code){this.record('CONTAINER_DESIGNATED_ZONE_MISMATCH',c.id,{operation,designatedZone:c.designatedZone,operationZone:requiredZone.code},session.id,null,'WARNING');this.raiseExceptionRecord({type:'CONTAINER_ZONE_MISMATCH',entityType:'CONTAINER',entityId:c.id,severity:'WARNING'})}
    if(!gate.statuses.includes(c.status))throw new DomainError('CONTAINER_STATUS_INVALID',`${operation} requires container status ${gate.statuses.join(' or ')}`,409);
    if(gate.empty&&c.batchIds.length)throw new DomainError('CONTAINER_NOT_AVAILABLE','Receiving container is already in use',409);
    for(const batchId of batchIds){const b=this.batch(batchId);this.assertBatchUsable(b);if(b.containerId!==c.id||!c.batchIds.includes(b.id))throw new DomainError('BATCH_CONTAINER_MISMATCH','Scanned container does not contain the requested batch',409);if(gate.batchStatuses&&!gate.batchStatuses.includes(b.status))throw new DomainError('BATCH_STAGE_INVALID',`${operation} does not allow batch status ${b.status}`,409)}
    c.activeSessionId=session.id;c.lastDeviceId=session.deviceId;return c;
  }
  assertBatchUsable(batch){if(batch.status==='QUARANTINED'||batch.zone==='QUARANTINE')throw new DomainError('BATCH_QUARANTINED','Quarantined inventory cannot enter an operational workflow',409);return batch}
  receive(input, key) {
    return this.run(key, 'BATCH_RECEIVED', () => {
      const session=this.requireSession(input.sessionId),container=this.containerForOperation('RECEIVE',input);
      if (!input.supplier || !input.product || !input.grade || !input.size) throw new DomainError('RECEIVING_FIELDS_REQUIRED', 'Supplier, product, grade and size are required', 400);
      if (!(input.weightKg > 0)) throw new DomainError('WEIGHT_INVALID', 'Weight must be greater than zero', 400);
      if(Number(input.weightKg)>container.capacityKg){this.raiseExceptionRecord({type:'CAPACITY_EXCEEDED',entityType:'CONTAINER',entityId:container.id,severity:'HIGH'});throw new DomainError('CONTAINER_CAPACITY_EXCEEDED','Receiving weight exceeds scanned container capacity',409)}
      const delivery=input.deliveryId?this.state.deliveries.find(x=>x.id===input.deliveryId):null;if(input.deliveryId&&(!delivery||delivery.status!=='OPEN'||delivery.supplierCode!==input.supplier))throw new DomainError('DELIVERY_INVALID','An open delivery for the same supplier is required',409);
      const product=this.reference('products',input.product),supplier=this.reference('suppliers',input.supplier),grade=this.reference('grades',input.grade),size=this.reference('sizes',input.size),zone=this.reference('zones','RECEIVING'),receivedAt=this.clock(),period=this.harvestPeriodFor(receivedAt);const batch = { id: randomUUID(), code: `B-${this.site}-${String(this.state.batches.length + 1).padStart(6,'0')}`, site: this.site, supplier: supplier.code,supplierId:supplier.id, product:product.code,productId:product.id, grade:grade.code,gradeId:grade.id, size:size.code,sizeId:size.id, harvestPeriod: period?.code??null, weightKg: input.weightKg, zone:zone.code,zoneId:zone.id, status: 'RECEIVED', containerId:container.id, deliveryId:input.deliveryId??null, sessionId:session.id, deviceId:session.deviceId, parentIds: [], configVersionId:this.activeConfigurationId('RECEIVING'), createdAt: receivedAt };
      container.batchIds.push(batch.id);container.status='IN_USE';
      this.state.batches.push(batch); this.measure(batch.id, input.weightKg, 'RECEIVING', input.sessionId);
      if(Number(input.expectedWeightKg)>0){const variance=Math.abs(Number(input.weightKg)-Number(input.expectedWeightKg))/Number(input.expectedWeightKg),limit=Number(input.weightVarianceLimit??0.05);if(variance>limit)this.raiseExceptionRecord({type:'WEIGHT_ANOMALY',entityType:'BATCH',entityId:batch.id,severity:variance>limit*2?'HIGH':'WARNING'})}
      if(!period)this.raiseExceptionRecord({type:'HARVEST_PERIOD_NOT_CONFIGURED',entityType:'BATCH',entityId:batch.id,severity:'WARNING'});
      if(delivery){const item={id:randomUUID(),deliveryId:delivery.id,batchId:batch.id,containerId:container.id,sequenceNo:1+this.state.deliveryBaskets.filter(x=>x.deliveryId===delivery.id).length,weightKg:batch.weightKg,receivedAt};this.state.deliveryBaskets.push(item);batch.deliverySequenceNo=item.sequenceNo}
      batch.printRequired=false;return batch;
    },input);
  }
  startDelivery(input,key){return this.run(key,'DELIVERY_STARTED',()=>{const session=this.requireSession(input.sessionId),supplier=this.reference('suppliers',input.supplierCode);if(this.state.deliveries.some(x=>x.status==='OPEN'&&x.sessionId===session.id))throw new DomainError('DELIVERY_ALREADY_OPEN','This session already has an open delivery',409);const delivery={id:randomUUID(),code:`DR-${this.site}-${String(this.state.deliveries.length+1).padStart(6,'0')}`,supplierCode:supplier.code,status:'OPEN',sessionId:session.id,receivingBatchId:null,startedAt:this.clock()};this.state.deliveries.push(delivery);return delivery},input)}
  completeDelivery(id,input,key){return this.run(key,'DELIVERY_COMPLETED',()=>{const delivery=this.state.deliveries.find(x=>x.id===id);if(!delivery)throw new DomainError('DELIVERY_NOT_FOUND','Delivery not found',404);if(delivery.status!=='OPEN')throw new DomainError('DELIVERY_NOT_OPEN','Only an open delivery can be completed',409);const session=this.requireSession(input.sessionId);if(delivery.sessionId!==session.id)throw new DomainError('DELIVERY_SESSION_MISMATCH','Delivery belongs to another session',403);const items=this.state.deliveryBaskets.filter(x=>x.deliveryId===id);if(!items.length)throw new DomainError('DELIVERY_EMPTY','At least one weighed basket is required',409);const baskets=items.map(x=>this.batch(x.batchId)),first=baskets[0];if(baskets.some(batch=>batch.product!==first.product||batch.harvestPeriod!==first.harvestPeriod))throw new DomainError('DELIVERY_PRODUCT_MIXED','Delivery baskets must share product and harvest period',409);const grade=this.reference('grades','UNSORTED'),size=this.reference('sizes','MIXED'),total=Number(items.reduce((n,x)=>n+x.weightKg,0).toFixed(3)),aggregate={id:randomUUID(),code:`B-${this.site}-${String(this.state.batches.length+1).padStart(6,'0')}`,site:this.site,supplier:delivery.supplierCode,product:first.product,grade:grade.code,gradeId:grade.id,size:size.code,sizeId:size.id,harvestPeriod:first.harvestPeriod,weightKg:total,zone:'RECEIVING',status:'RECEIVED',deliveryId:id,isAggregate:true,parentIds:baskets.map(x=>x.id),relationshipType:'DELIVERY_AGGREGATE',sessionId:session.id,deviceId:session.deviceId,createdAt:this.clock()};for(const basket of baskets){basket.weightKg=0;basket.status='CONSUMED';if(basket.containerId){const container=this.state.containers.find(x=>x.id===basket.containerId);if(container){container.batchIds=container.batchIds.filter(batchId=>batchId!==basket.id);if(!container.batchIds.length){container.status='AVAILABLE';container.activeSessionId=null}}basket.containerId=null}}this.state.batches.push(aggregate);delivery.status='COMPLETED';delivery.completedAt=this.clock();delivery.receivingBatchId=aggregate.id;const task={id:randomUUID(),site:this.site,title:`Move ${aggregate.code} to Cold Storage`,zone:'COLD_ROOM',priority:70,status:'OPEN',assignedTo:null,entityId:aggregate.id,requiredRole:'STORAGE_OPERATOR',requiredSkillId:null,dependsOnTaskId:null,stateHistory:[{from:null,to:'OPEN',action:'AUTO_CREATE',at:this.clock()}],createdAt:this.clock()};this.state.tasks.push(task);delivery.coldStorageTaskId=task.id;return{delivery,receivingBatch:aggregate,baskets,task}}, {id,...input})}
  measure(batchId, weightKg, reason, sessionId) {
    if (!(weightKg > 0)) throw new DomainError('WEIGHT_INVALID', 'Weight must be greater than zero', 400);
    const batch = this.batch(batchId),session=sessionId?this.requireSession(sessionId):null; const m = { id: randomUUID(), batchId, weightKg, reason, sessionId, deviceId:session?.deviceId??'SYSTEM', measuredAt: this.clock() };
    this.state.measurements.push(m); batch.weightKg = weightKg; return m;
  }
  batch(id) { const b = this.state.batches.find(x => x.id === id); if (!b) throw new DomainError('BATCH_NOT_FOUND', 'Batch not found', 404); return b; }
  move(batchId, zone, sessionId, key,overrideId=null) {
    return this.run(key, 'BATCH_MOVED', () => { const session=this.requireSession(sessionId),targetZone=this.reference('zones',zone); const b = this.batch(batchId),from=b.zone;if(from==='COLD_ROOM'&&zone!=='COLD_ROOM'){const eligible=this.state.batches.filter(x=>x.zone==='COLD_ROOM'&&x.product===b.product&&x.grade===b.grade&&x.size===b.size&&x.weightKg>0&&x.status!=='QUARANTINED').sort((a,z)=>a.createdAt.localeCompare(z.createdAt)),rank=eligible.findIndex(x=>x.id===b.id)+1,deviation=rank>1;if(deviation){this.record('FIFO_DEVIATION',b.id,{recommendedBatchId:eligible[0].id,recommendedBatchCode:eligible[0].code,actualRank:rank,scope:{product:b.product,grade:b.grade,size:b.size}},session.id,null,'WARNING');this.raiseExceptionRecord({type:'FIFO_DEVIATION',entityType:'BATCH',entityId:b.id,severity:'WARNING'})}b.zone=targetZone.code;b.zoneId=targetZone.id;const m={id:randomUUID(),batchId,sessionId,deviceId:session.deviceId,from,to:targetZone.code,overrideId:null,fifoRank:rank||null,fifoWarning:deviation,recommendedBatchId:deviation?eligible[0].id:null,movedAt:this.clock()};this.state.movements.push(m);return m}b.zone=targetZone.code;b.zoneId=targetZone.id;const m = { id: randomUUID(), batchId, sessionId, deviceId:session.deviceId, from, to: targetZone.code, overrideId:null,fifoRank:null,fifoWarning:false,movedAt: this.clock() }; this.state.movements.push(m); return m; },{batchId,zone,sessionId,overrideId});
  }
  createContainer(input,key){return this.run(key,'CONTAINER_CREATED',()=>{if(!(input.capacityKg>0))throw new DomainError('CONTAINER_CAPACITY_INVALID','Container capacity must be positive',400);const type=(input.type??'BASKET').toUpperCase();if(!['BASKET','CRATE','TRAY'].includes(type))throw new DomainError('CONTAINER_TYPE_INVALID','Container type must be BASKET, CRATE or TRAY',400);const zone=this.reference('zones',input.zone??'RECEIVING'),c={id:randomUUID(),code:`C-${this.site}-${String(this.state.containers.length+1).padStart(6,'0')}`,type,stage:input.stage??'PRE_SORT',capacityKg:Number(input.capacityKg),zone:zone.code,zoneId:zone.id,designatedZone:input.designatedZone??zone.code,status:'AVAILABLE',locked:false,activeSessionId:null,batchIds:[],createdAt:this.clock()};this.reference('zones',c.designatedZone);this.state.containers.push(c);this.queuePrint('CONTAINER',c.id,c.code);return c;},input);}
  updateContainer(id,input,key){return this.run(key,'CONTAINER_UPDATED',()=>{const c=this.state.containers.find(x=>x.id===id);if(!c)throw new DomainError('CONTAINER_NOT_FOUND','Container not found',404);if(input.designatedZone!==undefined)c.designatedZone=this.reference('zones',input.designatedZone).code;if(input.capacityKg!==undefined){if(!(Number(input.capacityKg)>0))throw new DomainError('CONTAINER_CAPACITY_INVALID','Container capacity must be positive',400);c.capacityKg=Number(input.capacityKg)}c.updatedAt=this.clock();return c},{id,...input})}
  assignBatchToContainer(containerId,batchId,sessionId,key){return this.run(key,'BATCH_ASSIGNED_TO_CONTAINER',()=>{const session=this.requireSession(sessionId),c=this.state.containers.find(x=>x.id===containerId);if(!c)throw new DomainError('CONTAINER_NOT_FOUND','Container not found',404);const owner=this.state.sessions.find(x=>x.id===c.activeSessionId&&x.status==='ACTIVE');if(c.locked)throw new DomainError('CONTAINER_LOCKED','Container is locked',409);if(owner&&owner.id!==session.id)throw new DomainError('CONTAINER_ASSIGNED_TO_ACTIVE_SESSION','Container belongs to another active session',409);const b=this.assertBatchUsable(this.batch(batchId)),existing=c.batchIds.filter(id=>id!==b.id).map(id=>this.batch(id));if(c.stage==='PRE_SORT'&&existing.some(x=>x.product!==b.product))throw new DomainError('CONTAINER_SINGLE_PRODUCT_RULE','Pre-sort container may hold only one product',409);const used=existing.reduce((n,x)=>n+x.weightKg,0);if(used+b.weightKg>c.capacityKg){this.raiseExceptionRecord({type:'CAPACITY_EXCEEDED',entityType:'CONTAINER',entityId:c.id,severity:'HIGH'});throw new DomainError('CONTAINER_CAPACITY_EXCEEDED','Container capacity exceeded',409)}if(b.containerId&&b.containerId!==c.id){const old=this.state.containers.find(x=>x.id===b.containerId);if(old){old.batchIds=old.batchIds.filter(id=>id!==b.id);if(!old.batchIds.length){old.status='AVAILABLE';old.activeSessionId=null}}}if(!c.batchIds.includes(b.id))c.batchIds.push(b.id);b.containerId=c.id;b.zone=c.zone;b.zoneId=c.zoneId;c.activeSessionId=session.id;c.lastDeviceId=session.deviceId;c.status=c.zone==='WASHING'&&b.status==='SORTED'?'READY_FOR_WASHING':c.zone==='DRYING'&&b.status==='SORTED'?'READY_FOR_DRYING':['WASHED','SLICED','FROZEN'].includes(b.status)?b.status:'IN_USE';return c;},{containerId,batchId,sessionId});}
  moveContainer(containerId,zone,sessionId,key){return this.run(key,'CONTAINER_MOVED',()=>{const session=this.requireSession(sessionId),targetZone=this.reference('zones',zone),c=this.state.containers.find(x=>x.id===containerId);if(!c)throw new DomainError('CONTAINER_NOT_FOUND','Container not found',404);const owner=this.state.sessions.find(x=>x.id===c.activeSessionId&&x.status==='ACTIVE');if(c.locked)throw new DomainError('CONTAINER_LOCKED','Container is locked',409);if(owner&&owner.id!==session.id)throw new DomainError('CONTAINER_ASSIGNED_TO_ACTIVE_SESSION','Container belongs to another active session',409);const from=c.zone;c.zone=targetZone.code;c.zoneId=targetZone.id;c.activeSessionId=session.id;c.lastDeviceId=session.deviceId;for(const id of c.batchIds){const b=this.batch(id),batchFrom=b.zone;b.zone=targetZone.code;b.zoneId=targetZone.id;this.state.movements.push({id:randomUUID(),batchId:id,containerId:c.id,sessionId,deviceId:session.deviceId,from:batchFrom,to:targetZone.code,movedAt:this.clock()})}const statuses=new Set(c.batchIds.map(id=>this.batch(id).status));if(zone==='WASHING'&&statuses.has('SORTED'))c.status='READY_FOR_WASHING';else if(zone==='DRYING'&&statuses.has('SORTED'))c.status='READY_FOR_DRYING';else if(zone==='SLICING'&&statuses.has('WASHED'))c.status='WASHED';else if(zone==='FREEZING'&&statuses.has('SLICED'))c.status='SLICED';else if(zone==='FREEZE_DRYING'&&statuses.has('FROZEN'))c.status='FROZEN';return{id:randomUUID(),containerId:c.id,sessionId,deviceId:session.deviceId,from,to:targetZone.code,movedAt:this.clock()};},{containerId,zone,sessionId});}
  transform(input, key) {
    return this.run(key, 'BATCH_TRANSFORMED', () => {
      const session=this.requireSession(input.sessionId);
      const rule=PROCESS_RULES[input.process];if(!rule)throw new DomainError('PROCESS_NOT_SUPPORTED','Unsupported production process',400);
      if(CYCLE_TYPES.has(input.process))throw new DomainError('CYCLE_WORKFLOW_REQUIRED',`${input.process} must be performed through a machine cycle; batch identity may not be replaced`,409);
      const requestedInputs = input.inputs?.length ? input.inputs : (input.parentIds ?? []).map(batchId => ({ batchId, consumeWeightKg:this.batch(batchId).weightKg }));
      if (!requestedInputs.length) throw new DomainError('PARENTS_REQUIRED','At least one input is required',400);
      const inputs = requestedInputs.map(x => ({ batch:this.assertBatchUsable(this.batch(x.batchId)), consumeWeightKg:Number(x.consumeWeightKg) }));
      const container=input.process==='MERGE'?null:this.containerForOperation(input.process,input,inputs.map(x=>x.batch.id));
      for (const x of inputs) if (!(x.consumeWeightKg > 0) || x.consumeWeightKg > x.batch.weightKg) throw new DomainError('INSUFFICIENT_INVENTORY','Input exceeds available batch weight',409);
      const inputWeight = inputs.reduce((n,x)=>n+x.consumeWeightKg,0);
      if (!(input.outputWeightKg > 0) || input.process!=='WASH'&&input.outputWeightKg > inputWeight) throw new DomainError('OUTPUT_WEIGHT_INVALID','Output weight exceeds consumed input',409);
      if(input.process==='WASH'&&input.outputWeightKg>inputWeight)this.raiseExceptionRecord({type:'WASH_WEIGHT_GAIN',entityType:'BATCH',entityId:inputs[0].batch.id,severity:'WARNING'});
      const parents=inputs.map(x=>x.batch);
      const product=this.reference('products',input.product??parents[0].product),grade=this.reference('grades',input.grade??parents[0].grade),size=this.reference('sizes',input.size??parents[0].size),zone=this.reference('zones',input.zone??rule.zone);const child = { id:randomUUID(), code:`B-${this.site}-${String(this.state.batches.length+1).padStart(6,'0')}`, site:this.site, supplier:null,supplierId:null, product:product.code,productId:product.id, grade:grade.code,gradeId:grade.id, size:size.code,sizeId:size.id, weightKg:input.outputWeightKg, zone:zone.code,zoneId:zone.id, status:rule.status, containerId:container?.id??null,sessionId:session.id,deviceId:session.deviceId,parentIds:input.parentIds, relationshipType:input.process==='MERGE'?'MERGE':'PROCESS', process:input.process, configVersionId:this.activeConfigurationId('PRODUCTION'), createdAt:this.clock() };
      child.parentIds=parents.map(x=>x.id); child.inputWeightKg=inputWeight; child.processLossKg=Math.max(0,Number((inputWeight-input.outputWeightKg).toFixed(3)));child.weightGainKg=Math.max(0,Number((input.outputWeightKg-inputWeight).toFixed(3)));
      for(const x of inputs){x.batch.weightKg=Number((x.batch.weightKg-x.consumeWeightKg).toFixed(3));if(x.batch.weightKg===0){x.batch.status='CONSUMED';x.batch.containerId=null}}
      if(container){container.batchIds=container.batchIds.filter(id=>!inputs.some(x=>x.batch.id===id&&x.batch.weightKg===0));if(!container.batchIds.includes(child.id))container.batchIds.push(child.id);container.status=rule.status;container.zone=rule.zone;container.activeSessionId=session.id;container.lastDeviceId=session.deviceId}
      this.state.batches.push(child);this.measure(child.id,input.outputWeightKg,input.process,input.sessionId);this.queuePrint('BATCH',child.id,child.code);if(input.process==='WASH')this.autoTask(child,'Sorting','SORTING','SORTING_OPERATOR');if(input.process==='SLICE')this.autoTask(child,'Freezing','FREEZING','FREEZING_OPERATOR');return child;
    },input);
  }
  autoTask(batch,title,zone,requiredRole=null){const task={id:randomUUID(),site:this.site,title:`${title}: ${batch.code}`,zone,priority:70,status:'OPEN',assignedTo:null,entityId:batch.id,requiredRole,requiredSkillId:null,dependsOnTaskId:null,stateHistory:[{from:null,to:'OPEN',action:'AUTO_CREATE',at:this.clock()}],createdAt:this.clock()};this.state.tasks.push(task);return task}
  createCycle(input,key){
    return this.run(key,'CYCLE_CREATED',()=>{
      const type=String(input.type??'').toUpperCase();if(!CYCLE_TYPES.has(type))throw new DomainError('CYCLE_TYPE_INVALID','Cycle type must be FREEZE, FREEZE_DRY or DRY',400);
      const session=this.requireSession(input.sessionId);if(!input.machineId?.trim())throw new DomainError('MACHINE_ID_REQUIRED','A physical machine ID is required',400);
      const scanned=type==='DRY'?(input.containerIds??[]):(input.trayIds??[]);if(!Array.isArray(scanned)||!scanned.length)throw new DomainError(type==='DRY'?'CONTAINER_SCAN_REQUIRED':'TRAY_SCAN_REQUIRED','At least one physical container must be scanned',400);
      if(new Set(scanned).size!==scanned.length)throw new DomainError('CYCLE_CONTAINER_DUPLICATE','A container may only be scanned once into a cycle',409);
      const containers=scanned.map(id=>this.containerForOperation(type,{sessionId:session.id,[CONTAINER_GATES[type].field]:id},[]));
      for(const c of containers){
        if(this.state.cycles.some(x=>ACTIVE_CYCLE_STATUSES.has(x.status)&&x.containerIds.includes(c.id)))throw new DomainError('CONTAINER_ACTIVE_CYCLE','Container is already assigned to another active cycle',409);
        if(!c.batchIds.length)throw new DomainError('CYCLE_CONTAINER_EMPTY','Scanned container has no production batch',409);
        if(type!=='DRY'&&c.batchIds.length!==1)throw new DomainError('TRAY_SINGLE_BATCH_REQUIRED','Each freeze or freeze-dry tray must contain exactly one batch',409);
        for(const batchId of c.batchIds)this.containerForOperation(type,{sessionId:session.id,[CONTAINER_GATES[type].field]:c.id},[batchId]);
      }
      const batchIds=[...new Set(containers.flatMap(c=>c.batchIds))],prefix={FREEZE:'FC',FREEZE_DRY:'FDC',DRY:'DC'}[type],cycle={id:randomUUID(),code:`${prefix}-${this.clock().slice(0,10).replaceAll('-','')}-${String(this.state.cycles.filter(x=>x.type===type).length+1).padStart(3,'0')}`,type,machineId:input.machineId.trim(),sessionId:session.id,deviceId:session.deviceId,operatorId:session.operatorId,containerIds:containers.map(c=>c.id),batchIds,status:'READY',stateHistory:[{from:null,to:'READY',action:'CREATE',at:this.clock(),sessionId:session.id,deviceId:session.deviceId}],configVersionId:this.activeConfigurationId(type),createdAt:this.clock(),updatedAt:this.clock()};
      this.state.cycles.push(cycle);for(const c of containers){c.activeCycleId=cycle.id;c.activeSessionId=session.id}return cycle;
    },input);
  }
  transitionCycle(id,action,input,key){
    return this.run(key,`CYCLE_${action}`,()=>{
      const cycle=this.state.cycles.find(x=>x.id===id);if(!cycle)throw new DomainError('CYCLE_NOT_FOUND','Cycle not found',404);const session=this.requireSession(input.sessionId);
      const running=cycle.type==='DRY'?'IN_PROGRESS':'RUNNING',allowed={READY:{START:running,CANCEL:'CANCELLED'},RUNNING:{PAUSE:'PAUSED',COMPLETE:'COMPLETING',FAIL:'FAILED'},IN_PROGRESS:{PAUSE:'PAUSED',COMPLETE:'COMPLETING',FAIL:'FAILED'},PAUSED:{RESUME:running,FAIL:'FAILED',CANCEL:'CANCELLED'},COMPLETING:{FINISH:'COMPLETED',FAIL:'FAILED'}};
      const next=allowed[cycle.status]?.[action];if(!next)throw new DomainError('CYCLE_TRANSITION_INVALID',`Cannot ${action} a ${cycle.status} ${cycle.type} cycle`,409);
      if(action==='FINISH'){
        const finalWeights=input.finalWeights??{};
        if(cycle.type!=='FREEZE')for(const batchId of cycle.batchIds){const weight=Number(finalWeights[batchId]);if(!(weight>0)||weight>this.batch(batchId).weightKg)throw new DomainError('CYCLE_FINAL_WEIGHT_REQUIRED','A valid final weight is required for every batch before unload',400);}
        for(const batchId of cycle.batchIds){const b=this.batch(batchId),before=b.weightKg;if(cycle.type!=='FREEZE'){this.measure(batchId,Number(finalWeights[batchId]),cycle.type,session.id);b.yieldPercent=Number((b.weightKg/before*100).toFixed(2));b.status=cycle.type==='FREEZE_DRY'?'FREEZE_DRIED':'DRIED';b.zone='PACKAGING';this.autoTask(b,'Package','PACKAGING','PACKAGING_OPERATOR')}else{b.status='FROZEN';b.zone='FREEZE_DRYING';this.autoTask(b,'Freeze dry','FREEZE_DRYING','DRYING_OPERATOR')}}
      }
      const from=cycle.status;cycle.status=next;cycle.updatedAt=this.clock();cycle.stateHistory.push({from,to:next,action,at:this.clock(),sessionId:session.id,deviceId:session.deviceId});if(action==='START')cycle.startedAt=this.clock();
      if(next==='FAILED')this.raiseExceptionRecord({type:'EQUIPMENT_CYCLE_FAILURE',entityType:'CYCLE',entityId:cycle.id,severity:'CRITICAL'});
      if(['COMPLETED','FAILED','CANCELLED'].includes(next)){cycle.endedAt=this.clock();for(const c of this.state.containers.filter(x=>cycle.containerIds.includes(x.id))){c.activeCycleId=null;c.activeSessionId=null;if(next==='COMPLETED'){for(const batchId of c.batchIds){const batch=this.batch(batchId);if(batch.containerId===c.id)batch.containerId=null}c.batchIds=[];c.status='AVAILABLE'}}}
      return cycle;
    },{id,action,...input});
  }
  sortBatch(input,key){
    return this.run(key,'BATCH_SORTED',()=>{
      const session=this.requireSession(input.sessionId),parent=this.assertBatchUsable(this.batch(input.batchId)),container=this.containerForOperation('SORT',input,[parent.id]),outputs=input.outputs??[];
      if(!outputs.length)throw new DomainError('SORT_OUTPUTS_REQUIRED','Sorting requires outputs',400);
      const total=outputs.reduce((n,x)=>n+Number(x.weightKg),0),lossKg=Number((parent.weightKg-total).toFixed(3));if(!(total>0)||lossKg<0)throw new DomainError('SORT_WEIGHT_INVALID','Sorted output exceeds available weight',409);if(input.lossKg!==undefined&&Math.abs(Number(input.lossKg)-lossKg)>.001)throw new DomainError('SORT_LOSS_MISMATCH','Outputs plus recorded loss must reconcile to input weight',409);const validated=outputs.map(x=>{if(!(x.weightKg>0)||!x.grade||!x.size)throw new DomainError('SORT_OUTPUT_INVALID','Every output needs positive weight, grade and size',400);return{...x,gradeRef:this.reference('grades',x.grade),sizeRef:this.reference('sizes',x.size)}});
      const children=validated.map(x=>{const child={id:randomUUID(),code:`B-${this.site}-${String(this.state.batches.length+1).padStart(6,'0')}`,site:this.site,supplier:null,product:parent.product,grade:x.gradeRef.code,gradeId:x.gradeRef.id,size:x.sizeRef.code,sizeId:x.sizeRef.id,weightKg:Number(x.weightKg),zone:'SORTING',destination:null,status:'SORTED',sessionId:session.id,deviceId:session.deviceId,parentIds:[parent.id],relationshipType:'GRADE_SPLIT',process:'SORT',configVersionId:this.activeConfigurationId('SORTING'),createdAt:this.clock()};this.state.batches.push(child);this.measure(child.id,child.weightKg,'SORT',input.sessionId);this.queuePrint('BATCH',child.id,child.code);this.autoTask(child,'Assign sorting destination','SORTING','MANAGER');return child});
      parent.sortingLossKg=lossKg;parent.weightKg=0;parent.status='CONSUMED';parent.containerId=null;container.batchIds=container.batchIds.filter(id=>id!==parent.id);container.status='SORTED';container.zone='SORTING';container.activeSessionId=session.id;container.lastDeviceId=session.deviceId;session.draft??={};session.draft.sortingCounters??={basketsProcessed:0,batchesCreated:0};session.draft.sortingCounters.basketsProcessed++;session.draft.sortingCounters.batchesCreated+=children.length;return{children,remainingWeightKg:0,lossKg,sortingLossKg:lossKg,containerId:container.id,counters:structuredClone(session.draft.sortingCounters)};
    },input);
  }
  weighForPackaging(input,key){return this.run(key,'PACKAGING_WEIGHT_RECORDED',()=>{const session=this.requireSession(input.sessionId);if(session.selectedRole!=='PACKAGING_OPERATOR')throw new DomainError('PACKAGING_SESSION_REQUIRED','A dedicated packaging session is required',409);const batch=this.assertBatchUsable(this.batch(input.batchId));if(!['DRIED','FREEZE_DRIED','READY_FOR_PACKAGING'].includes(batch.status))throw new DomainError('BATCH_NOT_READY_FOR_PACKAGING','Only finished dried inventory may enter packaging',409);const measured=Number(input.weightKg),configured=this.state.configurationVersions.find(x=>x.scope==='PACKAGING'&&x.status==='ACTIVE')?.values?.checkpointVariancePercent,threshold=Number(configured??5),variance=batch.weightKg?Math.abs(measured-batch.weightKg)/batch.weightKg*100:Infinity;if(!(measured>0))throw new DomainError('MEASUREMENT_INVALID','Weight must be positive',400);if(variance>threshold)throw new DomainError('PACKAGING_WEIGHT_ADJUSTMENT_REQUIRED','Weight variance exceeds the checkpoint threshold; record an inventory adjustment with a reason',409);const measurement=this.measure(batch.id,measured,'PACKAGING_CHECKPOINT',session.id);batch.status='READY_FOR_PACKAGING';batch.zone='PACKAGING';batch.packagingMeasurementId=measurement.id;return{batch,measurement,variancePercent:Number(variance.toFixed(2)),thresholdPercent:threshold}},{...input})}
  assignSortingDestination(batchId,destination,key){return this.run(key,'SORTING_DESTINATION_ASSIGNED',()=>{const batch=this.batch(batchId);if(batch.status!=='SORTED'||batch.destination)throw new DomainError('SORTING_DESTINATION_INVALID','Only an unassigned sorted batch may receive a destination',409);const zone=this.reference('zones',destination);batch.destination=zone.code;const mapping={WASHING:['Washing','WASHING_OPERATOR'],DRYING:['Drying','DRYING_OPERATOR'],COLD_ROOM:['Cold storage','STORAGE_OPERATOR'],PACKAGING:['Packaging','PACKAGING_OPERATOR']},[title,role]=mapping[zone.code]??[`Move to ${zone.code}`,'STORAGE_OPERATOR'];const decision=this.state.tasks.find(x=>x.entityId===batch.id&&x.requiredRole==='MANAGER'&&x.status==='OPEN');if(decision){decision.status='COMPLETED';decision.completedAt=this.clock();decision.stateHistory.push({from:'OPEN',to:'COMPLETED',action:'DESTINATION_ASSIGNED',at:this.clock()})}const task=this.autoTask(batch,title,zone.code,role);return{batch,task}},{batchId,destination})}
  createPackage(input,key){return this.run(key,'PACKAGE_CREATED',()=>{
    const session=this.requireSession(input.sessionId),level=input.level??'CARTON',carton=level==='CARTON'&&input.type==='CARTON',unit=level==='UNIT',requested=input.items??[],childIds=input.childPackageIds??[];
    if(unit&&session.selectedRole!=='PACKAGING_OPERATOR')throw new DomainError('PACKAGING_SESSION_REQUIRED','UNIT packages require a dedicated packaging session',409);
    if(!requested.length&&!childIds.length)throw new DomainError('PACKAGE_EMPTY','Package needs inventory items or child packages',400);
    if(requested.length&&childIds.length)throw new DomainError('PACKAGE_CONTENT_MIXED','A package cannot mix loose inventory and child packages',400);
    if(unit&&requested.length!==1)throw new DomainError('UNIT_PACKAGE_SINGLE_BATCH_REQUIRED','A retail unit must contain exactly one batch allocation',400);
    if(carton&&requested.length)throw new DomainError('CARTON_UNIT_CHILD_REQUIRED','Cartons must be assembled from UNIT packages, not raw batch allocations',409);
    const rank={UNIT:0,CARTON:1,EPS:2,PALLET:3},children=childIds.map(id=>{const child=this.state.packages.find(x=>x.id===id);if(!child)throw new DomainError('PACKAGE_NOT_FOUND','Child package not found',404);if(child.parentPackageId)throw new DomainError('PACKAGE_ALREADY_NESTED','Child package already belongs to a parent',409);if(rank[child.level]>=rank[level])throw new DomainError('PACKAGE_HIERARCHY_INVALID','Child package level must be lower than parent level',409);if(child.status!=='READY_TO_SHIP')throw new DomainError('CHILD_PACKAGE_NOT_READY','Child package must be ready before nesting',409);return child});
    if(carton&&children.some(x=>x.level!=='UNIT'))throw new DomainError('CARTON_UNIT_CHILD_REQUIRED','Cartons must be assembled from individually labeled UNIT packages',409);
    const raw=requested.map(x=>{const batch=this.assertBatchUsable(this.batch(x.batchId)),weightKg=Number(x.weightKg);if(!(weightKg>0))throw new DomainError('PACKAGE_ITEM_WEIGHT_INVALID','Every item requires positive weight',400);return{batch,weightKg}}),totals=new Map();for(const x of raw)totals.set(x.batch.id,(totals.get(x.batch.id)??0)+x.weightKg);let appliedTolerance=null;
    if(unit){const checkpoint=this.state.measurements.findLast(x=>x.batchId===raw[0].batch.id&&x.reason==='PACKAGING_CHECKPOINT');if(raw[0].batch.status!=='READY_FOR_PACKAGING'||!checkpoint)throw new DomainError('BATCH_NOT_READY_FOR_PACKAGING','Batch must pass the packaging weigh checkpoint first',409);const actual=raw[0].weightKg,target=Number(input.targetWeightKg);appliedTolerance=Number(input.tolerancePercent??this.state.configurationVersions.find(x=>x.scope==='PACKAGING'&&x.status==='ACTIVE')?.values?.weightTolerancePercent??2);if(!(target>0)||!(appliedTolerance>=0)||Math.abs(actual-target)>target*appliedTolerance/100)throw new DomainError('PACKAGE_WEIGHT_OUT_OF_TOLERANCE','Measured UNIT weight is outside configured tolerance',409)}
    for(const[batchId,weightKg]of totals)if(weightKg>this.batch(batchId).weightKg)throw new DomainError('INSUFFICIENT_INVENTORY','Package items exceed available batch weight',409);
    for(const[batchId,weightKg]of totals){const batch=this.batch(batchId);batch.weightKg=Number((batch.weightKg-weightKg).toFixed(3));if(batch.weightKg===0)batch.status='PACKAGED'}
    const p={id:randomUUID(),code:`P-${this.site}-${String(this.state.packages.length+1).padStart(6,'0')}`,type:input.type,level,parentPackageId:null,childPackageIds:[...childIds],items:[...totals].map(([batchId,weightKg])=>({batchId,weightKg})),measuredWeightKg:unit?raw[0].weightKg:null,targetWeightKg:unit?Number(input.targetWeightKg):null,tolerancePercent:unit?appliedTolerance:null,sessionId:session.id,deviceId:session.deviceId,status:'DRAFT',configVersionId:this.activeConfigurationId('PACKAGING'),createdAt:this.clock()};
    for(const child of children)child.parentPackageId=p.id;this.state.packages.push(p);return p;
  },input)}
  scanPackageItem(packageId,input,key){return this.run(key,'CARTON_ITEM_SCANNED',()=>{const p=this.state.packages.find(x=>x.id===packageId);if(!p)throw new DomainError('PACKAGE_NOT_FOUND','Package not found',404);if(p.level!=='CARTON'||p.type!=='CARTON'||!['DRAFT','PACKING'].includes(p.status))throw new DomainError('CARTON_SCAN_STATE_INVALID','Physical scans are accepted only while assembling a carton',409);const session=this.requireSession(input.sessionId),identity=String(input.unitPackageCode??input.itemIdentity??'').trim();if(!identity)throw new DomainError('CARTON_ITEM_IDENTITY_REQUIRED','A scanner-provided UNIT package identity is required',400);if(this.state.cartonScanEvents.some(x=>x.itemIdentity===identity))throw new DomainError('CARTON_DUPLICATE_SCAN','Physical identity was already scanned',409);const unit=this.state.packages.find(x=>x.code===identity&&x.level==='UNIT');if(!unit||!p.childPackageIds.includes(unit.id))throw new DomainError('CARTON_SCAN_NOT_ALLOCATED','Scanned UNIT package is not allocated to this carton',409);const item=unit.items[0],event={id:randomUUID(),packageId:p.id,batchId:item.batchId,unitPackageId:unit.id,itemIdentity:unit.code,weightKg:item.weightKg,scannedAt:this.clock(),sessionId:session.id,deviceId:session.deviceId,sequenceNo:1+this.state.cartonScanEvents.filter(x=>x.packageId===p.id).length};this.state.cartonScanEvents.push(event);return event},{packageId,...input})}
  transitionPackage(id,action,key,input={}){return this.run(key,`PACKAGE_${action}`,()=>{
    const p=this.state.packages.find(x=>x.id===id);if(!p)throw new DomainError('PACKAGE_NOT_FOUND','Package not found',404);
    if(['CANCEL','DAMAGE'].includes(action)){if(p.parentPackageId)throw new DomainError('PACKAGE_NESTED_TERMINATION_FORBIDDEN','Un-nest a package before terminating it',409);const valid=action==='CANCEL'?['DRAFT','PACKING','READY_FOR_LABEL','PRINTING','LABEL_PENDING','LABEL_PRINTED','READY_TO_SHIP']:['PACKING','READY_FOR_LABEL','PRINTING','LABEL_PENDING','LABEL_PRINTED','READY_TO_SHIP'];if(!valid.includes(p.status))throw new DomainError('PACKAGE_TERMINATION_INVALID',`Cannot ${action} a ${p.status} package`,409);if(!input.reason?.trim())throw new DomainError('PACKAGE_TERMINATION_REASON_REQUIRED','Cancellation or damage reason is required',400);for(const item of p.items??[]){const batch=this.batch(item.batchId);batch.weightKg=Number((batch.weightKg+item.weightKg).toFixed(3));if(batch.status==='PACKAGED')batch.status='READY_FOR_PACKAGING'}for(const childId of p.childPackageIds??[]){const child=this.state.packages.find(x=>x.id===childId);if(child)child.parentPackageId=null}p.items=[];p.childPackageIds=[];p.status=action==='CANCEL'?'CANCELLED':'DAMAGED';p.terminalReason=input.reason.trim();p.terminatedAt=this.clock();p.updatedAt=p.terminatedAt;if(action==='DAMAGE')this.raiseExceptionRecord({type:'PACKAGE_DAMAGED',entityType:'PACKAGE',entityId:p.id,severity:'HIGH'});return p}
    if(action==='SEAL'&&p.level==='CARTON'&&p.type==='CARTON'){const scanned=this.state.cartonScanEvents.filter(x=>x.packageId===p.id).map(x=>x.itemIdentity),expected=(p.childPackageIds??[]).map(childId=>this.state.packages.find(x=>x.id===childId)?.code);if(!scanned.length)throw new DomainError('CARTON_ITEM_SCAN_REQUIRED','Carton cannot be sealed without UNIT package scans',409);if(new Set(scanned).size!==scanned.length)throw new DomainError('CARTON_DUPLICATE_SCAN','Carton contains a duplicate physical scan',409);if(scanned.length!==expected.length||expected.some(code=>!scanned.includes(code)))throw new DomainError('CARTON_SCAN_ALLOCATION_MISMATCH','Every allocated UNIT package must be scanned before sealing',409)}
    const allowed={DRAFT:{PACK:'PACKING'},PACKING:{SEAL:'READY_FOR_LABEL'},READY_FOR_LABEL:{PRINT:'PRINTING'},PRINTING:{PRINT_SUCCESS:'LABEL_PRINTED',PRINT_FAIL:'LABEL_PENDING'},LABEL_PENDING:{RETRY:'PRINTING'},LABEL_PRINTED:{READY:'READY_TO_SHIP'},READY_TO_SHIP:{SHIP:'SHIPPED'}},next=allowed[p.status]?.[action];if(!next)throw new DomainError('PACKAGE_TRANSITION_INVALID',`Cannot ${action} a ${p.status} package`,409);p.status=next;p.updatedAt=this.clock();if(next==='READY_FOR_LABEL')this.queuePrint('PACKAGE',p.id,p.code);return p;
  },{id,action,...input})}
  activeConfigurationId(scope){return this.state.configurationVersions.find(x=>x.scope===scope&&x.status==='ACTIVE')?.id??null}
  createCustomer(input,key){return this.run(key,'CUSTOMER_CREATED',()=>{const code=String(input.code??'').trim(),name=String(input.name??'').trim();if(!code||!name)throw new DomainError('CUSTOMER_FIELDS_REQUIRED','Customer code and name are required',400);if(this.state.customers.some(x=>x.code===code))throw new DomainError('CUSTOMER_CODE_DUPLICATE','Customer code already exists',409);const customer={id:randomUUID(),code,name,address:String(input.address??''),contact:String(input.contact??''),status:'ACTIVE',createdAt:this.clock()};this.state.customers.push(customer);return customer},input)}
  updateCustomer(id,input,key){return this.run(key,'CUSTOMER_UPDATED',()=>{const customer=this.state.customers.find(x=>x.id===id);if(!customer)throw new DomainError('CUSTOMER_NOT_FOUND','Customer not found',404);if(input.name!==undefined)customer.name=String(input.name).trim();if(input.address!==undefined)customer.address=String(input.address);if(input.contact!==undefined)customer.contact=String(input.contact);if(input.status!==undefined){if(!['ACTIVE','INACTIVE'].includes(input.status))throw new DomainError('CUSTOMER_STATUS_INVALID','Invalid customer status',400);customer.status=input.status}customer.updatedAt=this.clock();return customer},{id,...input})}
  createSalesOrder(input,key){return this.run(key,'SALES_ORDER_CREATED',()=>{const customer=this.state.customers.find(x=>x.id===input.customerId&&x.status==='ACTIVE');if(!customer)throw new DomainError('CUSTOMER_NOT_ACTIVE','An active customer is required',409);const items=(input.items??[]).map(x=>({packageType:String(x.packageType??'CARTON'),quantity:Number(x.quantity)}));if(!items.length||items.some(x=>!x.packageType||!Number.isInteger(x.quantity)||x.quantity<1))throw new DomainError('SALES_ORDER_ITEMS_INVALID','Positive integer order quantities are required',400);const order={id:randomUUID(),code:`SO-${this.site}-${String(this.state.salesOrders.length+1).padStart(6,'0')}`,customerId:customer.id,status:'OPEN',items,createdAt:this.clock()};this.state.salesOrders.push(order);return order},input)}
  createShipment(input,key){return this.run(key,'SHIPMENT_CREATED',()=>{const order=this.state.salesOrders.find(x=>x.id===input.salesOrderId);if(!order||!['OPEN','PARTIALLY_FULFILLED'].includes(order.status))throw new DomainError('SALES_ORDER_NOT_OPEN','An open sales order is required',409);const ids=[...new Set(input.packageIds??[])];if(!ids.length)throw new DomainError('SHIPMENT_EMPTY','Shipment needs cartons',400);const packages=ids.map(id=>{const p=this.state.packages.find(x=>x.id===id);if(!p)throw new DomainError('PACKAGE_NOT_FOUND','Package not found',404);if(p.level!=='CARTON'||p.type!=='CARTON')throw new DomainError('SHIPMENT_CARTON_REQUIRED','Customer shipments accept CARTON packages only',409);if(p.status!=='READY_TO_SHIP')throw new DomainError('PACKAGE_NOT_READY_TO_SHIP','Carton must be ready to ship',409);if(p.shipmentId)throw new DomainError('PACKAGE_ALREADY_SHIPPED','Carton already assigned',409);for(const batchId of this.packageItemsRecursive(p.id).map(x=>x.batchId))this.assertBatchUsable(this.batch(batchId));return p});const already=this.state.shipments.filter(x=>x.salesOrderId===order.id&&x.status!=='CANCELLED').flatMap(x=>x.packageIds).map(id=>this.state.packages.find(p=>p.id===id)).filter(Boolean),limits=Object.fromEntries(order.items.map(x=>[x.packageType,x.quantity]));for(const p of [...already,...packages]){limits[p.type]=(limits[p.type]??0)-1;if(limits[p.type]<0)throw new DomainError('SALES_ORDER_QUANTITY_EXCEEDED','Shipment exceeds remaining sales-order quantity',409)}const shipment={id:randomUUID(),code:`S-${this.site}-${String(this.state.shipments.length+1).padStart(6,'0')}`,salesOrderId:order.id,customerId:order.customerId,packageIds:ids,status:'DRAFT',vehicle:null,createdAt:this.clock()};this.state.shipments.push(shipment);packages.forEach(p=>p.shipmentId=shipment.id);for(const p of packages)this.state.tasks.push({id:randomUUID(),site:this.site,title:`Pick carton ${p.code}`,zone:'SHIPPING',priority:60,status:'OPEN',assignedTo:null,entityId:p.id,requiredRole:'SHIPPING_OPERATOR',requiredSkillId:null,dependsOnTaskId:null,stateHistory:[{from:null,to:'OPEN',action:'CREATE',at:this.clock()}],createdAt:this.clock()});return shipment},input)}
  scanShipmentCarton(id,input,key){return this.run(key,'SHIPMENT_CARTON_SCANNED',()=>{const shipment=this.state.shipments.find(x=>x.id===id);if(!shipment||!['DRAFT','PICKING'].includes(shipment.status))throw new DomainError('SHIPMENT_SCAN_INVALID','Shipment is not accepting carton scans',409);const session=this.requireSession(input.sessionId),pkg=this.state.packages.find(x=>x.code===String(input.cartonCode??'').trim());if(!pkg||!shipment.packageIds.includes(pkg.id))throw new DomainError('SHIPMENT_CARTON_UNEXPECTED','Scanned carton is not expected in this shipment',409);if(this.state.shipmentCartonScans.some(x=>x.shipmentId===id&&x.packageId===pkg.id))throw new DomainError('SHIPMENT_CARTON_DUPLICATE','Carton was already scanned',409);const scan={id:randomUUID(),shipmentId:id,packageId:pkg.id,packageCode:pkg.code,sessionId:session.id,deviceId:session.deviceId,sequenceNo:1+this.state.shipmentCartonScans.filter(x=>x.shipmentId===id).length,scannedAt:this.clock()};this.state.shipmentCartonScans.push(scan);return scan},{id,...input})}
  updateShipment(id,action,input,key){return this.run(key,`SHIPMENT_${action}`,()=>{const s=this.state.shipments.find(x=>x.id===id&&x.kind!=='INTERNAL_TRANSFER');if(!s)throw new DomainError('CUSTOMER_SHIPMENT_NOT_FOUND','Customer shipment not found',404);if(action==='CANCEL'){if(!['DRAFT','PICKING','READY'].includes(s.status))throw new DomainError('SHIPMENT_TRANSITION_INVALID','Shipment can no longer be cancelled',409);s.status='CANCELLED';for(const packageId of s.packageIds){const p=this.state.packages.find(x=>x.id===packageId);if(p)p.shipmentId=null}s.cancelledAt=this.clock();return s}const allowed={DRAFT:{START_PICKING:'PICKING'},PICKING:{READY:'READY'},READY:{LOAD:'LOADED'},LOADED:{SHIP:'SHIPPED'},SHIPPED:{CLOSE:'CLOSED'}},next=allowed[s.status]?.[action];if(!next)throw new DomainError('SHIPMENT_TRANSITION_INVALID',`Cannot ${action} a ${s.status} shipment`,409);if(action==='READY'){const scanned=new Set(this.state.shipmentCartonScans.filter(x=>x.shipmentId===id).map(x=>x.packageId));if(s.packageIds.some(x=>!scanned.has(x)))throw new DomainError('SHIPMENT_SCAN_INCOMPLETE','Every expected carton must be scanned',409)}if(action==='LOAD'&&!String(input.vehicle??'').trim())throw new DomainError('SHIPMENT_VEHICLE_REQUIRED','Vehicle is required before loading',400);s.status=next;s.updatedAt=this.clock();if(action==='LOAD'){s.vehicle=String(input.vehicle).trim();s.loadedAt=this.clock()}if(action==='SHIP'){s.shippedAt=this.clock();for(const packageId of s.packageIds){const p=this.state.packages.find(x=>x.id===packageId);if(p)p.status='SHIPPED'}const order=this.state.salesOrders.find(x=>x.id===s.salesOrderId),shipped=this.state.shipments.filter(x=>x.salesOrderId===order.id&&['SHIPPED','CLOSED'].includes(x.status)).flatMap(x=>x.packageIds).length,total=order.items.reduce((n,x)=>n+x.quantity,0);order.status=shipped>=total?'FULFILLED':'PARTIALLY_FULFILLED'}if(action==='CLOSE')s.closedAt=this.clock();return s},{id,action,...input})}
  createInternalShipment(input,key){return this.run(key,'INTERNAL_SHIPMENT_CREATED',()=>{const ids=input.packageIds??[];if(!ids.length||!input.destinationSite)throw new DomainError('INTERNAL_SHIPMENT_FIELDS_REQUIRED','Destination site and packages are required',400);const packages=ids.map(id=>{const p=this.state.packages.find(x=>x.id===id);if(!p)throw new DomainError('PACKAGE_NOT_FOUND','Package not found',404);if(p.status!=='READY_TO_SHIP')throw new DomainError('PACKAGE_NOT_READY_TO_SHIP','Package must be ready',409);if(p.shipmentId)throw new DomainError('PACKAGE_ALREADY_SHIPPED','Package already assigned',409);return p});const s={id:randomUUID(),code:`IS-${this.site}-${String(this.state.shipments.length+1).padStart(6,'0')}`,kind:'INTERNAL_TRANSFER',destinationSite:input.destinationSite,packageIds:ids,status:'READY',createdAt:this.clock()};this.state.shipments.push(s);packages.forEach(p=>p.shipmentId=s.id);return s},input)}
  updateInternalShipment(id,action,key){return this.run(key,`INTERNAL_SHIPMENT_${action}`,()=>{const s=this.state.shipments.find(x=>x.id===id&&x.kind==='INTERNAL_TRANSFER');if(!s)throw new DomainError('INTERNAL_SHIPMENT_NOT_FOUND','Internal shipment not found',404);const next={READY:{LOAD:'LOADED',CANCEL:'CANCELLED'},LOADED:{DISPATCH:'DISPATCHED'},DISPATCHED:{DELIVER:'DELIVERED'}}[s.status]?.[action];if(!next)throw new DomainError('SHIPMENT_TRANSITION_INVALID','Invalid internal-shipment transition',409);s.status=next;s.updatedAt=this.clock();if(next==='DISPATCHED')for(const packageId of s.packageIds)this.state.packages.find(x=>x.id===packageId).status='SHIPPED';return s},{id,action})}
  packageItemsRecursive(packageId,seen=new Set()){if(seen.has(packageId))throw new DomainError('PACKAGE_HIERARCHY_CYCLE','Package hierarchy contains a cycle',409);seen.add(packageId);const p=this.state.packages.find(x=>x.id===packageId);if(!p)throw new DomainError('PACKAGE_NOT_FOUND','Package not found',404);const items=[...(p.items??[])];for(const childId of p.childPackageIds??[])items.push(...this.packageItemsRecursive(childId,new Set(seen)));return items}
  shipmentManifest(id){const s=this.state.shipments.find(x=>x.id===id);if(!s)throw new DomainError('SHIPMENT_NOT_FOUND','Shipment not found',404);return{manifestVersion:1,sourceSite:this.site,destinationSite:s.destinationSite,shipmentCode:s.code,status:s.status,packages:s.packageIds.map(id=>{const p=this.state.packages.find(x=>x.id===id),items=this.packageItemsRecursive(id);return{packageCode:p.code,type:p.type,items:items.map(x=>{const b=this.batch(x.batchId);return{batchCode:b.code,product:b.product,grade:b.grade,size:b.size,weightKg:x.weightKg}})}})}}
  receiveInternalTransfer(input,key){return this.run(key,'INTERNAL_TRANSFER_RECEIVED',()=>{this.requireSession(input.sessionId);const m=input.manifest;if(!m||m.destinationSite!==this.site)throw new DomainError('TRANSFER_DESTINATION_MISMATCH','Manifest destination does not match this site',403);if(m.status!=='DISPATCHED'&&m.status!=='DELIVERED')throw new DomainError('TRANSFER_NOT_DISPATCHED','Only dispatched manifests may be received',409);if(this.state.internalTransfers.some(x=>x.sourceSite===m.sourceSite&&x.shipmentCode===m.shipmentCode))throw new DomainError('TRANSFER_ALREADY_RECEIVED','Transfer already received',409);const manifestItems=(m.packages??[]).flatMap(p=>p.items??[]);if((m.packages??[]).length&&!manifestItems.length)throw new DomainError('TRANSFER_CONTENT_EMPTY','A non-empty shipment must contain transferable batch items',409);const validated=manifestItems.map(item=>{if(!(item.weightKg>0))throw new DomainError('TRANSFER_ITEM_INVALID','Transfer item weight must be positive',400);return{...item,product:this.reference('products',item.product),grade:this.reference('grades',item.grade),size:this.reference('sizes',item.size)}}),batches=[];for(const item of validated){const b={id:randomUUID(),code:`B-${this.site}-${String(this.state.batches.length+1).padStart(6,'0')}`,site:this.site,supplier:null,product:item.product.code,grade:item.grade.code,size:item.size.code,weightKg:Number(item.weightKg),zone:'RECEIVING',status:'RECEIVED',parentIds:[],externalParents:[{site:m.sourceSite,batchCode:item.batchCode}],sourceTransfer:m.shipmentCode,createdAt:this.clock()};this.state.batches.push(b);this.measure(b.id,b.weightKg,'INTERNAL_TRANSFER',input.sessionId);this.queuePrint('BATCH',b.id,b.code);batches.push(b)}const transfer={id:randomUUID(),sourceSite:m.sourceSite,shipmentCode:m.shipmentCode,receivedBy:input.receivedBy,manifest:structuredClone(m),batchIds:batches.map(x=>x.id),receivedAt:this.clock()};this.state.internalTransfers.push(transfer);return{transfer,batches};},input)}
  queuePrint(entityType,entityId,identity){let label=this.state.labels.find(x=>x.entityType===entityType&&x.entityId===entityId);if(!label){label={id:randomUUID(),entityType,entityId,identity,payload:{identity},status:'PENDING',createdAt:this.clock()};this.state.labels.push(label)}const attemptNo=1+this.state.printAttempts.filter(x=>x.labelId===label.id).length,attempt={id:randomUUID(),labelId:label.id,attemptNo,status:'PENDING',requestedAt:this.clock()};this.state.printAttempts.push(attempt);const j={id:attempt.id,labelId:label.id,entityType,entityId,label:identity,status:'PENDING',attempts:attemptNo-1,createdAt:attempt.requestedAt};this.state.printJobs.push(j);return j;}
  printSession(sessionId){if(!sessionId)throw new DomainError('DEVICE_SESSION_REQUIRED','Print operations require an active device session',400);return this.requireSession(sessionId)}
  completePrint(id,sessionId){const session=this.printSession(sessionId),j=this.state.printJobs.find(x=>x.id===id),attempt=this.state.printAttempts.find(x=>x.id===id);if(!j||!attempt)throw new DomainError('PRINT_JOB_NOT_FOUND','Print job not found',404);j.status='PRINTED';j.attempts=attempt.attemptNo;j.printedAt=this.clock();attempt.status='PRINTED';attempt.sessionId=session.id;attempt.deviceId=session.deviceId;attempt.completedAt=j.printedAt;this.record('LABEL_PRINTED',j.entityId,{attemptId:id,labelId:j.labelId},session.id);this.persist();return j;}
  failPrint(id,reason,sessionId){const session=this.printSession(sessionId),j=this.state.printJobs.find(x=>x.id===id),attempt=this.state.printAttempts.find(x=>x.id===id);if(!j||!attempt)throw new DomainError('PRINT_JOB_NOT_FOUND','Print job not found',404);if(j.status==='PRINTED')throw new DomainError('PRINT_ALREADY_COMPLETED','Printed job cannot fail',409);attempt.status='FAILED';attempt.sessionId=session.id;attempt.deviceId=session.deviceId;attempt.error=reason;attempt.completedAt=this.clock();j.attempts=attempt.attemptNo;j.lastError=reason;j.status='FAILED';j.updatedAt=this.clock();this.raiseExceptionRecord({type:'MISSING_OR_FAILED_LABEL',entityType:j.entityType,entityId:j.entityId,severity:'HIGH'});this.record('LABEL_PRINT_FAILED',j.entityId,{attemptId:id,labelId:j.labelId,reason},session.id);this.persist();return j;}
  retryPrint(id,verifiedScan,sessionId){const session=this.printSession(sessionId),j=this.state.printJobs.find(x=>x.id===id);if(!j)throw new DomainError('PRINT_JOB_NOT_FOUND','Print job not found',404);if(j.status!=='FAILED')throw new DomainError('PRINT_RETRY_INVALID','Only failed jobs can be retried',409);const label=this.state.labels.find(x=>x.id===j.labelId);if(verifiedScan!==label.identity)throw new DomainError('LABEL_SCAN_VERIFICATION_REQUIRED','Reprint requires scanning the existing label identity',409);const next=this.queuePrint(j.entityType,j.entityId,label.identity);const attempt=this.state.printAttempts.find(x=>x.id===next.id);attempt.sessionId=session.id;attempt.deviceId=session.deviceId;this.record('LABEL_PRINT_REQUEUED',j.entityId,{previousAttemptId:id,newAttemptId:next.id,labelId:label.id},session.id);this.persist();return next;}
  task(id){const task=this.state.tasks.find(x=>x.id===id);if(!task)throw new DomainError('TASK_NOT_FOUND','Task not found',404);return task}
  taskEligible(task,actor){const roles=actor.roles??[],skills=actor.skills??[];return(!task.requiredRole||roles.includes(task.requiredRole))&&(!task.requiredSkillId||skills.includes(task.requiredSkillId))&&(!task.dependsOnTaskId||this.state.tasks.find(x=>x.id===task.dependsOnTaskId)?.status==='COMPLETED')}
  createTask(input, key){return this.run(key,'TASK_CREATED',()=>{this.requireUuid(input.entityId,'entityId',{optional:true});this.requireUuid(input.requiredSkillId,'requiredSkillId',{optional:true});this.requireUuid(input.dependsOnTaskId,'dependsOnTaskId',{optional:true});if(!input.title?.trim()||!input.zone?.trim())throw new DomainError('TASK_FIELDS_REQUIRED','Task title and zone are required',400);if(input.dependsOnTaskId&&!this.state.tasks.some(x=>x.id===input.dependsOnTaskId))throw new DomainError('TASK_DEPENDENCY_NOT_FOUND','Task dependency not found',400);const task={id:randomUUID(),site:this.site,title:input.title.trim(),zone:input.zone.trim(),priority:Number(input.priority??50),status:'OPEN',assignedTo:input.assignedTo??null,entityId:input.entityId??null,requiredRole:input.requiredRole??null,requiredSkillId:input.requiredSkillId??null,dependsOnTaskId:input.dependsOnTaskId??null,stateHistory:[{from:null,to:'OPEN',action:'CREATE',at:this.clock()}],createdAt:this.clock()};this.state.tasks.push(task);return task;},input);}
  claimTask(id,actor,key){return this.run(key,'TASK_CLAIMED',()=>{const t=this.task(id),identity=typeof actor==='string'?{operatorId:actor,roles:[],skills:[]}:actor;if(t.status!=='OPEN')throw new DomainError('TASK_ALREADY_CLAIMED','Task is not open',409);if(!this.taskEligible(t,identity))throw new DomainError('TASK_NOT_ELIGIBLE','Operator lacks the required role/skill or a dependency is incomplete',403);t.stateHistory??=[];t.stateHistory.push({from:t.status,to:'IN_PROGRESS',action:'CLAIM',at:this.clock(),operatorId:identity.operatorId});t.status='IN_PROGRESS';t.assignedTo=identity.operatorId;t.claimedAt=this.clock();return t;},{id,operatorId:typeof actor==='string'?actor:actor.operatorId});}
  transitionTask(id,action,input,key){const actor=input.actor;return this.run(key,`TASK_${action}`,()=>{const t=this.task(id);if(actor&&(!this.taskEligible(t,actor)||t.assignedTo&&t.assignedTo!==actor.operatorId))throw new DomainError('TASK_NOT_ELIGIBLE','Only the assigned eligible operator may transition this task',403);const allowed={IN_PROGRESS:{COMPLETE:'COMPLETED',PAUSE:'PAUSED',FAIL:'FAILED'},PAUSED:{RESUME:'IN_PROGRESS'},FAILED:{REOPEN:'OPEN'}}[t.status]?.[action];if(!allowed)throw new DomainError('TASK_TRANSITION_INVALID',`Cannot ${action} a ${t.status} task`,409);if(action==='PAUSE'&&!input.reason?.trim())throw new DomainError('TASK_PAUSE_REASON_REQUIRED','Pause reason is required',400);if(action==='FAIL'&&!input.reason?.trim())throw new DomainError('TASK_FAIL_REASON_REQUIRED','Failure reason is required',400);const previous=t.status;t.status=allowed;t.updatedAt=this.clock();t.stateHistory??=[];t.stateHistory.push({from:previous,to:allowed,action,at:t.updatedAt,operatorId:actor?.operatorId??t.assignedTo});if(action==='COMPLETE')t.completedAt=this.clock();if(action==='PAUSE'){t.pausedAt=this.clock();t.pauseReason=input.reason.trim()}if(action==='FAIL'){t.failedAt=this.clock();t.failReason=input.reason.trim()}if(action==='RESUME'){t.pausedAt=null;t.pauseReason=null}if(action==='REOPEN'){t.failedAt=null;t.failReason=null;t.assignedTo=null;t.claimedAt=null}return t},{id,action,...input,actor:actor?{operatorId:actor.operatorId}:undefined});}
  reassignTask(id,input,key){return this.run(key,'TASK_REASSIGNED',()=>{const t=this.task(id);if(!['OPEN','IN_PROGRESS','PAUSED'].includes(t.status)||!input.operatorId)throw new DomainError('TASK_REASSIGN_INVALID','Active task and target operator are required',409);if(!this.taskEligible(t,input))throw new DomainError('TASK_NOT_ELIGIBLE','Target operator is not eligible',403);const previous=t.assignedTo;t.assignedTo=input.operatorId;t.reassignedFrom=previous;t.reassignedAt=this.clock();t.updatedAt=t.reassignedAt;t.stateHistory??=[];t.stateHistory.push({from:t.status,to:t.status,action:'REASSIGNED',fromOperatorId:previous,toOperatorId:input.operatorId,at:t.updatedAt});return t},{id,...input});}
  recommendedTask(actor){return this.state.tasks.filter(x=>x.status==='OPEN'&&this.taskEligible(x,actor)).sort((a,b)=>b.priority-a.priority||a.createdAt.localeCompare(b.createdAt))[0]??null}
  createQcChecklist(input,key){return this.run(key,'QC_CHECKLIST_CREATED',()=>{if(!input.code?.trim()||!input.product?.trim()||!input.stage?.trim()||!input.name?.trim()||!input.items?.length)throw new DomainError('QC_CHECKLIST_FIELDS_REQUIRED','Checklist identity, scope and items are required',400);if(this.state.qcChecklists.some(x=>x.code===input.code))throw new DomainError('QC_CHECKLIST_DUPLICATE','Checklist code already exists',409);const checklist={id:randomUUID(),code:input.code.trim(),product:input.product.trim(),stage:input.stage.trim(),name:input.name.trim(),active:true,items:input.items.map((x,i)=>({id:randomUUID(),code:String(x.code??'').trim(),prompt:String(x.prompt??'').trim(),required:x.required!==false,sequenceNo:i+1})),createdAt:this.clock()};if(checklist.items.some(x=>!x.code||!x.prompt)||new Set(checklist.items.map(x=>x.code)).size!==checklist.items.length)throw new DomainError('QC_CHECKLIST_ITEM_INVALID','Checklist items require unique codes and prompts',400);this.state.qcChecklists.push(checklist);return checklist},input)}
  qualityCheck(input,key){return this.run(key,'QUALITY_CHECK_RECORDED',()=>{const batch=this.batch(input.batchId);if(!['APPROVED','REJECTED','QUARANTINED'].includes(input.result))throw new DomainError('QUALITY_RESULT_INVALID','Invalid quality result',400);const checklist=this.state.qcChecklists.find(x=>x.id===input.checklistId&&x.active);if(!checklist||checklist.product!==batch.product||checklist.stage!==input.stage)throw new DomainError('QC_CHECKLIST_INVALID','An active checklist matching product and stage is required',400);const responses=input.responses??[],codes=new Set(responses.map(x=>x.itemCode));if(checklist.items.some(x=>x.required&&!codes.has(x.code)))throw new DomainError('QC_CHECKLIST_INCOMPLETE','Every required checklist item must be explicitly answered',400);if(input.attestation?.confirmed!==true||!input.attestation.role?.trim())throw new DomainError('QC_ATTESTATION_REQUIRED','Explicit confirmation and signing role are required',400);const q={id:randomUUID(),batchId:input.batchId,result:input.result,notes:input.notes??'',inspectorId:input.inspectorId,checklistId:checklist.id,responses:structuredClone(responses),attestation:{confirmed:true,role:input.attestation.role.trim(),signedAt:this.clock(),userId:input.inspectorId},createdAt:this.clock()};this.state.qualityChecks.push(q);if(input.result!=='APPROVED'&&input.createCorrectiveTask!==false){const task={id:randomUUID(),site:this.site,title:`QC rework: ${batch.code}`,zone:input.stage,priority:90,status:'OPEN',assignedTo:null,entityId:batch.id,requiredRole:input.reworkRole??null,requiredSkillId:null,dependsOnTaskId:null,createdAt:this.clock()};this.state.tasks.push(task);q.correctiveTaskId=task.id}if(input.result==='QUARANTINED'){const zone=this.reference('zones','QUARANTINE');batch.preQuarantineStatus=batch.status;batch.preQuarantineZone=batch.zone;batch.zone=zone.code;batch.zoneId=zone.id;batch.status='QUARANTINED';this.raiseExceptionRecord({type:'QUALITY_QUARANTINE',entityType:'BATCH',entityId:batch.id,severity:'HIGH'})}return q;},input)}
  releaseQuarantine(input,key){return this.run(key,'QUARANTINE_RELEASED',()=>{const b=this.batch(input.batchId);if(b.status!=='QUARANTINED'||b.zone!=='QUARANTINE')throw new DomainError('BATCH_NOT_QUARANTINED','Batch is not quarantined',409);if(!input.reason?.trim())throw new DomainError('RELEASE_REASON_REQUIRED','Release reason is required',400);const zone=this.reference('zones',input.destinationZone??b.preQuarantineZone??'COLD_ROOM'),q={id:randomUUID(),batchId:b.id,result:'APPROVED',notes:input.reason,inspectorId:input.inspectorId,createdAt:this.clock(),release:true};this.state.qualityChecks.push(q);b.zone=zone.code;b.zoneId=zone.id;b.status=b.preQuarantineStatus??'RECEIVED';delete b.preQuarantineStatus;delete b.preQuarantineZone;return q;},input)}
  adjustInventory(input,key){return this.run(key,'INVENTORY_ADJUSTED',()=>{const b=this.batch(input.batchId),delta=Number(input.deltaKg);if(!Number.isFinite(delta)||delta===0)throw new DomainError('ADJUSTMENT_INVALID','Adjustment must be non-zero',400);if(!input.reason?.trim())throw new DomainError('ADJUSTMENT_REASON_REQUIRED','Adjustment reason is required',400);if(b.weightKg+delta<0)throw new DomainError('INSUFFICIENT_INVENTORY','Adjustment would make inventory negative',409);const before=b.weightKg;b.weightKg=Number((before+delta).toFixed(3));if(b.weightKg===0)b.status=input.reasonCode==='WASTE'?'WASTED':'DEPLETED';if(input.reasonCode==='WASTE')b.zone='WASTE';const a={id:randomUUID(),batchId:b.id,beforeKg:before,deltaKg:delta,afterKg:b.weightKg,reasonCode:input.reasonCode??'CORRECTION',reason:input.reason,userId:input.userId,createdAt:this.clock()};this.state.inventoryAdjustments.push(a);return a;},input)}
  createConfiguration(input,key){return this.run(key,'CONFIGURATION_DRAFTED',()=>{const sequence=1+Math.max(0,...this.state.configurationVersions.filter(x=>x.scope===input.scope).map(x=>x.sequence));const version={id:randomUUID(),scope:input.scope,sequence,status:'DRAFT',values:structuredClone(input.values??{}),createdBy:input.userId,createdAt:this.clock()};this.state.configurationVersions.push(version);return version;},input)}
  transitionConfiguration(id,action,userId,key){return this.run(key,`CONFIGURATION_${action}`,()=>{const v=this.state.configurationVersions.find(x=>x.id===id);if(!v)throw new DomainError('CONFIGURATION_NOT_FOUND','Configuration version not found',404);const allowed={DRAFT:{APPROVE:'APPROVED'},APPROVED:{ACTIVATE:'ACTIVE'}};const next=allowed[v.status]?.[action];if(!next)throw new DomainError('CONFIGURATION_TRANSITION_INVALID',`Cannot ${action} ${v.status} configuration`,409);if(action==='APPROVE'&&v.createdBy===userId)throw new DomainError('SELF_APPROVAL_FORBIDDEN','Creator cannot approve own configuration',403);if(next==='ACTIVE')for(const old of this.state.configurationVersions.filter(x=>x.scope===v.scope&&x.status==='ACTIVE'))old.status='RETIRED';v.status=next;v.updatedBy=userId;v.updatedAt=this.clock();return v;},{id,action,userId})}
  requestOverride(input,key){return this.run(key,'OVERRIDE_REQUESTED',()=>{this.requireUuid(input.entityId,'entityId',{optional:true});if(!input.reason?.trim())throw new DomainError('OVERRIDE_REASON_REQUIRED','Override reason is required',400);const o={id:randomUUID(),ruleCode:input.ruleCode,entityId:input.entityId,reason:input.reason,requestedBy:input.requestedBy,status:'PENDING',createdAt:this.clock()};this.state.overrides.push(o);return o;},input)}
  resolveOverride(id,input,key){return this.run(key,'OVERRIDE_RESOLVED',()=>{const o=this.state.overrides.find(x=>x.id===id);if(!o)throw new DomainError('OVERRIDE_NOT_FOUND','Override not found',404);if(o.status!=='PENDING')throw new DomainError('OVERRIDE_ALREADY_RESOLVED','Override already resolved',409);if(o.requestedBy===input.resolvedBy)throw new DomainError('SELF_APPROVAL_FORBIDDEN','Requester cannot resolve own override',403);if(!['APPROVED','REJECTED'].includes(input.decision))throw new DomainError('OVERRIDE_DECISION_INVALID','Decision must be APPROVED or REJECTED',400);o.status=input.decision;o.resolvedBy=input.resolvedBy;o.resolutionNote=input.note??'';o.resolvedAt=this.clock();return o;},{id,...input})}
  inventory(){return this.state.batches.map(b=>({id:b.id,code:b.code,product:b.product,grade:b.grade,size:b.size,weightKg:b.weightKg,zone:b.zone,containerId:b.containerId??null,status:b.status,parentIds:b.parentIds,isAggregate:!!b.isAggregate}));}
  reports(){const inputKg=this.state.measurements.filter(x=>x.reason==='RECEIVING').reduce((n,x)=>n+x.weightKg,0),availableKg=this.state.batches.reduce((n,x)=>n+x.weightKg,0),completedCycles=this.state.cycles.filter(x=>x.status==='COMPLETED'),endedCycles=this.state.cycles.filter(x=>x.endedAt&&x.startedAt),openExceptions=this.state.exceptions.filter(x=>['OPEN','ASSIGNED'].includes(x.status)),machines={};for(const cycle of endedCycles){const minutes=(Date.parse(cycle.endedAt)-Date.parse(cycle.startedAt))/60000;machines[cycle.machineId]??={cycles:0,runtimeMinutes:0};machines[cycle.machineId].cycles++;machines[cycle.machineId].runtimeMinutes=Number((machines[cycle.machineId].runtimeMinutes+minutes).toFixed(2))}return{yield:{receivedKg:Number(inputKg.toFixed(3)),availableKg:Number(availableKg.toFixed(3)),yieldPercent:inputKg?Number((availableKg/inputKg*100).toFixed(2)):null},equipmentUtilization:{completedCycles:completedCycles.length,totalRuntimeMinutes:Number((endedCycles.reduce((n,x)=>n+Date.parse(x.endedAt)-Date.parse(x.startedAt),0)/60000).toFixed(2)),byMachine:machines},exceptions:{total:this.state.exceptions.length,open:openExceptions.length,resolved:this.state.exceptions.filter(x=>x.status==='RESOLVED').length,ratePer100Batches:this.state.batches.length?Number((this.state.exceptions.length/this.state.batches.length*100).toFixed(2)):0,byType:Object.fromEntries([...new Set(this.state.exceptions.map(x=>x.type))].map(type=>[type,this.state.exceptions.filter(x=>x.type===type).length]))},tasks:{open:this.state.tasks.filter(x=>x.status==='OPEN').length,inProgress:this.state.tasks.filter(x=>x.status==='IN_PROGRESS').length,completed:this.state.tasks.filter(x=>x.status==='COMPLETED').length,failed:this.state.tasks.filter(x=>x.status==='FAILED').length}}}
  trace(id){const root=this.batch(id);const ancestors=[];const visit=b=>{for(const pid of b.parentIds){const p=this.batch(pid);ancestors.push(p);visit(p);}};visit(root);return{batch:root,ancestors,measurements:this.state.measurements.filter(x=>x.batchId===id),movements:this.state.movements.filter(x=>x.batchId===id)};}
}
