import { randomUUID, createHash } from 'node:crypto';
import { AsyncLocalStorage } from 'node:async_hooks';
const PROCESS_RULES={SORT:{status:'SORTED',zone:'SORTING'},WASH:{status:'WASHED',zone:'WASHING'},SLICE:{status:'SLICED',zone:'SLICING'},FREEZE:{status:'FROZEN',zone:'FREEZING'},FREEZE_DRY:{status:'FREEZE_DRIED',zone:'FREEZE_DRYING'},DRY:{status:'DRIED',zone:'DRYING'},MERGE:{status:'MERGED',zone:'PROCESSING'}};
const CONTAINER_GATES={
  RECEIVE:{field:'containerId',types:['BASKET','CRATE'],zone:'RECEIVING',statuses:['AVAILABLE'],empty:true},
  SORT:{field:'containerId',types:['BASKET','CRATE'],zone:'COLD_ROOM',statuses:['IN_USE'],batchStatuses:['RECEIVED']},
  WASH:{field:'containerId',types:['BASKET','CRATE'],zone:'WASHING',statuses:['READY_FOR_WASHING'],batchStatuses:['SORTED']},
  SLICE:{field:'containerId',types:['BASKET','CRATE'],zone:'SLICING',statuses:['WASHED'],batchStatuses:['WASHED']},
  FREEZE:{field:'trayId',types:['TRAY'],zone:'FREEZING',statuses:['SLICED'],batchStatuses:['SLICED']},
  FREEZE_DRY:{field:'trayId',types:['TRAY'],zone:'FREEZE_DRYING',statuses:['FROZEN'],batchStatuses:['FROZEN']},
  DRY:{field:'containerId',types:['BASKET','CRATE','TRAY'],zone:'DRYING',statuses:['READY_FOR_DRYING'],batchStatuses:['SORTED']}
};
const CYCLE_TYPES=new Set(['FREEZE','FREEZE_DRY','DRY']);
const ACTIVE_CYCLE_STATUSES=new Set(['READY','LOADING','RUNNING','IN_PROGRESS','PAUSED','COMPLETING']);
const UUID_PATTERN=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const REFERENCE_TYPES=new Set(['products','suppliers','grades','sizes','zones','packageTypes']);
const DEMO_REFERENCES={products:['T','Truffle','Fruit'],suppliers:['S','S1'],grades:['A','B','UNSORTED'],sizes:['L','Large','MIXED','S','M'],zones:['RECEIVING','COLD_ROOM','SORTING','WASHING','SLICING','FREEZING','FREEZE_DRYING','DRYING','PROCESSING','PACKAGING','QC','QUARANTINE','WASTE'],packageTypes:['POUCH','CARTON','EPS','PALLET']};

export class DomainError extends Error {
  constructor(code, message, status = 422) { super(message); this.code = code; this.status = status; }
}

export class StoreMesh {
  constructor({ site = 'IRAN', clock = () => new Date().toISOString(), repository = null, initialState = null, seedDemoReferences = process.env.NODE_ENV!=='production', persistenceErrorLogger = error => console.error(JSON.stringify({level:'error',component:'persistence',errorCode:error.code??'PERSISTENCE_FAILED',message:error.message,at:new Date().toISOString()})) } = {}) {
    this.site = site; this.clock = clock;
    this.repository = repository;
    this.auditContext = new AsyncLocalStorage();
    this.pendingPersistence = Promise.resolve();
    this.lastPersistenceError = null;this.persistenceErrorLogger=persistenceErrorLogger;
    this.state = initialState || repository?.load() || { sessions: [], batches: [], measurements: [], movements: [], inventoryAdjustments: [], containers: [], cycles: [], packages: [], shipments: [], internalTransfers: [], labels: [], printAttempts: [], printJobs: [], audit: [], outbox: [], tasks: [], qualityChecks: [], exceptions: [], configurationVersions: [], overrides: [], idempotency: new Map(), idempotencyMeta: new Map() };
    if (this.state instanceof Promise) throw new Error('Async repositories must be loaded before constructing StoreMesh');
    this.state.tasks ??= []; this.state.qualityChecks ??= [];this.state.exceptions??=[];
    this.state.configurationVersions ??= []; this.state.overrides ??= []; this.state.containers ??= []; this.state.cycles ??= []; this.state.internalTransfers ??= []; this.state.inventoryAdjustments ??= [];this.state.labels??=[];this.state.printAttempts??=[];this.state.idempotencyMeta=this.state.idempotencyMeta instanceof Map?this.state.idempotencyMeta:new Map(this.state.idempotencyMeta??[]);
    this.state.masterData??=Object.fromEntries([...REFERENCE_TYPES].map(type=>[type,seedDemoReferences?(DEMO_REFERENCES[type]??[]).map(code=>({id:randomUUID(),code,name:code,status:'ACTIVE'})):[]]));
    this.lastDurableState=structuredClone(this.state);
  }
  persist() {
    if (!this.repository) return;
    if (this.repository.isAsync) {
      const snapshot = structuredClone({ ...this.state, idempotency: [...this.state.idempotency.entries()], idempotencyMeta:[...this.state.idempotencyMeta.entries()] });
      snapshot.idempotency = new Map(snapshot.idempotency);
      snapshot.idempotencyMeta = new Map(snapshot.idempotencyMeta);
      const write=this.pendingPersistence.then(async()=>{await this.repository.save(snapshot);this.lastDurableState=structuredClone(snapshot)});
      this.pendingPersistence=write.catch(error=>{this.state=structuredClone(this.lastDurableState);this.lastPersistenceError??=error;this.persistenceErrorLogger(error)});
    } else {const snapshot=structuredClone(this.state);try{this.repository.save(this.state);this.lastDurableState=snapshot}catch(error){this.state=structuredClone(this.lastDurableState);throw error}}
  }
  async flush() { await this.pendingPersistence;if(this.lastPersistenceError){const error=this.lastPersistenceError;this.lastPersistenceError=null;throw error} }
  withAuditContext(context,fn){return this.auditContext.run(context,fn)}
  requireUuid(value,field,{optional=false}={}){if((value===null||value===undefined||value==='')&&optional)return null;if(typeof value!=='string'||!UUID_PATTERN.test(value))throw new DomainError('UUID_INVALID',`${field} must be a valid UUID`,400);return value}
  reference(type,code){if(!REFERENCE_TYPES.has(type))throw new DomainError('MASTER_DATA_TYPE_INVALID','Unknown master-data type',400);const item=this.state.masterData[type].find(x=>x.code===code&&x.status==='ACTIVE');if(!item)throw new DomainError('MASTER_DATA_REFERENCE_INVALID',`${type} code ${code} is not active`,400);return item}
  createReference(type,input,key){return this.run(key,'MASTER_DATA_CREATED',()=>{if(!REFERENCE_TYPES.has(type))throw new DomainError('MASTER_DATA_TYPE_INVALID','Unknown master-data type',400);const code=String(input.code??'').trim();if(!code||!input.name?.trim())throw new DomainError('MASTER_DATA_FIELDS_REQUIRED','Code and name are required',400);if(this.state.masterData[type].some(x=>x.code===code))throw new DomainError('MASTER_DATA_CODE_DUPLICATE','Code already exists',409);const item={id:randomUUID(),code,name:input.name.trim(),status:'ACTIVE',createdAt:this.clock()};this.state.masterData[type].push(item);return item},input)}
  updateReference(type,id,input,key){return this.run(key,'MASTER_DATA_UPDATED',()=>{if(!REFERENCE_TYPES.has(type))throw new DomainError('MASTER_DATA_TYPE_INVALID','Unknown master-data type',400);const item=this.state.masterData[type].find(x=>x.id===id);if(!item)throw new DomainError('MASTER_DATA_NOT_FOUND','Reference item not found',404);if(input.name!==undefined)item.name=String(input.name).trim();if(input.status!==undefined){if(!['ACTIVE','INACTIVE'].includes(input.status))throw new DomainError('MASTER_DATA_STATUS_INVALID','Status must be ACTIVE or INACTIVE',400);item.status=input.status}item.updatedAt=this.clock();return item},{type,id,input})}
  raiseExceptionRecord(input){this.requireUuid(input.entityId,'entityId',{optional:true});const item={id:randomUUID(),type:input.type,entityType:input.entityType,entityId:input.entityId??null,severity:input.severity??'WARNING',status:'OPEN',assignedTo:null,raisedAt:this.clock()};if(!item.type||!item.entityType||!['INFO','WARNING','HIGH','CRITICAL'].includes(item.severity))throw new DomainError('EXCEPTION_FIELDS_INVALID','Exception type, entity type and valid severity are required',400);this.state.exceptions.push(item);return item}
  raiseException(input,key){return this.run(key,'EXCEPTION_RAISED',()=>this.raiseExceptionRecord(input),input)}
  assignException(id,input,key){return this.run(key,'EXCEPTION_ASSIGNED',()=>{const item=this.state.exceptions.find(x=>x.id===id);if(!item)throw new DomainError('EXCEPTION_NOT_FOUND','Exception not found',404);if(!['OPEN','ASSIGNED'].includes(item.status)||!input.assignedTo)throw new DomainError('EXCEPTION_ASSIGNMENT_INVALID','Only open exceptions may be assigned',409);item.status='ASSIGNED';item.assignedTo=input.assignedTo;return item},{id,...input})}
  resolveException(id,input,key){return this.run(key,'EXCEPTION_RESOLVED',()=>{const item=this.state.exceptions.find(x=>x.id===id);if(!item)throw new DomainError('EXCEPTION_NOT_FOUND','Exception not found',404);if(!['OPEN','ASSIGNED'].includes(item.status)||!['RESOLVED','DISMISSED'].includes(input.decision)||!input.resolutionNote?.trim())throw new DomainError('EXCEPTION_RESOLUTION_INVALID','Resolution requires a decision and note',409);item.status=input.decision;item.resolvedBy=input.resolvedBy;item.resolutionNote=input.resolutionNote.trim();item.resolvedAt=this.clock();return item},{id,...input})}
  run(key, action, fn, request = {}) {
    const now=Date.parse(this.clock());for(const[k,meta]of this.state.idempotencyMeta)if(Date.parse(meta.expiresAt)<=now){this.state.idempotencyMeta.delete(k);this.state.idempotency.delete(k)}
    if (!key) throw new DomainError('IDEMPOTENCY_KEY_REQUIRED', 'Idempotency-Key is required', 400);
    const requestHash=createHash('sha256').update(JSON.stringify(request)).digest('hex'),existing=this.state.idempotencyMeta.get(key);
    if(existing&&existing.requestHash!==requestHash)throw new DomainError('IDEMPOTENCY_PAYLOAD_MISMATCH','Idempotency key was already used with a different payload',409);
    if (this.state.idempotency.has(key)) return this.state.idempotency.get(key);
    try{const result = fn(); this.state.idempotency.set(key, result);this.state.idempotencyMeta.set(key,{requestHash,createdAt:this.clock(),expiresAt:new Date(Date.parse(this.clock())+7*86400000).toISOString()}); this.record(action, result.id,{},request.sessionId,null,'SUCCESS'); this.persist(); return result;}catch(error){this.record(action,null,{errorCode:error.code??'SYSTEM'},request.sessionId,null,'FAILURE');this.persist();throw error}
  }
  record(type, entityId, payload = {}, sessionId = null, explicitDeviceId = null, result='SUCCESS') {
    const context=this.auditContext.getStore()??{},session=sessionId?this.state.sessions.find(x=>x.id===sessionId):null,deviceId=explicitDeviceId??session?.deviceId??context.deviceId??'SYSTEM';
    const event = { id: randomUUID(), site: this.site, type, entityId, sessionId:session?.id??sessionId, deviceId, userId:context.userId??session?.operatorId??null,requestId:context.requestId??randomUUID(),ipAddress:context.ipAddress??null,result,payload,occurredAt: this.clock(), schemaVersion:1 };
    this.state.audit.push(event); this.state.outbox.push({ ...event, status: 'PENDING' }); return event;
  }
  openSession(operatorId, deviceId, station = 'terminal-01') {
    if(!deviceId?.trim())throw new DomainError('DEVICE_ID_REQUIRED','A registered originating device ID is required',400);
    const session = { id: randomUUID(), site: this.site, operatorId, deviceId:deviceId.trim(), station, status: 'ACTIVE', startedAt: this.clock(), updatedAt: this.clock() };
    this.state.sessions.push(session); this.record('SESSION_OPENED', session.id,{},session.id,session.deviceId); this.persist(); return session;
  }
  requireSession(id) {
    const s = this.state.sessions.find(x => x.id === id);
    if (!s) throw new DomainError('SESSION_NOT_FOUND', 'Session not found', 404);
    if (s.status !== 'ACTIVE') throw new DomainError('SESSION_NOT_ACTIVE', 'Session is not active', 409); return s;
  }
  updateSession(id, action) {
    const s=this.state.sessions.find(x=>x.id===id);if(!s)throw new DomainError('SESSION_NOT_FOUND','Session not found',404);
    const allowed={ACTIVE:{SUSPEND:'SUSPENDED',COMPLETE:'COMPLETED',CANCEL:'CANCELLED'},SUSPENDED:{RESUME:'ACTIVE',CANCEL:'CANCELLED'}};
    const next=allowed[s.status]?.[action];if(!next)throw new DomainError('SESSION_TRANSITION_INVALID',`Cannot ${action} a ${s.status} session`,409);
    s.status=next;s.updatedAt=this.clock();if(next!=='ACTIVE')for(const c of this.state.containers)if(c.activeSessionId===s.id)c.activeSessionId=null;if(['COMPLETED','CANCELLED'].includes(next))s.closedAt=this.clock();this.record(`SESSION_${next}`,s.id,{},s.id);this.persist();return s;
  }
  saveSessionDraft(id,draft){const s=this.requireSession(id);s.draft=structuredClone(draft??{});s.updatedAt=this.clock();this.record('SESSION_DRAFT_SAVED',s.id,{draft:s.draft},s.id);this.persist();return s}
  containerForOperation(operation,input,batchIds=[]){
    const gate=CONTAINER_GATES[operation],requiredZone=this.reference('zones',gate.zone),id=input[gate.field];
    if(!id)throw new DomainError(gate.field==='trayId'?'TRAY_SCAN_REQUIRED':'CONTAINER_SCAN_REQUIRED',`${gate.field} must come from a physical QR scan`,400);
    const c=this.state.containers.find(x=>x.id===id);if(!c)throw new DomainError(gate.field==='trayId'?'TRAY_NOT_FOUND':'CONTAINER_NOT_FOUND',`${gate.field==='trayId'?'Tray':'Container'} not found`,404);
    const session=this.requireSession(input.sessionId),owner=this.state.sessions.find(x=>x.id===c.activeSessionId&&x.status==='ACTIVE');
    if(c.locked)throw new DomainError('CONTAINER_LOCKED','Scanned container is locked',409);
    if(owner&&owner.id!==session.id)throw new DomainError('CONTAINER_ASSIGNED_TO_ACTIVE_SESSION',`Container is assigned to active session ${owner.id}`,409);
    if(!gate.types.includes(c.type))throw new DomainError('CONTAINER_TYPE_INVALID',`${operation} requires ${gate.types.join(' or ')}`,409);
    if(c.zoneId!==requiredZone.id&&c.zone!==requiredZone.code)throw new DomainError('CONTAINER_STAGE_INVALID',`${operation} requires container zone ${requiredZone.code}`,409);
    if(!gate.statuses.includes(c.status))throw new DomainError('CONTAINER_STATUS_INVALID',`${operation} requires container status ${gate.statuses.join(' or ')}`,409);
    if(gate.empty&&c.batchIds.length)throw new DomainError('CONTAINER_NOT_AVAILABLE','Receiving container is already in use',409);
    for(const batchId of batchIds){const b=this.batch(batchId);if(b.containerId!==c.id||!c.batchIds.includes(b.id))throw new DomainError('BATCH_CONTAINER_MISMATCH','Scanned container does not contain the requested batch',409);if(gate.batchStatuses&&!gate.batchStatuses.includes(b.status))throw new DomainError('BATCH_STAGE_INVALID',`${operation} does not allow batch status ${b.status}`,409)}
    c.activeSessionId=session.id;c.lastDeviceId=session.deviceId;return c;
  }
  receive(input, key) {
    return this.run(key, 'BATCH_RECEIVED', () => {
      const session=this.requireSession(input.sessionId),container=this.containerForOperation('RECEIVE',input);
      if (!input.supplier || !input.product || !input.grade || !input.size) throw new DomainError('RECEIVING_FIELDS_REQUIRED', 'Supplier, product, grade and size are required', 400);
      if (!(input.weightKg > 0)) throw new DomainError('WEIGHT_INVALID', 'Weight must be greater than zero', 400);
      if(Number(input.weightKg)>container.capacityKg){this.raiseExceptionRecord({type:'CAPACITY_EXCEEDED',entityType:'CONTAINER',entityId:container.id,severity:'HIGH'});throw new DomainError('CONTAINER_CAPACITY_EXCEEDED','Receiving weight exceeds scanned container capacity',409)}
      const product=this.reference('products',input.product),supplier=this.reference('suppliers',input.supplier),grade=this.reference('grades',input.grade),size=this.reference('sizes',input.size),zone=this.reference('zones','RECEIVING');const batch = { id: randomUUID(), code: `B-${this.site}-${String(this.state.batches.length + 1).padStart(6,'0')}`, site: this.site, supplier: supplier.code,supplierId:supplier.id, product:product.code,productId:product.id, grade:grade.code,gradeId:grade.id, size:size.code,sizeId:size.id, harvestPeriod: input.harvestPeriod ?? null, weightKg: input.weightKg, zone:zone.code,zoneId:zone.id, status: 'RECEIVED', containerId:container.id, sessionId:session.id, deviceId:session.deviceId, parentIds: [], configVersionId:this.activeConfigurationId('RECEIVING'), createdAt: this.clock() };
      container.batchIds.push(batch.id);container.status='IN_USE';
      this.state.batches.push(batch); this.measure(batch.id, input.weightKg, 'RECEIVING', input.sessionId);
      this.queuePrint('BATCH', batch.id, batch.code); return batch;
    },input);
  }
  measure(batchId, weightKg, reason, sessionId) {
    if (!(weightKg > 0)) throw new DomainError('WEIGHT_INVALID', 'Weight must be greater than zero', 400);
    const batch = this.batch(batchId),session=sessionId?this.requireSession(sessionId):null; const m = { id: randomUUID(), batchId, weightKg, reason, sessionId, deviceId:session?.deviceId??'SYSTEM', measuredAt: this.clock() };
    this.state.measurements.push(m); batch.weightKg = weightKg; return m;
  }
  batch(id) { const b = this.state.batches.find(x => x.id === id); if (!b) throw new DomainError('BATCH_NOT_FOUND', 'Batch not found', 404); return b; }
  move(batchId, zone, sessionId, key,overrideId=null) {
    return this.run(key, 'BATCH_MOVED', () => { const session=this.requireSession(sessionId),targetZone=this.reference('zones',zone); const b = this.batch(batchId),from=b.zone;if(from==='COLD_ROOM'&&zone!=='COLD_ROOM'){const eligible=this.state.batches.filter(x=>x.zone==='COLD_ROOM'&&x.product===b.product&&x.grade===b.grade&&x.size===b.size&&x.weightKg>0&&x.status!=='QUARANTINED').sort((a,z)=>a.createdAt.localeCompare(z.createdAt)),rank=eligible.findIndex(x=>x.id===b.id)+1,deviation=rank>1;if(deviation){this.record('FIFO_DEVIATION',b.id,{recommendedBatchId:eligible[0].id,recommendedBatchCode:eligible[0].code,actualRank:rank,scope:{product:b.product,grade:b.grade,size:b.size}},session.id,null,'WARNING');this.raiseExceptionRecord({type:'FIFO_DEVIATION',entityType:'BATCH',entityId:b.id,severity:'WARNING'})}b.zone=targetZone.code;b.zoneId=targetZone.id;const m={id:randomUUID(),batchId,sessionId,deviceId:session.deviceId,from,to:targetZone.code,overrideId:null,fifoRank:rank||null,fifoWarning:deviation,recommendedBatchId:deviation?eligible[0].id:null,movedAt:this.clock()};this.state.movements.push(m);return m}b.zone=targetZone.code;b.zoneId=targetZone.id;const m = { id: randomUUID(), batchId, sessionId, deviceId:session.deviceId, from, to: targetZone.code, overrideId:null,fifoRank:null,fifoWarning:false,movedAt: this.clock() }; this.state.movements.push(m); return m; },{batchId,zone,sessionId,overrideId});
  }
  createContainer(input,key){return this.run(key,'CONTAINER_CREATED',()=>{if(!(input.capacityKg>0))throw new DomainError('CONTAINER_CAPACITY_INVALID','Container capacity must be positive',400);const type=(input.type??'BASKET').toUpperCase();if(!['BASKET','CRATE','TRAY'].includes(type))throw new DomainError('CONTAINER_TYPE_INVALID','Container type must be BASKET, CRATE or TRAY',400);const zone=this.reference('zones',input.zone??'RECEIVING'),c={id:randomUUID(),code:`C-${this.site}-${String(this.state.containers.length+1).padStart(6,'0')}`,type,stage:input.stage??'PRE_SORT',capacityKg:Number(input.capacityKg),zone:zone.code,zoneId:zone.id,status:'AVAILABLE',locked:false,activeSessionId:null,batchIds:[],createdAt:this.clock()};this.state.containers.push(c);this.queuePrint('CONTAINER',c.id,c.code);return c;},input);}
  assignBatchToContainer(containerId,batchId,sessionId,key){return this.run(key,'BATCH_ASSIGNED_TO_CONTAINER',()=>{const session=this.requireSession(sessionId),c=this.state.containers.find(x=>x.id===containerId);if(!c)throw new DomainError('CONTAINER_NOT_FOUND','Container not found',404);const owner=this.state.sessions.find(x=>x.id===c.activeSessionId&&x.status==='ACTIVE');if(c.locked)throw new DomainError('CONTAINER_LOCKED','Container is locked',409);if(owner&&owner.id!==session.id)throw new DomainError('CONTAINER_ASSIGNED_TO_ACTIVE_SESSION','Container belongs to another active session',409);const b=this.batch(batchId),existing=c.batchIds.map(id=>this.batch(id));if(c.stage==='PRE_SORT'&&existing.some(x=>x.product!==b.product))throw new DomainError('CONTAINER_SINGLE_PRODUCT_RULE','Pre-sort container may hold only one product',409);const used=existing.reduce((n,x)=>n+x.weightKg,0);if(used+b.weightKg>c.capacityKg){this.raiseExceptionRecord({type:'CAPACITY_EXCEEDED',entityType:'CONTAINER',entityId:c.id,severity:'HIGH'});throw new DomainError('CONTAINER_CAPACITY_EXCEEDED','Container capacity exceeded',409)}if(b.containerId&&b.containerId!==c.id){const old=this.state.containers.find(x=>x.id===b.containerId);if(old){old.batchIds=old.batchIds.filter(id=>id!==b.id);if(!old.batchIds.length){old.status='AVAILABLE';old.activeSessionId=null}}}if(!c.batchIds.includes(b.id))c.batchIds.push(b.id);b.containerId=c.id;b.zone=c.zone;b.zoneId=c.zoneId;c.activeSessionId=session.id;c.lastDeviceId=session.deviceId;c.status=c.zone==='WASHING'&&b.status==='SORTED'?'READY_FOR_WASHING':c.zone==='DRYING'&&b.status==='SORTED'?'READY_FOR_DRYING':['WASHED','SLICED','FROZEN'].includes(b.status)?b.status:'IN_USE';return c;},{containerId,batchId,sessionId});}
  moveContainer(containerId,zone,sessionId,key){return this.run(key,'CONTAINER_MOVED',()=>{const session=this.requireSession(sessionId),targetZone=this.reference('zones',zone),c=this.state.containers.find(x=>x.id===containerId);if(!c)throw new DomainError('CONTAINER_NOT_FOUND','Container not found',404);const owner=this.state.sessions.find(x=>x.id===c.activeSessionId&&x.status==='ACTIVE');if(c.locked)throw new DomainError('CONTAINER_LOCKED','Container is locked',409);if(owner&&owner.id!==session.id)throw new DomainError('CONTAINER_ASSIGNED_TO_ACTIVE_SESSION','Container belongs to another active session',409);const from=c.zone;c.zone=targetZone.code;c.zoneId=targetZone.id;c.activeSessionId=session.id;c.lastDeviceId=session.deviceId;for(const id of c.batchIds){const b=this.batch(id),batchFrom=b.zone;b.zone=targetZone.code;b.zoneId=targetZone.id;this.state.movements.push({id:randomUUID(),batchId:id,containerId:c.id,sessionId,deviceId:session.deviceId,from:batchFrom,to:targetZone.code,movedAt:this.clock()})}const statuses=new Set(c.batchIds.map(id=>this.batch(id).status));if(zone==='WASHING'&&statuses.has('SORTED'))c.status='READY_FOR_WASHING';else if(zone==='DRYING'&&statuses.has('SORTED'))c.status='READY_FOR_DRYING';else if(zone==='SLICING'&&statuses.has('WASHED'))c.status='WASHED';else if(zone==='FREEZING'&&statuses.has('SLICED'))c.status='SLICED';else if(zone==='FREEZE_DRYING'&&statuses.has('FROZEN'))c.status='FROZEN';return{id:randomUUID(),containerId:c.id,sessionId,deviceId:session.deviceId,from,to:targetZone.code,movedAt:this.clock()};},{containerId,zone,sessionId});}
  transform(input, key) {
    return this.run(key, 'BATCH_TRANSFORMED', () => {
      const session=this.requireSession(input.sessionId);
      const rule=PROCESS_RULES[input.process];if(!rule)throw new DomainError('PROCESS_NOT_SUPPORTED','Unsupported production process',400);
      if(CYCLE_TYPES.has(input.process))throw new DomainError('CYCLE_WORKFLOW_REQUIRED',`${input.process} must be performed through a machine cycle; batch identity may not be replaced`,409);
      const requestedInputs = input.inputs?.length ? input.inputs : (input.parentIds ?? []).map(batchId => ({ batchId, consumeWeightKg:this.batch(batchId).weightKg }));
      if (!requestedInputs.length) throw new DomainError('PARENTS_REQUIRED','At least one input is required',400);
      const inputs = requestedInputs.map(x => ({ batch:this.batch(x.batchId), consumeWeightKg:Number(x.consumeWeightKg) }));
      const container=input.process==='MERGE'?null:this.containerForOperation(input.process,input,inputs.map(x=>x.batch.id));
      for (const x of inputs) if (!(x.consumeWeightKg > 0) || x.consumeWeightKg > x.batch.weightKg) throw new DomainError('INSUFFICIENT_INVENTORY','Input exceeds available batch weight',409);
      const inputWeight = inputs.reduce((n,x)=>n+x.consumeWeightKg,0);
      if (!(input.outputWeightKg > 0) || input.outputWeightKg > inputWeight) throw new DomainError('OUTPUT_WEIGHT_INVALID','Output weight exceeds consumed input',409);
      const parents=inputs.map(x=>x.batch);
      const product=this.reference('products',input.product??parents[0].product),grade=this.reference('grades',input.grade??parents[0].grade),size=this.reference('sizes',input.size??parents[0].size),zone=this.reference('zones',input.zone??rule.zone);const child = { id:randomUUID(), code:`B-${this.site}-${String(this.state.batches.length+1).padStart(6,'0')}`, site:this.site, supplier:null,supplierId:null, product:product.code,productId:product.id, grade:grade.code,gradeId:grade.id, size:size.code,sizeId:size.id, weightKg:input.outputWeightKg, zone:zone.code,zoneId:zone.id, status:rule.status, containerId:container?.id??null,sessionId:session.id,deviceId:session.deviceId,parentIds:input.parentIds, relationshipType:input.process==='MERGE'?'MERGE':'PROCESS', process:input.process, configVersionId:this.activeConfigurationId('PRODUCTION'), createdAt:this.clock() };
      child.parentIds=parents.map(x=>x.id); child.inputWeightKg=inputWeight; child.processLossKg=inputWeight-input.outputWeightKg;
      for(const x of inputs){x.batch.weightKg=Number((x.batch.weightKg-x.consumeWeightKg).toFixed(3));if(x.batch.weightKg===0)x.batch.status='CONSUMED';}
      if(container){container.batchIds=container.batchIds.filter(id=>!inputs.some(x=>x.batch.id===id&&x.batch.weightKg===0));if(!container.batchIds.includes(child.id))container.batchIds.push(child.id);container.status=rule.status;container.zone=rule.zone;container.activeSessionId=session.id;container.lastDeviceId=session.deviceId}
      this.state.batches.push(child); this.measure(child.id,input.outputWeightKg,input.process,input.sessionId); this.queuePrint('BATCH',child.id,child.code); return child;
    },input);
  }
  createCycle(input,key){
    return this.run(key,'CYCLE_CREATED',()=>{
      const type=String(input.type??'').toUpperCase();if(!CYCLE_TYPES.has(type))throw new DomainError('CYCLE_TYPE_INVALID','Cycle type must be FREEZE, FREEZE_DRY or DRY',400);
      const session=this.requireSession(input.sessionId);if(!input.machineId?.trim())throw new DomainError('MACHINE_ID_REQUIRED','A physical machine ID is required',400);
      const scanned=type==='DRY'?(input.containerIds??[]):(input.trayIds??[]);if(!Array.isArray(scanned)||!scanned.length)throw new DomainError(type==='DRY'?'CONTAINER_SCAN_REQUIRED':'TRAY_SCAN_REQUIRED','At least one physical container must be scanned',400);
      if(new Set(scanned).size!==scanned.length)throw new DomainError('CYCLE_CONTAINER_DUPLICATE','A container may only be scanned once into a cycle',409);
      const containers=scanned.map(id=>this.containerForOperation(type,{sessionId:session.id,[CONTAINER_GATES[type].field]:id},[]));
      for(const c of containers){
        if(this.state.cycles.some(x=>ACTIVE_CYCLE_STATUSES.has(x.status)&&x.containerIds.includes(c.id)))throw new DomainError('CONTAINER_ACTIVE_CYCLE','Container is already assigned to another active cycle',409);
        if(!c.batchIds.length)throw new DomainError('CYCLE_CONTAINER_EMPTY','Scanned container has no production batch',409);
        if(type!=='DRY'&&c.batchIds.length!==1)throw new DomainError('TRAY_SINGLE_BATCH_REQUIRED','Each freeze or freeze-dry tray must contain exactly one batch',409);
        for(const batchId of c.batchIds)this.containerForOperation(type,{sessionId:session.id,[CONTAINER_GATES[type].field]:c.id},[batchId]);
      }
      const batchIds=[...new Set(containers.flatMap(c=>c.batchIds))],prefix={FREEZE:'FC',FREEZE_DRY:'FDC',DRY:'DC'}[type],cycle={id:randomUUID(),code:`${prefix}-${this.clock().slice(0,10).replaceAll('-','')}-${String(this.state.cycles.filter(x=>x.type===type).length+1).padStart(3,'0')}`,type,machineId:input.machineId.trim(),sessionId:session.id,deviceId:session.deviceId,operatorId:session.operatorId,containerIds:containers.map(c=>c.id),batchIds,status:'READY',stateHistory:[{from:null,to:'READY',action:'CREATE',at:this.clock(),sessionId:session.id,deviceId:session.deviceId}],configVersionId:this.activeConfigurationId(type),createdAt:this.clock(),updatedAt:this.clock()};
      this.state.cycles.push(cycle);for(const c of containers){c.activeCycleId=cycle.id;c.activeSessionId=session.id}return cycle;
    },input);
  }
  transitionCycle(id,action,input,key){
    return this.run(key,`CYCLE_${action}`,()=>{
      const cycle=this.state.cycles.find(x=>x.id===id);if(!cycle)throw new DomainError('CYCLE_NOT_FOUND','Cycle not found',404);const session=this.requireSession(input.sessionId);
      const running=cycle.type==='DRY'?'IN_PROGRESS':'RUNNING',allowed={READY:{START:running,CANCEL:'CANCELLED'},RUNNING:{PAUSE:'PAUSED',COMPLETE:'COMPLETING',FAIL:'FAILED'},IN_PROGRESS:{PAUSE:'PAUSED',COMPLETE:'COMPLETING',FAIL:'FAILED'},PAUSED:{RESUME:running,FAIL:'FAILED',CANCEL:'CANCELLED'},COMPLETING:{FINISH:'COMPLETED',FAIL:'FAILED'}};
      const next=allowed[cycle.status]?.[action];if(!next)throw new DomainError('CYCLE_TRANSITION_INVALID',`Cannot ${action} a ${cycle.status} ${cycle.type} cycle`,409);
      if(action==='FINISH'){
        const finalWeights=input.finalWeights??{};
        if(cycle.type!=='FREEZE')for(const batchId of cycle.batchIds){const weight=Number(finalWeights[batchId]);if(!(weight>0)||weight>this.batch(batchId).weightKg)throw new DomainError('CYCLE_FINAL_WEIGHT_REQUIRED','A valid final weight is required for every batch before unload',400);}
        for(const batchId of cycle.batchIds){const b=this.batch(batchId),before=b.weightKg;if(cycle.type!=='FREEZE'){this.measure(batchId,Number(finalWeights[batchId]),cycle.type,session.id);b.yieldPercent=Number((b.weightKg/before*100).toFixed(2));b.status=cycle.type==='FREEZE_DRY'?'FREEZE_DRIED':'DRIED';b.zone='PACKAGING';const task={id:randomUUID(),site:this.site,title:`Package ${b.code}`,zone:'PACKAGING',priority:'NORMAL',status:'OPEN',assignedTo:null,entityId:b.id,createdAt:this.clock()};this.state.tasks.push(task)}else{b.status='FROZEN';b.zone='FREEZE_DRYING';}}
      }
      const from=cycle.status;cycle.status=next;cycle.updatedAt=this.clock();cycle.stateHistory.push({from,to:next,action,at:this.clock(),sessionId:session.id,deviceId:session.deviceId});if(action==='START')cycle.startedAt=this.clock();
      if(next==='FAILED')this.raiseExceptionRecord({type:'EQUIPMENT_CYCLE_FAILURE',entityType:'CYCLE',entityId:cycle.id,severity:'CRITICAL'});
      if(['COMPLETED','FAILED','CANCELLED'].includes(next)){cycle.endedAt=this.clock();for(const c of this.state.containers.filter(x=>cycle.containerIds.includes(x.id))){c.activeCycleId=null;c.activeSessionId=null;if(next==='COMPLETED')c.status=cycle.type==='FREEZE'?'FROZEN':'READY_FOR_PACKAGING';}}
      return cycle;
    },{id,action,...input});
  }
  sortBatch(input,key){return this.run(key,'BATCH_SORTED',()=>{const session=this.requireSession(input.sessionId),parent=this.batch(input.batchId),container=this.containerForOperation('SORT',input,[parent.id]),outputs=input.outputs??[];if(!outputs.length)throw new DomainError('SORT_OUTPUTS_REQUIRED','Sorting requires outputs',400);const total=outputs.reduce((n,x)=>n+Number(x.weightKg),0);if(!(total>0)||total>parent.weightKg)throw new DomainError('SORT_WEIGHT_INVALID','Sorted output exceeds available weight',409);const children=outputs.map(x=>{if(!(x.weightKg>0)||!x.grade||!x.size)throw new DomainError('SORT_OUTPUT_INVALID','Every output needs positive weight, grade and size',400);const child={id:randomUUID(),code:`B-${this.site}-${String(this.state.batches.length+1).padStart(6,'0')}`,site:this.site,supplier:null,product:parent.product,grade:x.grade,size:x.size,weightKg:Number(x.weightKg),zone:x.zone??'SORTING',status:'SORTED',sessionId:session.id,deviceId:session.deviceId,parentIds:[parent.id],relationshipType:'GRADE_SPLIT',process:'SORT',configVersionId:this.activeConfigurationId('SORTING'),createdAt:this.clock()};this.state.batches.push(child);this.measure(child.id,child.weightKg,'SORT',input.sessionId);this.queuePrint('BATCH',child.id,child.code);return child});parent.weightKg=Number((parent.weightKg-total).toFixed(3));if(parent.weightKg===0){parent.status='CONSUMED';container.batchIds=container.batchIds.filter(id=>id!==parent.id)}container.status='SORTED';container.zone='SORTING';container.activeSessionId=session.id;container.lastDeviceId=session.deviceId;return{children,remainingWeightKg:parent.weightKg,lossKg:Number(input.lossKg??0),containerId:container.id};},input);}
  createPackage(input, key) {
    return this.run(key, 'PACKAGE_CREATED', () => { this.requireSession(input.sessionId);const requested=input.items??[],childIds=input.childPackageIds??[];if(!requested.length&&!childIds.length)throw new DomainError('PACKAGE_EMPTY','Package needs inventory items or child packages',400);if(requested.length&&childIds.length)throw new DomainError('PACKAGE_CONTENT_MIXED','A package cannot mix loose inventory and child packages',400);const level=input.level??'CARTON',rank={UNIT:0,CARTON:1,EPS:2,PALLET:3},children=childIds.map(id=>{const child=this.state.packages.find(x=>x.id===id);if(!child)throw new DomainError('PACKAGE_NOT_FOUND','Child package not found',404);if(child.parentPackageId)throw new DomainError('PACKAGE_ALREADY_NESTED','Child package already belongs to a parent',409);if(rank[child.level]>=rank[level])throw new DomainError('PACKAGE_HIERARCHY_INVALID','Child package level must be lower than parent level',409);if(child.status!=='READY_TO_SHIP')throw new DomainError('CHILD_PACKAGE_NOT_READY','Child package must be ready before nesting',409);return child}),items=requested.map(x=>{const batch=this.batch(x.batchId),weightKg=Number(x.weightKg);if(!(weightKg>0)||weightKg>batch.weightKg)throw new DomainError('INSUFFICIENT_INVENTORY','Package item exceeds available batch weight',409);return{batch,weightKg}});for(const x of items){x.batch.weightKg=Number((x.batch.weightKg-x.weightKg).toFixed(3));if(x.batch.weightKg===0)x.batch.status='PACKAGED';}const p={id:randomUUID(),code:`P-${this.site}-${String(this.state.packages.length+1).padStart(6,'0')}`,type:input.type,level,parentPackageId:null,childPackageIds:[...childIds],items:items.map(x=>({batchId:x.batch.id,weightKg:x.weightKg})),status:'DRAFT',configVersionId:this.activeConfigurationId('PACKAGING'),createdAt:this.clock()};for(const child of children)child.parentPackageId=p.id;this.state.packages.push(p);return p; },input);
  }
  transitionPackage(id,action,key){return this.run(key,`PACKAGE_${action}`,()=>{const p=this.state.packages.find(x=>x.id===id);if(!p)throw new DomainError('PACKAGE_NOT_FOUND','Package not found',404);const allowed={DRAFT:{PACK:'PACKING'},PACKING:{SEAL:'READY_FOR_LABEL'},READY_FOR_LABEL:{PRINT:'PRINTING'},PRINTING:{PRINT_SUCCESS:'LABEL_PRINTED',PRINT_FAIL:'LABEL_PENDING'},LABEL_PENDING:{RETRY:'PRINTING'},LABEL_PRINTED:{READY:'READY_TO_SHIP'},READY_TO_SHIP:{SHIP:'SHIPPED'}};const next=allowed[p.status]?.[action];if(!next)throw new DomainError('PACKAGE_TRANSITION_INVALID',`Cannot ${action} a ${p.status} package`,409);p.status=next;p.updatedAt=this.clock();if(next==='READY_FOR_LABEL')this.queuePrint('PACKAGE',p.id,p.code);return p;},{id,action});}
  activeConfigurationId(scope){return this.state.configurationVersions.find(x=>x.scope===scope&&x.status==='ACTIVE')?.id??null}
  createShipment(input, key) {
    return this.run(key, 'SHIPMENT_CREATED', () => { const ids=input.packageIds ?? []; if(!ids.length) throw new DomainError('SHIPMENT_EMPTY','Shipment needs packages',400); const packages=ids.map(id=>{const p=this.state.packages.find(x=>x.id===id); if(!p) throw new DomainError('PACKAGE_NOT_FOUND','Package not found',404); if(p.status!=='READY_TO_SHIP')throw new DomainError('PACKAGE_NOT_READY_TO_SHIP','Package must complete labeling before shipment',409);if(p.shipmentId) throw new DomainError('PACKAGE_ALREADY_SHIPPED','Package already assigned',409); return p;}); const s={id:randomUUID(),code:`S-${this.site}-${String(this.state.shipments.length+1).padStart(6,'0')}`,destinationSite:input.destinationSite,packageIds:ids,status:'READY',createdAt:this.clock()}; this.state.shipments.push(s); packages.forEach(p=>p.shipmentId=s.id); return s; },input);
  }
  updateShipment(id, action, key){return this.run(key,`SHIPMENT_${action}`,()=>{const s=this.state.shipments.find(x=>x.id===id);if(!s)throw new DomainError('SHIPMENT_NOT_FOUND','Shipment not found',404);const allowed={READY:{LOAD:'LOADED',CANCEL:'CANCELLED'},LOADED:{DISPATCH:'DISPATCHED'},DISPATCHED:{DELIVER:'DELIVERED'}};const next=allowed[s.status]?.[action];if(!next)throw new DomainError('SHIPMENT_TRANSITION_INVALID',`Cannot ${action} a ${s.status} shipment`,409);s.status=next;s.updatedAt=this.clock();if(next==='DISPATCHED'){const mark=id=>{const p=this.state.packages.find(x=>x.id===id);p.status='SHIPPED';for(const childId of p.childPackageIds??[])mark(childId)};for(const packageId of s.packageIds)mark(packageId)}return s;});}
  shipmentManifest(id){const s=this.state.shipments.find(x=>x.id===id);if(!s)throw new DomainError('SHIPMENT_NOT_FOUND','Shipment not found',404);return{manifestVersion:1,sourceSite:this.site,destinationSite:s.destinationSite,shipmentCode:s.code,status:s.status,packages:s.packageIds.map(id=>{const p=this.state.packages.find(x=>x.id===id);return{packageCode:p.code,type:p.type,items:p.items.map(x=>{const b=this.batch(x.batchId);return{batchCode:b.code,product:b.product,grade:b.grade,size:b.size,weightKg:x.weightKg}})}})}}
  receiveInternalTransfer(input,key){return this.run(key,'INTERNAL_TRANSFER_RECEIVED',()=>{this.requireSession(input.sessionId);const m=input.manifest;if(!m||m.destinationSite!==this.site)throw new DomainError('TRANSFER_DESTINATION_MISMATCH','Manifest destination does not match this site',403);if(m.status!=='DISPATCHED'&&m.status!=='DELIVERED')throw new DomainError('TRANSFER_NOT_DISPATCHED','Only dispatched manifests may be received',409);if(this.state.internalTransfers.some(x=>x.sourceSite===m.sourceSite&&x.shipmentCode===m.shipmentCode))throw new DomainError('TRANSFER_ALREADY_RECEIVED','Transfer already received',409);const batches=[];for(const p of m.packages??[])for(const item of p.items??[]){if(!(item.weightKg>0))throw new DomainError('TRANSFER_ITEM_INVALID','Transfer item weight must be positive',400);const b={id:randomUUID(),code:`B-${this.site}-${String(this.state.batches.length+1).padStart(6,'0')}`,site:this.site,supplier:null,product:item.product,grade:item.grade,size:item.size,weightKg:Number(item.weightKg),zone:'RECEIVING',status:'RECEIVED',parentIds:[],externalParents:[{site:m.sourceSite,batchCode:item.batchCode}],sourceTransfer:m.shipmentCode,createdAt:this.clock()};this.state.batches.push(b);this.measure(b.id,b.weightKg,'INTERNAL_TRANSFER',input.sessionId);this.queuePrint('BATCH',b.id,b.code);batches.push(b)}const transfer={id:randomUUID(),sourceSite:m.sourceSite,shipmentCode:m.shipmentCode,receivedBy:input.receivedBy,manifest:structuredClone(m),batchIds:batches.map(x=>x.id),receivedAt:this.clock()};this.state.internalTransfers.push(transfer);return{transfer,batches};});}
  queuePrint(entityType,entityId,identity){let label=this.state.labels.find(x=>x.entityType===entityType&&x.entityId===entityId);if(!label){label={id:randomUUID(),entityType,entityId,identity,payload:{identity},status:'PENDING',createdAt:this.clock()};this.state.labels.push(label)}const attemptNo=1+this.state.printAttempts.filter(x=>x.labelId===label.id).length,attempt={id:randomUUID(),labelId:label.id,attemptNo,status:'PENDING',requestedAt:this.clock()};this.state.printAttempts.push(attempt);const j={id:attempt.id,labelId:label.id,entityType,entityId,label:identity,status:'PENDING',attempts:attemptNo-1,createdAt:attempt.requestedAt};this.state.printJobs.push(j);return j;}
  printSession(sessionId){if(!sessionId)throw new DomainError('DEVICE_SESSION_REQUIRED','Print operations require an active device session',400);return this.requireSession(sessionId)}
  completePrint(id,sessionId){const session=this.printSession(sessionId),j=this.state.printJobs.find(x=>x.id===id),attempt=this.state.printAttempts.find(x=>x.id===id);if(!j||!attempt)throw new DomainError('PRINT_JOB_NOT_FOUND','Print job not found',404);j.status='PRINTED';j.attempts=attempt.attemptNo;j.printedAt=this.clock();attempt.status='PRINTED';attempt.sessionId=session.id;attempt.deviceId=session.deviceId;attempt.completedAt=j.printedAt;this.record('LABEL_PRINTED',j.entityId,{attemptId:id,labelId:j.labelId},session.id);this.persist();return j;}
  failPrint(id,reason,sessionId){const session=this.printSession(sessionId),j=this.state.printJobs.find(x=>x.id===id),attempt=this.state.printAttempts.find(x=>x.id===id);if(!j||!attempt)throw new DomainError('PRINT_JOB_NOT_FOUND','Print job not found',404);if(j.status==='PRINTED')throw new DomainError('PRINT_ALREADY_COMPLETED','Printed job cannot fail',409);attempt.status='FAILED';attempt.sessionId=session.id;attempt.deviceId=session.deviceId;attempt.error=reason;attempt.completedAt=this.clock();j.attempts=attempt.attemptNo;j.lastError=reason;j.status='FAILED';j.updatedAt=this.clock();this.record('LABEL_PRINT_FAILED',j.entityId,{attemptId:id,labelId:j.labelId,reason},session.id);this.persist();return j;}
  retryPrint(id,verifiedScan,sessionId){const session=this.printSession(sessionId),j=this.state.printJobs.find(x=>x.id===id);if(!j)throw new DomainError('PRINT_JOB_NOT_FOUND','Print job not found',404);if(j.status!=='FAILED')throw new DomainError('PRINT_RETRY_INVALID','Only failed jobs can be retried',409);const label=this.state.labels.find(x=>x.id===j.labelId);if(verifiedScan!==label.identity)throw new DomainError('LABEL_SCAN_VERIFICATION_REQUIRED','Reprint requires scanning the existing label identity',409);const next=this.queuePrint(j.entityType,j.entityId,label.identity);const attempt=this.state.printAttempts.find(x=>x.id===next.id);attempt.sessionId=session.id;attempt.deviceId=session.deviceId;this.record('LABEL_PRINT_REQUEUED',j.entityId,{previousAttemptId:id,newAttemptId:next.id,labelId:label.id},session.id);this.persist();return next;}
  createTask(input, key){return this.run(key,'TASK_CREATED',()=>{this.requireUuid(input.entityId,'entityId',{optional:true});const task={id:randomUUID(),site:this.site,title:input.title,zone:input.zone,priority:input.priority??50,status:'OPEN',assignedTo:input.assignedTo??null,entityId:input.entityId??null,createdAt:this.clock()};this.state.tasks.push(task);return task;});}
  claimTask(id,operatorId,key){return this.run(key,'TASK_CLAIMED',()=>{const t=this.state.tasks.find(x=>x.id===id);if(!t)throw new DomainError('TASK_NOT_FOUND','Task not found',404);if(t.status!=='OPEN')throw new DomainError('TASK_ALREADY_CLAIMED','Task is not open',409);t.status='IN_PROGRESS';t.assignedTo=operatorId;t.claimedAt=this.clock();return t;});}
  qualityCheck(input,key){return this.run(key,'QUALITY_CHECK_RECORDED',()=>{this.batch(input.batchId);if(!['APPROVED','REJECTED','QUARANTINED'].includes(input.result))throw new DomainError('QUALITY_RESULT_INVALID','Invalid quality result',400);const q={id:randomUUID(),batchId:input.batchId,result:input.result,notes:input.notes??'',inspectorId:input.inspectorId,createdAt:this.clock()};this.state.qualityChecks.push(q);if(input.result==='QUARANTINED'){const zone=this.reference('zones','QUARANTINE'),batch=this.batch(input.batchId);batch.zone=zone.code;batch.zoneId=zone.id;this.raiseExceptionRecord({type:'QUALITY_QUARANTINE',entityType:'BATCH',entityId:batch.id,severity:'HIGH'})}return q;});}
  releaseQuarantine(input,key){return this.run(key,'QUARANTINE_RELEASED',()=>{const b=this.batch(input.batchId);if(b.zone!=='QUARANTINE')throw new DomainError('BATCH_NOT_QUARANTINED','Batch is not quarantined',409);if(!input.reason?.trim())throw new DomainError('RELEASE_REASON_REQUIRED','Release reason is required',400);const q={id:randomUUID(),batchId:b.id,result:'APPROVED',notes:input.reason,inspectorId:input.inspectorId,createdAt:this.clock(),release:true};this.state.qualityChecks.push(q);b.zone=input.destinationZone??'COLD_ROOM';b.status='RELEASED';return q;});}
  adjustInventory(input,key){return this.run(key,'INVENTORY_ADJUSTED',()=>{const b=this.batch(input.batchId),delta=Number(input.deltaKg);if(!Number.isFinite(delta)||delta===0)throw new DomainError('ADJUSTMENT_INVALID','Adjustment must be non-zero',400);if(!input.reason?.trim())throw new DomainError('ADJUSTMENT_REASON_REQUIRED','Adjustment reason is required',400);if(b.weightKg+delta<0)throw new DomainError('INSUFFICIENT_INVENTORY','Adjustment would make inventory negative',409);const before=b.weightKg;b.weightKg=Number((before+delta).toFixed(3));if(b.weightKg===0)b.status=input.reasonCode==='WASTE'?'WASTED':'DEPLETED';if(input.reasonCode==='WASTE')b.zone='WASTE';const a={id:randomUUID(),batchId:b.id,beforeKg:before,deltaKg:delta,afterKg:b.weightKg,reasonCode:input.reasonCode??'CORRECTION',reason:input.reason,userId:input.userId,createdAt:this.clock()};this.state.inventoryAdjustments.push(a);return a;});}
  createConfiguration(input,key){return this.run(key,'CONFIGURATION_DRAFTED',()=>{const sequence=1+Math.max(0,...this.state.configurationVersions.filter(x=>x.scope===input.scope).map(x=>x.sequence));const version={id:randomUUID(),scope:input.scope,sequence,status:'DRAFT',values:structuredClone(input.values??{}),createdBy:input.userId,createdAt:this.clock()};this.state.configurationVersions.push(version);return version;});}
  transitionConfiguration(id,action,userId,key){return this.run(key,`CONFIGURATION_${action}`,()=>{const v=this.state.configurationVersions.find(x=>x.id===id);if(!v)throw new DomainError('CONFIGURATION_NOT_FOUND','Configuration version not found',404);const allowed={DRAFT:{APPROVE:'APPROVED'},APPROVED:{ACTIVATE:'ACTIVE'}};const next=allowed[v.status]?.[action];if(!next)throw new DomainError('CONFIGURATION_TRANSITION_INVALID',`Cannot ${action} ${v.status} configuration`,409);if(action==='APPROVE'&&v.createdBy===userId)throw new DomainError('SELF_APPROVAL_FORBIDDEN','Creator cannot approve own configuration',403);if(next==='ACTIVE')for(const old of this.state.configurationVersions.filter(x=>x.scope===v.scope&&x.status==='ACTIVE'))old.status='RETIRED';v.status=next;v.updatedBy=userId;v.updatedAt=this.clock();return v;});}
  requestOverride(input,key){return this.run(key,'OVERRIDE_REQUESTED',()=>{this.requireUuid(input.entityId,'entityId',{optional:true});if(!input.reason?.trim())throw new DomainError('OVERRIDE_REASON_REQUIRED','Override reason is required',400);const o={id:randomUUID(),ruleCode:input.ruleCode,entityId:input.entityId,reason:input.reason,requestedBy:input.requestedBy,status:'PENDING',createdAt:this.clock()};this.state.overrides.push(o);return o;});}
  resolveOverride(id,input,key){return this.run(key,'OVERRIDE_RESOLVED',()=>{const o=this.state.overrides.find(x=>x.id===id);if(!o)throw new DomainError('OVERRIDE_NOT_FOUND','Override not found',404);if(o.status!=='PENDING')throw new DomainError('OVERRIDE_ALREADY_RESOLVED','Override already resolved',409);if(o.requestedBy===input.resolvedBy)throw new DomainError('SELF_APPROVAL_FORBIDDEN','Requester cannot resolve own override',403);if(!['APPROVED','REJECTED'].includes(input.decision))throw new DomainError('OVERRIDE_DECISION_INVALID','Decision must be APPROVED or REJECTED',400);o.status=input.decision;o.resolvedBy=input.resolvedBy;o.resolutionNote=input.note??'';o.resolvedAt=this.clock();return o;});}
  inventory(){return this.state.batches.map(b=>({id:b.id,code:b.code,product:b.product,grade:b.grade,size:b.size,weightKg:b.weightKg,zone:b.zone,containerId:b.containerId??null,status:b.status,parentIds:b.parentIds}));}
  trace(id){const root=this.batch(id);const ancestors=[];const visit=b=>{for(const pid of b.parentIds){const p=this.batch(pid);ancestors.push(p);visit(p);}};visit(root);return{batch:root,ancestors,measurements:this.state.measurements.filter(x=>x.batchId===id),movements:this.state.movements.filter(x=>x.batchId===id)};}
}
