import http from 'node:http';
import { randomUUID } from 'node:crypto';
import { pathToFileURL } from 'node:url';
import { StoreMesh, DomainError } from './domain.js';
import { AuthService, PostgresAuthStore, authRequiredFromEnvironment, authorized } from './auth.js';
import { JsonRepository } from './persistence.js';
import { PostgresRepository } from './postgres-repository.js';
import { OutboxPublisher } from './outbox-publisher.js';
import { errorResponse } from './errors.js';
import { applyAuditedAuthMutation, credentialFingerprint, reconcileAuthAudit } from './auth-audit-integrity.js';
export const BOOTSTRAP_ADMIN_ID='00000000-0000-4000-a000-000000000001',BOOTSTRAP_OPERATOR_ID='00000000-0000-4000-a000-000000000002';

const receivingContainerInput=input=>{
  const allowedFields=new Set(['type','capacityKg','tareWeightKg','zone','designatedZones']);
  if(Object.keys(input).some(field=>!allowedFields.has(field)))throw new DomainError('BASIC_CONTAINER_FIELDS_FORBIDDEN','Receiving operators may only set basic reusable-container fields',403);
  const type=String(input.type??'BASKET').toUpperCase(),zone=String(input.zone??'RECEIVING').toUpperCase(),designatedZones=input.designatedZones??['RECEIVING','COLD_ROOM_DIRTY'];
  if(!['BASKET','CRATE'].includes(type))throw new DomainError('BASIC_CONTAINER_TYPE_FORBIDDEN','Receiving operators may only create reusable BASKET or CRATE containers',403);
  if(zone!=='RECEIVING')throw new DomainError('BASIC_CONTAINER_ZONE_FORBIDDEN','Receiving operators may only create containers in RECEIVING',403);
  if(!Array.isArray(designatedZones)||!designatedZones.length||designatedZones.some(code=>!['RECEIVING','COLD_ROOM_DIRTY'].includes(String(code).toUpperCase())))throw new DomainError('BASIC_CONTAINER_DESIGNATION_FORBIDDEN','Receiving containers may only be designated for RECEIVING and COLD_ROOM_DIRTY',403);
  return{type,capacityKg:input.capacityKg,tareWeightKg:input.tareWeightKg,zone,designatedZones:[...new Set(designatedZones.map(code=>String(code).toUpperCase()))]};
};

export function createServer({ app = new StoreMesh({ site: process.env.SITE_CODE || 'IRAN', repository: process.env.DATA_FILE ? new JsonRepository(process.env.DATA_FILE) : null }), auth = null, requireAuth = true } = {}) {
  auth ??= new AuthService({ site: app.site });
  if (!auth.users.size) {
    const demoAllowed=process.env.NODE_ENV!=='production'&&process.env.ALLOW_DEMO_CREDENTIALS!=='false';
    if(!demoAllowed&&(!process.env.BOOTSTRAP_ADMIN_USER||!process.env.BOOTSTRAP_ADMIN_PASSWORD))throw new Error('Production bootstrap credentials are required');
    auth.addUser({ id:BOOTSTRAP_ADMIN_ID, username:process.env.BOOTSTRAP_ADMIN_USER||'admin', password:process.env.BOOTSTRAP_ADMIN_PASSWORD||'storemesh-demo', roles:['ADMIN'] });
    if(demoAllowed)auth.addUser({ id:BOOTSTRAP_OPERATOR_ID, username:'operator', password:'operator-demo', roles:['RECEIVING_OPERATOR','STORAGE_OPERATOR','SORTING_OPERATOR','WASHING_OPERATOR','SLICING_OPERATOR','FREEZING_OPERATOR','FREEZE_DRY_OPERATOR','DRYING_OPERATOR','PACKAGING_OPERATOR','SHIPPING_OPERATOR'] });
  }
  const stats={requests:0,errors:0,startedAt:Date.now()};
  const auditedMutation=options=>applyAuditedAuthMutation({...options,persist:()=>app.persist(),flush:()=>app.flush()});
  const server=http.createServer(async (req,res)=>{
    const auditContext={requestId:String(req.headers['x-request-id']??randomUUID()),ipAddress:String(req.headers['x-forwarded-for']??req.socket.remoteAddress??'').split(',')[0].trim()||null,userId:null,deviceId:null};
    return app.withAuditContext(auditContext,async()=>{
    stats.requests++;
    res.setHeader('Access-Control-Allow-Origin','*'); res.setHeader('Access-Control-Allow-Headers','Content-Type,Idempotency-Key,Authorization,X-Request-Id'); res.setHeader('Access-Control-Allow-Methods','GET,POST,DELETE,OPTIONS');res.setHeader('X-Request-Id',auditContext.requestId);
    if(req.method==='OPTIONS'){res.writeHead(204);return res.end();}
    const send=(status,data)=>{res.writeHead(status,{'Content-Type':'application/json'});res.end(JSON.stringify(data));};
    const body=async()=>{let raw='';for await(const c of req)raw+=c;return raw?JSON.parse(raw):{};};
    try {
      const u=new URL(req.url,'http://localhost'); const key=req.headers['idempotency-key']; let result;
      if(req.method==='GET'&&u.pathname==='/health') return send(200,{status:'ok',site:app.site});
      if(req.method==='GET'&&u.pathname==='/ready'){try{if(app.repository?.ready)await app.repository.ready();return send(200,{status:'ready',site:app.site})}catch{return send(503,{status:'not_ready',site:app.site})}}
      if(req.method==='GET'&&u.pathname==='/metrics'){res.writeHead(200,{'Content-Type':'text/plain; version=0.0.4'});return res.end([`storemesh_http_requests_total ${stats.requests}`,`storemesh_http_errors_total ${stats.errors}`,`storemesh_uptime_seconds ${Math.floor((Date.now()-stats.startedAt)/1000)}`,`storemesh_batches ${app.state.batches.length}`,`storemesh_outbox_pending ${app.state.outbox.filter(x=>x.status==='PENDING').length}`,`storemesh_print_jobs_pending ${app.state.printJobs.filter(x=>x.status==='PENDING').length}`].join('\n')+'\n')}
      if(req.method==='POST'&&u.pathname==='/api/auth/login'){const b=await body();auditContext.deviceId=b.deviceId??null;const token=auth.login(b.username,b.password,b.deviceId),account=auth.users.get(b.username);await auth.flush();auditContext.userId=token?account.id:null;app.record(token?'LOGIN_SUCCEEDED':'LOGIN_FAILED',account?.id??null,{username:b.username},null,b.deviceId??null,token?'SUCCESS':'FAILURE');app.persist();await app.flush();return token?send(200,{success:true,data:{token}}):send(401,{success:false,errorCode:'INVALID_CREDENTIALS',message:'Invalid credentials'});}
      if(req.method==='POST'&&u.pathname==='/api/auth/login-badge'){const b=await body();auditContext.deviceId=b.deviceId??null;const token=auth.loginBadge(b.badgeCode,b.pin,b.deviceId),account=token?auth.userById(JSON.parse(Buffer.from(token.split('.')[1],'base64url')).sub):null;await auth.flush();auditContext.userId=account?.id??null;app.record(token?'BADGE_LOGIN_SUCCEEDED':'BADGE_LOGIN_FAILED',account?.id??null,{},null,b.deviceId??null,token?'SUCCESS':'FAILURE');app.persist();await app.flush();return token?send(200,{success:true,data:{token}}):send(401,{success:false,errorCode:'INVALID_CREDENTIALS',message:'Invalid credentials'});}
      const user=auth.verify(req.headers.authorization?.replace(/^Bearer /,''));
      auditContext.userId=user?.sub??null;auditContext.deviceId=user?.deviceId??null;auditContext.roles=[...(user?.roles??[])];auditContext.station=app.state.devices.find(x=>x.code===user?.deviceId)?.assignedStation??null;
      if(requireAuth&&!user)return send(401,{success:false,errorCode:'AUTHENTICATION_REQUIRED',message:'Authentication required'});
      const needs=permission=>{if(requireAuth&&!authorized(user,permission))throw new DomainError('FORBIDDEN','Insufficient permission',403,{permission,path:u.pathname,method:req.method});};
      const canManageTarget=target=>{if(user.roles?.includes('ADMIN'))return true;const caller=new Set(user.permissions??[]),targetPermissions=new Set((target?.roles??[]).flatMap(role=>auth.roles.get(role)?.permissions??[]));return !targetPermissions.has('*')&&[...targetPermissions].every(permission=>caller.has(permission))};
      const taskSessionActor=sessionId=>{if(!sessionId)throw new DomainError('TASK_SESSION_REQUIRED','An active role-scoped operational session is required',400);const session=app.requireSession(sessionId);if(user?.sub&&session.operatorId!==user.sub)throw new DomainError('SESSION_ACTOR_MISMATCH','Operational session belongs to another user',403);if(!session.selectedRole)throw new DomainError('TASK_SESSION_ROLE_REQUIRED','Task eligibility requires a selected session role',400);return{operatorId:user.sub,roles:[session.selectedRole],skills:user.skills??[],sessionId:session.id,deviceId:session.deviceId,station:session.station}};
      if(req.method==='POST'&&/^\/api\/auth\/sessions\/[^/]+\/revoke$/.test(u.pathname)){const sessionId=u.pathname.split('/')[4];if(sessionId!==user.jti)needs('session:revoke');if(!auth.revokeSession(sessionId,user.sub))throw new DomainError('AUTH_SESSION_NOT_FOUND','Authentication session not found',404);await auth.flush();app.record('AUTH_SESSION_REVOKED',sessionId,{},null,user.deviceId,'SUCCESS');app.persist();await app.flush();return send(200,{success:true,data:{id:sessionId,status:'REVOKED'}});}
      if(req.method==='GET'&&u.pathname==='/api/tasks/recommended'){needs('inventory:read');const task=app.recommendedTask(taskSessionActor(u.searchParams.get('sessionId')));return send(200,{data:task?app.taskView(task):null});}
      if(req.method==='GET'&&u.pathname==='/api/skills'){needs('inventory:read');return send(200,{items:[...auth.skills.values()]});}
      if(req.method==='GET'&&u.pathname==='/api/roles'){needs('inventory:read');return send(200,{items:[...auth.roles.values()]});}
      if(req.method==='GET'&&u.pathname==='/api/users'){needs('roles:assign');return send(200,{items:auth.publicUsers()});}
      if(req.method==='GET'&&u.pathname==='/api/devices'){needs('inventory:read');return send(200,{items:app.devicesWithPresence()});}
      if(req.method==='GET'&&u.pathname==='/api/tasks'){needs('inventory:read');const assigned=u.searchParams.get('assignedTo'),eligible=u.searchParams.get('eligible');if(eligible==='me'){const actor=taskSessionActor(u.searchParams.get('sessionId')),available=app.state.tasks.filter(x=>['OPEN','BLOCKED'].includes(x.status)&&!x.assignedTo&&app.taskEligible(x,actor)).map(x=>app.taskView(x)),mine=app.state.tasks.filter(x=>['IN_PROGRESS','PAUSED','BLOCKED'].includes(x.status)&&x.assignedTo===actor.operatorId).map(x=>app.taskView(x));return send(200,{available,mine})}const items=(assigned==='me'?app.state.tasks.filter(x=>x.assignedTo===user.sub):app.state.tasks).map(x=>app.taskView(x));return send(200,{items});}
      if(req.method==='GET'&&u.pathname==='/api/exceptions'){needs('inventory:read');return send(200,{items:app.searchExceptions(Object.fromEntries(u.searchParams))});}
      if(req.method==='GET'&&u.pathname==='/api/deliveries'){needs('inventory:read');const items=app.state.deliveries.map(x=>({...x,baskets:app.state.deliveryBaskets.filter(b=>b.deliveryId===x.id)}));return send(200,{items});}
      if(req.method==='GET'&&u.pathname==='/api/fresh-net-lots'){needs('inventory:read');return send(200,{items:app.state.freshNetLots});}
      if(req.method==='GET'&&u.pathname==='/api/fresh-shipping-boxes'){needs('inventory:read');return send(200,{items:app.state.shippingBoxes});}
      if(req.method==='GET'&&u.pathname==='/api/consumables'){needs('inventory:read');return send(200,{items:app.state.consumables});}
      if(req.method==='GET'&&u.pathname==='/api/harvest-periods'){needs('inventory:read');return send(200,{items:app.state.harvestPeriods});}
      if(req.method==='GET'&&/^\/api\/master-data\/(products|suppliers|grades|sizes|zones|packageTypes)$/.test(u.pathname)){needs('inventory:read');return send(200,{items:app.state.masterData[u.pathname.split('/')[3]]});}
      if(req.method==='GET'&&u.pathname==='/api/containers'){needs('inventory:read');return send(200,{items:app.state.containers});}
      if(req.method==='GET'&&u.pathname==='/api/configurations'){needs('inventory:read');return send(200,{items:app.configurationVersionsView()});}
      if(req.method==='GET'&&u.pathname==='/api/overrides'){needs('inventory:read');return send(200,{items:app.state.overrides});}
      if(req.method==='GET'&&u.pathname==='/api/inventory'){needs('inventory:read');return send(200,{items:app.inventory()});}
      if(req.method==='GET'&&u.pathname==='/api/print-jobs'){needs('inventory:read');return send(200,{items:app.state.printJobs});}
      if(req.method==='GET'&&u.pathname==='/api/outbox'){needs('audit:read');return send(200,{items:app.state.outbox});}
      if(req.method==='GET'&&u.pathname==='/api/sessions'){needs('inventory:read');return send(200,{items:app.state.sessions});}
      if(req.method==='GET'&&u.pathname==='/api/packages'){needs('inventory:read');return send(200,{items:app.state.packages});}
      if(req.method==='GET'&&u.pathname==='/api/cycles'){needs('inventory:read');return send(200,{items:app.state.cycles});}
      if(req.method==='GET'&&u.pathname==='/api/tray-allocations'){needs('inventory:read');return send(200,{items:app.state.trayAllocations});}
      if(req.method==='GET'&&u.pathname==='/api/shipments'){needs('inventory:read');return send(200,{items:app.state.shipments});}
      if(req.method==='GET'&&u.pathname==='/api/customers'){needs('inventory:read');return send(200,{items:app.state.customers});}
      if(req.method==='GET'&&u.pathname==='/api/sales-orders'){needs('inventory:read');return send(200,{items:app.state.salesOrders});}
      if(req.method==='GET'&&u.pathname==='/api/shipment-carton-scans'){needs('inventory:read');return send(200,{items:app.state.shipmentCartonScans});}
      if(req.method==='GET'&&u.pathname==='/api/quality-checks'){needs('inventory:read');return send(200,{items:app.state.qualityChecks});}
      if(req.method==='GET'&&u.pathname==='/api/qc-checklists'){needs('inventory:read');return send(200,{items:app.state.qcChecklists});}
      if(req.method==='GET'&&u.pathname==='/api/reports/operations'){needs('inventory:read');return send(200,{data:app.reports()});}
      if(req.method==='GET'&&u.pathname==='/api/reports/sorting-loss'){needs('inventory:read');return send(200,{data:app.sortingLossReport({from:u.searchParams.get('from'),to:u.searchParams.get('to')})});}
      if(req.method==='GET'&&u.pathname==='/api/inventory-adjustments'){needs('inventory:read');return send(200,{items:app.state.inventoryAdjustments});}
      if(req.method==='GET'&&u.pathname==='/api/audit'){needs('audit:read');return send(200,{items:app.state.audit});}
      if(req.method==='GET'&&u.pathname==='/api/internal-transfers'){needs('inventory:read');return send(200,{items:app.state.internalTransfers});}
      if(req.method==='GET'&&/^\/api\/shipments\/[^/]+\/manifest$/.test(u.pathname)){needs('shipping:write');return send(200,app.shipmentManifest(u.pathname.split('/')[3]));}
      if(req.method==='GET'&&u.pathname==='/api/trace/search'){needs('inventory:read');const query=u.searchParams.get('code'),result=app.resolveTraceEntryPoint(query);app.record('TRACE_SEARCHED',result.matchedObject.id,{query,matchedObject:result.matchedObject,batchIds:result.batchIds,searchType:'CODE_LOOKUP'},null,user?.deviceId??null,'SUCCESS');app.persist();await app.flush();return send(200,result)}
      if(req.method==='GET'&&/^\/api\/trace\/supplier\/[^/]+$/.test(u.pathname)){needs('inventory:read');const code=decodeURIComponent(u.pathname.split('/').at(-1)),result=app.supplierTrace(code);app.record('TRACE_SEARCHED',result.supplier.id,{supplierCode:result.supplier.code,searchType:'SUPPLIER'},null,user?.deviceId??null,'SUCCESS');app.persist();await app.flush();return send(200,result)}
      if(req.method==='GET'&&/^\/api\/trace\/customer\/[^/]+$/.test(u.pathname)){needs('inventory:read');const id=decodeURIComponent(u.pathname.split('/').at(-1)),result=app.customerTrace(id);app.record('TRACE_SEARCHED',result.customer.id,{customerId:result.customer.id,searchType:'CUSTOMER'},null,user?.deviceId??null,'SUCCESS');app.persist();await app.flush();return send(200,result)}
      if(req.method==='GET'&&/^\/api\/trace\/[^/]+\/recall$/.test(u.pathname)){needs('inventory:read');const batchId=u.pathname.split('/').at(-2),result=app.recallAnalysis(batchId);app.record('TRACE_SEARCHED',batchId,{searchedBatchId:batchId,searchType:'RECALL'},null,user?.deviceId??null,'SUCCESS');app.persist();await app.flush();return send(200,result)}
      if(req.method==='GET'&&/^\/api\/trace\/[^/]+\/forward$/.test(u.pathname)){needs('inventory:read');const batchId=u.pathname.split('/').at(-2),result=app.traceForward(batchId);app.record('TRACE_SEARCHED',batchId,{searchedBatchId:batchId,searchType:'BATCH_FORWARD'},null,user?.deviceId??null,'SUCCESS');app.persist();await app.flush();return send(200,result)}
      if(req.method==='GET'&&u.pathname.startsWith('/api/trace/')){needs('inventory:read');const batchId=u.pathname.split('/').at(-1),result=app.trace(batchId);app.record('TRACE_SEARCHED',batchId,{searchedBatchId:batchId,searchType:'BATCH'},null,user?.deviceId??null,'SUCCESS');app.persist();await app.flush();return send(200,result)}
      if(req.method==='POST'&&u.pathname==='/api/packaging/sessions'){needs('packaging:write');const b=await body();if(!user.roles?.includes('PACKAGING_OPERATOR')&&!user.roles?.includes('ADMIN'))throw new DomainError('PACKAGING_ROLE_REQUIRED','Packaging role is required',403);result=app.openSession(user.sub,b.deviceId,b.station??'PACKAGING','PACKAGING_OPERATOR');await app.flush();return send(201,{success:true,data:result});}
      if(req.method==='POST'&&u.pathname==='/api/sessions'){needs('operations:write');const b=await body();if(b.selectedRole&&!user.roles?.includes(b.selectedRole)&&!user.roles?.includes('ADMIN'))throw new DomainError('SESSION_ROLE_NOT_ASSIGNED','Selected role is not assigned to this user',403);result=app.openSession(user.sub,b.deviceId,b.station,b.selectedRole??null);}
      else if(req.method==='POST'&&u.pathname==='/api/skills'){needs('user-skills:write');result=await auth.createSkill(await body());app.record('SKILL_CREATED',result.id,{code:result.code});app.persist();}
      else if(req.method==='POST'&&u.pathname==='/api/roles'){needs('roles:create');result=await auth.createRole(await body());app.record('ROLE_CREATED',result.id,{afterState:result});app.persist();}
      else if(req.method==='POST'&&/^\/api\/roles\/[^/]+\/update$/.test(u.pathname)){needs('roles:create');const code=u.pathname.split('/')[3],before=structuredClone(auth.roles.get(code));result=await auth.updateRole(code,await body());app.record('ROLE_UPDATED',result.id,{beforeState:before,afterState:result});app.persist();}
      else if(req.method==='POST'&&/^\/api\/users\/[^/]+\/roles$/.test(u.pathname)){needs('roles:assign');const b=await body(),userId=u.pathname.split('/')[3],target=auth.userById(userId),role=auth.roles.get(b.roleCode);if(userId===user.sub)throw new DomainError('ROLE_SELF_ASSIGNMENT_FORBIDDEN','Users cannot assign roles to themselves',403);if(!target||!role)throw new DomainError('USER_OR_ROLE_NOT_FOUND','User or role not found',404);if(!canManageTarget(target)||role.permissions.includes('*')||!user.roles?.includes('ADMIN')&&role.permissions.some(permission=>!user.permissions?.includes(permission)))throw new DomainError('ROLE_ASSIGNMENT_EXCEEDS_CALLER','Cannot assign privileges above the caller',403);result=await auditedMutation({apply:async()=>{if(!await auth.assignRole(userId,b.roleCode))throw new DomainError('USER_OR_ROLE_NOT_FOUND','User or role not found',404);await auth.flush();return{userId,roleCode:b.roleCode,status:'ASSIGNED'}},record:value=>app.record('USER_ROLE_ASSIGNED',userId,value),compensate:async()=>{await auth.revokeRole(userId,b.roleCode);await auth.flush()}});}
      else if(req.method==='POST'&&/^\/api\/users\/[^/]+\/badge$/.test(u.pathname)){needs('credentials:issue');const target=auth.userById(u.pathname.split('/')[3]);if(!target||!canManageTarget(target))throw new DomainError('CREDENTIAL_ISSUANCE_FORBIDDEN','Cannot issue credentials for a more privileged user',403);const before=target.badgeCodeHash;result=await auditedMutation({apply:async()=>{const value=auth.assignBadge(target.id);await auth.flush();return value},record:value=>app.record('USER_BADGE_REGENERATED',target.id,{userId:value.userId,credentialFingerprint:credentialFingerprint(target.badgeCodeHash)}),compensate:()=>auth.restoreBadge(target.id,before)});}
      else if(req.method==='POST'&&/^\/api\/users\/[^/]+\/pin$/.test(u.pathname)){needs('credentials:issue');const target=auth.userById(u.pathname.split('/')[3]);if(!target||!canManageTarget(target))throw new DomainError('CREDENTIAL_ISSUANCE_FORBIDDEN','Cannot issue credentials for a more privileged user',403);const before=target.badgePinHash;result=await auditedMutation({apply:async()=>{const value=auth.assignPin(target.id);await auth.flush();return value},record:value=>app.record('USER_BADGE_PIN_RESET',target.id,{userId:value.userId,credentialFingerprint:credentialFingerprint(target.badgePinHash)}),compensate:()=>auth.restorePin(target.id,before)});}
      else if(req.method==='DELETE'&&/^\/api\/users\/[^/]+\/roles\/[^/]+$/.test(u.pathname)){needs('roles:assign');const parts=u.pathname.split('/'),userId=parts[3],roleCode=parts[5],target=auth.userById(userId);if(!target||!canManageTarget(target))throw new DomainError('ROLE_ASSIGNMENT_EXCEEDS_CALLER','Cannot revoke roles from a user above the caller',403);result=await auditedMutation({apply:async()=>{if(!await auth.revokeRole(userId,roleCode))throw new DomainError('USER_ROLE_NOT_FOUND','User role assignment not found',404);await auth.flush();return{userId,roleCode,status:'REVOKED'}},record:value=>app.record('USER_ROLE_REVOKED',userId,value),compensate:async()=>{await auth.assignRole(userId,roleCode);await auth.flush()}});}
      else if(req.method==='POST'&&/^\/api\/users\/[^/]+\/skills$/.test(u.pathname)){needs('user-skills:write');const b=await body(),userId=u.pathname.split('/')[3];if(!await auth.assignSkill(userId,b.skillId))throw new DomainError('USER_OR_SKILL_NOT_FOUND','User or skill not found',404);result={userId,skillId:b.skillId,status:'ASSIGNED'};app.record('USER_SKILL_ASSIGNED',null,{userId,skillId:b.skillId});app.persist();}
      else if(req.method==='DELETE'&&/^\/api\/users\/[^/]+\/skills\/[^/]+$/.test(u.pathname)){needs('user-skills:write');const parts=u.pathname.split('/'),userId=parts[3],skillId=parts[5];if(!await auth.revokeSkill(userId,skillId))throw new DomainError('USER_SKILL_NOT_FOUND','User skill assignment not found',404);result={userId,skillId,status:'REVOKED'};app.record('USER_SKILL_REVOKED',null,{userId,skillId});app.persist();}
      else if(req.method==='POST'&&u.pathname==='/api/devices'){needs('config:write');result=app.registerDevice(await body(),key);}
      else if(req.method==='POST'&&u.pathname==='/api/measurements'){needs('operations:write');result=app.captureMeasurement(await body(),key);}
      else if(req.method==='POST'&&/^\/api\/devices\/[^/]+\/heartbeat$/.test(u.pathname)){needs('operations:write');result=app.heartbeatDevice(u.pathname.split('/')[3]);}
      else if(req.method==='POST'&&/^\/api\/devices\/[^/]+\/retire$/.test(u.pathname)){needs('config:write');result=app.retireDevice(u.pathname.split('/')[3],key);}
      else if(req.method==='POST'&&/^\/api\/master-data\/(products|suppliers|grades|sizes|zones|packageTypes)$/.test(u.pathname)){needs('master-data:write');result=app.createReference(u.pathname.split('/')[3],await body(),key);}
      else if(req.method==='POST'&&/^\/api\/master-data\/(products|suppliers|grades|sizes|zones|packageTypes)\/[^/]+\/update$/.test(u.pathname)){needs('master-data:write');const parts=u.pathname.split('/');result=app.updateReference(parts[3],parts[4],await body(),key);}
      else if(req.method==='POST'&&u.pathname==='/api/harvest-periods'){needs('master-data:write');result=app.createHarvestPeriod(await body(),key);}
      else if(req.method==='POST'&&/^\/api\/harvest-periods\/[^/]+\/update$/.test(u.pathname)){needs('master-data:write');result=app.updateHarvestPeriod(u.pathname.split('/')[3],await body(),key);}
      else if(req.method==='POST'&&/^\/api\/sessions\/[^/]+\/draft$/.test(u.pathname)){needs('operations:write');result=app.saveSessionDraft(u.pathname.split('/')[3],(await body()).draft);}
      else if(req.method==='POST'&&/^\/api\/sessions\/[^/]+\/(suspend|resume|complete|cancel)$/.test(u.pathname)){needs('operations:write');const parts=u.pathname.split('/');result=app.updateSession(parts[3],parts[4].toUpperCase());}
      else if(req.method==='POST'&&/^\/api\/sessions\/[^/]+\/terminate$/.test(u.pathname)){needs('session:terminate');result=app.forceCloseSession(u.pathname.split('/')[3],user.sub);}
      else if(req.method==='POST'&&/^\/api\/sessions\/[^/]+\/handover$/.test(u.pathname)){needs('operations:write');const target=auth.userById((await body()).toOperatorId);if(!target||target.status!=='ACTIVE')throw new DomainError('SESSION_HANDOVER_TARGET_INVALID','Handover target must be an active authenticated operator',400);result=app.handoverSession(u.pathname.split('/')[3],user.sub,target.id);}
      else if(req.method==='POST'&&u.pathname==='/api/receiving'){needs('receiving:write');const b=await body();delete b.weightKg;delete b.grossWeightKg;result=app.receive({...b,requireMeasurement:true},key);}
      else if(req.method==='POST'&&/^\/api\/batches\/[^/]+\/cancel-receiving$/.test(u.pathname)){needs('receiving:write');result=app.cancelBatch(u.pathname.split('/')[3],await body(),key);}
      else if(req.method==='POST'&&u.pathname==='/api/deliveries'){needs('receiving:write');result=app.startDelivery(await body(),key);}
      else if(req.method==='POST'&&/^\/api\/deliveries\/[^/]+\/cancel$/.test(u.pathname)){needs('receiving:write');result=app.cancelDelivery(u.pathname.split('/')[3],await body(),key);}
      else if(req.method==='POST'&&/^\/api\/deliveries\/[^/]+\/complete$/.test(u.pathname)){needs('receiving:write');result=app.completeDelivery(u.pathname.split('/')[3],await body(),key);}
      else if(req.method==='POST'&&/^\/api\/deliveries\/[^/]+\/move-to-cold-storage$/.test(u.pathname)){needs('storage:write');result=app.moveDeliveryContainers(u.pathname.split('/')[3],await body(),key);}
      else if(req.method==='POST'&&u.pathname==='/api/movements'){needs('storage:write');const b=await body();result=app.move(b.batchId,b.zone,b.sessionId,key,b.overrideId,b.reason);}
      else if(req.method==='POST'&&u.pathname==='/api/containers'){const b=await body();if(!requireAuth||authorized(user,'storage:write'))result=app.createContainer(b,key);else{needs('containers:create-basic');result=app.createContainer(receivingContainerInput(b),key);}}
      else if(req.method==='POST'&&/^\/api\/containers\/[^/]+\/label$/.test(u.pathname)){needs('print:write');result=app.requestContainerLabel(u.pathname.split('/')[3],key);}
      else if(req.method==='POST'&&/^\/api\/containers\/[^/]+\/update$/.test(u.pathname)){const b=await body();needs(b.designatedZone!==undefined?'container:designate':'storage:write');result=app.updateContainer(u.pathname.split('/')[3],b,key);}
      else if(req.method==='POST'&&/^\/api\/containers\/[^/]+\/assign$/.test(u.pathname)){needs('storage:write');const b=await body();result=app.assignBatchToContainer(u.pathname.split('/')[3],b.batchId,b.sessionId,key);}
      else if(req.method==='POST'&&/^\/api\/containers\/[^/]+\/move$/.test(u.pathname)){needs('storage:write');const b=await body();result=app.moveContainer(u.pathname.split('/')[3],b.zone,b.sessionId,key,b.reason);}
      else if(req.method==='POST'&&/^\/api\/containers\/[^/]+\/priority$/.test(u.pathname)){needs('container:priority');const b=await body();result=app.setContainerPriority(u.pathname.split('/')[3],b.priority,b.reason,key);}
      else if(req.method==='POST'&&/^\/api\/containers\/[^/]+\/transfer-damaged$/.test(u.pathname)){needs('storage:write');result=app.transferDamagedContainer(u.pathname.split('/')[3],await body(),key);}
      else if(req.method==='POST'&&u.pathname==='/api/transforms'){const b=await body();needs({WASH:'washing:write',SLICE:'slicing:write',MERGE:'sorting:write'}[b.process]??'operations:write');if(['WASH','SLICE'].includes(b.process)){delete b.outputWeightKg;delete b.consumeWeightKg}result=app.transform(b,key);}
      else if(req.method==='POST'&&/^\/api\/batches\/[^/]+\/tray-allocations$/.test(u.pathname)){needs('slicing:write');result=app.allocateToTray(u.pathname.split('/')[3],await body(),key);}
      else if(req.method==='POST'&&u.pathname==='/api/cycles'){const b=await body();needs(b.type==='FREEZE'?'freezing:write':b.type==='FREEZE_DRY'?'freeze-drying:write':'drying:write');result=app.createCycle(b,key);}
      else if(req.method==='POST'&&/^\/api\/cycles\/[^/]+\/(start|pause|resume|restart|scrap|complete|finish|fail|cancel)$/.test(u.pathname)){const parts=u.pathname.split('/'),cycle=app.state.cycles.find(x=>x.id===parts[3]),action=parts[4].toUpperCase(),b=await body(),failureDecision=cycle?.status==='FAILED'&&['RESUME','RESTART','SCRAP'].includes(action);needs(failureDecision?'cycle:override':cycle?.type==='FREEZE'?'freezing:write':cycle?.type==='FREEZE_DRY'?'freeze-drying:write':'drying:write');if(action==='FINISH'&&cycle?.type!=='FREEZE'){if(!b.measurementIds||cycle.batchIds.some(id=>!b.measurementIds[id]))throw new DomainError('MEASUREMENT_REQUIRED','Production unload requires a captured scale measurement for every batch',400);delete b.finalWeights}result=app.transitionCycle(parts[3],action,b,key);}
      else if(req.method==='POST'&&/^\/api\/cycles\/[^/]+\/trays\/add$/.test(u.pathname)){needs('cycle:override');result=app.addCycleTray(u.pathname.split('/')[3],await body(),key);}
      else if(req.method==='POST'&&/^\/api\/cycles\/[^/]+\/trays\/remove$/.test(u.pathname)){needs('cycle:override');result=app.removeCycleTray(u.pathname.split('/')[3],await body(),key);}
      else if(req.method==='POST'&&u.pathname==='/api/sorting'){needs('sorting:write');result=app.sortBatch(await body(),key);}
      else if(req.method==='POST'&&/^\/api\/batches\/[^/]+\/destination$/.test(u.pathname)){needs('sorting:destination');result=app.assignSortingDestination(u.pathname.split('/')[3],(await body()).destination,key);}
      else if(req.method==='POST'&&/^\/api\/batches\/[^/]+\/override-grade$/.test(u.pathname)){needs('batch:override');const b=await body();result=app.overrideBatchGrade(u.pathname.split('/')[3],b.grade,b.reason,key);}
      else if(req.method==='POST'&&/^\/api\/batches\/[^/]+\/override-destination$/.test(u.pathname)){needs('batch:override');const b=await body();result=app.overrideBatchDestination(u.pathname.split('/')[3],b.destination,b.reason,key);}
      else if(req.method==='POST'&&/^\/api\/batches\/[^/]+\/priority$/.test(u.pathname)){needs('batch:override');const b=await body();result=app.setBatchPriority(u.pathname.split('/')[3],b.priority,b.reason,key);}
      else if(req.method==='POST'&&/^\/api\/shipments\/[^/]+\/priority$/.test(u.pathname)){needs('shipment:override');const b=await body();result=app.setShipmentPriority(u.pathname.split('/')[3],b.priority,b.reason,key);}
      else if(req.method==='POST'&&/^\/api\/fresh-shipping-boxes\/[^/]+\/split$/.test(u.pathname)){needs('shipment:override');result=app.splitShippingBox(u.pathname.split('/')[3],await body(),key);}
      else if(req.method==='POST'&&/^\/api\/fresh-shipping-boxes\/[^/]+\/cold-holding$/.test(u.pathname)){needs('fresh-export:write');result=app.moveToColdHolding(u.pathname.split('/')[3],await body(),key);}
      else if(req.method==='POST'&&u.pathname==='/api/fresh-shipping-boxes/drafts'){needs('fresh-export:write');result=app.draftShippingBox(await body(),key);}
      else if(req.method==='POST'&&/^\/api\/fresh-shipping-boxes\/[^/]+\/draft$/.test(u.pathname)){needs('fresh-export:write');result=app.updateShippingBoxDraft(u.pathname.split('/')[3],await body(),key);}
      else if(req.method==='POST'&&/^\/api\/fresh-shipping-boxes\/[^/]+\/confirm$/.test(u.pathname)){needs('fresh-export:write');result=app.confirmShippingBox(u.pathname.split('/')[3],await body(),key);}
      else if(req.method==='POST'&&/^\/api\/shipments\/[^/]+\/merge$/.test(u.pathname)){needs('shipment:override');const b=await body();result=app.mergeShipments(u.pathname.split('/')[3],b.targetShipmentId,b.reason,key);}
      else if(req.method==='POST'&&u.pathname==='/api/fresh-net-lots'){needs('fresh-export:write');result=app.createFreshNetLot(await body(),key);}
      else if(req.method==='POST'&&u.pathname==='/api/fresh-shipping-boxes'){needs('fresh-export:write');result=app.createShippingBox(await body(),key);}
      else if(req.method==='POST'&&/^\/api\/fresh-shipping-boxes\/[^/]+\/(cancel|damage)$/.test(u.pathname)){needs('fresh-export:write');const parts=u.pathname.split('/'),box=app.state.shippingBoxes.find(x=>x.id===parts.at(-2)),action=parts.at(-1).toUpperCase();if(action==='DAMAGE'&&box?.shipmentId)needs('override:approve');result=app.updateShippingBox(parts.at(-2),action,await body(),key);}
      else if(req.method==='POST'&&u.pathname==='/api/consumables'){needs('master-data:write');result=app.createConsumable(await body(),key);}
      else if(req.method==='PATCH'&&/^\/api\/consumables\/[^/]+$/.test(u.pathname)){needs('master-data:write');result=app.updateConsumable(u.pathname.split('/')[3],await body(),key);}
      else if(req.method==='POST'&&/^\/api\/consumables\/[^/]+\/activate$/.test(u.pathname)){needs('master-data:write');result=app.activateConsumable(u.pathname.split('/')[3],key);}
      else if(req.method==='POST'&&/^\/api\/consumables\/[^/]+\/deactivate$/.test(u.pathname)){needs('master-data:write');result=app.deactivateConsumable(u.pathname.split('/')[3],await body(),key);}
      else if(req.method==='POST'&&/^\/api\/consumables\/[^/]+\/receive$/.test(u.pathname)){needs('master-data:write');result=app.receiveConsumable(u.pathname.split('/')[3],await body(),key);}
      else if(req.method==='POST'&&u.pathname==='/api/packages'){needs('packaging:write');const b=await body();app.reference('packageTypes',b.type);if((b.level??'CARTON')==='UNIT'){if(!b.measurementId)throw new DomainError('MEASUREMENT_REQUIRED','UNIT creation must reference a separately captured scale measurement',400);delete b.targetWeightKg;delete b.tolerancePercent;const captured=app.state.measurements.find(x=>x.id===b.measurementId);if(b.items?.[0])b.items[0].weightKg=captured?.weightKg}result=app.createPackage(b,key);}
      else if(req.method==='POST'&&u.pathname==='/api/packaging/weigh'){needs('packaging:write');const b=await body();if(!b.measurementId)throw new DomainError('MEASUREMENT_REQUIRED','Packaging weigh must reference a separately captured scale measurement',400);delete b.weightKg;result=app.weighForPackaging(b,key);}
      else if(req.method==='POST'&&/^\/api\/packages\/[^/]+\/scans$/.test(u.pathname)){needs('packaging:write');result=app.scanPackageItem(u.pathname.split('/')[3],await body(),key);}
      else if(req.method==='POST'&&/^\/api\/packages\/[^/]+\/scans\/remove$/.test(u.pathname)){needs('packaging:write');result=app.unscanPackageItem(u.pathname.split('/')[3],await body(),key);}
      else if(req.method==='POST'&&/^\/api\/packages\/[^/]+\/finished-goods$/.test(u.pathname)){needs('packaging:write');const id=u.pathname.split('/')[3],p=app.state.packages.find(x=>x.id===id),b=await body();if(p?.warehouseLocation)needs('override:approve');result=app.moveFinishedGoods(id,b,key);}
      else if(req.method==='POST'&&/^\/api\/inventory-items\/[^/]+\/[^/]+\/move$/.test(u.pathname)){needs('storage:write');const parts=u.pathname.split('/');result=app.moveInventoryItem(parts[3],parts[4],await body(),key);}
      else if(req.method==='POST'&&/^\/api\/inventory-items\/[^/]+\/[^/]+\/emergency-relocate$/.test(u.pathname)){needs('override:approve');const parts=u.pathname.split('/');result=app.emergencyRelocate(parts[3],parts[4],await body(),key);}
      else if(req.method==='POST'&&/^\/api\/packages\/[^/]+\/(pack|seal|print|print_fail|retry|ready|ship|cancel|damage|reopen)$/.test(u.pathname)){const parts=u.pathname.split('/'),p=app.state.packages.find(x=>x.id===parts[3]),action=parts[4].toUpperCase();needs('packaging:write');if(action==='REOPEN'||action==='CANCEL'&&!['DRAFT','PACKING'].includes(p?.status)||action==='DAMAGE'&&p?.shipmentId)needs('override:approve');const b=['CANCEL','DAMAGE','REOPEN'].includes(action)?await body():{};result=app.transitionPackage(parts[3],action,key,b);}
      else if(req.method==='POST'&&u.pathname==='/api/customers'){needs('shipping:write');result=app.createCustomer(await body(),key);}
      else if(req.method==='POST'&&/^\/api\/customers\/[^/]+\/update$/.test(u.pathname)){needs('shipping:write');result=app.updateCustomer(u.pathname.split('/')[3],await body(),key);}
      else if(req.method==='POST'&&u.pathname==='/api/sales-orders'){needs('shipping:write');result=app.createSalesOrder(await body(),key);}
      else if(req.method==='POST'&&u.pathname==='/api/shipments'){needs('shipping:write');result=app.createShipment(await body(),key);}
      else if(req.method==='POST'&&/^\/api\/shipments\/[^/]+\/items$/.test(u.pathname)){needs('shipment:override');result=app.addShipmentItem(u.pathname.split('/')[3],await body(),key);}
      else if(req.method==='POST'&&/^\/api\/shipments\/[^/]+\/scans$/.test(u.pathname)){needs('shipping:write');result=app.scanShipmentCarton(u.pathname.split('/')[3],await body(),key);}
      else if(req.method==='POST'&&/^\/api\/shipments\/[^/]+\/(start_picking|ready|load|ship|close|cancel)$/.test(u.pathname)){needs('shipping:write');const parts=u.pathname.split('/'),input=await body(),action=parts[4].toUpperCase(),shipment=app.state.shipments.find(x=>x.id===parts[3]);if(action==='CANCEL'&&shipment&&shipment.status!=='DRAFT')needs('override:approve');result=app.updateShipment(parts[3],action,input,key);}
      else if(req.method==='POST'&&u.pathname==='/api/internal-shipments'){needs('shipping:write');result=app.createInternalShipment(await body(),key);}
      else if(req.method==='POST'&&/^\/api\/internal-shipments\/[^/]+\/(load|dispatch|deliver|cancel)$/.test(u.pathname)){needs('shipping:write');const parts=u.pathname.split('/'),b=await body(),action=parts[4].toUpperCase();if(['LOAD','DISPATCH'].includes(action)){const session=app.requireSession(b.sessionId);if(user?.sub&&session.operatorId!==user.sub)throw new DomainError('SESSION_ACTOR_MISMATCH','Operational session belongs to another user',403)}result=app.updateInternalShipment(parts[3],action,b,key);}
      else if(req.method==='POST'&&u.pathname==='/api/internal-transfers/receive'){needs('operations:write');const b=await body(),session=app.requireSession(b.sessionId);if(user?.sub&&session.operatorId!==user.sub)throw new DomainError('SESSION_ACTOR_MISMATCH','Operational session belongs to another user',403);result=app.receiveInternalTransfer(b,key);}
      else if(req.method==='POST'&&u.pathname==='/api/tasks'){needs('operations:write');result=app.createTask(await body(),key);}
      else if(req.method==='POST'&&u.pathname==='/api/exceptions'){needs('operations:write');result=app.raiseException({...await body(),createdBy:user.sub},key);}
      else if(req.method==='POST'&&/^\/api\/exceptions\/[^/]+\/assign$/.test(u.pathname)){needs('operations:write');result=app.assignException(u.pathname.split('/')[3],await body(),key);}
      else if(req.method==='POST'&&/^\/api\/exceptions\/[^/]+\/start$/.test(u.pathname)){needs('operations:write');await body();result=app.startExceptionWork(u.pathname.split('/')[3],{actorId:user.sub},key);}
      else if(req.method==='POST'&&/^\/api\/exceptions\/[^/]+\/resolve$/.test(u.pathname)){needs('override:approve');const b=await body();result=app.resolveException(u.pathname.split('/')[3],{...b,resolvedBy:user.sub},key);}
      else if(req.method==='POST'&&/^\/api\/exceptions\/[^/]+\/close$/.test(u.pathname)){needs('override:approve');const b=await body();result=app.closeException(u.pathname.split('/')[3],{...b,closedBy:user.sub},key);}
      else if(req.method==='POST'&&/^\/api\/tasks\/[^/]+\/claim$/.test(u.pathname)){needs('operations:write');const b=await body();result=app.claimTask(u.pathname.split('/')[3],taskSessionActor(b.sessionId),key);}
      else if(req.method==='POST'&&/^\/api\/tasks\/[^/]+\/(complete|pause|fail|resume|reopen)$/.test(u.pathname)){needs('operations:write');const parts=u.pathname.split('/'),b=await body();result=app.transitionTask(parts[3],parts[4].toUpperCase(),{...b,actor:{operatorId:user.sub,roles:user.roles,skills:user.skills??[]}},key);}
      else if(req.method==='POST'&&/^\/api\/tasks\/[^/]+\/reassign$/.test(u.pathname)){needs('override:approve');const b=await body(),target=auth.userById(b.operatorId);if(!target)throw new DomainError('USER_NOT_FOUND','Target operator not found',404);result=app.reassignTask(u.pathname.split('/')[3],{operatorId:target.id,roles:target.roles,skills:target.skills??[],reason:b.reason},key);}
      else if(req.method==='POST'&&u.pathname==='/api/qc-checklists'){needs('config:write');result=app.createQcChecklist(await body(),key);}
      else if(req.method==='POST'&&u.pathname==='/api/quality-checks'){needs('quality:approve');const b=await body();result=app.qualityCheck({...b,inspectorId:user.sub,actorRoles:[...(user.roles??[])],attestation:{...(b.attestation??{}),userId:user.sub}},key);}
      else if(req.method==='POST'&&u.pathname==='/api/quality-checks/release'){needs('quality:approve');const b=await body();result=app.releaseQuarantine({...b,inspectorId:user.sub,actorRoles:[...(user.roles??[])],attestation:{...(b.attestation??{}),userId:user.sub}},key);}
      else if(req.method==='POST'&&u.pathname==='/api/inventory-adjustments'){needs('inventory:adjust');const input={...await body(),requestedBy:user.sub};result=input.adjustmentType==='LOCATION_CORRECTION'?app.requestInventoryAdjustment(input,key):authorized(user,'inventory:adjust.approve')&&Math.abs(Number(input.deltaKg))<app.inventoryAdjustmentToleranceKg()?app.requestAndApproveInventoryAdjustment(input,key):app.requestInventoryAdjustment(input,key);}
      else if(req.method==='POST'&&/^\/api\/inventory-adjustments\/[^/]+\/approve$/.test(u.pathname)){needs('inventory:adjust.approve');result=app.approveInventoryAdjustment(u.pathname.split('/')[3],user.sub,key);}
      else if(req.method==='POST'&&/^\/api\/inventory-adjustments\/[^/]+\/reject$/.test(u.pathname)){needs('inventory:adjust.approve');const input=await body();result=app.rejectInventoryAdjustment(u.pathname.split('/')[3],user.sub,input.reason,key);}
      else if(req.method==='POST'&&u.pathname==='/api/configurations'){needs('config:write');const b=await body();result=app.createConfiguration({...b,userId:user.sub},key);}
      else if(req.method==='POST'&&/^\/api\/configurations\/[^/]+\/(approve|activate)$/.test(u.pathname)){needs('config:approve');const parts=u.pathname.split('/');await body();result=app.transitionConfiguration(parts[3],parts[4].toUpperCase(),user.sub,key);}
      else if(req.method==='POST'&&u.pathname==='/api/overrides'){needs('operations:write');const b=await body();result=app.requestOverride({...b,requestedBy:user.sub},key);}
      else if(req.method==='POST'&&/^\/api\/overrides\/[^/]+\/resolve$/.test(u.pathname)){needs('override:approve');const b=await body();result=app.resolveOverride(u.pathname.split('/')[3],{...b,resolvedBy:user.sub},key);}
      else if(req.method==='POST'&&u.pathname==='/api/labels/reprint'){needs('print:write');const b=await body();if(app.reprintApprovalRequired(b.objectType))needs('override:approve');result=app.reprintLabel(b,key);}
      else if(req.method==='POST'&&/^\/api\/print-jobs\/[^/]+\/printer$/.test(u.pathname)){needs('print:write');const b=await body();result=app.overridePrintPrinter(u.pathname.split('/')[3],b.printerId,b.sessionId,key);}
      else if(req.method==='POST'&&/^\/api\/print-jobs\/[^/]+\/claim$/.test(u.pathname)){needs('print:write');const b=await body();result=app.claimPrint(u.pathname.split('/')[3],b.sessionId);}
      else if(req.method==='POST'&&/^\/api\/print-jobs\/[^/]+\/complete$/.test(u.pathname)){needs('print:write');const b=await body();result=app.completePrint(u.pathname.split('/')[3],b.sessionId);}
      else if(req.method==='POST'&&/^\/api\/print-jobs\/[^/]+\/fail$/.test(u.pathname)){needs('print:write');const b=await body();result=app.failPrint(u.pathname.split('/')[3],b.reason,b.sessionId);}
      else if(req.method==='POST'&&/^\/api\/print-jobs\/[^/]+\/retry$/.test(u.pathname)){needs('print:write');const b=await body();result=app.retryPrint(u.pathname.split('/')[3],b.verifiedScan,b.sessionId,b.reason);}
      else return send(404,{success:false,errorCode:'NOT_FOUND',message:'Route not found'});
      await app.flush(); send(201,{success:true,data:result});
    } catch(e){stats.errors++;app.record(e.code==='FORBIDDEN'?'PERMISSION_DENIED':'REQUEST_FAILED',null,e.code==='FORBIDDEN'?(e.details??{}):{method:req.method,path:req.url,errorCode:e.code??'SYSTEM'},null,auditContext.deviceId,'FAILURE');app.persist();const failure=errorResponse(e);if(failure.status>=500)console.error(JSON.stringify({level:'error',site:app.site,errorCode:e.code??'SYSTEM',message:e.message,at:new Date().toISOString()}));send(failure.status,failure.body);}
    });
  });
  const idleSweep=setInterval(()=>app.sweepIdleSessions(),1000),reconciliationIntervalMs=Math.max(1000,Number(process.env.AUTH_AUDIT_RECONCILIATION_INTERVAL_MS||900000)),reconciliationSweep=setInterval(()=>reconcileAuthAudit({auth,app}),reconciliationIntervalMs);idleSweep.unref();reconciliationSweep.unref();server.on('close',()=>{clearInterval(idleSweep);clearInterval(reconciliationSweep)});server.stats=stats;server.reconcileAuthAudit=()=>reconcileAuthAudit({auth,app});return server;
}

export async function createRuntimeServer() {
  const site = process.env.SITE_CODE || 'IRAN'; let repository; let initialState;
  if(process.env.NODE_ENV==='production'&&process.env.CLOUD_URL&&(!process.env.SITE_SYNC_KEY||['iran-dev-key','dubai-dev-key','rome-dev-key'].includes(process.env.SITE_SYNC_KEY)))throw new Error('SITE_SYNC_KEY must be a non-default secret in production');
  if(process.env.NODE_ENV==='production'&&(!process.env.TRANSFER_MANIFEST_KEY||process.env.TRANSFER_MANIFEST_KEY.length<32))throw new Error('TRANSFER_MANIFEST_KEY must be a secret of at least 32 characters in production');
  if (process.env.DATABASE_URL) { repository = new PostgresRepository({ siteCode:site }); await repository.archiveHistory();initialState = await repository.load(); }
  else repository = process.env.DATA_FILE ? new JsonRepository(process.env.DATA_FILE) : null;
  const app = new StoreMesh({ site, repository: process.env.DATABASE_URL ? null : repository, initialState });
  if (process.env.DATABASE_URL) app.repository = repository;
  const authStore=process.env.DATABASE_URL?new PostgresAuthStore({pool:repository.pool,siteId:repository.siteId,siteCode:site}):null,auth=new AuthService({site,store:authStore});await auth.hydrate();
  const server=createServer({ app, auth, requireAuth:authRequiredFromEnvironment() });await auth.flush();
  const publisher=new OutboxPublisher({app,cloudUrl:process.env.CLOUD_URL,siteKey:process.env.SITE_SYNC_KEY});publisher.start();server.on('close',()=>publisher.stop());server.storemesh={app,publisher};return server;
}

if(process.argv[1]&&import.meta.url===pathToFileURL(process.argv[1]).href){const port=Number(process.env.PORT||3000);const server=await createRuntimeServer();server.listen(port,()=>console.log(`StoreMesh site server on ${port}`));}
